waku-org/nwaku

tests/v2/standard_setup.nim
waku/node/v2/config.nim
waku/node/v2/start_network.nim
waku/node/v2/wakunode.nim

WIP https://github.com/status-im/nim-waku/issues/12
Current:
> Error: type mismatch: got <SkResult[secp.SkPrivateKey]> but expected 'SkPrivateKey = distinct SkSecretKey'
Getting the inverse error if I add `.get()`. Probably missing something obvious
TODO: Still need to look at v1 files.

Upgrade vendor nim-libp2p and related packages

---

waku/node/v2/quicksim.nim
waku/protocol/v2/waku_protocol.nim

PR while waiting for https://github.com/status-im/nim-waku/pull/13 CI to build

Floodsub poc

---

waku/protocol/v2/waku_protocol.nim

In one go, per previous comment

Update all vendor

---

waku/protocol/v2/waku_protocol.nim

Use gossipsub instead of floodsub for https://github.com/vacp2p/research/issues/37
```
DBG 2020-05-29 12:45:20+08:00 start                                      tid=9717 topic=WakuSub
INF 2020-05-29 12:45:20+08:00 PeerInfo                                   tid=9717 addrs=@[/ip4/127.0.0.1/tcp/60000] id=16Uiu2HAm7c6ViG4Qhnso7P6zWNBNHsFrfVM4HG3h23qPwEDZzVce
INF 2020-05-29 12:45:20+08:00 Listening on                               tid=9717 full=/ip4/127.0.0.1/tcp/60000/p2p/16Uiu2HAm7c6ViG4Qhnso7P6zWNBNHsFrfVM4HG3h23qPwEDZzVce
Traceback (most recent call last, using override)
/home/oskarth/git/github.com/status-im/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim(614) signalHandler
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
DBG 2020-05-29 12:45:23+08:00 UPnP: …
```

Floodsub->gossipsub

---

tests/v2/standard_setup.nim
waku/node/v2/config.nim
waku/node/v2/wakunode2.nim
waku/protocol/v2/waku_protocol2.nim

Addresses https://github.com/status-im/nim-waku/issues/60
The current `run` function isn't very useful IMO. Started pulling it apart into `CreateWakuNode` and `.start` methods instead. This is modelled after how NBC does it.
cc @kdeme

Create Waku node

---

docs/api/v2/node.md
examples/v2/basic2.nim
waku/node/v2/wakunode2.nim

Closes https://github.com/status-im/nim-waku/issues/81

Fix init signature according to Node API

---

docs/api/v2/node.md
examples/v2/basic2.nim
waku/node/v2/wakunode2.nim

Addresses https://github.com/status-im/nim-waku/issues/82
TopicHandler is still a function of data field. This needs to be changed to take a Message. This can be addressed in a separate follow up issue.
Follow up issue https://github.com/status-im/nim-waku/issues/90

Node API: Implement basic subscribe topic

---

tests/v2/test_waku.nim
waku.nimble
waku/node/v2/nim.cfg
waku/node/v2/rpc/wakurpc.nim
waku/node/v2/standard_setup.nim
waku/node/v2/waku_types.nim
waku/node/v2/wakunode2.nim
waku/protocol/v2/waku_relay.nim

Including updating protocol string.
Addresses https://github.com/status-im/nim-waku/issues/101

Refactor: Waku protocol -> Waku relay protocol

---

docs/api/v2/node.md
examples/v2/basic2.nim
waku/node/v2/wakunode2.nim

- Publish and subscribe implemented
- Three protocol split

Waku v2: Update docs and API with current state

---

Makefile
examples/v2/basic2.nim
waku/node/v2/wakunode2.nim

Regression introduced in https://github.com/status-im/nim-waku/pull/117
Happened due to example not being run on CI.
- Add wakuexample to all target
- Fix example2 to run
- Basic formatting

Make basic Waku v2 examples run again

---

Makefile
docs/tutorial/nangang.md
waku.nimble
waku/node/v2/rpc/rpc_publish.nim
waku/node/v2/rpc/rpc_subscribe.nim
waku/node/v2/rpc/wakurpc.nim
waku/protocol/v2/waku_relay.nim

Fixes https://github.com/status-im/nim-waku/issues/139

Add basic rpc scripts to publish and subscribe

---

waku/protocol/v2/waku_relay.nim

Merge when https://github.com/vacp2p/specs/pull/185 is merged

Bump relay protocol to beta1

---

.github/workflows/test.yml

Don't merge, testing if CI is so slow because this gets updated or not.

Is it because of an update?

---

docs/faq.md

Added a basic FAQ. We can fill this out as people have specific questions.
If you have one and find an answer, feel free to add it to the FAQ. If you just have a question, feel free to ask in #waku or add issue so we can add it here :)

Add FAQ docs for cluster logs etc

---

waku/node/v2/wakunode2.nim

https://github.com/status-im/nim-waku/issues/218

Pass ReuseAddr flag for wakunode2

---

waku/node/v2/waku_types.nim

This PR addresses [this issue](https://github.com/vacp2p/specs/issues/214).

Pagination: Pagination feature/datatypes

---

tests/v2/test_waku_pagination.nim
waku/node/v2/waku_types.nim

This PR addresses [this issue](https://github.com/vacp2p/specs/issues/215).

Pagination: Pagination feature/compute index

---

docs/tutorial/dingpu.md
examples/v2/basic2.nim
examples/v2/chat2.nim
waku/node/v2/config.nim
waku/node/v2/wakunode2.nim

Not much to see here, just removal of some unused config code.
Wanted to add some better input parsing on staticnodes, etc. also, but that will give too much conflict with https://github.com/status-im/nim-waku/pull/228 , I'll do that later.

Cleanup the wakunode2 config

---

tests/v2/test_waku_pagination.nim
tests/v2/test_waku_store.nim
waku/node/v2/waku_types.nim
waku/protocol/v2/waku_store.nim

This PR addresses this issue https://github.com/status-im/nim-waku/issues/232

Pagination feature/indexing waku messages

---

tests/all_tests_v2.nim
tests/v2/test_waku_swap.nim
waku/node/v2/waku_types.nim
waku/protocol/v2/waku_swap.nim

Partial progress towards https://github.com/status-im/nim-waku/issues/260
Ready to be reviewed and merged.
Making it more end to end and integrated will be done in subsequent PRs.

Accounting SWAP protocol basic data types and test

---

examples/v2/basic2.nim
waku/v1/node/start_network.nim

- Updated submodules to latest
- Import `options` as workaround until https://github.com/status-im/nim-confutils/pull/27 is merged

Updated submodules

---

examples/v2/chat2.nim
tests/v2/test_waku_swap.nim
waku/v2/node/wakunode2.nim
waku/v2/protocol/waku_store/waku_store.nim
waku/v2/protocol/waku_store/waku_store_types.nim
waku/v2/protocol/waku_swap/waku_swap.nim
waku/v2/protocol/waku_swap/waku_swap_types.nim

Closes https://github.com/status-im/nim-waku/issues/285
- Does accounting on receiving end
- Exposes swap protocol through store protocol
- Replaces accountFor with credit and debit function
- Simplify query sig and misc formatting

Accounting credit receiving node

---

tests/v2/test_jsonrpc_waku.nim
waku/v2/node/jsonrpc/debug_api.nim
waku/v2/node/jsonrpc/jsonrpc_callsigs.nim
waku/v2/node/jsonrpc/relay_api.nim
waku/v2/node/jsonrpc/store_api.nim

Incremental PR towards #299 
It adds:
- Basic Debug API
- Ability to subscribe and unsubscribe from PubSub topics
Still TODO:
- Publishing WakuMessages
- Polling subscribed PubSub topics for new messages
- Filter API

Some basic Debug and Relay API calls

---

CHANGELOG.md
examples/v2/chat2.nim
tests/v2/test_jsonrpc_waku.nim
tests/v2/test_waku_filter.nim
tests/v2/test_wakunode.nim
waku/v2/node/jsonrpc/admin_api.nim
waku/v2/node/jsonrpc/filter_api.nim
waku/v2/node/rpc/wakurpc.nim
waku/v2/node/wakunode2.nim
waku/v2/protocol/waku_filter/README.md
waku/v2/protocol/waku_filter/waku_filter.nim
waku/v2/protocol/waku_filter/waku_filter_types.nim
waku/v2/waku_types.nim

Also create a folder with README for filter protocol.
No functional code changes

Refactor: waku_types -> waku_filter

---

CHANGELOG.md

Release v0.2.
Once merged I will create a release in GH.

Release v0.2

---

CHANGELOG.md
docs/contributors/README.md
docs/contributors/cluster-logs.md
docs/contributors/git-submodules.md
docs/faq.md
docs/tutorial/dingpu.md
examples/v2/chat2.nim

Add basic docs for cluster fleet

---

examples/v2/basic2.nim
examples/v2/chat2.nim
waku/v2/node/config.nim
waku/v2/node/wakunode2.nim

Addresses https://github.com/status-im/nim-waku/issues/344

Adds rln-relay flag

---

docs/api/v2/node.md
examples/v2/basic2.nim
examples/v2/chat2.nim
tests/v2/test_jsonrpc_waku.nim
tests/v2/test_rpc_waku.nim
tests/v2/test_waku.nim
tests/v2/test_wakunode.nim
waku/common/wakubridge.nim
waku/v2/node/jsonrpc/relay_api.nim
waku/v2/node/rpc/wakurpc.nim
waku/v2/node/wakunode2.nim
waku/v2/protocol/waku_relay.nim

Resolves: #338 #343
Fix: status-im/nim-metrics#29
cc @jakubgs -- this also bumps `nim-metrics` to the latest `master`. We update all submodules at once to avoid interdependency issues.
UPDATE: 
- d053478 removes async from `WakuRelay` subscribe/unsubscribe to reflect GossipSub refactoring (see https://github.com/status-im/nim-libp2p/commit/05e789a34f6f1c3d037f85232c3d14d6a5e3932f and https://github.com/status-im/nimbus-eth2/commit/ed24f60f70c500ce395201ebbb4c18ff8c7cb947)

Bump submodules

---

tests/all_tests_v2.nim
tests/v2/test_waku_swap_contracts.nim

This showcases how to use a separate Swap module by shelling out and using defined Hardhat tasks to do operations against a running node.
First step towards: https://github.com/status-im/nim-waku/issues/360 alternative path to using nim-web3 etc directly.
No functional code changes. Only a test that isn't run by default.
Upcoming:
- JSON interface
- More tasks defined in other module
- Add as submodule (possibly defer to after PoC stage)

Swap contract module test - initial step

---

Makefile
tests/all_tests_v2.nim
waku/v2/protocol/waku_rln_relay/rln.nim

Addresses https://github.com/status-im/nim-waku/issues/374

rlnlib dependency

---

tests/all_tests_v2.nim
tests/v2/test_waku_swap_contracts.nim
waku/v2/protocol/waku_swap/waku_swap.nim
waku/v2/protocol/waku_swap/waku_swap_contracts.nim
waku/v2/protocol/waku_swap/waku_swap_types.nim

Send cheque after signing it by interacting with external node.
Also cleans up waku swap contracts module and adds signature field.
```
INF 2021-02-22 13:18:50.463+08:00 sendCheque                                 topics="wakuswap" tid=297048   cd ../swap-contracts-module; npx hardhat --network localhost signCheque --swapaddress '0x6C3d502f1a97d4470b8
81015b83D9Dd1062172e1'                                                                                      {"signature":"0x65b9e07f83b05c17b3379939953543fbba69fbdf2c0c00744e107bcba4f755867a4c2257f4c7a6af40bcb47a5ba2c537253b9ff1536ae3d0278ec1d66a2cc6621c"}                                                                    0x65b9e07f83b05c17b3379939953543fbba69fbdf2c0c00744e107bcba4f755867a4c2257f4c7a6af40bcb47a5ba2c537253b9ff1536ae3d0278ec1d66 …
```

Waku Swap: sign and send cheque

---

tests/v2/test_waku_swap.nim
waku/v2/protocol/waku_swap/waku_swap.nim

Swap redeem cheque and update accounting state accordingly

Swap redeem cheque and update accounting state accordingly

---

.gitmodules
Makefile
waku.nimble
waku.nims
waku/v2/protocol/waku_rln_relay/rln.nim

Addresses https://github.com/status-im/nim-waku/issues/401

Adds rln as a submodule

---

examples/v2/chat2.nim
waku/v2/node/message_store/waku_message_store.nim

Adding bugfixes as I go along.
This PR:
1. Shows chat prompt in `chat2` application after receiving messages on subscribed topics.
2. Ensures historical messages from persistent storage are returned in time order.

Minor fixes for chat2 and store

---

examples/v2/chat2.nim

This is a further increment towards #399
It improves the encoding of `chat2` messages by serialising the chat text and metadata together using protocol buffers. For now the included fields for every `chat2` message are: `timestamp`, `nick` and `payload`.
One immediate advantage of this approach is that `chat2` peers can interpret these metadata fields, e.g. displaying message timestamps in local time.
In order to seamlessly use the `chat2` application for dogfooding, there should be [peering between cluster nodes](https://github.com/status-im/nim-waku/issues/408).

Improved chat2 message encoding

---

waku/v2/node/config.nim

Updated description of some config items for increased clarity, mostly based on feedback from new users.

Improved description for config items

---

tests/v2/test_wakunode.nim
waku/v2/node/wakunode2.nim
waku/v2/protocol/waku_message.nim
waku/v2/protocol/waku_rln_relay/rln.nim
waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim

Addresses https://github.com/status-im/nim-waku/issues/416

Basic proof gen and vrfy

---

waku/v1/protocol/waku_protocol.nim

This PR closes #267
@kdeme this seemed like the best place to add a "new incoming envelope" hook in `waku_protocol`, while avoiding unnecessary duplicates. Lmk if this is not quite what you had in mind.

Add hook on newly added envelope

---

waku/common/wakubridge.nim

This PR is a first increment towards #205
It scripts the running of both a Waku v1 and Waku v2 node in a single process and passes received data/payload from v1 to v2 and vice versa. A common RPC server exists between the v1 and v2 nodes, allowing for interaction using both v1 and v2 RPC commands.
This is not yet a standalone bridge node, neither does it check for duplicates or do any envelope verification. These will be addressed in subsequent PRs.

Add message passing to waku bridge script

---

.gitmodules
examples/v1/example.nim
tests/test_helpers.nim
tests/v1/test_waku_bridge.nim
tests/v1/test_waku_connect.nim
tests/v1/test_waku_mail.nim
tests/v2/test_jsonrpc_waku.nim
tests/v2/test_peer_manager.nim
tests/v2/test_waku_bridge.nim
tests/v2/test_waku_filter.nim
tests/v2/test_waku_pagination.nim
tests/v2/test_waku_payload.nim
tests/v2/test_waku_rln_relay.nim
tests/v2/test_waku_store.nim
tests/v2/test_waku_swap.nim
tests/v2/test_wakunode.nim
waku/v1/node/wakunode1.nim
waku/v2/node/wakunode2.nim

Exception tracking support was added recently to chronos : https://github.com/status-im/nim-chronos/pull/166
This PR bumps to that chronos version and attempts to fix any exception effect issue in order to be compatible with that chronos version (bumping nim-eth and nim-libp2p along the way).
~~Work in progress: Need to fix a proc type still in nim-eth and relies on https://github.com/status-im/nim-chronos/pull/168 of which I'm not sure it is the right fix.~~

Bump chronos and fix exception tracking issues

---

docs/contributors/cluster-logs.md

Also, return last 7 days of logs instead of
fixed date in the past.

Update kibana link to only filter on fleet

---

waku.nimble

Logs too noisy by default, full of gossipsub TRC making it hard to see what is going on on a local node
```
=behavior.nim:260 peers=0 mesh=0 gossipsub=0 topic=/waku/2/default-waku/proto
TRC 2021-04-07 17:59:47.919+08:00 grafting                                   tid=3849991 file=behavior.nim:284 grafting=0 mesh=0 gossipsub=0 topic=/waku/2/default-waku/proto
TRC 2021-04-07 17:59:47.919+08:00 mesh balanced                              tid=3849991 file=behavior.nim:443 mesh=0 gossipsub=0 topic=/waku/2/default-waku/proto
TRC 2021-04-07 17:59:47.919+08:00 getting gossip peers (iHave)               tid=3849991 file=behavior.nim:490
TRC 2021-04-07 17:59:48.920+08:00 running heartbeat                          tid=3849991 file=behavior.nim:602 instance=140081537917000
TRC 2021-04-07 …
```

Make wakunode2 and wakunode2 default to DEBUG log

---

tests/v2/test_waku_pagination.nim
waku/v2/protocol/waku_store/waku_store.nim
waku/v2/protocol/waku_store/waku_store_types.nim

Addresses https://github.com/status-im/nim-waku/issues/465

Change page size type to uint64

---

.gitignore

Generated as part of the build/upgrade process.

Ignore .update.timestamp file

---

waku/v2/protocol/waku_store/waku_store.nim

Makes it easier to see what is going on

Log more in store protocol

---

tests/v2/test_jsonrpc_waku.nim
waku/v2/node/jsonrpc/jsonrpc_callsigs.nim
waku/v2/node/jsonrpc/store_api.nim
waku/v2/node/scripts/rpc_query.nim

Closes https://github.com/status-im/nim-waku/issues/489
The corresponding specs PR https://github.com/vacp2p/rfc/pull/356

Updates store json rpc api

---

tests/v2/test_waku_lightpush.nim
tests/v2/test_wakunode.nim
waku/v2/node/config.nim
waku/v2/node/wakunode2.nim
waku/v2/protocol/waku_lightpush/waku_lightpush.nim
waku/v2/protocol/waku_lightpush/waku_lightpush_types.nim

Closes https://github.com/status-im/nim-waku/issues/502
- Integrates with node (flag off by default)
- If relay protocol is mounted it publishes messages on that
- End to end node test to ensure (1) is_success is return to light node (2) other relay node receives lightpushed message

Lightpush protocol cont

---

tests/v2/test_wakunode.nim
waku/v2/protocol/waku_store/waku_store.nim

Closes https://github.com/status-im/nim-waku/issues/456
The store protocol identifier was behind the identifier indicated in the specs.

Fix store protocol identifier

---

tests/v2/test_wakunode.nim

Windows CI failing:
```
DBG 2021-04-25 12:37:08.925+00:00 start                                      topics="wakurelay" tid=6604
INF 2021-04-25 12:37:08.925+00:00 relay mounted and started successfully     topics="wakunode" tid=6604
DBG 2021-04-25 12:37:08.930+00:00 Waku peer initialized                      topics="waku" tid=6604 peer=Node[127.0.0.1:30303]
INF 2021-04-25 12:37:08.930+00:00 connectToNodes                             topics="wakunode" tid=6604 peer="(peerId: \"16Uiu2HAmP2esoz2xztqVLdw9wFY1aVxLbPgG8tpYAvAevJBJCpn3\", addrs: @[\"/ip4/0.0.0.0/tcp/60000\"], protocols: @[], protoVersion: \"\", agentVersion: \"\")"
DBG 2021-04-25 12:37:08.930+00:00 Adding peer to manager                     topics="wakupeers" tid=6604 peerId=16U*BJCpn3 addr=/ip4/0.0.0.0/tcp/60000 …
```

Windows CI debug

---

LICENSE-APACHEv2
LICENSE-MIT

I noticed a typo when copy-pasting the files for js-waku :)

Fix name in licence

---

.gitignore
waku/v2/node/libwaku/README.md
waku/v2/node/libwaku/build.sh
waku/v2/node/libwaku/libwaku.c
waku/v2/node/libwaku/libwaku.h
waku/v2/node/libwaku/libwaku.nim
waku/v2/node/libwaku/nim.cfg

Just playing around with C interop over the weekend, might be nice to merge partial progress.

Libwaku spike start

---

waku/v2/node/wakunode2.nim

This PR addresses #498. It is closer to a workaround than a permanent fix.
It allows running `FILTER` protocol on a light node without enabling `RELAY` protocol. A known issue, however, requires `RELAY` to be mounted on the light node in order to dial the full node where `RELAY` _is_ mounted. See [this comment](https://github.com/status-im/nim-waku/issues/498#issuecomment-828543874) for details. We therefore still initialise and mount `RELAY`. `WakuRelay` is never started, though, and the node is never subscribed to any PubSub topics, so it does not participate in any full-message peerings. This way it behaves like a "true" light node.

Allow relay=false for light filter nodes

---

CHANGELOG.md
examples/v2/matterbridge/chat2bridge.nim
examples/v2/matterbridge/config_chat2bridge.nim

- Updated CHANGELOG
- Changed config to be consistent with https://github.com/status-im/nim-waku/blob/master/waku/v2/node/config.nim

Minor chat2bridge improvements

---

CHANGELOG.md
tests/v2/test_jsonrpc_waku.nim
waku/v2/node/jsonrpc/jsonrpc_callsigs.nim
waku/v2/node/jsonrpc/store_api.nim

Closes https://github.com/status-im/nim-waku/issues/558
Corresponding specs PR https://github.com/vacp2p/rfc/pull/376

Enable time-based history query in the store rpc api

---

tests/v2/test_wakunode.nim

See https://github.com/status-im/nim-waku/issues/515#issuecomment-847140774

Re-enable lightpush tests and fix Windows CI failure

---

waku/v2/protocol/waku_relay.nim

This is a stability fix for the keep-alive function.
It ensures that mesh peers being kept alive do not have any backoff period set against them.
This is to address a possible race condition between kicking off [`prune` procedures](https://github.com/status-im/nim-libp2p/blob/master/libp2p/protocols/pubsub/gossipsub/behavior.nim#L42) for a specific peer and [removing that peer](https://github.com/status-im/nim-libp2p/blob/master/libp2p/protocols/pubsub/gossipsub/behavior.nim#L181) from the `mesh`. During this period it has a simultaneous entry in the `backingOff` and `mesh` tables.

Fix: No keep-alive for backoff peers

---

waku/v2/protocol/waku_lightpush/waku_lightpush.nim

Closes https://github.com/status-im/nim-waku/issues/565
https://github.com/vacp2p/rfc/pull/390

Light push beta bump

---

.gitignore
Makefile
waku/v2/node/libwaku/build.sh
waku/v2/node/libwaku/nim.cfg
wrappers/README.md
wrappers/libwaku.h
wrappers/libwaku.nim
wrappers/wrapper_example.c
wrappers/wrapper_example.go

- Move stuff to Makefile
- Move libwaku to root
- Make examples compile for C and Go
- Update README
No functional code changes, ready to be merged. Follow up PR: https://github.com/status-im/nim-waku/pull/614

libwaku: Improve C/Go wrappers

---

tests/v1/test_rpc_waku.nim
tests/v1/test_waku_connect.nim
waku.nimble
waku/common/wakubridge.nim
waku/v1/protocol/waku_protocol.nim

And accompanying changes and clean-up

Use chronosStrictException for Waku v1 code

---

waku/v2/protocol/waku_swap/waku_swap.nim

closes #625 
Change `waku_peer_swap_account_balance` from guage to histogram.
Update peer counter variable name to `waku_swap_peers_count`

Update Swap Account Metrics

---

docs/tutorial/swap.md

closes #636 
Covers basic SWAP Setup, including guides on viewing metrics on Grafana.

Add Swap Protocol Docs

---

CHANGELOG.md
tests/v2/test_waku_store.nim
waku/v2/node/wakunode2.nim
waku/v2/protocol/waku_store/waku_store.nim
waku/v2/protocol/waku_store/waku_store_types.nim

Closes https://github.com/status-im/nim-waku/issues/650

Integrating pagination into the resume proc

---

waku/v1/protocol/waku_bridge.nim
waku/v1/protocol/waku_mail.nim
waku/v1/protocol/waku_protocol.nim

Draft as depends on https://github.com/status-im/nim-eth/pull/374

Add top level push raises Defect to protocol v1

---

tests/v1/test_waku_bridge.nim
waku/v1/node/rpc/key_storage.nim
waku/v1/node/wakunode1.nim
waku/v1/protocol/waku_bridge.nim
waku/v1/protocol/waku_protocol.nim
waku/v2/node/waku_payload.nim
waku/whisper/whisper_protocol.nim
waku/whisper/whisper_types.nim

Addresses https://github.com/status-im/nim-waku/issues/654 as part of refactor week

Move Whisper types and protocol from nim-eth to this repo

---

waku/v2/protocol/waku_swap/waku_swap.nim
waku/v2/protocol/waku_swap/waku_swap_types.nim

Doesn't try to deal with errors, just being explicit about them.

Adds `{.push raises: [Defect].}` to waku_swap

---

Makefile
tests/all_tests_whisper.nim
tests/whisper/test_shh.nim
tests/whisper/test_shh_config.nim
tests/whisper/test_shh_connect.nim
waku.nimble
waku/v1/protocol/waku_bridge.nim

Follow up to https://github.com/status-im/nim-waku/pull/663 re comments

Whisper tests

---

CHANGELOG.md
docs/tutorial/jsonrpc-api.md
tests/v2/test_jsonrpc_waku.nim
waku/v2/node/jsonrpc/jsonrpc_types.nim
waku/v2/node/jsonrpc/jsonrpc_utils.nim
waku/v2/node/quicksim2.nim

This PR closes https://github.com/status-im/nim-waku/issues/674. 
For more context please see https://github.com/status-im/nim-waku/issues/674#issuecomment-882812404 and https://github.com/status-im/nim-waku/issues/674#issuecomment-882814937.
I also used this PR to tide up the imports in  quicksim2 module as part of refactoring week.

Adds timestamp to waku relay message

---

waku/v2/protocol/waku_store/waku_store.nim

Closes https://github.com/status-im/nim-waku/issues/484

Simplify pagination

---

waku/v2/node/wakunode2.nim
waku/v2/utils/wakuswitch.nim

Closes Issue #764. Increment towards #744 
Will publish multiple address when websocket config is enabled.
This PR also adds announced addresses in node object and references it for display of the node address.
Screenshot of the multiple address:

Publish multiple address when websocket enabled.

---

ci/Jenkinsfile.prs

Upped Jenkins CI `make` verbosity to 1

---

Dockerfile
ci/Jenkinsfile.release

Helps with debugging issues related to specific versions.
Test build: https://ci.status.im/job/nim-waku/job/deploy-waku-connect/9

ci: add commit as label to Docker image

---

CHANGELOG.md

Draft release notes for release `v0.8`: https://github.com/status-im/nim-waku/issues/870
Let me know if I skipped anything.

Release v0.8

---

Makefile
docs/tutorial/bridge.md

This makes the current `Dockerfile` usable with `wakubridge`.

ci: rename bridge to wakubridge

---

waku/v2/protocol/waku_store/waku_store.nim
waku/v2/protocol/waku_store/waku_store_types.nim

This PR adds a significant amount of `trace` level logs for the `store` and related operations.
The hope is that this can help with debugging in future.

Increase store and store queue logging

---

CHANGELOG.md

This PR adds DNS bootstrap as a new feature to the changelog.

add dns bootstrap to changelog

---

CHANGELOG.md
docs/tutorial/rln-chat2-live-testnet.md
examples/v2/chat2.nim

This PR contains a tutorial on how to participate in the rln-relay live testnet using rate-limited chat2. Aligned with #830.

Tutorial for rln-relay live testnet

---

waku/v2/node/wakunode2.nim

feat(jsonrpc): add ENR to debug_v1_info call

---

tests/v2/test_peer_storage.nim
waku/v2/node/peer_manager/peer_manager.nim
waku/v2/node/peer_manager/waku_peer_store.nim
waku/v2/node/storage/peer/waku_peer_storage.nim
waku/v2/node/wakunode2.nim

Updates submodules.
Main focus is to include at least two fixes related to websockets:
- Setting activity flag to prevent websocket connections timing out: https://github.com/status-im/nim-libp2p/commit/1696d0c7077fc1d4bec740546a296b3d400f1375
- Several improvements/fixes in nim-websock: https://github.com/status-im/nim-websock/commits/main
Some fixes were required for compatibility with underlying changes in the `PeerStore`. This is still a workaround until we prioritise work to replace our own `WakuPeerStore` with the underlying libp2p `PeerStore` as set out in https://github.com/status-im/nwaku/issues/622

chore: update submodules

---

tests/all_tests_v1.nim

test_shh is nowhere run anymore however it tests code used in waku v1
For sake of completeness, added here.

Run test_shh test as this is used in Waku v1

---

.github/labels.yml

Partially addresses https://github.com/vacp2p/research/issues/112
Subset of labels defined here https://github.com/vacp2p/research/blob/master/.github/labels.yml

chore: Add labels for tracks

---

waku/v2/protocol/waku_lightpush/rpc.nim

Fixes a typo in the top-level annotation

chore(lightpush): Fix typo in annotation

---

waku/v2/protocol/waku_noise/noise_handshake_processing.nim
waku/v2/protocol/waku_noise/noise_utils.nim

chore(noise): minor refactor of default checks of keypairs

---

waku/v2/protocol/waku_store/protocol.nim

* Added some improvements in the waku store protocol request handler to improve history queries traceability (e.g., peer id, request id).
* Removed redundant logging.

chore(waku-store): improve logging and query traceability

---

examples/v2/chat2.nim

chore(chat2): selection of store node at random

---

waku/v2/utils/time.nim

Small cleanup. Remove unused imports, methods and constant

chore(utils): remove unused types and methods

---

waku/v2/utils/pagination.nim

Small refactoring to accommodate upcoming changes in the `MessageStore` interface

refactor(utils): split message digest calculation form index calculation

---

docs/operators/droplet-quickstart.md
docs/operators/quickstart.md

Should resolve #1130
Please note that while there are instructions given to create the most basic droplet, 
there is also documentation on how the operator would choose different sizes, regions and 
OS's for the droplet. This would improve diversity.

docs(operator-outreach): nwaku on droplets

---

tests/v2/test_message_store_queue.nim
waku/v2/node/storage/message/dual_message_store.nim
waku/v2/node/storage/message/message_retention_policy_capacity.nim
waku/v2/node/storage/message/message_retention_policy_time.nim
waku/v2/node/storage/message/message_store.nim
waku/v2/node/storage/message/sqlite_store/sqlite_store.nim
waku/v2/node/storage/message/waku_store_queue.nim
waku/v2/protocol/waku_store/protocol.nim
waku/v2/protocol/waku_store/rpc_codec.nim
waku/v2/utils/pagination.nim

Small PR moving the store message retention constants from the message store module to the right module

chore(store): move constants to retention policies modules

---

ci/Jenkinsfile.prs
ci/Jenkinsfile.release

This way teams can track what deployments happen when.

ci: add Discord notification for successful builds

---

ci/Jenkinsfile.release
docs/contributors/continuous-integration.md
docs/contributors/release-process.md
docs/contributors/waku-fleets.md

ci: add diff link for previously deployed commit

---

tests/v2/test_message_store_queue.nim
tests/v2/test_message_store_queue_pagination.nim
waku/v2/node/storage/message/queue_store/queue_store.nim

This PR is part of the "fix waku store pagination" series:
In this PR:
- Unified into `getPage` the `fwdPage` and the `bwdPage` methods
- Replace the returned tuple with a result type for better error handling
- Update test suites accordingly

refactor(store): simplify store queue query implementation

---

tests/v2/test_message_store_sqlite.nim
waku/v2/node/storage/migration.nim
waku/v2/node/storage/migration/migration_types.nim
waku/v2/node/storage/migration/migration_utils.nim
waku/v2/node/storage/sqlite.nim
waku/v2/node/wakunode2_setup_sql_migrations.nim

This PR improves the database migration logging.
- Collocate all DB migrations code under `migrations` module
- Improve error reporting and debug logging

chore(store): improve database migrations logging

---

ci/Jenkinsfile.release

Makes it easier to identify who to talk to about a deployment.
This depends on the following plugin being installed:
https://plugins.jenkins.io/build-user-vars-plugin/

ci: add username and email to build notifications

---

apps/wakunode2/wakunode2.nim

fix(wakunode2): no peer-exchange peer error msg

---

tools/networkmonitor/networkmonitor.nim
tools/networkmonitor/networkmonitor_utils.nim

Related #1010 
Related https://github.com/status-im/infra-misc/issues/104

chore(networkmonitor): use nim-presto + add timeout

---

tests/v2/test_waku_store.nim
waku/v2/protocol/waku_store/protocol.nim

The Waku relay and filter protocols already implement a message handler in their API, and we specify the desired behavior at the `waku_node` module. To decouple the Waku message archiving logic from the Waku store protocol handler and to be consistent with the protocols that already have a message handler as part of their API, a history query handler has been specified.
The plan is to altogether remove the archiving logic from the Waku store protocol turning it into a simple query mechanism to retrieve historical messages. The archiving logic will be split into the Waku archive module.
>~~ℹ️ This PR depends on #1403 and #1404. Once merged, this PR will be ready to review.~~

feat(store): add support for history query handler

---

README.md
docs/operators/quickstart.md

chore(docs): add docker-compose instructions

---

apps/wakunode2/wakunode2.nim
tools/networkmonitor/README.md
tools/networkmonitor/networkmonitor.nim
tools/networkmonitor/networkmonitor_config.nim
tools/networkmonitor/networkmonitor_metrics.nim

chore(networkmonitor): Add DNS discovery

---

tests/v2/test_waku_rln_relay.nim
tests/v2/test_waku_rln_relay_onchain.nim

Addresses https://github.com/waku-org/nwaku/issues/1358
The tests now adhere to the style guide
- chore(rln-relay): s/var/let
- chore(rln-relay): s/var/let
- chore(rln-relay): s/check/require
- chore(rln-relay): s/check/require
- fix(rln-relay): s/check/require

chore(rln-relay): address laundry list for tests

---

tools/networkmonitor/networkmonitor.nim

chore: remove unused imports

---

waku/v2/node/waku_node.nim
waku/v2/protocol/waku_relay.nim

* Remove unnecessary peermanager dependency from waku_relay.

refactor: remove unnecessary peermanager dependency

---

tests/v2/waku_store/test_wakunode_store.nim

While debugging #1514 I extended the Waku Store - Waku Node integration test coverage.

test(store): extend wankunode's waku store test coverage

---

.github/workflows/ci-experimental.yml
.github/workflows/ci.yml

Bump CI compiled log level to DEBUG.

fix(ci): bump log level during CI runs

---

waku/v1/node/rpc/waku.nim
waku/whisper/whisper_types.nim

chore(v1): fix deprecation warnings

---

waku/v2/node/discv5/waku_discv5.nim

A little code cleanup gardening PR 🪴

chore(discv5): waku discv5 module code cleanup

---

tests/v2/test_waku_switch.nim

Should fix but does not close (until tested) https://github.com/waku-org/nwaku/issues/1499
Also updates test as per https://github.com/status-im/nim-libp2p/pull/842

chore: bump nim-libp2p 444b837

---

waku/v2/node/peer_manager/peer_manager.nim

* Fixes an important issue, causing the connectedness state of the peers to be stored wrongly `Connected`/`NotConnected`. This had further implications, since the connected state was wrong, we were trying to connect to already connected peers, leading to `Max streams for protocol reached` error after 10 streams were created.
* Also closes https://github.com/waku-org/nwaku/issues/1503
* TLDR: We can't use `ConnEventHandler` to track the peer connected state, we should use `PeerEventHandler` instead. This
* Connection state cant be tracked using `ConnEventHandler` when more than one conn is allowed and when using autonat (which we currently are). For example, if a peer has 2 conns and one get disconnected we cant assume that the peer is disconnected, so it doesnt make sense to update the …

fix(networking): fix wrong peer connected state

---

waku/v2/protocol/waku_noise/noise_utils.nim

Relevant RFC PR:
https://github.com/vacp2p/rfc/pull/575

chore: use base64 url safe encoding for noise

---

tests/v2/test_waku_rln_relay.nim
waku/v2/protocol/waku_keystore/protocol_types.nim
waku/v2/protocol/waku_rln_relay/constants.nim
waku/v2/protocol/waku_rln_relay/conversion_utils.nim
waku/v2/protocol/waku_rln_relay/rln/wrappers.nim

Fixes https://github.com/waku-org/nwaku/issues/1487

chore(rln-relay): address laundry list of improvements

---

tests/v2/test_waku_enr.nim
waku/v2/protocol/waku_enr.nim

Following the new `TypedRecord` accessors, the `waku2` capabilities accessor extension has been added to the `waku_enr` module. The next step is the multiaddress field.

refactor(enr): added waku2 capabilities accessor

---

waku/v2/protocol/waku_rln_relay/group_manager/on_chain/group_manager.nim
waku/v2/protocol/waku_rln_relay/rln/wrappers.nim

Fixes on-chain registration with custom gas limit. Uncaught on ganache tests, need to revisit arguments later.

fix(rln-relay): on chain registration

---

waku/v2/protocol/waku_lightpush/protocol.nim
waku/v2/protocol/waku_store/protocol.nim

During the `wakunode2` refactoring, some issues were detected. The following changes aim to fix them:

fix: wrap untracked protocol handler exceptions

---

waku/v2/protocol/waku_rln_relay/group_manager/on_chain/group_manager.nim

Fixes a bug where removed events were included in the valid event block table, thanks @richard-ramos
Also, fixes https://github.com/waku-org/nwaku/pull/1623#pullrequestreview-1362558825

fix(rln-relay): scope of getEvents

---

waku/v1/README.md

Fix spec link

---

ci/Jenkinsfile.release

Includes a debug flag in the jenkinsfile

fix(ci): remove target flag from docker command

---

.github/workflows/ci.yml

Fix to avoid ci errors in PR's.
e.g. https://github.com/waku-org/nwaku/actions/runs/4959224218

fix: setting 'os' instead of 'platform'

---

waku/v2/waku_rln_relay/group_manager/on_chain/group_manager.nim

Fixes an error that was undetected in CI, for tests (not sure how?)

fix(rln-relay): trace log

---

waku/v2/waku_rln_relay/group_manager/group_manager_base.nim
waku/v2/waku_rln_relay/group_manager/on_chain/group_manager.nim

Fixes some metrics that were not being tracked

chore(rln-relay): updated metrics for testnet 3

---

metrics/waku-rln-relay-fleet-dashboard.json
metrics/waku-rln-relay-single-node-dashboard.json

With #1624, a change in the grafana panels are required, we include proof verification durations now.

chore(rln-relay): update metrics dashboard

---

apps/wakunode2/app.nim
examples/v2/publisher.nim
examples/v2/subscriber.nim
tests/v2/test_waku_discv5.nim
tests/v2/test_waku_peer_exchange.nim
waku/v2/node/waku_node.nim
waku/v2/waku_discv5.nim

Creating an interim PR to move changes in https://github.com/waku-org/nwaku/pull/1709 to a base repo branch.

feat(discv5): added find random nodes with predicate

---

waku/v2/waku_relay/protocol.nim

Update nim-libp2p to latest `unstable` and fix incorrect wrapperHandler proc signature

chore(libp2p): update nim-libp2p

---

CHANGELOG.md

This PR updates CHANGELOG for release [v0.18.0](https://github.com/waku-org/nwaku/milestone/10)
Please check if the changelog looks ok and propose highlights!

docs(changelog): release notes for v0.18.0

---

waku/v2/waku_relay/protocol.nim

Reverts https://github.com/waku-org/nwaku/pull/1788
Also includes a websock fix that should help with the memory issues

chore(deps): bump libp2p & websock

---

apps/wakunode2/app.nim
apps/wakunode2/config.nim
apps/wakunode2/external_config.nim
apps/wakunode2/internal_config.nim
apps/wakunode2/wakunode2.nim
waku/v2/node/builder.nim
waku/v2/node/config.nim
waku/v2/node/waku_node.nim
waku/v2/waku_discv5.nim
waku/v2/waku_enr/sharding.nim

Setting the code for the move of discv5 out of node. Note that some changes might look weird without context, feel free to ask.
- keys, netconfig and ENR are created when the app initialize
- modified node builder
tracking #1812

chore: discv5 re-org setup

---

apps/wakunode2/app.nim
apps/wakunode2/wakunode2.nim
examples/v2/publisher.nim
examples/v2/subscriber.nim
tests/v2/test_waku_discv5.nim
tests/v2/test_waku_peer_exchange.nim
tests/v2/testlib/wakunode.nim
tests/wakunode2/test_app.nim
waku/v2/node/builder.nim
waku/v2/node/waku_node.nim
waku/v2/waku_discv5.nim

Move discv5 out of node and into app
- Remove redundant discv5 start and stop
- Move all the logic into discv5 file
- Renaming
- Fix tests and examples
track #1812

chore: discv5 move

---

waku/v2/node/waku_node.nim

* The `nim-libp2p` adds many changes although we are actually interested in the latest commit:
> wstransport.nim: avoid re-raising 'TransportOsError' to avoid stopping
`switch.accept` (#929)
* The `nim-stew` bump is needed so that the `nim-libp2p` can compile.
* The changes in `waku_node.nim` are needed due to the changes in `nim-stew`.
closes https://github.com/waku-org/nwaku/issues/1831

fix(libp2p): Updating nim-libp2p to fix the `wss` connectivity issue

---

CHANGELOG.md

Changelog / Release notes for the v0.19.0
Please review and suggest more/different highlits or notes.

docs(changelog): release notes for v0.19.0

---

apps/wakucanary/wakucanary.nim

Changes in https://github.com/waku-org/nwaku/commit/cf46fb7cf6d4598386457947c149d91a22bd716f introduced a requirement for ENR record to be provided to waku node builder. `wakucanary` missed this change.
NOTE: Not sure if we need to provide other info for ENR (e.g. multiaddresses) since wakucanary is not really ment to be connected to.
closes #1880

fix(wakucanary): add enr record to builder

---

.github/ISSUE_TEMPLATE/milestone.md

Adding a milestone-issue template

chore: Adding milestone issue template inspired by the one present in the `pm` repo

---

apps/wakunode2/app.nim
apps/wakunode2/external_config.nim
tests/wakunode2/test_app.nim

If #1857 is not merged in time for v0.19
Fix #1896

fix: bring back default topic in config

---

apps/chat2/chat2.nim

Fixes an `node record is required ` error which crashes chat2.

fix(chat2): no enr record in chat2

---

tests/waku_rln_relay/test_rln_group_manager_onchain.nim

The macos runners were timing out consistently due to a version change in ganache. This pr addresses it by locking the 
version of ganache used, and killing the child processes that ganache creates

fix(rln-relay): timeout on macos runners, use fixed version of ganache

---

waku/waku_rln_relay/group_manager/on_chain/group_manager.nim
waku/waku_rln_relay/protocol_metrics.nim
waku/waku_rln_relay/rln_relay.nim

* Removes unused RLN metrics.
* Add new RLN metric to track the amount of active RLN memberships.

chore(rln): remove old and add new rln metric

---

waku/waku_rln_relay/rln_relay.nim

Removes some duplicated logs, used appropriate log levels for some
Addresses a part of #1906

chore(rln-relay): apt log levels for certain logs

---

README.md

Update README with some relevant information/issues I found while setting up the `nwaku` environment in my computer, namely:
- A possible fix to building issues when working on WSL.
- Bundled nim runtime

docs(README): List possible WSL Issue

---

.gitmodules

The 'nim-results' package is extracted from 'nim-stew' and added separately.
bump vendor dependencies for 0.21.0 https://github.com/waku-org/nwaku/issues/2041

chore: Bump vendor/nim-stew

---

.github/workflows/ci.yml
.github/workflows/pre-release.yml

Fixes to reflect js-waku ci changes: https://github.com/waku-org/js-waku/issues/1548
Calling only the test part of the js-waku ci that is relevant of nwaku

chore: fix js-waku tests in the ci

---

waku/node/waku_node.nim

New bumping for 0.21.0. Almost done. In this case, the `nim-libp2p` is updated again because the correct branch is the `unstable` one. `nim-libp2p` has the `master` branch but `master` is only updated every few months. We'll take care of that on further bumps.
The next dependencies are updated:
- vendor/nim-libp2p
- vendor/nim-toml-serialization
- vendor/nim-unicodedb
- vendor/nim-unittest2
- vendor/nim-websock
- vendor/nim-zlib
- vendor/nimbus-build-system
https://github.com/waku-org/nwaku/issues/2041

chore: bump nim-libp2p, nim-toml-serialization, nim-unicodedb, nim-unittest2, nim-websock, nim-zlib, & nimbus-build-system

---

.github/ISSUE_TEMPLATE/bump_dependencies.md

Creates dependency bump template for releases.

chore: create dependency bump template for releases

---

waku/node/peer_manager/peer_manager.nim

Tiny PR adding an optional shard filter when selecting a peer via peer manager.
Tracking #1941

feat: added optional filtering by shard to selectPeer()

---

ci/Jenkinsfile.release
ci/discord.groovy

Also use absolute path to load Groovy script.

fix(ci): fix name of discord notify method

---

tests/test_waku_discv5.nim
tests/test_waku_enr.nim
tests/waku_core/test_namespaced_topics.nim
tests/waku_core/test_sharding.nim
waku/waku_core/topics/pubsub_topic.nim
waku/waku_core/topics/sharding.nim
waku/waku_discv5.nim
waku/waku_enr/sharding.nim

fix: sharding terminology & cluster id

---

waku/waku_archive/driver/postgres_driver/postgres_driver.nim

Revert "chore: postgres_driver.nim - rename table's name from "messages" to "message""

---

apps/wakunode2/app.nim

Filter rest api installation was rely on wrong configuration argument. --filter was checked (which is intended to filter service) instead of --filternode (that one is for filter client support).
1. run: wakunode2 --relay --filter --lightpush --rest=true --rest-port=11111
a. should not crash, but start properly
2. run: curl -i -X GET "http://127.0.0.1:11111/filter/v2/subscriptions/111" -H "accept: application/json"
a. should return Http404
3. run:  wakunode2 --relay --filternode=<address of the first node> --rest=true --rest-port=11112
4. run:  curl -i -X GET "http://127.0.0.1:11112/filter/v2/subscriptions/111" -H "accept: application/json"
a. must return Some meaing full json response with or without error code.
[bug: SIGSEGV when Filter and REST are …

fix(restapi init): wrong install of filter rest api

---

tests/waku_archive/test_driver_postgres.nim
tests/waku_archive/test_driver_sqlite.nim
tests/waku_archive/test_driver_sqlite_query.nim
tests/waku_archive/test_retention_policy.nim
waku/waku_archive/archive.nim
waku/waku_archive/driver.nim
waku/waku_archive/driver/postgres_driver/postgres_driver.nim
waku/waku_archive/driver/queue_driver/queue_driver.nim
waku/waku_archive/driver/sqlite_driver/queries.nim
waku/waku_archive/driver/sqlite_driver/sqlite_driver.nim

This reverts commit 9cd8c73d273bdfc95e6bcf870cd94030690f2630.

chore: Revert "feat: messageHash attribute added in SQLite + testcase (#2142)"

---

CHANGELOG.md

chore(release): update changelog for v0.21.1 release

---

CHANGELOG.md

Updating v0.21.1 release date in changelog

fix: updating v0.21.1 release date in changelog

---

ci/Jenkinsfile.release

fix(ci): fix Docker tag for latest and release jobs

---

README.md

docs: Add REST API Docs

---

CHANGELOG.md

chore(release): update changelog for v0.21.2 release

---

ci/Jenkinsfile.prs
ci/Jenkinsfile.release

Closes: https://github.com/waku-org/nwaku/issues/2107

fix: default runtime available log level in ci

---

CHANGELOG.md

chore(release): update changelog for v0.21.3 release

---

docs/tutorial/pre-requisites-of-running-on-chain-spam-protected-chat2.md

Some rewrites for clarity.
Updates screenshots where necessary (especially for the Infura workflow).

docs: rewrite for clarity, update screenshots

---

CHANGELOG.md

Changelog for v0.22.0
Please review carefully and suggest highlights, upgrade instructions or notes that should be added :)

chore(release): update changelog for v0.22.0 release

---

tests/waku_relay/test_protocol.nim

fix(relay): Failing protocol tests

---

Makefile
docs/tutorial/rln-keystore-generator.md
waku.nimble

This PR updates the Makefile entry and waku.nimble file to remove the rln_keystore_generator target

chore: update docs for rln-keystore-generator

---

tests/test_peer_storage.nim
waku/node/peer_manager/peer_manager.nim
waku/node/peer_manager/peer_store/peer_storage.nim
waku/node/peer_manager/peer_store/waku_peer_storage.nim

The intent is to refactor the peer storage so that relevant peer information, enr included, is saved.
Closes #2237

chore: refactoring peer storage

---

waku/waku_relay/protocol.nim
waku/waku_rln_relay/rln_relay.nim

Simple PR to add more logs in case of relay validation `ValidationResult.Reject`.

chore: relay - add trace logs in case of msg validation rejection

---

docs/contributors/release-process.md

Added one step. Check and update fleet config if needed.

docs: update after release steps

---

CHANGELOG.md

chore: update CHANGELOG.md for v0.24.0

---

tests/node/test_wakunode_relay_rln.nim
tests/testlib/futures.nim
tests/waku_rln_relay/rln/buffer_utils.nim
tests/waku_rln_relay/rln/test_rln_interface.nim
tests/waku_rln_relay/rln/test_wrappers.nim
tests/waku_rln_relay/rln/waku_rln_relay_utils.nim
tests/waku_rln_relay/test_waku_rln_relay.nim
waku/waku_rln_relay/rln/wrappers.nim

Implement some basic unic tests for RLN

test(rln): Implement some rln unit tests

---

waku/node/waku_metrics.nim

Simple PR to change the log cadence as per our last PM meeting.
It changes the frequency of "Total *" logs (metrics logs) from 30 seconds to 10 minutes.

chore: waku_metrics - change log interval from 30'' to 10'

---

Makefile
README.md

Added example in `README.md`of using custom nim compilation flags
#2466

chore: adding NIMFLAGS usage to readme

---

waku/waku_filter/protocol.nim
waku/waku_filter_v2/protocol.nim
waku/waku_lightpush/protocol.nim
waku/waku_metadata/protocol.nim
waku/waku_relay/protocol.nim

Super simple PR to cleanup some code and encapsulate a few protocol procs.

chore: tiny cleanup and more encapsulation in protocol.nim files

---

waku/waku_archive/retention_policy/builder.nim

Allows the usage of optional decimal values in the storage policy, and limits the size unit in the regexp itself. Since i preeventively lowercase the ret policy argument, I ended up removing the different combinations of uppercase/lowercase and just compare against `gb` or `mb`.
closes #2522

fix(store): retention policy regex

---

docs/contributors/nph.md

Add instructions on how to properly configure the `nph` formatter.

docs: create nph.md

---

waku/waku_api/rest/store/types.nim

Standardize the contentTopic field returned by store rest
closes https://github.com/waku-org/nwaku/issues/2582

fix: rest store: content_topic -> contentTopic in the response

---

waku/waku_api/rest/store/client.nim

Updating `nim-chronicles` version
#2570

chore: bumping chronicles version

---

docs/operators/how-to/connect.md

... and change to he correct rest api reference page.
No code change just connect.md doc fix.
https://github.com/waku-org/nwaku/issues/2540

chore:Removed remaining of json-rpc reference from connect.md 

---

waku/waku_api/rest/store/types.nim

Simple PR to change to properly return `content_topic` in _Store_ REST reponses
closes https://github.com/waku-org/nwaku/issues/2582

fix: rest/store/types: contentTopic -> content_topic

---

waku/waku_archive/driver/postgres_driver/postgres_driver.nim

Simple PR to reduce Postgres logs

chore: postgres_driver.nim: debug -> trace put PotsgresDriver

---

tests/waku_sync/sync_utils.nim
tests/waku_sync/test_protocol.nim
waku/node/waku_node.nim
waku/waku_sync/common.nim
waku/waku_sync/protocol.nim

First draft of pruning mechanism!
@chaitanyaprem

feat: pruning storage mehcanism

---

waku/waku_archive/driver/postgres_driver/postgres_driver.nim

Enhance the time retention policy in _Postgres_
In this PR we are starting to remove whole partitions and rows within the last remaining partition.
Given a timestamp, `ts`:
- Remove the old partitions that don't contain `ts`
- Remove the rows older than `ts` from the partition that contains `ts`
closes https://github.com/waku-org/nwaku/issues/2666 - message retention policy not applied

chore: postgres_driver - delete partitions in time retention policy

---

waku/waku_api/rest/legacy_store/types.nim
waku/waku_api/rest/store/types.nim

Standardize the case use by all REST endpoints' attributes. We are using CamelCase
closes https://github.com/waku-org/nwaku/issues/2582

chore: standardize store types by using camel case instead of snake case

---

docs/contributors/release-process.md

Linking our Notion guide with the details on how to validate our releases. The Notion guide was also updated and now includes the guide on how to test the release for Status

chore: link validation process docs to the release process file

---

CHANGELOG.md

Merging branches so release tag is propagated to master

chore(release): merging release/v0.28 branch to master (#2713)

---

CHANGELOG.md

Trying another option to merge release branch into master

chore(release): update changelog for v0.28.0 release (#2713)

---

ci/Jenkinsfile.release

Description :-
update nwaku-compose automatically whenever a new nwaku release occurs.
Logic :- 
push the newest nwaku image with the 'latest-release' tag to identify it as the latest version in nwaku-compose.

feat: sync the newly released nwaku image with nwaku-compose.

---

waku/waku_archive/driver/postgres_driver/migrations.nim
waku/waku_archive/driver/postgres_driver/postgres_driver.nim

Uses an advisory lock which acts as a mutex for the postgresql migrations.
This lock will be acquired before any migration is executed. If it's not possible to acquire, the instance will fail to start with these errors:
```
ERR 2024-05-27 17:59:38.155-04:00 failed to acquire lock                     topics="waku archive migration" tid=479763 file=migrations.nim:77 error="another waku instance is currently executing a migration"
ERR 2024-05-27 17:59:38.155-04:00 Mounting protocols failed                  tid=479763 file=node_factory.nim:435 error="failed to setup archive driver: ArchiveDriver build failed in migration: failed to lock the db"
```
Once the migration process is done, the lock will be released.
This is required for scenarios in which a postgresql database is used by more than …

fix(waku_archive): only allow a single instance to execute migrations

---

waku/waku_archive/archive.nim
waku/waku_archive/common.nim
waku/waku_archive/driver.nim

I updated the `Archive`, the commonly used types and the driver interface.

chore(archive): archive refactor

---

waku/README.md

chore: simple link refactor

---

apps/networkmonitor/networkmonitor_config.nim
waku/waku_archive/archive.nim
waku/waku_archive/driver/sqlite_driver/sqlite_driver.nim

The main purpose of this PR is to reduce the number of `SELECT count(*) FROM MESSAGES` queries that we make to the databases.
Aside from that, I'm just removing some minor leftovers.

chore: Minor enhancements

---

tests/waku_rln_relay/test_rln_group_manager_onchain.nim

Adding message to failed assert in order to debug this failure in the CI

chore: added message to failed assert

---

.github/ISSUE_TEMPLATE/feature_request.md

This is meant to help align the new feature issues that we create with the existing epics. Notice that each Epic, in turn, should be under a certain Deliverable.

chore: add epic and link feature_request.md

---

waku/common/databases/db_sqlite.nim
waku/waku_archive/driver/sqlite_driver/queries.nim

Simple PR to tackle SP's comment: https://github.com/waku-org/nwaku/pull/2885#discussion_r1668466412
Thanks for that @SionoiS !

chore: sqlite make sure code is always run

---

waku/node/peer_manager/peer_manager.nim

Small PR improving logging when using the `debugDiscv5` flag
Thanks @AlbertoSoutullo for noticing 🤩

chore: improving logging under debugDiscv5 flag

---

waku/waku_relay/protocol.nim

Logging the content topic of spam messages to get more info about who spams the network

chore: logging content topic of spam messages

---

waku/waku_archive/archive.nim
waku/waku_archive/driver/postgres_driver/postgres_driver.nim
waku/waku_archive/retention_policy/retention_policy_capacity.nim
waku/waku_archive/retention_policy/retention_policy_size.nim
waku/waku_archive/retention_policy/retention_policy_time.nim

Enhance postgres, archive, and retention policy logs.
This should be merged after https://github.com/waku-org/nwaku/pull/2761 is completed and then update the logs on top of it

chore: simple PR to enhance postgres and retention policy logs

---

CHANGELOG.md
waku/waku_filter_v2/protocol.nim

closes https://github.com/waku-org/nwaku/issues/2909

chore: update master from release/v0.31

---

tests/test_peer_manager.nim

Bumping dependencies for release `v0.32.0`
closes #2959

chore: updating dependencies for release 0.32.0

---

waku/waku_archive/driver/postgres_driver/postgres_driver.nim

Limit the query by hashes to 100 hashes per query

chore: postgres_driver limit max num hashes to 100

---

waku/factory/external_config.nim

remove unused external parameter `rest-private`

chore: Update external_config.nim

---

.github/ISSUE_TEMPLATE/prepare_release.md

add a new step to review https://github.com/waku-org/docs.waku.org/blob/develop/docs/guides/nwaku/config-options.md

chore: update prepare_release.md

---

library/libwaku.nim
waku/waku_api/rest/admin/handlers.nim
waku/waku_api/rest/legacy_store/handlers.nim
waku/waku_api/rest/store/handlers.nim

Bump dependencies.
nim-eth, nim-json-rpc, and nim-web3 are not being updated because they caused too many issues
closes https://github.com/waku-org/nwaku/issues/3016

chore: Bump dependencies for v0.33

---

examples/cbindings/waku_example.c
library/libwaku.h
library/libwaku.nim
library/waku_thread/inter_thread_communication/requests/discovery_request.nim
library/waku_thread/inter_thread_communication/requests/peer_manager_request.nim
waku/waku_peer_exchange/protocol.nim
waku/waku_relay/protocol.nim

One more step towards exposing nwaku through libwaku. The exposed features are currently needed by status-go.
Notice that there will be more upcoming features soon.
Adding new features:
- waku_get_peerids_from_peerstore
- waku_get_peerids_by_protocol
- waku_peer_exchange_request

chore: libwaku - extending the library with peer_manager and peer_exchange features

---

library/waku_thread/inter_thread_communication/requests/debug_node_request.nim
library/waku_thread/inter_thread_communication/requests/discovery_request.nim
library/waku_thread/inter_thread_communication/requests/node_lifecycle_request.nim
library/waku_thread/inter_thread_communication/requests/peer_manager_request.nim
library/waku_thread/inter_thread_communication/requests/protocols/lightpush_request.nim
library/waku_thread/inter_thread_communication/requests/protocols/relay_request.nim
library/waku_thread/inter_thread_communication/requests/protocols/store_request.nim

Logging in libwaku errors of failed requests. This will help us debug more easily any issue that may be found.
On a separate PR, we will error handling from the request's sender
#3039

chore: adding error logs for failed libwaku operations

---

waku/node/waku_node.nim

Removing leftover log used for debugging
closes #3090

fix: remove spammy log

---

library/libwaku.nim

Whenever we called `callback(RET_OK, unsafeAddr msg[0], cast[csize_t](len(msg)), userData)` with `msg` being an empty string, we got a segfault.
Changed de data type of `msg` to `cstring` instead of nim strings, which fixes the segfault.
Additionally, fixed the usage of `foreignThreadGc` and added usage of `handleRes` in missing parts
#3039

fix: segfault for libwaku's empty response messages

---

waku/common/databases/db_postgres/dbconn.nim

Format e.g.:
XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX

chore: dbconn - allow uuid in requestId by allowing hyphen

---

examples/golang/waku.go

Updating the golang example with the the newly exposed procedures.
For consistency, copy-pasted the definitions from status-go, which implies the change of some variable names.
In nwaku's root directory, build libwaku and run the example with the following commands
```
make libwaku
cd examples/golang/
go run waku.go
```

chore: updating available procs in golang example

---

waku/waku_core/time.nim

I think this is the simplest possible PR lol
It fixes a linting error we get when running nph in the CI

fix: linting error

---

library/waku_thread/inter_thread_communication/requests/ping_request.nim
waku/waku_core/peers.nim

We've noticed before in status-go that sometimes multiaddresses that use dns names fail due to the ISP dns or the nameservers not being available. A change was done before in status-go to instead of having a single multiaddress per storenode, to have multiple multiaddresses: one with the dns and another one with the IP address.
As such, when go-waku does a ping, it does it by creating a `PeerInfo` (a go-libp2p structure) which contains these multiaddresses and then go-libp2p would use its own heurisitc to determine which multiaddress to use when pinging.
Looking at nim-libp2p, `switch.dial` supports multiple addresses too, so this PR modifies part of the nwaku code to make it possible to ping a peer with multiple multiaddresses
It also fixes a stream that was left open.

chore: support ping with multiple multiaddresses and close stream

---

apps/chat2bridge/chat2bridge.nim
apps/liteprotocoltester/tester_config.nim
tests/wakunode2/test_validators.nim
waku/factory/external_config.nim

chore: fix some typos in comment

---

library/libwaku.nim

SUBSCRIBE was being called instead of UNSUBSCRIBE

fix(libwaku): waku_relay_unsubscribe

---

waku/waku_archive/archive.nim
waku/waku_archive_legacy/archive.nim

We need to give better insight on what is happening during the archive process.
closes https://github.com/waku-org/nwaku/issues/3164

chore: archive enhance logging

---

tests/waku_archive/test_waku_archive.nim
waku/common/databases/db_postgres/dbconn.nim
waku/common/databases/db_postgres/query_metrics.nim

- Better implementation of query-to-metric conversor
- Also adding simple unittest to confirm it works as expected
#closes https://github.com/waku-org/nwaku/issues/3282

chore: better implementation to properly convert database query metrics

---

.github/workflows/ci.yml

Just tiny PR to update ci-action name

chore: relevent ci name

---

waku/factory/external_config.nim
waku/factory/waku.nim

Tracked with #3349 
closes https://github.com/waku-org/nwaku/issues/3050

chore!: remove pubsub topics arguments 

---

examples/cbindings/README.md
examples/cbindings/waku_example.c
examples/cpp/README.md
examples/cpp/waku.cpp
library/libwaku.nim

Simple PR to adapt the simple C and C++ examples to the current libwaku implementation where we have async operations.

chore: maintenance to c and c++ simple examples

---

library/events/json_connection_change_event.nim
library/events/json_message_event.nim
library/events/json_topic_health_change_event.nim

Removing comments that are wrong (came from a copy-paste mistake), and fixing broken url
#3236

fix: wrong comments and broken link

---

apps/wakunode2/wakunode2.nim
waku/factory/external_config.nim
waku/factory/internal_config.nim
waku/factory/waku.nim
waku/factory/waku_conf.nim

Simple changes to keep the code consistent at some extent.

chore: Simple restyle

---

waku/factory/waku_conf.nim
waku/waku_rln_relay/group_manager/on_chain/group_manager.nim

fix: release v0.36

---

metrics/waku-fleet-dashboard.json

The last Store sync panel had a wrong query and label. I fixed it, looks like that now.

fix: sync dashboard panel

---

ci/Jenkinsfile.lpt
ci/Jenkinsfile.prs
ci/Jenkinsfile.release

related issue : https://github.com/status-im/infra-ci/issues/202

fix: disable restart from stage in jenkins

---

tests/factory/test_external_config.nim
waku/factory/external_config.nim

fix: updates regex pattern to support username:password authentication in http/https URLs

---

tests/factory/test_external_config.nim
waku/waku_rln_relay/group_manager/on_chain/group_manager.nim
waku/waku_rln_relay/group_manager/on_chain/rpc_wrapper.nim

@stubbsta  suggested in the comments to improve the RPC call. This is an initial PR to streamline all RPCs using a workaround wrapper. Next, I’ll try to update nim-web3 so this workaround is no longer needed. 
this one is kind a maintance issue https://github.com/waku-org/nwaku/issues/3483

fix: streamline contract api

---

waku.nimble

Make the nimble waku version consistent with released tags.
Related to https://github.com/waku-org/nim-chat-sdk/issues/7

chore: update the version to reflect the latest tag
