waku-org/nwaku

.github/workflows/pr-lint.yml

This PR adds a CI job checking changes in the PR and matching them agains files which contain
1. configuration options for apps
2. DB schema for archive drivers
If it matches, it will post a comment nudging the submitter to check whether there is a risk for a breaking change and also suggests to use `release-notes` label, to make sure the change is covered in Release Notes and changelog
I tried to articulate the comments clearly, but maybe there is a better wording/suggestion to submitter, please let me know what would be the information you'd like to see in the comment.
Also, let me know if I missed any files that should make it into the lists:)
closes #1873

chore(ci): add a job checking config options and db schema

---

tests/waku_rln_relay/test_rln_group_manager_onchain.nim
tests/waku_rln_relay/test_waku_rln_relay.nim
waku/waku_rln_relay/group_manager/on_chain/group_manager.nim
waku/waku_rln_relay/rln/wrappers.nim

If an operator runs waku-rln-relay in 2 different runs, once with chainId x and another with chainId y, then the tree 
used would be the same. This leads to inconsistencies, and hence, we use the `metadata` feature to store the chainId, as 
well as the contractAddress. If there is a mismatch in any of the 2 fields, we raise an exception and prevent the node 
from starting up.
closes #1921

fix(rln-relay): RLN DB should be aware of chain and contract address

---

apps/wakunode2/app.nim
tests/test_waku_discv5.nim
tests/test_waku_enr.nim
waku/node/jsonrpc/relay/handlers.nim
waku/node/rest/relay/handlers.nim
waku/node/waku_node.nim
waku/waku_core/topics.nim
waku/waku_discv5.nim
waku/waku_enr/sharding.nim

I added a way to update the Discv5 ENR and used a `AsyncEventQueue` to broadcast topic subscriptions.
Fix #1843
Followed by #1918

feat: ENR can now be updated

---

.gitmodules
scripts/build_rln.sh

Bumps zerokit to v0.3.2, which includes a fix for tree persistence
closes #1944

fix(rln-relay): bump zerokit to v0.3.2

---

tests/waku_rln_relay/test_rln_group_manager_onchain.nim
waku/waku_rln_relay/group_manager/on_chain/group_manager.nim
waku/waku_rln_relay/rln/wrappers.nim

It is noticed that when a node is restarted, and has access to a persisted tree, the window of acceptable roots is not 
persisted, and may result in an empty deque. To mitigate this bug, we are persisting the window of acceptable roots in 
the rln metadata.
closes #1952
Thanks @alrevuelta for the report!

fix(rln-relay): window of acceptable roots synced to rln metadata

---

tests/waku_rln_relay/test_rln_group_manager_onchain.nim
waku/waku_rln_relay/group_manager/on_chain/group_manager.nim

Syncs from the deployed block number to prevent excess network calls
closes #1942

fix(rln-relay): sync from deployed block number

---

Makefile

This pr is associated to https://github.com/waku-org/nwaku/pull/1956#issuecomment-1695562089
We need to ensure that RLN is set to true when compiling the `rln-keystore-generator` target

fix(Makefile): error out if rln-keystore-generator not compiled with rln flag

---

apps/chat2/chat2.nim
apps/chat2/config_chat2.nim
apps/wakunode2/app.nim
apps/wakunode2/external_config.nim
tests/test_waku_keystore.nim
tests/waku_rln_relay/test_waku_rln_relay.nim
tools/rln_keystore_generator/rln_keystore_generator.nim
waku/waku_keystore/conversion_utils.nim
waku/waku_keystore/keystore.nim
waku/waku_keystore/protocol_types.nim
waku/waku_keystore/utils.nim
waku/waku_rln_relay/constants.nim
waku/waku_rln_relay/group_manager/on_chain/group_manager.nim
waku/waku_rln_relay/rln_relay.nim

This PR includes the modification to the waku_rln_keystore lib, where instead of credentials being sorted according to 
membership contract etc, we store it as a k-v pair, the key being `sha256(chainId|contractAddress|treeIndex)`
When the user starts a new `wakunode`, we hash the 3 together, and check if the corresponding credentials exist, if not, 
we error out.
The same goes for the `rln_keystore_generator`
This brings significant performance gains since reads are O(1) instead of O(n) 
> [!IMPORTANT]  
> This is a breaking change to existing keystores, and the version has been incremented to 0.2
1. Generate a new set of credentials using the `rln_keystore_generator`
```
./build/rln_keystore_generator \
--rln-relay-cred-path=./rlnKeystore.json \
--rln-relay-eth-client-address=<url> \ …
```

fix(rln-relay): modify keystore credentials logic

---

Makefile

With https://github.com/waku-org/nwaku/pull/1960, we introduced a change that made all compilations (even wakunode2) with rln enabled. This PR fixes that regression

fix(Makefile): rln was enabled by default

---

tools/rln_keystore_generator/rln_keystore_generator.nim

This PR helps users obtain the membership index after they run the keystore generator

chore(rln-keystore-generator): log out the membership index upon registration

---

.github/workflows/pre-release.yml

Addition of [rln_keystore_generator](https://github.com/waku-org/nwaku/tree/master/tools/rln_keystore_generator) broke `pre-release` (nightly, rc) workflow

fix(ci): rename tools artifact to prevent conflict

---

waku/waku_filter_v2/protocol.nim

one suggestion that was made during today's message reliability call was to add this information to help debug cases where a message appears to have been pushed succesfully to all subscribers yet the message appears to not have been delivered.
To see this change in action, it would require the fleet to be deployed and also use `debug` level for logs
Notice that might add some noise on the logs for full filter nodes, due to changing the log level for one of the messages from TRACE to DEBUG, and also due to adding an extra log line, but it should be an acceptable tradeoff while dogfooding for filter is in progress. We can do a separate PR in the future to change the affected log lines to TRACE

chore: add debug log indicating succesful message pushes and also log the message hash

---

waku/waku_rln_relay/rln/wrappers.nim

This PR fixes a regression introduced in https://github.com/waku-org/nwaku/pull/1953
Deserialization of merkle roots has been fixed
1. Follow https://github.com/waku-org/nwaku/issues/1952#issuecomment-1698880309
closes #1952

fix(rln-relay): deserialization of valid merkle roots

---

apps/wakunode2/external_config.nim

Little cleanup of the `external_config.nim`. Removing the `store-resume-peer` attribute.
The _Store_ resume feature was partially removed in the next commit:
https://github.com/waku-org/nwaku/commit/c8081c885975d5b39803ee086df8d4b59af54f34
Hanno commented:
> I think this functionality can also be removed/disable in go-waku. It was sort of an experimental start to a "fault tolerant" store that will retrieve messages it's missed after an offline period from another store node. But the feature is not very fleshed out and should not be used in production. This would rather be followed-up by a proper redesign of the store protocol, roadmapped by the Waku Research team
> The resume code is still there behind a compile flag: https://github.com/waku-org/nwaku/blob/7d53aec16430b637b60ef8b9fd6b5a066 …

chore(refactoring): external_config.nim - cleanup 'store-resume-peer' attribute

---

apps/wakunode2/app.nim
waku/waku_core/topics/sharding.nim

The deprecated `--topic` config has a default.
When using the newer options `--content-topic` & `--pubsub-topic` it should be ignored.
Also added `getShard` that take and return `string`

fix: deprecated --topic config option should be ignored when using newer options

---

Dockerfile

For any reason, the `master` branch from [heaptrack](https://github.com/KDE/heaptrack) repo became unstable and the _Docker_ build isn't working due to that.
We are enforcing a working version, instead of cloning the `master` branch each time, which can cause esporadic failures.

chore(Dockerfile): forcing a particular heaptrack version to avoid build issues

---

examples/cbindings/waku_example.c
library/alloc.nim
library/libwaku.nim
library/waku_thread/inter_thread_communication/node_lifecycle_request.nim
library/waku_thread/inter_thread_communication/peer_manager_request.nim
library/waku_thread/inter_thread_communication/protocols/relay_request.nim
library/waku_thread/inter_thread_communication/request.nim
library/waku_thread/waku_thread.nim

This is aimed at having a safer c-bindings `libwaku`. With that regard, given that the [WakuNode](https://github.com/waku-org/nwaku/blob/01634f57f0386efebfcfcb1d6e6c88de345a17e7/waku/node/waku_node.nim#L85) is a GC-managed type, we need to make sure the instance of the _WakuNode_ is directly created from within the _Waku Thread_ itself.
note: each `ref`, `seq[T]`, or `string` are GC-manged types
https://github.com/waku-org/nwaku/issues/1878

chore(cbindings): Thread-safe libwaku. WakuNode instance created directly from the Waku Thread

---

Makefile

ref: https://ci.infra.status.im/job/nim-waku/job/manual/51/execution/node/23/log/
```
error: manifest path `/app/vendor/zerokit/target/release/rln/Cargo.toml` does not exist
```
Removed the `/target/release` from the `LIBRLN_BUILDDIR` var

fix(Makefile): invalid path to crate build

---

tests/waku_rln_relay/test_waku_rln_relay.nim
tests/wakunode_jsonrpc/test_jsonrpc_relay.nim
tests/wakunode_rest/test_rest_relay.nim
waku/node/jsonrpc/relay/handlers.nim
waku/node/rest/relay/handlers.nim
waku/waku_relay/protocol.nim
waku/waku_rln_relay/rln_relay.nim

Description:
* Adds validation to rest+rpc api so that an rln message proof is verified before sending the message. If the proof is wrong or the message is considered spam, the message won't be sent and it will error out so that the user is aware that the message didn't made it.
* Adds validation to rest+rpc api so that it errors out when trying to publish to a topic that the node is not subcribed, since it risks that there are no connected peers "listening" in that topic.
* Update tests so that they work with rln enabled/disabled.
How to test it:
```
./build/wakunode2 \
--rln-relay=true \
--rpc-address=0.0.0.0 \
--rpc-admin=true \
--rest=true \
--rest-admin=true \
--rest-private=true \
--rest-address=0.0.0.0 \
--rln-relay-dynamic=true \
--rln-relay-cred-password=password \ …
```

chore(api): validate rln message before sending (rest + rpc)

---

apps/chat2/config_chat2.nim
apps/wakunode2/external_config.nim
tests/test_waku_keystore.nim
tests/waku_rln_relay/test_waku_rln_relay.nim
tests/waku_rln_relay/test_wakunode_rln_relay.nim
tests/wakunode_jsonrpc/test_jsonrpc_relay.nim
tests/wakunode_rest/test_rest_relay.nim
waku/waku_keystore/keystore.nim
waku/waku_rln_relay/group_manager/on_chain/group_manager.nim
waku/waku_rln_relay/rln_relay.nim

from the perspective of an end user, i will most likely have only one membership per chainId-contractAddress pair.
To account for this, we are removing `rln-relay-membership-index` as a compulsory argument to wakunode2, and instead, using the `only` available key in the keystore
1. Create a fresh keystore using rln-keystore-generator - contractAddress: `0x0A988fd9CA5BAebDf098b8A73621b2AaDa6492E8` 
1. Run wakunode2 with the following args 
```shell
./build/wakunode2 \
--rln-relay=true \
--rln-relay-dynamic=true \
--rln-relay-cred-password=$KEYSTORE_PASSWORD \
--rln-relay-cred-path=rlnKeystore.json \
--rln-relay-tree-path=rln_tree_new_1.db \
--rln-relay-eth-contract-address=0x0A988fd9CA5BAebDf098b8A73621b2AaDa6492E8  \
--rln-relay-eth-client-address=$SEPOLIA_URL \ …
```

chore(rln-relay): use the only key from keystore if only 1 exists

---

.github/workflows/container-image.yml

Using double braces leads to workflow trying to resolve env var as a template

fix(ci): incorrect use of braces

---

.github/workflows/container-image.yml

per @alrevuelta's reuest - replacing `master` tag with git commit for traceability

chore(ci): use commit instead of master for docker image

---

apps/wakunode2/app.nim
tests/waku_rln_relay/test_wakunode_rln_relay.nim
waku/waku_rln_relay/rln_relay.nim

This PR clears the nullifier table every time there are more than `MaxEpochGap` epochs stored in it
Addresses a part of #1906

chore(rln-relay): clean up nullifier table every MaxEpochGap

---

tests/waku_rln_relay/test_rln_group_manager_onchain.nim
waku/node/waku_node.nim
waku/waku_rln_relay/group_manager/group_manager_base.nim
waku/waku_rln_relay/group_manager/on_chain/group_manager.nim
waku/waku_rln_relay/group_manager/static/group_manager.nim
waku/waku_rln_relay/rln_relay.nim

Adds an `isReady` proc to waku_node, waku_rln_relay  
Addresses 25. #1906

chore(rln-relay): add isReady check

---

apps/wakunode2/app.nim
waku/common/databases/db_postgres/pgasyncpool.nim
waku/waku_archive/driver.nim
waku/waku_archive/driver/builder.nim
waku/waku_archive/driver/postgres_driver/postgres_driver.nim
waku/waku_archive/driver/postgres_driver/postgres_healthcheck.nim

It starts an asynchronous infinite task that checks the connectivity with the database.
In case of error, the `postgres_healthcheck` task tries to reconnect for a while, and if it determines that the connection cannot be resumed, then it invokes a callback indicating that situation.
For the case of the `wakunode2` app, that callback quits the application itself and adds a log trace indicating the connectivity issue with the database.
1. Run node A - `./build/wakunode2 --config-file=cfg_node_a.txt`
[cfg_node_a.txt](https://github.com/waku-org/nwaku/files/12537414/cfg_node_a.txt)
2. Run node B - `./build/wakunode2 --config-file=cfg_node_b.txt`
[cfg_node_b.txt](https://github.com/waku-org/nwaku/files/12537417/cfg_node_b.txt)
3. Run a _Postgres_ instance: `docker compose -f …

chore(postgres): Adding healtcheck and reconnection mechanism to the postgres archive driver

---

tests/waku_relay/test_wakunode_relay.nim
tests/wakunode_rest/test_rest_store.nim

I've looked at all the tests to see if `Port()` had any conflicts and fixed what I could.
If we still have conflicts, in the future, adding a `randomPort()` could do the trick.
Closes #1826

fix(tests): relay tests use random port to avoid conflict

---

Makefile
tools/rln_db_inspector/external_config.nim
tools/rln_db_inspector/nim.cfg
tools/rln_db_inspector/rln_db_inspector.nim
waku.nimble

While debugging and running simulations, it can be useful to inspect the rln tree db. 
Future PRs can add more inspection capabilities, but this will be useful for now.
1. Have a pre-existing rln tree db (from running wakunode2)
1. Compile the binary `make -j12 rln-db-inspector`
1. Run `./build/rln-db-inspector --rln-relay-tree-path:<path>`

feat(rln_db_inspector): create rln_db_inspector tool

---

tools/rln_db_inspector/rln_db_inspector.nim

Uses `valueOr` instead of `isOkOr` since we wish to preserve the values that the results return (not 
void)

fix(rln-db-inspector): use valueOr pattern

---

apps/wakunode2/app.nim
tests/all_tests_waku.nim
tests/wakunode_rest/test_rest_health.nim
waku/node/rest/health/client.nim
waku/node/rest/health/handlers.nim
waku/node/rest/health/openapi.yaml
waku/node/waku_node.nim

For RLN readiness /health rest endpoint is added.
It checks if wakunode is ready - currently it means rln is mounted correctly. returns proper http status upon.
1. make test EXPERIMENTAL=true
or
1. ./scripts/build_rln.sh ./vendor/zerokit
2. nim c -r -d:chronicles_log_level=DEBUG -d:os=Linux --parallelBuild:2 --verbosity:1 -d:chronicles_log_level=DEBUG -d:release -d:rln --passL:./vendor/zerokit/target/release/librln.a --passL:-lm ./tests/wakunode_rest/test_rest_health.nim 
[feat(rest): Add /health endpoint to rest api](https://github.com/waku-org/nwaku/issues/1988)

feat: Rest endoint /health for rln

---

waku/node/peer_manager/peer_manager.nim
waku/node/waku_switch.nim

Description:
* Temporally comment inbound relay peer prunning, since it may be causing connectivity issues. Note that prunning by IP is kept, this just affects the general prunning.
* Increase default peer store size. If the max amount of peers is `x` the peerstore size should be way bigger than that. If no, we wont benefit much from the exponential backoff, since after prunning, this state is "forgotten".
* Increase peerstore prunning interval to 10 minutes.
Test:
* Simulated in an environment with `waku-simulator`

fix(p2p): fix possible connectivity issue

---

.github/workflows/ci-experimental.yml
.github/workflows/ci.yml
.github/workflows/container-image.yml

Depends on https://github.com/waku-org/js-waku/pull/1541 (merged)
This PR adds another step in our CI workflow - it executes js-waku tests on top of the image built from a PR - you can think of this as an integration test attempt

chore(ci): execute js-waku integration tests on image build

---

docs/operators/how-to/run-with-rln.md
docs/tutorial/onchain-rln-relay-chat2.md
docs/tutorial/rln-keystore-generator.md
tools/rln_keystore_generator/README.md

This PR updates the contract address in documentation, and includes docs for `rln-keystore-generator`

chore(rln-relay): updated docs

---

tests/all_tests_waku.nim
tests/waku_core/test_published_address.nim
tests/wakunode_jsonrpc/test_jsonrpc_admin.nim
waku/node/config.nim
waku/node/peer_manager/peer_manager.nim

Currently, the IP address `0.0.0.0` is being published in the Identify message when there's no external addresses found. This happens in cases when Waku nodes are being run locally.
This goes against [RFC 1122](https://www.rfc-editor.org/rfc/rfc1122#page-29), section 3.2.1.3 where referring to the `0.0.0.0` IP it states:
>This host on this network. MUST NOT be sent, except as a source address as part of an initialization procedure by which the host learns its own IP address.
In that case, we will publish localhost's loopback interface's address `127.0.0.1` instead.
When running the node locally, if no IP address is specified (or if the 0 IP is provided as an input), the node should publish the `127.0.0.1` IP instead.
If a custom IP is provided, it should be published
closes …

fix: preventing IP 0.0.0.0 from being published

---

waku/waku_rln_relay/group_manager/on_chain/group_manager.nim
waku/waku_rln_relay/protocol_metrics.nim

This PR sets the number of registered memberships to the `start` index (i.e last index that was inserted) + number of commitments - commitments removed
Upon startup, if we fetch the tree db, there is no way currently from the zerokit ffi api to fetch the number of members registered - hence, we set the metric based on the event thrown by the contract.
closes #2008

fix(rln-relay): waku_rln_number_registered_memberships metrics appropriately handled

---

waku/common/databases/db_sqlite.nim
waku/waku_archive/driver/sqlite_driver/migrations.nim

Given a `nwaku` node with _Store-SQLite_ mounted, it will try to apply a migration script because the `user_version` present in the SQLite file is 0, whereas the expected version is 7. 
In order to replicate the issue, the node should have a certain amount of messages stored in the database.
Use the next command, tailored by @vpavlin, to start the node, but change the docker image each time:
```
docker run -it --rm -v $PWD/data:/data:z XXXdocker-imageXXX --relay --store --store-message-db-url=sqlite:///data/wakustore.sqlite3 --log-level=DEBUG --dns-discovery=true --dns-discovery-url=enrtree://AOGECG2SPND25EEFMAJ5WF3KSGJNSGV356DSTL2YVLLZWIV6SAYBM@prod.waku.nodes.status.im --discv5-discovery=true --discv5-udp-port=9005 --discv5-enr-auto-update=True
```
1. Start the node with: …

fix(sqlite): Prevent the execution of 'migrate' script if user_version==0

---

.gitmodules
Makefile
scripts/build_rln.sh
tests/waku_rln_relay/test_waku_rln_relay.nim
waku/waku_rln_relay/group_manager/on_chain/group_manager.nim
waku/waku_rln_relay/rln/rln_interface.nim

This PR includes very minor changes to improve qol
To make sure you don't get errors while linking `librln.a`, remove the file from the project root

chore(rln-relay): logs, updated submodule, leaves_set metric

---

waku/node/rest/store/handlers.nim
waku/node/waku_metrics.nim
waku/node/waku_node.nim
waku/waku_archive/archive.nim
waku/waku_filter_v2/protocol.nim

This is a maintenance PR, and the most relevant vendor dependencies are being updated. Not all of the dependencies are updated to try to reduce the number of candidates, in case of any error.
https://github.com/waku-org/nwaku/issues/2041

chore: Updating nim-chronicles, nim-chronos, nim-presto, nimcrypto, nim-libp2p, and nim-nat-transversal

---

Dockerfile
scripts/build_rln.sh

To resolve RLN build issues like this:
```
Building: librln_v0.3.4.a
./scripts/build_rln.sh: line 29: rustup: command not found
Warning: to ensure you are building in a supported repo state, please always run "make update" after "git pull"
(it looks like you've forgotten to do this).
This also applies whenever you switch to a new branch or commit, e.g.: whenever you run "git checkout ...".
Failed to download -rln.tar.gz
./scripts/build_rln.sh: line 42: jq: command not found
error: could not find `Cargo.toml` in `/app` or any parent directory
make: *** [Makefile:131: librln_v0.3.4.a] Error 127
```
https://ci.infra.status.im/job/nim-waku/job/deploy-wakuv2-test/301/console

chore(ci): add jq, fix RLN build script to not use rustup 

---

Makefile
examples/cbindings/waku_example.c
waku/waku_rln_relay/rln_relay.nim

* When adding the dependency with 'librln' to 'libwaku', it is required to remove the dependency with 'confutils' because the 'nim-confutils' module prevents the creation of a dynamic library (libwaku.so.)
* waku_example.c: less code is needed because the Waku Thread attends any Waku event whereas the main thread can have a blocking scanf to retrieve user inputs.

refactor(cbindings): Adding 'librln' to `libwaku` and cleaning waku_example.c

---

.github/workflows/pre-release.yml

Forgot to add `js-waku` job into `needs` for the `create-release-candidate job` - which means the RC creation is not gated by the js-waku job

chore(ci): add js-waku as a dependency for pre-release createion

---

apps/chat2/config_chat2.nim
apps/chat2bridge/config_chat2bridge.nim
apps/networkmonitor/networkmonitor_config.nim
apps/wakucanary/wakucanary.nim
apps/wakunode2/external_config.nim
tests/common/test_confutils_envvar.nim
waku/common/confutils/envvar/std/net.nim
waku/common/envvar_serialization/reader.nim

This is by far the most tricky vendor update that we''ll have until now.
Concepts like `mixin`, `template`, and "inferred types" are involved in this PR, so there might be changes that seem not to be straightforward at first sight.
https://github.com/waku-org/nwaku/issues/2041

chore: Bumping vendor/nim-confutils and vendor/nim-serialization

---

apps/wakunode2/app.nim
tests/all_tests_waku.nim
tests/wakunode_rest/test_rest_lightpush.nim
tests/wakunode_rest/test_rest_relay_serdes.nim
waku/node/rest/lightpush/client.nim
waku/node/rest/lightpush/handlers.nim
waku/node/rest/lightpush/openapi.yaml
waku/node/rest/lightpush/types.nim
waku/node/rest/relay/types.nim
waku/node/rest/responses.nim
waku/node/waku_node.nim

As part of epic https://github.com/waku-org/nwaku/issues/1076 RestApi endpoint for lightpush service is provided here
New endpoint POST:/lightpush/v1/message is added for wakunode.
1. nim c -r ./tests/wakunode_rest/test_rest_lightpush.nim
https://github.com/waku-org/nwaku/issues/2040

feat: lightpush rest api

---

library/waku_thread/waku_thread.nim

Use of a better approach to synchronize threads. Use of `ThreadSignalPtr` instead of an intense loop.
This PR is motivated by the following comment: https://github.com/waku-org/nwaku/pull/1978#discussion_r1318154604

refactor(cbindings): waku_thread.nim - Using 'ThreadSignalPtr' instead of loop to handle req/resp

---

waku/waku_rln_relay/group_manager/on_chain/group_manager.nim

The last PR for bumping vendor dependencies.
The update `nim-web3` cause changes in `waku/waku_rln_relay/group_manager/on_chain/group_manager.nim`.
closes https://github.com/waku-org/nwaku/issues/2041

chore: Bump nim-web3

---

Makefile

This is to make sure the upcoming refactoring tasks ensure that the `libwaku` still builds properly.

chore: Makefile - making the 'libwaku.so' to be built with 'make all'

---

waku/waku_rln_relay/group_manager/static/group_manager.nim
waku/waku_rln_relay/rln_relay.nim

When no other params except `--rln-relay` is provided to wakunode2, it segfaults.
This is due to the static group manager unwrapping the membership index without checking if it was set.
This PR fixes that and errors out appropriately.
1. Build wakunode2 `make -j12 wakunode2`
1. Run `./build/wakunode2 --rln-relay=true`
1. You should not see a segfault, but rather an error message asking to set the membership index.
closes #2039

fix(rln-relay): segfault when no params except rln-relay is passed in

---

apps/networkmonitor/networkmonitor.nim
apps/networkmonitor/networkmonitor_config.nim
apps/networkmonitor/networkmonitor_metrics.nim

This PR leverages `ping` protocol to measure latency in between the network monitor instance and discovered nodes.
It records the latency as a
* histogram metric
* last measured latency per node
* average latency per node with sliding window of 10 
It also adds retry limit for failed connections and adds a cliff to repeatedly discovered nodes to only reconnect to them after 60s

feat(networkmonitor): add ping latencies, optimize reconnections

---

.github/workflows/container-image.yml
.github/workflows/pre-release.yml
.github/workflows/release-assets.yml
ci/Jenkinsfile.prs
ci/Jenkinsfile.release

The `-d:postgres` _Nim_ flag was added in order to not build the _Postgres_ archive driver when a new user wanted to compile the `wakunode` from the command line manually. However, we do want to have _Postgres_ support on each _Docker_ image, both in releases and in PRs.

chore: Adding -d:postgres flag when creating a Docker image for release and PRs

---

apps/wakunode2/external_config.nim
waku/common/databases/dburl.nim

This is to make the database URL regex to accept `.` and `-` within the hostname.
Also, the user and password fields can be anything not empty.
notes:
- also cleaning dead code in `apps/wakunode2/external_config.nim`.
- creating the temporary quay image with POSTGRES=1 in .github/workflows/container-image.yml
1. Run `nwaku` with `--store-message-db-url = "postgres://nim-waku-user:nim-waku-pass@store-db-01.do-ams3.shards.test.wg:5432/postgres"`.
2. The node should start and complain about not being able to resolve the host name but it shouldn't complain anything about the db URL format.
https://github.com/status-im/infra-shards/pull/8#issuecomment-1731393876

fix(archive): dburl check

---

.github/workflows/ci.yml
library/waku_thread/inter_thread_communication/requests/protocols/relay_request.nim

We introduced a change in the next PR
https://github.com/waku-org/nwaku/pull/1983/files
that made the `libwaku` to stop building properly
(make libwaku) because a signature change in the
`unsubscribe` proc of waku/waku_relay/protocol.nim.
This commit is a temporary workaround to make it work, and not block any ongoing PR tests,
although not exactly as it is expected because we are unsubscribing from all topics.

fix: libwaku.nim: unsubscribe -> unsubscribeAll to make it build properly

---

tests/wakunode_rest/test_rest_relay.nim
waku/waku_api/rest/relay/client.nim
waku/waku_api/rest/relay/handlers.nim
waku/waku_api/rest/relay/openapi.yaml
waku/waku_api/rest/relay/types.nim

Forgot to update openapi.yml for the new autosharding relay API in #1983
I also removed the topic when auto posting as it's already included in the message itself.

fix: relay openapi definitions

---

Makefile
ci/Jenkinsfile.release
ci/discord.groovy
docs/contributors/release-process.md
docs/operators/docker-quickstart.md
docs/operators/how-to/configure.md
docs/operators/how-to/run-with-rln.md
docs/operators/overview.md
docs/operators/quickstart.md

And other changes that make sense in the context.

chore(ci): push images to new wakuorg/nwaku repo

---

apps/chat2/chat2.nim
apps/networkmonitor/README.md
docs/operators/docker-quickstart.md
docs/operators/droplet-quickstart.md
docs/operators/how-to/configure-dns-disc.md
docs/operators/how-to/run.md
docs/operators/quickstart.md
waku/README.md

Enrtrees were regenerated. Need to update the old one.
DNS discoverty should continue to work.

update wakuv2 fleet DNS discovery enrtree

---

apps/wakunode2/internal_config.nim
tests/test_wakunode.nim
tests/testlib/wakunode.nim
tests/wakunode2/test_app.nim

When running a node and no external IP is provided but a DNS4 address is, we want the ENR to use the resolved DNS IP instead of using `0.0.0.0`, which is currently the case.
closes [#1576](https://github.com/waku-org/nwaku/issues/1576)

chore: resolving DNS IP and publishing it when no extIp provided

---

.gitignore
scripts/run_cov.sh
tests/all_tests_common.nim
tests/all_tests_wakunode2.nim
tests/common/test_all.nim
tests/test_all.nim
tests/waku_archive/test_all.nim
tests/waku_core/test_all.nim
tests/waku_filter_v2/test_all.nim
tests/waku_relay/test_all.nim
tests/waku_rln_relay/test_all.nim
tests/waku_store/test_all.nim
tests/wakunode2/test_all.nim
tests/wakunode_jsonrpc/test_all.nim
tests/wakunode_rest/test_all.nim

Implement a coverage script that runs all tests and generates the coverage report.

feat(coverage): Add simple coverage

---

apps/networkmonitor/networkmonitor.nim
apps/networkmonitor/networkmonitor_config.nim
apps/networkmonitor/networkmonitor_metrics.nim

This PR refactors `setConnectedPeersMetrics` proc a bit
* splits out the `shouldReconnect` check
* splits out the reconnection (i.e. dial and ping) to separate proc
* uses seq of futures to make the dials to newly discovered peers concurrent
* adds `ResetRetriesAfter` time (in seconds) to retry peers we failed to connect (if they are re-discovered)
It also adds `--version` (cc @jakubgs)
partially based on comments from #2068

chore(networkmonitor): refactor setConnectedPeersMetrics, make it partially concurrent, add version

---

Makefile
examples/cpp/base64.cpp
examples/cpp/base64.h
examples/cpp/waku.cpp
library/libwaku.h

In this example, we can see how to integrate a `nwaku` node from within a `cpp` code. The code is very similar to the `C` version. The interesting point is the usage of cpp-lambdas and how they can seamlessly integrate with the execution context.
e.g.
```
std::string defautPubsubTopic;
WAKU_CALL(waku_default_pubsub_topic(cify([&](const char* msg, size_t len) {
defautPubsubTopic = msg;
})));
```

chore(cbindings): Adding cpp example that integrates the 'libwaku'

---

.github/workflows/pre-release.yml

Pre-release (nightly) builds are failing due to rename of js-waku* tasks

fix(ci): update the dependency list in pre-release WF

---

tests/wakunode_rest/test_rest_lightpush.nim
waku/node/waku_node.nim

Previous change on lightpush error handling caused js-waku tests failing and thus ci errors on nwaku side as well.
There had been a discussion around and decision is made to enrich the protocol for the future.
[[Epic] Enhance light push protocol ](https://github.com/waku-org/pm/issues/93)
Up until than we do not return error in case there is no suitable peer to publish message comes from lightpush.
- CI's js-waku should not fail

chore: Revert lightpush error handling to allow zero peer publish again succeed

---

waku/waku_archive/driver/builder.nim
waku/waku_archive/driver/postgres_driver/postgres_driver.nim

During _Postgres_ performance analysis I realized that we have this duplicated `const` that can lead into a confusion.
This PR will simplify that.

chore: postgres_driver - remove duplicated const MaxNumConns.

---

apps/wakunode2/app.nim
tests/all_tests_waku.nim
tests/wakunode_rest/test_all.nim
tests/wakunode_rest/test_rest_admin.nim
waku/waku_api/jsonrpc/admin/handlers.nim
waku/waku_api/rest/admin/client.nim
waku/waku_api/rest/admin/handlers.nim
waku/waku_api/rest/admin/openapi.yaml
waku/waku_api/rest/admin/types.nim
waku/waku_core.nim
waku/waku_core/multiaddrstr.nim

/admin rest api endpoint implementation and test
1. run tests/wakunode_rest/test_rest_admin.nim
https://github.com/waku-org/nwaku/issues/2075

feat: /admin rest api endpoint 

---

waku/waku_archive/driver/sqlite_driver/queries.nim

Observed a bug while testing the retention policy where the database, if filled beyond its size limit, reaches a point where the deletion query `proc deleteOldestMessagesNotWithinLimitQuery(table: string, limit: int): SqlQueryStr = `ceases to function. The database size remains unchanged, leading to an endless loop in the deletion process, especially when the deletion is expected to be achieved via a loop.
This impacts the retention policy process. Turns out that the sqlite DB query assumes that the `id` column alone can uniquely identify rows in the table. If two different rows have the same `id` but different `storedAt` values, then using only `id` in the subquery may not produce the intended results. Given the schema has a composite primary key (`storedAt, id, pubsubTopic`), just …

fix: sqlite limited delete query bug

---

tests/test_waku_lightpush.nim
waku/waku_lightpush/protocol.nim

The Lightpush PFC prohibits empty content topics. The implementation did not reflect this. This PR fixes this: the server now checks if the content topic is empty, and if it is, sends an erring response to the client (no interaction with the P2P network occurs). A new test is added to test this behavior.
Note: this PR only considers the "empty content topic" erring case. There are other erring cases (e.g., decoding error), for which the server does not return a response. I think these are to be addressed in a separate issue / branch.
P.S. I wanted to put a link to the RFC that says that content topic must not be empty, but cannot find it (apparently, it's not [19/WAKU2-LIGHTPUSH](https://rfc.vac.dev/spec/19/)). Can anyone point to the spec that specifies this restriction?
```
./env.sh …
```

fix: return erring response if Lightpush content topic is empty

---

apps/wakunode2/external_config.nim
apps/wakunode2/internal_config.nim
tests/test_peer_manager.nim
tests/test_waku_metadata.nim
tests/test_waku_protobufs.nim
tests/testlib/wakunode.nim
waku/node/config.nim
waku/node/peer_manager/peer_manager.nim
waku/node/waku_node.nim
waku/waku_metadata.nim
waku/waku_metadata/protocol.nim
waku/waku_metadata/rpc.nim

Description:
* Add `cluster-id` flag to `wakunode2`.
* Create `WakuMetadata `protocol. See https://github.com/vacp2p/rfc/pull/619
* Use `WakuMetadata` and `cluster-id` in the peer manager, triggering disconnecitons with peers that support a different `cluster-id` than us. This is applied only if `cluster-id!=0` so since `cluster-id=0` by default, this prevents from breaking backwards compat.

feat: add new metadata protocol

---

docs/contributors/release-process.md

Include Postgres compilation flag to the `docker-manual` job parameters for releases in order for the uploaded image to support Postgres.

chore: adding postgres flag to manual docker job instructions

---

tests/waku_archive/test_driver_postgres.nim
tests/waku_archive/test_driver_sqlite.nim
tests/waku_archive/test_driver_sqlite_query.nim
tests/waku_archive/test_retention_policy.nim
waku/waku_archive/archive.nim
waku/waku_archive/driver.nim
waku/waku_archive/driver/postgres_driver/postgres_driver.nim
waku/waku_archive/driver/queue_driver/queue_driver.nim
waku/waku_archive/driver/sqlite_driver/queries.nim
waku/waku_archive/driver/sqlite_driver/sqlite_driver.nim

`messageHash` attributed added to SQLite, which aims to remove the `id` attribute in upcoming PRs. An associated test case also added. 
migration scripts will be changed after the deletion of `id` attribute in upcoming PRs.
#2112

feat: messageHash attribute added in SQLite + testcase

---

.github/workflows/container-image.yml

Simple PR to extend the validity of the temporary images that are generated when a PR is submitted.
Those images are temporarily stored in: https://quay.io/repository/wakuorg/nwaku-pr?tab=tags
( Thanks @vpavlin for the hint on how to achieve this ! )

chore: Extend temporary pr images validity to 30 days

---

apps/wakunode2/app.nim
waku/waku_api/rest/server.nim

Issue https://github.com/waku-org/nwaku/issues/2135
describes the case when intentionally we do not install certain endpoints.
In such cases we shall report nicely that the offered endpoint is missing due configuration not by error.
1. run: wakunode2 --relay --filter --lightpush --rest=true --rest-port=11111
2. run: curl -i -X GET "http://127.0.0.1:11111/filter/v2/subscriptions/111" -H "accept: application/json"
3. Check response, it shall tell the endpoint is not installed, configuration shall be checked.
4. curl -i -X GET "http://127.0.0.1:11111/admin/v1/peers" -H "accept: application/json"
5. Response shall be Http200 and may list connected peers or may return empty list.
6. curl -i -X GET "http://127.0.0.1:11111/aaaadmin/v1/peers" -H "accept: application/json"
7. Response shall be …

chore: Enhance rest request error handling

---

waku/waku_relay/protocol.nim

This PR lowers gossipsub's `Dhigh` value so that nodes have a more predictable amplification factor (in terms of bandwidth). Before `4 to 12` now `4 to 8`.
Used [this tool](https://github.com/waku-org/research/tree/master/rln-delay-simulations) to run simulations using 1000 nodes and propagation time should not be affected, since average `D` in the network stays the same.
**before**: mean of D among 1000 randomly connected nodes 6.129. Message latency average 509 ms (8991 samples).
```
Statistics. mean=6.129 max=12 min=4
Statistics. mean=509.4595706817929 max=695 min=263
```
**after this PR**: mean of D among 1000 randomly connected nodes 6.124. Message latency average 506 ms  (8991 samples). But with the main difference that max D is `8` instead of `12`.
```
Statistics. mean=6.124 max=8 …
```

chore(networking): lower dhigh to limit amplification factor

---

tests/test_waku_metadata.nim
waku/node/waku_node.nim
waku/waku_metadata/protocol.nim

The shards a node support can dynamically changes and the metadata protocol must be updated at run-time to reflect this.
Tracking #1940
Fix #2105

feat: metadata protocol shard subscription

---

waku/common/databases/db_postgres/dbconn.nim
waku/common/databases/db_postgres/pgasyncpool.nim
waku/waku_archive/driver/postgres_driver/postgres_driver.nim
waku/waku_archive/driver/postgres_driver/postgres_healthcheck.nim

This represents a quite important time reduction in _Postgres_ queries. However, still slower than _SQLite_.
The main issue happened because the we were processing the obtained rows multiple times, and there were an overhead due to changing the rows objects from one type to another.
In this PR we aim to reduce the type conversion overhead by providing a `rowCallback(result: ptr PGresult)` to the `dbconn` object.
( Thanks to @NagyZoltanPeter for the help to achieve that. )
https://github.com/waku-org/nwaku/issues/1842

chore: Optimize postgres - use of rowCallback approach

---

waku/waku_api/rest/lightpush/handlers.nim
waku/waku_api/rest/lightpush/openapi.yaml

This PR aims to enhance the `lightpush rest` API a little.
This was detected by @weboko. Thanks for spotting it !
- We need to review all the open API definitions and make sure all the cases work as expected.
- Important to define examples of how to use each API. Maybe something that can be written within each open API.
- It is not very handy to import openapi.yaml file into _Postman_. The parameter types are not properly described. For example, in the case of `lightpush`, we should make it clear that the `payload` should be base64-encoded. On the other hand, the numeric fields are imported (in Postman) as `"<number>"` but that confuses a little and it should be `<number>` instead, or having an example would help.

fix: lightpush rest 

---

library/waku_thread/inter_thread_communication/requests/protocols/relay_request.nim
waku/common/logging.nim

Updated dependencies, resolved conflict by using in Waku the `LogLevel` type defined in chronicles, fixed libwaku compilation error.
closes #2170

chore: upgrade dependencies v0.22

---

tests/test_waku_discv5.nim
waku/waku_discv5.nim

RFC#31 specify that discv5 must filter out ENRs that don't have `waku2` field or empty capability list.
Closes #2179

feat: discv5 filter peer by capability 

---

tests/waku_archive/test_driver_postgres.nim
waku/common/databases/db_postgres/dbconn.nim
waku/common/databases/db_postgres/pgasyncpool.nim
waku/waku_archive/driver/postgres_driver/postgres_driver.nim

The [prepared statements](https://www.postgresql.org/docs/current/sql-prepare.html#:~:text=A%20prepared%20statement%20is%20a,statement%20is%20planned%20and%20executed.) is a mechanism that allows saving time for common queries.
We are applying that approach for the "select" queries, i.e. queries that come from the _Store_ protocol requests. Notice that we were already applying this in "insert" operations.
With that, we enhance the performance of "select" queries. However, bear in mind that there is an underlying time consumption when performing concurrent queries. I've added a long comment about that in `dbconn.nim`.
https://github.com/waku-org/nwaku/issues/1842

chore: Optimize postgres - prepared statements in select

---

waku/waku_api/jsonrpc/relay/handlers.nim
waku/waku_api/rest/relay/handlers.nim

Fixing leftover check for `define(rln)` from when RLN was compiled in conditionally.
Using the option to get a boolean instead

fix(rest): properly check if rln is used

---

waku/waku_api/rest/admin/client.nim
waku/waku_api/rest/admin/handlers.nim
waku/waku_api/rest/debug/client.nim
waku/waku_api/rest/filter/client.nim
waku/waku_api/rest/filter/handlers.nim
waku/waku_api/rest/filter/legacy_client.nim
waku/waku_api/rest/filter/legacy_handlers.nim
waku/waku_api/rest/health/client.nim
waku/waku_api/rest/lightpush/client.nim
waku/waku_api/rest/lightpush/handlers.nim
waku/waku_api/rest/relay/client.nim
waku/waku_api/rest/relay/handlers.nim
waku/waku_api/rest/rest_serdes.nim
waku/waku_api/rest/serdes.nim

@weboko requested that from browser no-coors mode we need to supprt text/plain content-body requests.
1. Setup a light client node.
2. Send normal rest requests (POST/PUT) with curl as text/plain
3. Should work as normal as with application/json content-type (notice no json format changed)
https://github.com/waku-org/nwaku/issues/2207

chore: Allow text/plain content type descriptor for json formatted content body

---

tests/node/test_wakunode_filter.nim

Implement privacy and security tests for waku node filter.
https://github.com/waku-org/nwaku/pull/2095

test(waku-filter): Waku node filter privacy and security tests

---

tests/node/test_wakunode_filter.nim
tests/testlib/sequtils.nim
tests/waku_filter_v2/test_data.nim
tests/waku_filter_v2/test_waku_client.nim
waku/waku_filter_v2/protocol.nim
waku/waku_filter_v2/subscriptions.nim

Implement unsubscribe tests for waku filter.
https://github.com/waku-org/nwaku/pull/2057

test(waku-filter): Unsubscribe tests

---

tests/all_tests_waku.nim
tests/node/test_wakunode_filter.nim
tests/resources/payloads.nim
tests/testlib/futures.nim
tests/waku_filter_v2/test_all.nim
tests/waku_filter_v2/test_waku_client.nim
tests/waku_relay/crypto_utils.nim
tests/waku_relay/test_all.nim
tests/waku_relay/test_message_id.nim
tests/waku_relay/test_protocol.nim
tests/waku_relay/test_waku_relay.nim
tests/waku_relay/utils.nim
waku/waku_relay/protocol.nim

Implement waku filter relay tests for message id generation
https://github.com/waku-org/nwaku/pull/2096

test(waku-relay): Relay

---

tests/node/test_wakunode_filter.nim
tests/waku_relay/test_protocol.nim

There were some missing keywords that slipped by in recent PRs, making compilation fail. This PR adds those keywords.
There are still some issues within the tests, meaning: 
- Some tests are failing.
- Some tests are not being run.
I'm checking those right as I finish publishing this PR but, if you consider it a good idea, we can merge this in the meantime, so other PRs' jobs are not blocked.

fix(tests): Compilation failure fix.

---

waku/waku_rln_relay/group_manager/on_chain/group_manager.nim

Simple PR to add a little bit more detail when exception occurs while trying to connect to eth client (running the 
https://github.com/waku-org/nwaku-compose/blob/master/register_rln.sh script)

chore: group_manager.nim more except detail when cant connect eth client

---

tests/waku_archive/test_retention_policy.nim
waku/waku_archive/retention_policy/retention_policy_capacity.nim
waku/waku_archive/retention_policy/retention_policy_size.nim

As discussed in #2226, the automatic vacuuming is removed from the retention policy code.
closes #2226

chore: removing automatic vacuuming from retention policy code

---

waku/node/peer_manager/peer_manager.nim

Very simple PR to have better insight if the dial against a node supposed to support the "WakuMetadataCodec".

chore: peer_manager.nim - better feedback if can't dial peer with WakuMetadaCodec

---

apps/wakunode2/app.nim
examples/publisher.nim
examples/subscriber.nim
tests/test_peer_manager.nim
tests/test_waku_discv5.nim
tests/test_waku_peer_exchange.nim
tests/testlib/wakunode.nim
tests/wakunode2/test_app.nim
waku/node/waku_node.nim
waku/waku_discv5.nim
waku/waku_metadata/protocol.nim

Various misc. fixes and changes related to shards, Waku metadata and testings.
Motivated by #2151 which made me realized testing was not ergonomic w.r.t. sharding.
Close #2183

chore: improving node setup w.r.t sharding information

---

tests/waku_core/test_message_digest.nim
waku/waku_core/message/digest.nim

As described in RFC related [change](https://github.com/vacp2p/rfc/pull/632), the deterministic message hash algorithm is updated. Waku message `timestamp` is added to the hash/digest computation. 
closes #2215

chore: deterministic message hash algorithm updated

---

apps/wakunode2/app.nim
apps/wakunode2/external_config.nim
waku/waku_archive/driver/builder.nim
waku/waku_archive/driver/postgres_driver/postgres_driver.nim

It is more handy to be able to easily change the maximum number of _PostgreSQL_ connections a _nwaku_ node can handle simultaneously.

chore: postres driver allow setting the max number of connection from a parameter

---

apps/chat2bridge/chat2bridge.nim
apps/wakunode2/app.nim
tests/test_message_cache.nim
tests/wakunode_jsonrpc/test_jsonrpc_filter.nim
tests/wakunode_jsonrpc/test_jsonrpc_relay.nim
tests/wakunode_rest/test_rest_filter.nim
tests/wakunode_rest/test_rest_legacy_filter.nim
tests/wakunode_rest/test_rest_relay.nim
waku/waku_api/handlers.nim
waku/waku_api/jsonrpc/filter/handlers.nim
waku/waku_api/jsonrpc/relay/handlers.nim
waku/waku_api/message_cache.nim
waku/waku_api/rest/filter/handlers.nim
waku/waku_api/rest/filter/legacy_handlers.nim
waku/waku_api/rest/relay/handlers.nim

I refactored the message cache with the intent to allow fetching messages by pubsub OR content topic. Adding a message now add the missing topic either pubsub or content (still need to be subscribed to either). I also added a check to prevent duplicate messages.
The capacity is now TOTAL instead of PER topic.
Tracking: #2201
Fix: #2192

chore(rest): improved message cache logic

---

ci/Jenkinsfile.release

Using custom registry for hosting Docker images: https://harbor.status.im
Images will be replicated from Harbor repository to Docker Hub

feat: setting image deployment to harbor registry 

---

.github/ISSUE_TEMPLATE/prepare_release.md

Creating GitHub issue template for release work

chore: creating prepare_release template

---

waku/waku_filter_v2/common.nim

Changing the return code to a more meaningful value when `PEER_DIAL_FAILURE` happens.

fix: waku_filter_v2/common: PEER_DIAL_FAILURE ret code change: 200 -> 504

---

waku/waku_store/common.nim

Simple PR to have proper return error codes in Store protocol.
This is inspired by the following comment: https://github.com/waku-org/nwaku/pull/2236#pullrequestreview-1744220535

chore: waku_store/common.nim: correct ret code in PEER_DIAL_FAILURE

---

library/waku_thread/inter_thread_communication/waku_thread_response.nim

Simple PR to properly allocate the string response.
Remember that this response is generated from the _Waku Thread_ and handled by the main thread.

chore: waku_thread_response.nim: use correct alloc() proc to allocate response correctly

---

waku/node/waku_node.nim
waku/waku_archive/archive.nim

This PR fixes an issue that made the whole `wakunode2` to get stuck when applying the retention policy at the beginning of the execution. That happened because we used `waitFor` which blocks everything until the task end.
With that PR, we perform a better retention policy application approach, i.e. a fully asynchronous task that can be canceled anytime. We also simplify the approach by avoiding using a "timer".
1. Start a node with _Store_ configured, with _Postgres for example, and then it many messages, with a wide retention policy (capacity:10000000)
2. Restart the node but in this case with shorter retention policy, capacity:10.
3. The node applies the retention policy, without blocking any other task.
1. Start the node, changing the code a little so that the retention policy is …

fix: archive - simplify and enhance async retention policy application

---

waku/node/peer_manager/peer_manager.nim

Simple PR to reduce log spamming from `peer_manager.nim`.
I changed all the logs. Feel free to comment any log that don't want to change.
closes https://github.com/waku-org/nwaku/issues/1562

chore: peer_manager.nim - reduce logs from debug to trace

---

waku/waku_archive/driver/postgres_driver/postgres_driver.nim

Before this commit, the following execution of a prepared statement returned nothing even though the database had 2 rows to be returned:
```
nwaku-db-1  | 2023-12-14 12:55:17.575 UTC [73] LOG:  execute SelectWithoutCursorAsc: SELECT storedAt, contentTopic, payload, pubsubTopic, version, timestamp, id FROM messages
nwaku-db-1  | 	    WHERE contentTopic IN ($1) AND
nwaku-db-1  | 	          pubsubTopic = $2 AND
nwaku-db-1  | 	          storedAt >= $3 AND
nwaku-db-1  | 	          storedAt <= $4
nwaku-db-1  | 	    ORDER BY storedAt ASC LIMIT $5;
nwaku-db-1  | 2023-12-14 12:55:17.575 UTC [73] DETAIL:  parameters: $1 =
'my/ctopic/1,my/ctopic/2', $2 = '/waku/2/default-waku/proto', $3 =
'1702552968570786800', $4 = '1702552968585347557', $5 = '101'
```
The reason why it is not returning anything is …

fix: postgres_driver.nim: restrict getMessages prepared stmt to query with 1 content topic

---

waku/node/waku_node.nim
waku/waku_archive/archive.nim

This issue was reported/detected by @richard-ramos 
There was a problem that the archive metrics (number of archived messages) were not properly updated regularly.
With this, we update the metrics every minute

fix: update num-msgs archive metrics every minute and not only at the beginning

---

tests/waku_rln_relay/test_wakunode_rln_relay.nim
waku/waku_rln_relay/constants.nim

fix: make rln rate limit spec compliant
closes https://github.com/waku-org/nwaku/issues/2289

fix: make rln rate limit spec compliant

---

examples/cbindings/waku_example.c
library/libwaku.h
library/libwaku.nim

This PR aims to simplify the creation of `waku` node and context, in C-bindings libwaku.
This is motivated by the following comment: https://github.com/waku-org/go-waku/pull/929#discussion_r1419857779

chore: libwaku - avoid using waku_init. Only use waku_new to create node and context

---

waku/waku_filter_v2/rpc.nim

Currently, when receiving a Filter subscription request, the content topics subscribed to were not getting logged.
Modified the logging so content topics are included.

chore: including content topics on FilterSubscribeRequest logs

---

waku/waku_archive/archive.nim

That is helpful to prevent the node to spam the logs when it shares connection to the same Postgres database with other nodes, in which case the following log appears too much:
topics="waku archive" tid=1 file=archive.nim:113 err="error in runStmt: error in dbConnQueryPrepared calling waitQueryToFinish: error in query: ERROR: duplicate key value violates unique constraint "messageindex" DETAIL: Key
(messagehash)=(88f4ee115eef6f233a7dceaf975f03946e18666adda877e38d61be98add934e8) already exists. "

chore: archive - move error to trace level when insert row fails

---

examples/nodejs/waku.js
examples/nodejs/waku_addon.c

NodeJs example adaptation to the latest cbindings approach, where we use a Context and userData.

chore: examples/nodejs - adapt code to latest callback and ctx/userData definitions

---

tests/waku_archive/test_driver_postgres_query.nim

This is to enhance the test coverage in postgres queries.
With this, we test the prepared statement query and the standard query (less optimal.)
This PR is motivated by this @alrevuelta's comment: https://github.com/waku-org/nwaku/pull/2296#issuecomment-1855968983

test: test_driver_postgres - enhance test coverage, multiple and single topic

---

tests/waku_archive/test_waku_archive.nim
tests/waku_store/test_rpc_codec.nim
tests/waku_store/test_waku_store.nim
tests/waku_store/test_wakunode_store.nim
tests/wakunode_rest/test_rest_store.nim
waku/common/paging.nim
waku/node/waku_node.nim
waku/waku_api/jsonrpc/store/handlers.nim
waku/waku_api/rest/store/handlers.nim
waku/waku_api/rest/store/openapi.yaml
waku/waku_archive/archive.nim
waku/waku_archive/common.nim
waku/waku_store/client.nim
waku/waku_store/common.nim
waku/waku_store/rpc.nim
waku/waku_store/rpc_codec.nim

Update `HistoryQuery.ascending` (and related) references to  `direction` so they are consistent with RFC naming. Also, fix a default value issue with it.

refactor(store): HistoryQuery.direction

---

tests/node/test_wakunode_store.nim
tests/testlib/futures.nim
tests/waku_archive/archive_utils.nim
tests/waku_store/test_client.nim
tests/wakunode_rest/test_rest_store.nim

test(store): Implement store tests (1/2)

---

waku/node/peer_manager/peer_manager.nim

After changing the connectivity loop interval from 15 seconds to 1 minute, the node is taking long to find peers at startup. Reverting the change and returning to 15 seconds intervals.
closes #2299

fix: setting connectivity loop interval to 15 seconds

---

CHANGELOG.md

Update CHANGELOG.md for `v0.23.0`.
Notice that we are discarding the change added in this PR https://github.com/waku-org/nwaku/pull/2151 because we found the `waku-simulator` to not establish connections among the nodes set.
note: it may sound this PR as duplicated. The previous one was by mistake made against the `release/0.23` branch.
https://github.com/waku-org/nwaku/issues/2302

docs: CHANGELOG.md for 0.23.0

---

apps/wakunode2/app.nim
apps/wakunode2/external_config.nim
tests/common/test_all.nim
tests/common/test_parse_size.nim
tests/resources/payloads.nim
tests/testlib/wakunode.nim
tests/waku_filter_v2/test_waku_client.nim
tests/waku_relay/test_protocol.nim
waku/common/utils/parse_size_units.nim
waku/node/waku_node.nim
waku/waku_core/message.nim
waku/waku_core/message/default_values.nim
waku/waku_core/message/message.nim
waku/waku_filter_v2/client.nim
waku/waku_filter_v2/protocol.nim
waku/waku_relay/protocol.nim

Change to align the actual message limit with the one written in the spec: https://rfc.vac.dev/spec/64/#message-size
Notice that the spect states 150KB but we are setting the maximum to 150KiB because that sounds more aligned with the actual default value defined within nim-libp2p (1024 * 1024)
closes https://github.com/waku-org/nwaku/issues/2297

chore: message.nim - set max message size to 150KiB according to spec

---

waku/waku_api/rest/debug/types.nim
waku/waku_api/rest/filter/types.nim
waku/waku_api/rest/relay/types.nim
waku/waku_api/rest/serdes.nim
waku/waku_api/rest/store/types.nim

The following vendors have changes but are not being updated for the reason explained.
nim-web3: not updated because unit tests started to fail and no straightforward solution found.
nim-toml-serialization: not updated because it introduced a breaking change on how the --config-file attribute is parsed. The array attributes now need a comma. For example, the following attribute from within the config file:
pubsub-topic = [ "/waku/2/default-waku/proto" "/waku/2/testing-store" ]
... should be converted to:
pubsub-topic = [ "/waku/2/default-waku/proto", "/waku/2/testing-store" ]
and we cannot accept that breaking change
closes https://github.com/waku-org/nwaku/issues/2329

chore: bump vendors for 0.24.0

---

waku/waku_discv5.nim

Bootstrapping nodes should not be filtered out.
Closes #2162

fix(discv5): add bootnode filter exception

---

examples/publisher.nim
examples/subscriber.nim

I followed the instructions in the [examples](https://github.com/waku-org/nwaku/tree/master/examples) readme. After running `make example2`, everything appeared to be in order. However, when executing `./build/subscriber`, I encountered the following message:
```
NTC 2024-01-02 16:50:37.824+02:00 starting subscriber                        tid=132009 file=subscriber.nim:35 wakuPort=50000 discv5Port=8000
/some/nice/path/nwaku/examples/subscriber.nim(102) subscriber
/some/nice/path/nwaku/vendor/nim-chronos/chronos/internal/asyncfutures.nim(660) cb
Error: unhandled exception: Asynchronous task [setupAndSubscribe() at subscriber.nim:34] finished with an exception "LPError"!
Message: node record is required
Stack trace: /some/nice/path/nwaku/examples/subscriber.nim(102) subscriber …
```

fix(examples): Set `record` to the Waku Node Builder as it is required.

---

tests/testlib/sequtils.nim

test(peer-connection-managenent): Functional Tests (#2321) @ e9d083b2 introduced build error through ambigous function call, testwaku build failed on master.
It turned out, some commits ago a new - duplicated toBytes proc was introduced that makes build fail for testwaku.
Removed it and checked that all tests on master no runs fine.
- [X ] tests/testlib/sequtils.nim removed unnecessary toBytes

fix: build failure on testwaku

---

tests/wakunode_rest/test_rest_admin.nim
waku/waku_api/rest/admin/client.nim
waku/waku_api/rest/admin/handlers.nim
waku/waku_api/rest/admin/openapi.yaml
waku/waku_api/rest/admin/types.nim

Adding admin REST endpoint to retrieve the serving node's subscriber filter clients and their subscribed pubsub and content topics.
Endpoint: GET /admin/v1/filter/subscriptions
closes #2290

feat: adding filter data admin endpoint (REST)

---

CHANGELOG.md

Update CHANGELOG.md to reflect the latest `v0.23.1` version created.

chore: Update CHANGELOG.md to reflect bug fix for issue #2317

---

CHANGELOG.md

Update CHANGELOG.md for `v0.24.0`
My first release. Yeah! One thing of note, for this release is https://github.com/waku-org/nwaku/issues/2305
I also had to create the notes manually because `make release-notes` for me returns `failed to discovery repository top level, error: exit status 128 - fatal: detected dubious ownership in repository at '/opt/sv4git/repo'`
Tracking https://github.com/waku-org/nwaku/issues/2343

chore: update CHANGELOG.md for v0.24.0

---

docs/benchmarks/postgres-adoption.md

Simple PR that adds metadata information (title and description), needed to make the _Docusaurus_ platform to properly parse it.

docs: postgres-adoption.md add metadata title, description, and better first-readable-title

---

apps/chat2/chat2.nim
apps/chat2bridge/chat2bridge.nim
apps/wakunode2/app.nim
apps/wakunode2/external_config.nim
tests/node/test_wakunode_filter.nim
tests/test_peer_manager.nim
tests/test_wakunode_filter_legacy.nim
tests/waku_filter_v2/test_waku_client.nim
tests/waku_filter_v2/test_waku_filter_protocol.nim
tests/waku_filter_v2/waku_filter_utils.nim
tests/waku_store/test_wakunode_store.nim
tests/wakunode_jsonrpc/test_jsonrpc_admin.nim
tests/wakunode_jsonrpc/test_jsonrpc_filter.nim
tests/wakunode_rest/test_rest_admin.nim
tests/wakunode_rest/test_rest_filter.nim
tests/wakunode_rest/test_rest_legacy_filter.nim
waku/node/waku_node.nim
waku/utils/tableutils.nim
waku/waku_api/rest/admin/handlers.nim
waku/waku_filter/protocol.nim
waku/waku_filter_v2.nim
waku/waku_filter_v2/protocol.nim
waku/waku_filter_v2/subscriptions.nim

As during Status dogfooding it turned out we need to handle situation with stale filter subscriptions to ensure  service quality.
NOTE: This become a relative large refactor on management filter subscription. Sorry for that to issue such a big PR.
The structure changes involved a lot changes in filter v2 test.
But because of the I would like to ask you to start reviewing it, if there is something not ok should come early as possible.
THX!!!
NOTE2: Still a work in progress, as realized need to add some more test cases.
https://github.com/waku-org/nwaku/issues/2293
covers also: https://github.com/waku-org/nwaku/issues/2338

chore: Refactor of FilterV2 subscription management with Time-to-live maintenance

---

tests/wakunode_rest/test_rest_admin.nim

Generalized test to not rely on order of neither peers subscriptions nor of subscription criteria within each peer.

fix: making filter admin data test order independent

---

apps/chat2/chat2.nim
apps/chat2bridge/chat2bridge.nim
examples/publisher.nim
tests/test_wakunode.nim
tests/test_wakunode_lightpush.nim
tests/waku_relay/test_wakunode_relay.nim
tests/waku_rln_relay/test_wakunode_rln_relay.nim
tests/wakunode2/test_validators.nim
tests/wakunode_jsonrpc/test_jsonrpc_relay.nim
tests/wakunode_rest/test_rest_relay.nim
waku/node/waku_node.nim
waku/waku_api/rest/relay/handlers.nim

When calling the endpoint `POST /relay/v1/auto/messages/{topic}` with an invalid content topic, the API response was 200 OK even though it had failed internally in the node.
Added error handling so a proper status code and message get returned.
closes #2190

chore: improve POST /relay/v1/auto/messages/{topic} error handling

---

tests/node/test_wakunode_filter.nim

Fixes https://github.com/waku-org/nwaku/issues/2175. 
This fixes one test for filter clients: filter clients should continue to receive messages from active subscriptions after a restart. Although the behaviour in the Waku node was as expected, the test failed for two reasons:
1. a Waku node will not update its advertised addresses if its listening port was dynamically allocated after instantiating the node with port `0`. This behaviour was recently fixed for the `wakunode2` app, but not for the `WakuNode` object itself. Issue/feature request reported here: https://github.com/waku-org/nwaku/issues/2359. For now this was fixed by using statically allocated ports.
2. for some reason just `stop`ping an instantiated `node` object does not fully clean up the underlying libp2p switch and the …

fix: Fix test for filter client receiving messages after restart

---

apps/chat2/config_chat2.nim
apps/wakunode2/external_config.nim
tests/waku_rln_relay/test_rln_group_manager_onchain.nim
waku/waku_rln_relay/constants.nim
waku/waku_rln_relay/group_manager/on_chain/group_manager.nim
waku/waku_rln_relay/group_manager/on_chain/retry_wrapper.nim

Removes dependence on eth_subscribe since websocket connections can be flaky.
1. Pass in a http rpc provider instead of ws while running nwaku / `make -j16 test`
2. Generate an rln keystore using
```
./build/wakunode2 generateRlnKeystore \
--rln-relay-cred-path:./rlnKeystore.json \
--rln-relay-eth-client-address:https:<> \
--rln-relay-cred-password:sup3rsecure \
--rln-relay-eth-contract-address:0xF471d71E9b1455bBF4b85d475afb9BB0954A29c4 \
--rln-relay-eth-private-key:<> \
--execute
```
insert your https rpc provider as well as private key in the required positions
addresses part of #2345

chore(rln-relay): remove websocket from OnchainGroupManager

---

waku/waku_lightpush/protocol.nim

While debugging message loss issues with status, had noticed that messageHash is not logged for lightpush which helps in debugging to know if message is received by the fleet nodes.
Note: Tested by using a go-waku lightpush client to ensure messageHash is logged properly

chore: log messageHash for lightpush request received

---

docs/contributors/release-process.md

Adding to the release process doc the step of updating nwaku-compose's image after release

chore: adding nwaku compose image update to release process

---

waku/node/waku_node.nim
waku/waku_relay/protocol.nim

It was noticed that RLN validator wasn't configured for dynamically subscribed pubsub topics.
Therefore, we decided to implement the same approach to validators as in go-waku: we're adding now support for default validators, which will be run for all pubsub topics. We're adding RLN validator to the default validators whenever RLN is enabled.
Simulated the scenario in which we send an invalid message on a dynamically added pubsub topics with and without this fix.
With this fix:
Without it:
Thanks @AlejandroCabeza for it!
Not adding the test in this PR as it is added in Alex's PR of the RLN test suite
Also, thanks @chaitanyaprem for helping from go-waku side to maintain consistency between both :)
closes #2365

fix: adding rln validator as default

---

tests/wakunode_rest/test_rest_store.nim
waku/waku_api/rest/store/client.nim
waku/waku_api/rest/store/handlers.nim
waku/waku_store/protocol.nim
waku/waku_store/self_req_handler.nim

A node that handles REST-Store requests it normally acted as a Store-client and therefore it retrieved the messages from another Store-node.
With these changes, we allow a node that has Store mounted, to retrieve its own messages. In other words, the node can act as a Store-server of its own messages.
* test_rest_store.nim: add new test to validate that the self-node can retrieve its own messages to the REST client.
* rest/store/client.nim: add new proc to allow making a GET store request without peerAddr.
* rest/store/handle.nim: add logic to handle requests that doesn't provide peerAddr but the self/local node has Store mounted. In this case the self/local node will retrieve its local stored messages.
* waku_store/self_req_handler.nim: logic to handle "store" requests allowing the …

chore: REST store - get msgs from self node when store is mounted and no peerAddr is passed

---

ci/Jenkinsfile.release

Simple PR to enforce the `-d:postgres` flag is always being set when creating a release image.
Jenkins is not 100% reliable in terms of its parameters and therefore, we need to enforce the usage of this compulsory compilation flag in releases.
With that, we want to prevent errors like the following:
```
2024-01-26 16:05:49 ERR 2024-01-26 14:05:49.204+00:00 4/7 Mounting protocols failed              topics="wakunode main" tid=1 file=wakunode2.nim:89 error="failed to setup archive driver: Postgres has been configured but not been compiled. Check compiler definitions."
```
closes https://github.com/waku-org/nwaku/issues/2372

chore: ci/Jenkinsfile.release: enforce -d:postgres flag is always used

---

tests/waku_lightpush/test_client.nim
waku/waku_lightpush/client.nim

This PR:
- Enhances the test protection against `core dump` issue when an exception is raised within the test body.
- Enables the "Valid Payload Sizes" test.
- Performs better exception management in `waku_lightpush/client.nim`
See the commit list for better details :)
The test of interest can be run with:
`nim c -r -d:chronicles_log_level=DEBUG -d:release -d:postgres  -d:rln --passL:librln_v0.3.4.a --passL:-lm -d:nimDebugDlOpen ./tests/waku_lightpush/test_client.nim test "Valid Payload Sizes"`
Notice that this test will still fail because it is trying to push a message too large. I suggest using the msg size constants so that the test is always aligned with those values: https://github.com/waku-org/nwaku/blob/2f8e8bcb529ebe7ad1528de213b39d887cf08596/waku/waku_core/message/default_values.n …

fix: Lightpush fixes

---

ci/Jenkinsfile.release

This PR fixes an issue that came from a change where we enforced the `-d:postgres` flag to always be used when creating a release.
Before this fix, the `-d:postgres` wasn't considered properly as a `NIMFLAG`. Instead, it was considered as a Docker parameter.
@apentori - apologies for the inconvenience and thanks for the hints!
https://github.com/waku-org/nwaku/issues/2372

fix: bug fix in ci/Jenkinsfile.release: make -d:postgres part of NIMFLAGS

---

tests/wakunode_rest/test_rest_relay.nim
waku/waku_api/rest/relay/handlers.nim

Small PR adding for the `/relay/v1/auto/messages/{topic}` endpoint the same checks implemented in https://github.com/waku-org/nwaku/pull/2373 for `/relay/v1/messages/{topic}`
closes #2284

feat: running validators in /relay/v1/auto/messages/{topic}

---

waku/node/waku_switch.nim

Added support to yamux. Since the order of multiplexers matter, it's added after mplex so it continues being the default multiplexer (instead of completely removing mplex, as suggested in the og issue). This is required since go-libp2p is removing support for mplex.
Closes #2331

feat: add yamux support

---

examples/cbindings/waku_example.c
examples/nodejs/waku_addon.c
examples/python/waku.py
library/libwaku.nim

This change is needed so that interoperability with other languages becomes simpler. Particularly, this simplification is needed from the Python point of view, where it is tricky to pass a void** as a parameter to an FFI function.

chore: libwaku - simpler ctx mgmt. Param now receiving void* instead of void**

---

Makefile
apps/benchmarks/benchmarks.nim
waku.nimble

Add simple tool to benchmark RLN proof generation and verification.
Run as:
```
make benchmarks LOG_LEVEL=NOTICE
./build/benchmarks
```
Output:
```
Proof generation times: 85 milliseconds, 723 microseconds, and 313 nanoseconds
Proof verification times: 2 milliseconds, 707 microseconds, and 137 nanoseconds
```

feat: Add tool to benchmark RLN proof generation/verification

---

apps/networkmonitor/networkmonitor.nim
apps/networkmonitor/networkmonitor_config.nim

This PR adds support of RLN into NetworkMonitor - so that we can tun it for The Waku Network
1. `make networkmonitor`
1. ```
/build/networkmonitor --rln-relay-eth-client-address=$ETH_CLIENT_ADDRESS --bootstrap-node="enr:-QESuEC1p_s3xJzAC_XlOuuNrhVUETmfhbm1wxRGis0f7DlqGSw2FM-p2Ugl_r25UHQJ3f1rIRrpzxJXSMaJe4yk1XFSAYJpZIJ2NIJpcISygI2rim11bHRpYWRkcnO4XAArNiZub2RlLTAxLmRvLWFtczMud2FrdS50ZXN0LnN0YXR1c2ltLm5ldAZ2XwAtNiZub2RlLTAxLmRvLWFtczMud2FrdS50ZXN0LnN0YXR1c2ltLm5ldAYfQN4DgnJzkwABCAAAAAEAAgADAAQABQAGAAeJc2VjcDI1NmsxoQJATXRSRSUyTw_QLB6H_U3oziVQgNRgrXpK7wp2AMyNxYN0Y3CCdl-DdWRwgiMohXdha3UyDw" --pubsub-topic=/waku/2/rs/1/0  --pubsub-topic=/waku/2/rs/1/1   --pubsub-topic=/waku/2/rs/1/2  --pubsub-topic=/waku/2/rs/1/3  --pubsub-topic=/waku/2/rs/1/4  --pubsub-topic=/waku/2/rs/1/5 …
```

feat(networkmonitor): add support for rln

---

apps/wakucanary/certsgenerator.nim
apps/wakucanary/wakucanary.nim

Automatically generating a self signed certificate in Waku Canary if not provided and WSS is used.
Notice that the keys and certificate are generated only if `OpenSSL` is installed. It comes preinstalled in Ubuntu, other common Linux distributions and MacOS.
If `openssl` command is not available and certificates are not provided, an error message is shown.
1. Build Waku Canary: `make wakucanary`
3. Run it on a WSS address without setting certificates: `./build/wakucanary --address=/dns4/node-01.gc-us-central1-a.status.test.statusim.net/tcp/443/wss/p2p/16Uiu2HAmGDX3iAFox93PupVYaHa88kULGqMpJ7AEHGwj3jbMtt76 --protocol=relay`
closes #2349

chore: automatically generating certs if not provided (Waku Canary)

---

apps/chat2/chat2.nim
apps/chat2/config_chat2.nim
apps/wakunode2/app.nim
tests/node/test_wakunode_relay_rln.nim
tests/waku_rln_relay/test_all.nim
tests/waku_rln_relay/test_rln_nonce_manager.nim
tests/waku_rln_relay/test_waku_rln_relay.nim
tests/waku_rln_relay/test_wakunode_rln_relay.nim
waku/waku_api/jsonrpc/relay/handlers.nim
waku/waku_api/rest/relay/handlers.nim
waku/waku_rln_relay/group_manager/group_manager_base.nim
waku/waku_rln_relay/nonce_manager.nim
waku/waku_rln_relay/rln_relay.nim

This PR introduces a new submodule within `waku_rln_relay`, called the `NonceManager` which provides functionality to fetch the next given `nonce`/`messageId` on a per epoch basis which is required to generate rln-v2 proofs.
It also fixes the bad function signature of `appendRLNProof` which previously returned a boolean upon execution. It now returns a result.
1. `RLN_V2=true make -j16 test` is broken at the moment since the onchain/static group manager tests have not been updated yet. However, the NonceManager is independent of those changes, and can be run, and has not been guarded by the `rln_v2` feature flag upon running `make -j16 test` 
closes https://github.com/waku-org/nwaku/issues/2415

feat(rln-relay-v2): nonce/messageId manager

---

apps/wakunode2/wakunode2.nim

Moves the TWN default config into the wakunode2 default sub-command branch (i.e run the wakunode), instead of running it before the keystore generator subcommand
1. `make -j16 wakunode2`, run the keystore generator
closes #2422

fix(wakunode2): move node config inside app init branch

---

library/libwaku.h

While generating the bindings for rust, I ran into the error `unknown type name 'size_t'`. This PR adds a header to `libwaku.h` to fix that problem. 
Curiously enough, in the c-bindings example we don't have such error because we include `stdio.h` which includes `stddef.h`

chore: add stdef.h to libwaku.h

---

examples/cbindings/waku_example.c
library/callback.nim
library/libwaku.h
library/libwaku.nim
library/waku_thread/waku_thread.nim

1. Instead of using a global variable for the event callback, each wakunode instance will have their own event callback
2. Uses some of the code changes from https://github.com/waku-org/nwaku/pull/2089 to pass the `userData` to the callbacks

feat: `eventCallback` per wakunode and `userData` 

---

tests/waku_rln_relay/rln_v2/test_rln_relay_v2_serde.nim
waku/waku_rln_relay/conversion_utils.nim
waku/waku_rln_relay/rln/wrappers.nim

This PR includes tests for the serde changes in rln-v2, including `toLeaf` and `proofGen/proofVerify`
1.
`nim c --out:build/rln_v2_serde -r -d:chronicles_log_level=INFO --verbosity:0 --hints:off -d:git_version="v0.24.0-rc.0-35-g50308e" -d:release --passL:librln_v0.4.1.a --passL:-lm -d:rln_v2 tests/waku_rln_relay/rln_v2/test_rln_relay_v2_serde.nim` (provided you ran `RLN_V2=true make -j16 update` before)
OR
`RLN_V2=true make -j16 test`

chore(rln-relay-v2): add tests for serde

---

tests/wakunode_rest/test_rest_relay.nim
waku/waku_relay/protocol.nim

Maximum message size is a configurable parameter. Therefore, we're updating the validator that we run in our REST handlers to check against the configured value.
Notice that for clusterId=1, the configuration is overriden to the Waku Network's max message size during app startup.
https://github.com/waku-org/nwaku/blob/50308eda0d678ab1a63136d6ed931ba9fc5a700e/apps/wakunode2/wakunode2.nim#L78
closes #2406

fix: check max message size in validator according to configured value

---

tests/wakunode2/test_validators.nim
tests/wakunode_rest/test_rest_filter.nim
tests/wakunode_rest/test_rest_relay.nim
tests/wakunode_rest/test_rest_store.nim
waku/waku_api/rest/filter/client.nim
waku/waku_api/rest/filter/types.nim
waku/waku_api/rest/relay/types.nim
waku/waku_api/rest/store/types.nim

The "meta" field is late addition to the Waku Message specification. It is currently supported in go-waku and not in nwaku. We're implementing its support in this PR.
closes #2214 
We also wanted to avoid responding with an error when an extra field is sent in a POST request.
There seems to be an issue in the `nim-json-serialization` dependency that throws an exception when this happens. Will report and track the issue to make sure it gets fixed

feat: supporting meta field in WakuMessage

---

apps/wakunode2/app.nim
library/waku_thread/inter_thread_communication/requests/node_lifecycle_request.nim
waku/common/error_handling.nim
waku/node/waku_node.nim
waku/waku_archive/driver.nim
waku/waku_archive/driver/builder.nim
waku/waku_archive/driver/postgres_driver/postgres_driver.nim
waku/waku_archive/driver/postgres_driver/postgres_healthcheck.nim
waku/waku_rln_relay/group_manager/group_manager_base.nim
waku/waku_rln_relay/group_manager/on_chain/group_manager.nim
waku/waku_rln_relay/group_manager/on_chain/retry_wrapper.nim
waku/waku_rln_relay/rln_relay.nim

This PR follows the pattern set by the waku_archive protocol, which propagates fatal error handling to appropriate protocols, without which the node goes into UB.
1. Run a wakunode, after the protocols are mounted, disable your internet. you will see the following -

fix(rln-relay): graceful shutdown with non-zero exit code

---

README.md

README points wrong docs link after recent docs refactor

docs: Wrong docs link

---

examples/cbindings/waku_example.c
library/libwaku.h
library/libwaku.nim
library/waku_thread/inter_thread_communication/requests/debug_node_request.nim
library/waku_thread/inter_thread_communication/waku_thread_request.nim

Adding new function that helps to extract the multiaddresses the node is listening to. The information is returned as a string with that contains a JSON-array. e.g.: `["/ip4/100.79.7.227/tcp/60001/p2p/16Uiu2HAm2eqzqp6xn32fzgGi8K4BuF88W4Xy6yxsmDcW8h1gj6ie"]`
kudos to @richard-ramos! It's been a great pair programming session :)
- examples/cbindings/waku_example.c: adapt signatures to accept the recently added `void* userData` (outside of the scope of this PR.)
- examples/cbindings/waku_example.c: invoke `waku_listen_addresses(ctx, event_handler, userData);`
- library/waku_thread/inter_thread_communication/requests/debug_node_request.nim: new file added.
- library/libwaku.nim, libwaku.h:  waku_listen_addresses implementation
1. make cwaku_example -j11
2. `./build/cwaku_example …

chore: bindings return multiaddress array

---

tests/waku_archive/test_retention_policy.nim
waku/waku_archive/driver.nim
waku/waku_archive/driver/postgres_driver/postgres_driver.nim
waku/waku_archive/driver/queue_driver/queue_driver.nim
waku/waku_archive/driver/sqlite_driver/sqlite_driver.nim
waku/waku_archive/retention_policy/builder.nim
waku/waku_archive/retention_policy/retention_policy_capacity.nim
waku/waku_archive/retention_policy/retention_policy_size.nim
waku/waku_archive/retention_policy/retention_policy_time.nim

The new proc, `decreaseDatabaseSize`, will have different implementations per driver. For example, in future commits, we will implement a size retention policy thanks to partitions management, in Postgres.

refactor: new proc to foster different size retention policy implementations

---

apps/benchmarks/benchmarks.nim
apps/chat2/chat2.nim
apps/chat2/config_chat2.nim
apps/networkmonitor/networkmonitor.nim
apps/networkmonitor/networkmonitor_config.nim
apps/wakunode2/app.nim
apps/wakunode2/external_config.nim
apps/wakunode2/networks_config.nim
apps/wakunode2/wakunode2.nim
tests/node/test_wakunode_relay_rln.nim
tests/waku_rln_relay/rln_v2/test_rln_relay_v2_serde.nim
tests/waku_rln_relay/test_waku_rln_relay.nim
tests/waku_rln_relay/test_wakunode_rln_relay.nim
tests/wakunode_jsonrpc/test_jsonrpc_relay.nim
tests/wakunode_rest/test_rest_health.nim
tests/wakunode_rest/test_rest_relay.nim
waku/waku_rln_relay/constants.nim
waku/waku_rln_relay/nonce_manager.nim
waku/waku_rln_relay/rln_relay.nim

* Remove hardcoded `EpochUnitSeconds` and allows configuring it via `rln-relay-epoch-sec`. 
* It also sets TheWakuNetwork default epoch value in [here](https://github.com/waku-org/nwaku/blob/caad9f88100923b6aed2da5b13b8d7a2e30db290/apps/wakunode2/networks_config.nim#L30) as per [spec](https://rfc.vac.dev/spec/64/#rln-parameters)
* This allows anyone to deploy another network with their own RLN configuration.

chore: remove rln epoch hardcoding

---

apps/wakunode2/app.nim
apps/wakunode2/external_config.nim
tests/all_tests_waku.nim
tests/wakunode_rest/test_all.nim
tests/wakunode_rest/test_rest_admin.nim
tests/wakunode_rest/test_rest_cors.nim
tests/wakunode_rest/test_rest_debug.nim
tests/wakunode_rest/test_rest_filter.nim
tests/wakunode_rest/test_rest_health.nim
tests/wakunode_rest/test_rest_legacy_filter.nim
tests/wakunode_rest/test_rest_lightpush.nim
tests/wakunode_rest/test_rest_relay.nim
tests/wakunode_rest/test_rest_store.nim
waku/waku_api/rest/origin_handler.nim
waku/waku_api/rest/server.nim

Long running CORS issue come to the end. 
After serveral ping pong on solution about where and how CORS headers / aka allowed origin / shall be solved for nim-waku rest services we have full flexibility on configuring this behavior of rest responses.
Main goal is to enable calling rest api from inside a browser window against a local wakunode. Without this solution browsers are rejecting to properly propage the response from the service to the script layer.
This act of course as a protection layer, but also prevented js-waku to correctly use nwaku REST services.
Change to the CLI argument!
New option introduced for rest:
--rest-allow-origin=<string>
- option can be repeated multiple times
- value can contain ? or * as wildcard characters for greater flexibility (e.g. easier to describe …

chore: Implemented CORS handling for nwaku REST server

---

Dockerfile
Makefile
ci/Jenkinsfile.release

This way we get both the full commit and the version, whether it's a proper release or not.
```
> d inspect docker.io/wakuorg/nwaku:wakunode2-v0.25.0-rc.0-33-ga49930 | grep -A4 commit
"build": "https://ci.infra.status.im/job/nim-waku/job/docker-manual/119/",
"commit": "a4993005944741a4418ded35c8a0a37d8271bba6",
"description": "Wakunode: Waku client",
"maintainer": "jakub@status.im",
"source": "https://github.com/waku-org/nwaku",
"version": "v0.25.0-rc.0-33-ga49930"
```

chore(ci): use git describe for image version

---

library/alloc.nim
library/events/json_message_event.nim
library/libwaku.nim
library/waku_thread/inter_thread_communication/requests/protocols/relay_request.nim

As defined in the [bindings](https://rfc.vac.dev/spec/36/#extern-unsinged-int-waku_relay_publishchar-messagejson-char-pubsubtopic-int-timeoutms-char-jsonresp), `waku_relay_publish` returns a message id on success

fix: return message id on `waku_relay_publish`

---

tests/waku_rln_relay/test_rln_group_manager_onchain.nim
tests/waku_rln_relay/test_wakunode_rln_relay.nim
waku/waku_rln_relay/group_manager/on_chain/group_manager.nim
waku/waku_rln_relay/nonce_manager.nim
waku/waku_rln_relay/rln/wrappers.nim
waku/waku_rln_relay/rln_relay.nim

This PR includes changes to the `test_rln_group_manager_onchain` with fixes to some of the serde done at the event parsing side.
> [!NOTE]
> The rln-v2 test suite is not feature complete yet, i.e it has to be integrated in other test suites like `test_wakunode_rln_relay.nim` and `test_waku_rln_relay.nim`, those will be addressed in follow up PRs
1. `source env.sh`
2. `nim c --out:build/onchain_rln_test -r -d:chronicles_log_level=DEBUG -d:rln_v2:true -d:os=Darwin --verbosity:0 --hints:off -d:chronicles_log_level=TRACE -d:git_version="v0.24.0-rc.0-35-g50308e" -d:release --passL:librln_v0.4.1.a --passL:-lm  tests/waku_rln_relay/test_rln_group_manager_onchain.nim`
closes #2481

chore(rln-relay-v2): added tests for onchain rln-relay-v2

---

tests/testlib/wakucore.nim
tests/waku_core/test_time.nim
waku/waku_core/time.nim

Copy of https://github.com/waku-org/nwaku/pull/2476 for merging purpose.
> Description
> The function [getNanosecondTime](https://github.com/waku-org/nwaku/blob/master/waku/waku_core/time.nim#L12) does not > work on 32 bit architecture, so this is a suggestion of a fix.
> 
> Changes
> Use int64.
> 
> To reproduce the problem
> Pass --cpu:i386 -t:-m32 -l:-m32 to the nim compiler
> 
> Issue
> closes # https://github.com/waku-org/nwaku/issues/2475

fix: time on 32 bits architecture

---

waku/node/waku_node.nim

Filter subscribe now trigger an topic subscription event which result in Waku Metadata being updated.
Previously light nodes would get disconnected because they had no shards specified in Waku Metadata.
Close https://github.com/waku-org/nwaku/issues/2491

fix: emit event when FILTER subscribe to a topic.

---

waku/README.md

The link to the DNS discovery tutorial is currently broken. This commit should fix it
Removed one of the ".." from the link path.
Click the links

docs: Update link to DNS discovery tutorial

---

waku/waku_archive/driver/builder.nim

Previously, the postgres migration was imported outside of the feature flag and hence caused a dependency on the libpq library

fix(postgres): import under feature flag

---

tests/waku_rln_relay/test_waku_rln_relay.nim
waku/waku_rln_relay/rln_relay.nim

~Instead of using the `epoch` as the key for the nullifierLog, `externalNullifier` was being used. This could lead to a node only accepting one valid message sent during an epoch `e`, and reject all other messages sent during epoch `e`.~
Made the NullifierLog properly map from Epoch to Nullifiers instead of ExternalNullifier to ProofMetadata.
Optimized by nesting the hashmap to locate duplicates faster instead of searching an array.

fix(rln-relay): make nullifier log abide by epoch ordering

---

.github/workflows/ci.yml
tests/postgres-docker-compose.yml
tests/waku_archive/test_driver_postgres.nim
waku/waku_archive/driver.nim
waku/waku_archive/driver/builder.nim
waku/waku_archive/driver/postgres_driver.nim
waku/waku_archive/driver/postgres_driver/migrations.nim
waku/waku_archive/driver/postgres_driver/partitions_manager.nim
waku/waku_archive/driver/postgres_driver/postgres_driver.nim
waku/waku_archive/driver/queue_driver/queue_driver.nim
waku/waku_archive/driver/sqlite_driver/sqlite_driver.nim

First of all, special thanks to @NagyZoltanPeter for suggesting such a great partition proposal :partying_face: !
In this PR we start managing the partition creation and deletion.
This is interesting from the database size maintenance pov.
There will always be a current partition.
The `loopPartitionFactory` proc responsible for making sure that there will always be a future partition available.
The `loopPartitionFactory` will check every `DefaultDatabasePartitionCheckTimeInterval` (10 minutes hard-coded) whether a new partition should be created or not.
The `PartitionsRangeInterval` is also hard-coded (1 hour.) This value establishes the time window to store messaged based in their `storedAt` (epoch time in nanoseconds.)
Notice that the partitions are *only* removed when `size` retention …

feat: Postgres partition implementation

---

library/libwaku.h
library/libwaku.nim
library/waku_thread/waku_thread.nim

While working with the rust bindings I noticed that when I closed the example program, it segfaulted, and this happened due to the waku thread still being alive. This PR adds a `waku_destroy` function that stops the thread, as well as firing a signal so the code does not stay stuck at https://github.com/waku-org/nwaku/blob/9ef2eccb8aa19e80a9381dcb2ece29718ebce30f/library/waku_thread/waku_thread.nim#L59

feat(c-bindings): add function to dealloc nodes

---

Makefile
tests/waku_rln_relay/test_rln_group_manager_onchain.nim
tests/waku_rln_relay/test_waku_rln_relay.nim
tools/rln_db_inspector/rln_db_inspector.nim
waku/waku_rln_relay/group_manager/on_chain/group_manager.nim
waku/waku_rln_relay/rln/wrappers.nim

- **fix(rln-relay): silence error on startup when metadata is not found**
- **chore: fix fetching value from option**
This PR silences the execution error that is received when trying to fetch the rln metadata from the db.
Zerokit's PR: https://github.com/vacp2p/zerokit/pull/231
If it returns a buf of len 0, then we assume the metadata is not found, and proceed execution as usual.
1. `make -j16 test`
closes #2471

fix(rln-relay): handle empty metadata returned by getMetadata proc

---

waku/waku_metadata/rpc.nim

This is the solution #3 described in https://github.com/waku-org/nwaku/pull/2509
Add a new field for the shards and deprecate field 2, and for at least 2 releases support both fields i.e.:
```proto
message WakuMetadataRequest {
optional uint32 cluster_id = 1;
repeated uint32 shards = 2  [deprecated = true];
repeated uint32 shards = 3;
}
```
We would use getPackedRepeatedField on field 3, and if it's not populated, use getPackedRepeatedField on field2, and if it's empty, use getRepeatedField. This would solve the problem of nwaku not understanding go-waku's packed field. 
For writing, we'd still use write3 for field 2 and writePacked for field3.
Currently go-waku does not care about the format of the field for reading data since it seems to try decoding both packed and unpacked data. …

fix: introduce new field for shards in metadata protocol

---

CHANGELOG.md

CHANGELOG for next, v0.26.0 release!
@jm-clius: Please make your point on decomissioning Filter v1 and its API in the next release. Thank you.
CC: @chair28980

chore: update CHANGELOG for v0.26.0 release

---

.github/workflows/ci.yml
.github/workflows/container-image.yml
Makefile
tests/all_tests_waku.nim
tests/waku_rln_relay/rln/waku_rln_relay_utils.nim
tests/waku_rln_relay/rln_v2/test_rln_relay_v2_serde.nim
tests/waku_rln_relay/test_all.nim
tests/waku_rln_relay/test_rln_nonce_manager.nim
tests/waku_rln_relay/test_waku_rln_relay.nim
tests/waku_rln_relay/test_wakunode_rln_relay.nim
tests/wakunode_rest/test_rest_relay.nim
waku/waku_api/rest/relay/handlers.nim
waku/waku_rln_relay/constants.nim
waku/waku_rln_relay/conversion_utils.nim
waku/waku_rln_relay/nonce_manager.nim
waku/waku_rln_relay/rln/wrappers.nim
waku/waku_rln_relay/rln_relay.nim

Follows suit with the changes that were made in https://github.com/waku-org/nwaku/pull/2482, https://github.com/waku-org/nwaku/pull/2484
Updates the wakunode tests for rln-v2, defaulting the UserMessageLimit to 1 for testing purposes.
> [!NOTE]
> This PR wraps up the modifications to all the tests related to rln-v2, and does not add additional test vectors. We should be ready to test this in waku-simulator.
1. `RLN_V2=true make -j16 test`
closes #2345

chore(rln-relay-v2): wakunode testing + improvements

---

tests/waku_archive/archive_utils.nim
tests/waku_archive/test_driver_postgres.nim
tests/waku_archive/test_driver_postgres_query.nim
tests/waku_archive/test_driver_queue.nim
tests/waku_archive/test_driver_queue_pagination.nim
tests/waku_archive/test_driver_queue_query.nim
tests/waku_archive/test_driver_sqlite.nim
tests/waku_archive/test_retention_policy.nim
tests/waku_archive/test_waku_archive.nim
waku/node/waku_node.nim
waku/waku_archive/archive.nim
waku/waku_archive/common.nim
waku/waku_archive/driver.nim
waku/waku_archive/driver/postgres_driver/postgres_driver.nim
waku/waku_archive/driver/queue_driver/index.nim
waku/waku_archive/driver/queue_driver/queue_driver.nim
waku/waku_archive/driver/sqlite_driver/migrations.nim
waku/waku_archive/driver/sqlite_driver/queries.nim
waku/waku_archive/driver/sqlite_driver/sqlite_driver.nim
waku/waku_core/message/digest.nim
waku/waku_core/message/message.nim

I tried a bunch of things that didn't work. In the end I simply added hashed to requests and responses. This approach will require a good clean-up after store v2 is removed.
I simplified how message are validated since we never exposed the validation even if the intent seamed to be to make it configurable. Do we want fully configurable validation? What kind of messages do we reject exactly?
There are also couple of comments that require reviewers input.
Tracking #2425

feat: archive update for store v3

---

apps/wakunode2/app.nim
waku/factory/node_factory.nim

Cleaning `node_factory.nim`. Only exporting `setupNode()` and `startNode()`.
extends #2441

chore: factory cleanup

---

tests/waku_core/topics/test_sharding.nim
tests/waku_relay/test_wakunode_relay.nim
tests/wakunode_rest/test_rest_relay.nim
waku/factory/internal_config.nim
waku/factory/node_factory.nim
waku/node/waku_node.nim
waku/waku_api/rest/relay/handlers.nim
waku/waku_core/topics/sharding.nim
waku/waku_enr/sharding.nim

* Removes hardcoding of amount of shards.
* Removes hardcoding of cluster-id with enabled autosharding.
* This enables any `cluster-id` != 1 to i) have autosharding if desired and ii) have whatever amount of shards they want.
For example, this PR enables the following. Creating a `cluster-id=10` with `4` shards, where the node only subscribed to `0, 1`
```
./build/wakunode2\
--rest=true\
--log-level=DEBUG\
--relay=true\
--pubsub-topic=/waku/2/rs/10/0\
--pubsub-topic=/waku/2/rs/10/1\
--pubsub-topic=/waku/2/rs/10/2\
--pubsub-topic=/waku/2/rs/10/3\
--cluster-id=10\
--shard=0\
--shard=1
```

fix: Enable autosharding in any cluster

---

tests/wakunode_rest/test_rest_relay.nim
tests/wakunode_rest/test_rest_relay_serdes.nim
waku/waku_api/rest/filter/types.nim
waku/waku_api/rest/relay/types.nim

Adds support to use the `ephemeral` field in the Waku messages with REST api as described in https://github.com/waku-org/waku-rest-api/pull/2
closes #2436

feat(rest): add `ephemeral` field support.

---

apps/wakunode2/app.nim
tests/node/test_wakunode_peer_exchange.nim
waku/factory/node_factory.nim
waku/node/waku_node.nim

Upgrade return type of `Wakunode.fetchPeerExchangePeers`.
Feel free to suggest better `error` returns.

feat(wakunode): Resultify fetch peer exchange peers

---

tests/wakunode_rest/test_rest_filter.nim
waku/waku_api/rest/filter/handlers.nim
waku/waku_api/rest/filter/types.nim

Returns a "OK" for the response when subscription is succesful, and also removes the status code from the response as it is not part of the API. Ping responses also return "OK" when succesful.
closes https://github.com/waku-org/nwaku/issues/2286

fix(rest): filter/v2/subscriptions response

---

waku/node/peer_manager/peer_manager.nim

@danisharora099 informed about a very low number of `in` connections on his node:
We've also noticed this behavior in other nodes.
------
This is how `peer_manager` establishes new `out` connections in a `nwaku` node:
Every node tries to establish connections to its known peers, every minute.
On every iteration, `await pm.connectToNodes(outsideBackoffPeers[0..<numPeersToConnect])` is run but the number of parallel connections is bound to just 10 (`MaxParallelDials`.) And that means that any other node will try to establish a connection with 10 peers, every minute.
Then, given the number of known peers that each other node has (754 in the Danish node) that makes it more difficult, or slower, to try to connect to other nodes.
------
With this change, we make any node to establish as many …

fix: peer_manager - extend the number of connection requests to known peers

---

waku/node/waku_node.nim

I removed the limit on the number of subscription events the queue can handle.
Close https://github.com/waku-org/nwaku/issues/2550

fix: remove subscription queue limit

---

waku/waku_archive/driver/postgres_driver/postgres_driver.nim

This PR fixes an issue where the list of partitions wasn't obtained correctly.
A node operator, @redwhiteeee , informed about the error:
That was caused because the list of partitions was obtained in random order, as can be seen in the following image:

fix: postgres_driver.nim  make sure the partition list is loaded in correct order

---

tests/all_tests_waku.nim
tests/incentivization/test_all.nim
tests/incentivization/test_rpc_codec.nim
waku/incentivization/rpc.nim
waku/incentivization/rpc_codec.nim

Encoding and decoding data structures that store proofs of eligibility is the first step towards a PoC implementation of incentivization for Store (and, in the future, other protocols), as outlined in #1961 and RFC [73/WAKU2-INCENTIVIZATION](https://github.com/vacp2p/rfc/tree/master/content/docs/rfcs/73).
The PR implements the following:
```
./env.sh bash
nim c -r ./tests/incentivization/test_rpc_codec.nim
```

feat: Incentivization: add codec for eligibility proofs

---

library/waku_thread/config.nim
tests/node/peer_manager/test_peer_manager.nim
tests/test_peer_manager.nim
tests/test_peer_storage.nim
tests/testlib/wakunode.nim
waku/factory/external_config.nim
waku/factory/internal_config.nim
waku/factory/node_factory.nim

* https://github.com/waku-org/nwaku/pull/2505 introduced a subtle regression due to using the deprecated config flag `topics`. Deprecated long time ago in favour of `pubsubTopics`.
* This PR fixes said regression.
* And removes deprecated `topics` flag.

fix: fix regresion + remove deprecated flag

---

waku/waku_rln_relay/rln_relay.nim

* Fixes `rlnMaxEpochGap`, so that a minimum of `1` is set.
* This produced a bug noticed in `RLN v2` where setting a high `rlnEpochSizeSec` caused `rlnMaxEpochGap=0` which caused problems in `clearNullifierLog`.

fix(rln): set a minimum epoch gap

---

library/waku_thread/config.nim
library/waku_thread/inter_thread_communication/requests/node_lifecycle_request.nim
waku/factory/external_config.nim

Exposes the rln relay configuration to the bindings.
closes #2454

feat(c-bindings): rln relay

---

examples/golang/waku.go

This PR adds a simple example and approach on how to perform cbindings over Golang. In other words, this PR allows the integration of `libwaku.so` in a tiny example to demonstrate how to use it.
As a pre-requisite, the `libwaku.so` must exist. To compile it, `make libwaku -j11`.

feat: examples/golang/waku.go add new example

---

waku/factory/external_config.nim

* The regex matching `--rln-relay-eth-client-address` flag was not allowing some valid RPC urls.
* Example, this should be valid `http://foundry:8545`
* But was failing:
```
Error while processing the rln-relay-eth-client-address=http://foundry:8545 parameter: Invalid HTTP RPC URL
```
* This PR fixes it so that it allows such URLs.
It can be also reproduced with:
```bash
docker run harbor.status.im/wakuorg/nwaku@sha256:d193792202726c51cd656c48f4ffd04f261ec2d8663a00591947a5aab3677dc5 --rln-relay-eth-client-address="http://foundry:3000"
Error while processing the rln-relay-eth-client-address=http://foundry:3000 parameter: Invalid HTTP RPC URL
Try wakunode2 --help for more information
```

fix: regex for rpc endpoint

---

apps/wakunode2/networks_config.nim
apps/wakunode2/wakunode2.nim

* [This PR](https://github.com/waku-org/nwaku/pull/2556/files#diff-43f34e84eeb9a4b4061898c3bd78274e149e50bd6b5d24aeb0a982e07629172eL300) deprecated `topics` but introduced a regression.
* Since `topics` flag default value `/waku/2/default-waku/proto` was being used when constructing the ENR, after removing that flag, we no longer had a default value.
* This means that eg `wakunode2 --cluster-id=0 ...` discv5 was not working properly, since the node had no default pubsub topic configured.
* This PR fixes it, by setting the default pubsub topic for `cluster-id=0`.
* Other unknown clusters, would need to provide their desired `pubsub-topic`.

fix: cluster-id 0 discv5 issue

---

docs/contributors/release-process.md

Just to simple fix of our release notation gone wrong on releases/images made from master, there is a need to merge the release branch - that got tagged with the release tag - back to master. 
This helps git to find the last relevant tag on the path for versioning the build.

chore: Extend release process with the need of merging back release branch to master

---

Makefile

An error reported by @IvanSete-status provided an opportunity to drop unused crates from zerokit that were initially used for testing of hypotheses.

chore(rln): update submodule + rln patch version

---

Dockerfile

Updated Dockerfile to enable Docker image build and run for Linux/MacOS on ARM64. Tested with Apple M1 and Raspberry Pi4.
- Build image is based on out of the box Rust images.
- Alpine Linux is still being used, bumped the version a bit. 
```
[+] Building 937.6s (20/20) FINISHED                                                                                                          docker:default
=> [internal] load build definition from Dockerfile                                                                                                    0.0s
=> => transferring dockerfile: 2.90kB                                                                                                                  0.0s
=> [internal] load metadata for docker.io/library/rust:1.77.1-alpine3.18 …
```

chore: add ARM64 Docker support for Linux/MacOS 

---

waku/waku_rln_relay/group_manager/on_chain/group_manager.nim

Parallelizes RPC calls during initial sync while maintaining an RPC call delay to ensure client is not throttled.
We have to await them sequentially so we can retry the failed RPC call, maybe this can be improved.
Brings down sync time from 15 mins to ~ ~~2~~ 3 mins.
In retrospect, this is how it should have been done from the start, my fault!

fix(rln-relay): reduce sync time

---

migrations/message_store_postgres/content_script_version_3.nim
migrations/message_store_postgres/pg_migration_manager.nim
waku/waku_archive/driver/postgres_driver/migrations.nim
waku/waku_archive/driver/sqlite_driver/queries.nim
waku/waku_archive/driver/sqlite_driver/sqlite_driver.nim

Creating new `i_query` index for the postgres db, which is currently added only in sqlite
closes #2357

chore: adding migration script adding i_query index

---

tests/waku_lightpush/lightpush_utils.nim
tests/waku_lightpush/test_all.nim
tests/waku_lightpush/test_client.nim
tests/waku_lightpush/test_ratelimit.nim
tests/waku_store/test_wakunode_store.nim
tests/wakunode_rest/test_rest_lightpush.nim
tests/wakunode_rest/test_rest_store.nim
waku/common/ratelimit.nim
waku/common/tokenbucket.nim
waku/common/waku_service_metrics.nim
waku/factory/external_config.nim
waku/factory/node_factory.nim
waku/node/waku_node.nim
waku/waku_api/rest/lightpush/handlers.nim
waku/waku_api/rest/responses.nim
waku/waku_api/rest/store/handlers.nim
waku/waku_lightpush/common.nim
waku/waku_lightpush/protocol.nim
waku/waku_lightpush/protocol_metrics.nim
waku/waku_store/common.nim
waku/waku_store/protocol.nim
waku/waku_store/rpc.nim

As a first step for rate and bandwidth caping of non relay protocol, hereby a very simple request rate / period limitation is added to light-push and store protocols.
https://github.com/waku-org/nwaku/issues/2032

feat: Added simple, configurable rate limit for lightpush and store-query

---

docs/api/rest-api.md

The `docs` folder contained outdated links and structure for the Waku REST API

fix(doc): update REST API docs

---

tests/waku_relay/test_protocol.nim
tests/waku_relay/utils.nim
waku/waku_relay/protocol.nim

It has been detected an issue regarding node restart and reconnection. After reconnecting, the messages didn't get its destination.
Special thanks to @AlejandroCabeza for such a great issue description :partying_face: 
closes https://github.com/waku-org/nwaku/issues/2145

fix: node restart test issue

---

.github/workflows/auto_assign_pr.yml

This avoids a manual step of assigning PR by auto-assigning it to the creator.

chore: workflow to autoassign PR

---

docs/contributors/nph.md

Thanks for the reminder @gabrielmer 
We need to make sure we always use the `0.5.1` version

docs: nph - clarify the version that is needed 0.5.1

---

CHANGELOG.md

Changelog for v0.27.0
Please review carefully and suggest highlights, upgrade instructions or notes that should be added :)

chore(release): update changelog for v0.27.0 release 

---

tests/waku_filter_v2/test_waku_client.nim
tests/waku_lightpush/test_client.nim
tests/waku_peer_exchange/test_protocol.nim
tests/waku_relay/test_protocol.nim
tests/wakunode_rest/test_rest_relay.nim
waku/factory/node_factory.nim
waku/node/waku_node.nim
waku/waku_core/message/default_values.nim
waku/waku_filter_v2/client.nim
waku/waku_filter_v2/protocol.nim
waku/waku_filter_v2/rpc_codec.nim
waku/waku_lightpush/client.nim
waku/waku_lightpush/protocol.nim
waku/waku_lightpush/rpc_codec.nim
waku/waku_peer_exchange/protocol.nim
waku/waku_relay/protocol.nim
waku/waku_store/client.nim
waku/waku_store/protocol.nim
waku/waku_store/rpc_codec.nim

While debugging https://github.com/waku-org/go-waku/issues/1076, i had noticed that for lightpush protocol, the read from stream is being done by using defaultMaxMsgSize which is 150Kib. This means even if a node sets this value to a higher one, lightpush send fails from a client if messageSize crosses 150Kb+overhead. 
More discussion on this here : https://discord.com/channels/1110799176264056863/1230492037099294720
~~- [ ] LightPush serviceNode to use MaxWakuMessageSize to calculate RPCSize while reading a message. **Now i am not so sure if this is the right approach, rather let it try to publish via relay which would fail?**~~

fix: don't use WakuMessageSize in req/resp protocols

---

waku/waku_rln_relay/group_manager/on_chain/retry_wrapper.nim

This PR increases the values for `retryDelay` and `retryCount` to allow nodes to recover over a longer duration than before (3 seconds)

fix(rln-relay): increase retries for 1 minute recovery time

---

CHANGELOG.md

The changelog is full of references to https://rfc.vac.dev and those links are broken.
Updating all links in file to their relevant RFCs
Thanks @vpavlin for noticing 🤩

chore: updating broken links in changelog

---

apps/wakunode2/wakunode2.nim
tests/wakunode2/test_app.nim
waku/factory/app.nim
waku/waku_api/rest/builder.nim

Extract some REST logic from app.nim, aiming for simplify app.nim a little.
I will submit a couple of similar PRs simplifying app.nim.
note: this has the same goal as https://github.com/waku-org/nwaku/pull/2610 but I decided to submit a different one just to keep the original one as a temporary reference. I will drop the initial PR once this gets merged

refactor: addition of waku_api/rest/builder.nim and reduce app.nim

---

tools/rln_db_inspector/rln_db_inspector.nim

This PR adds logs to the rln-db-inspector which allows to find indices in the tree that have not been set.

chore(rln-db-inspector): add more logging to find zero leaf indices

---

scripts/chkhealth.sh

Follow up PR on nwaku-compose https://github.com/waku-org/nwaku-compose/pull/86
This enhancement to the script handles more edge cases and prints accordingly.

chore: Copy back from nwaku-compose - an enhanced version of convenient node health check script

---

waku/common/ratelimit.nim
waku/factory/node_factory.nim

https://github.com/waku-org/nwaku/pull/2431 missed setting rate limit configuration for legacy store protocol mount.
Also set default rate limit setting to zero in order to let rate limit checks switched off for now.

fix: missing rate limit setting for legacy store protocol

---

waku/node/waku_node.nim
waku/waku_store/protocol.nim
waku/waku_store/rpc_codec.nim

Updated the protobuf field numbers according to the spec. https://github.com/vacp2p/rfc/tree/docs/new-store-v3-protocol/content/docs/rfcs/13#payloads

fix: store v3 proto field numbers

---

waku/node/waku_node.nim
waku/waku_api/rest/builder.nim
waku/waku_api/rest/lightpush/handlers.nim
waku/waku_lightpush/self_req_handler.nim

This is helper enhancment for testing (rate limit specifically for me) on lightpush... similar to query self store node via REST API.
With this change one can issue lightpush request via REST API on a service node having lightpush protocol installed.
In contrast it was needed to run a full node with lightpush service and a light client (configured with the service node peerId) to be usable from REST API.
With this change a lightpush service node (with relay of course) can serve such lightpush API request and can relay such messages.
This can help in various way.
- easy develop on REST API with nwaku-compose (where a full node is set up)
- easy test lightpush features via rest api.
1. Run a full node or nwaku-compose with the right image
2. issue REST /lightpush POST message
3. check that …

chore: Enabling to use a full node for lightpush via rest api without lightpush client configured

---

waku/factory/internal_config.nim

fix: handle named sharding in enr

---

waku/node/waku_node.nim

There is no need to explicitly stop mounted libp2p protocols because they are already being stopped after the switch.stop() is being called.
I've noticed that while debugging:
Peer Reconnection not working - https://github.com/waku-org/nwaku/issues/2592

refactor: waku_node.nim - simplify stop proc

---

waku/node/waku_node.nim

This is aimed to avoid having flaky tests by keeping the original invocation order that we had before applying the following change: https://github.com/waku-org/nwaku/pull/2645/files

fix: waku_node - first of all stop the waku-switch when stopping the waku-node

---

apps/wakunode2/wakunode2.nim
tests/wakunode2/test_app.nim
waku/factory/app.nim
waku/node/waku_metrics.nim

Simplify `app.nim` and move the "metrics factory" procs to an already existing `waku_metrics` module

refactor: metrics server. Simplify app.nim module

---

tests/waku_sync/test_protocol.nim
waku/waku_sync/protocol.nim
waku/waku_sync/raw_bindings.nim
waku/waku_sync/session.nim

Use negentropy subrange which gives flexibility to choose sync time.
Still some optimizations are needed in negentropy side, but functionally this change has passed all existing tests.
@SionoiS SubRange seems to work with just timestamp alone, i think the ID argument may not be required then.

feat: sync use subranges

---

tests/waku_rln_relay/test_rln_group_manager_onchain.nim
waku/waku_rln_relay/group_manager/on_chain/group_manager.nim

This PR offloads the `setMetadata` proc from the `atomicBatch` proc to the callsites of the `getAndHandleEvents` so that it is not called twice, and during the initial sync when we parallelize the rpc calls we want to ensure the metadata is set in increasing block number counts to avoid race conditions and missed blocks.

fix(rln-relay): persist metadata every batch during initial sync

---

waku/node/waku_node.nim
waku/waku_archive/archive.nim
waku/waku_filter_v2/protocol.nim
waku/waku_lightpush/protocol.nim
waku/waku_relay/protocol.nim

The next modules are touched:
- waku_node.nim
- archive.nim
- waku_filter_v2/protocol.nim
- waku_lightpush/protocol.nim
- waku_relay/protocol.nim
Add logging of hashes to all nodes - https://github.com/waku-org/nwaku/issues/2474

chore: log enhancement for message reliability analysis

---

tests/test_waku_keystore.nim
waku/waku_keystore/keystore.nim
waku/waku_keystore/protocol_types.nim

- **fix(waku_keystore): sigsegv on different appInfo**
The `matchingAppKeystore` is set only when a match is found, else it is returned as void. This PR converts it to an option and adds a check before returning it so that we dont segfault :)
closes #1934

fix(waku_keystore): sigsegv on different appInfo

---

tests/node/test_wakunode_store.nim
tests/waku_archive/test_waku_archive.nim
tests/waku_store/test_client.nim
tests/waku_store/test_rpc_codec.nim
tests/waku_store/test_waku_store.nim
tests/waku_store/test_wakunode_store.nim
tests/wakunode_rest/test_rest_store.nim
waku/common/protobuf.nim
waku/node/waku_node.nim
waku/waku_api/rest/store/types.nim
waku/waku_archive/archive.nim
waku/waku_archive/common.nim
waku/waku_archive/driver.nim
waku/waku_archive/driver/postgres_driver/postgres_driver.nim
waku/waku_archive/driver/queue_driver/queue_driver.nim
waku/waku_archive/driver/sqlite_driver/queries.nim
waku/waku_archive/driver/sqlite_driver/sqlite_driver.nim
waku/waku_core/message/codec.nim
waku/waku_store/common.nim
waku/waku_store/protocol.nim
waku/waku_store/rpc_codec.nim

Fixes https://github.com/waku-org/nwaku/issues/2635 and https://github.com/waku-org/nwaku/issues/2634

fix: store v3 validate cursor & remove messages 

---

apps/wakunode2/wakunode2.nim
examples/wakustealthcommitments/node_spec.nim
examples/wakustealthcommitments/stealth_commitment_protocol.nim
library/waku_thread/inter_thread_communication/requests/debug_node_request.nim
library/waku_thread/inter_thread_communication/requests/node_lifecycle_request.nim
library/waku_thread/inter_thread_communication/requests/peer_manager_request.nim
library/waku_thread/inter_thread_communication/requests/protocols/relay_request.nim
library/waku_thread/inter_thread_communication/requests/protocols/store_request.nim
library/waku_thread/inter_thread_communication/waku_thread_request.nim
library/waku_thread/waku_thread.nim
tests/wakunode2/test_app.nim
waku/factory/node_factory.nim
waku/factory/waku.nim
waku/node/waku_node.nim
waku/waku.nim
waku/waku_peer_exchange/protocol.nim

With this PR we:
- rename the `app.nim` module to `waku.nim`
- rename `App` type to `Waku` type. We start considering `Waku` as the type that contains `WakuNode`, discovery elements, and will contain an instance of `PeerManager` in the future. `Waku` type represents Waku ;P (very original name ;P)
- refactor `libwaku` code so that we start dealing with the `Waku` object from within `libwaku` and therefore, start having a similar behaviour as the `wakunode2` app
`migrate DiscV5 and DNS Discovery from app.nim to waku_node.nim` - https://github.com/waku-org/nwaku/issues/2452

refactor: big refactor to add waku component in libwaku instead of onlu waku node

---

migrations/message_store_postgres/content_script_version_4.nim
waku/factory/external_config.nim

There appeared _Postgres_ schema migration issue when going from schema version 3 to 4.
The problem occurred while trying to remove an index that doesn't seem to exist in version 3.
Aside from that, I'm adding the following line, which is part of the script for version 3, to make sure that index is created in case it doesn't exist. I've notice that when testing in `waku.test`:
`CREATE INDEX IF NOT EXISTS i_query ON messages (contentTopic, pubsubTopic, storedAt, id);`

fix: content_script_version_4.nim: migration failed when dropping unexisting constraing

---

migrations/message_store_postgres/content_script_version_4.nim
waku/factory/external_config.nim

While running migration scripts we noticed that is better to try to change the table schema directly in the `messages` table. The reason is that is not possible to keep handle a table backup when the `message` table occupies 45GiB and the max size allowed in 50GiB
With this PR we try to allow database migration with low disk availability constraints.
We want to avoid errors like:
```
nim-waku  | ERR 2024-05-06 17:22:42.470+00:00 failed to execute migration statement      topics="waku archive migration" tid=1 file=migrations.nim:81 statement="INSERT INTO messages (\n                        pubsubTopic,\n                        contentTopic,\n                        payload,\n                        version,\n                        timestamp,\n                        id,\n …
```

chore: simplify migration script

---

migrations/message_store/00009_addMetaColumn.up.sql
waku/waku_archive/driver/sqlite_driver/migrations.nim

While running `./build/waku --store` on latest master, i ran into the following error:
```
/home/richard/waku-org/nwaku/apps/wakunode2/wakunode2.nim(138) wakunode2
/home/richard/waku-org/nwaku/waku/factory/waku.nim(95) init
/home/richard/waku-org/nwaku/waku/factory/node_factory.nim(432) setupNode
/home/richard/waku-org/nwaku/waku/factory/node_factory.nim(113) setupProtocols
/home/richard/waku-org/nwaku/vendor/nim-chronos/chronos/internal/asyncfutures.nim(382) futureContinue
/home/richard/waku-org/nwaku/waku/factory/node_factory.nim(231) setupProtocols
/home/richard/waku-org/nwaku/waku/waku_archive/driver/builder.nim(24) new
/home/richard/waku-org/nwaku/vendor/nim-chronos/chronos/internal/asyncfutures.nim(382) futureContinue
/home/richard/waku-org/nwaku/waku/waku_archive/driver/builder.nim( …
```

fix: add `meta` to sqlite migration scripts

---

waku/waku_rln_relay/group_manager/on_chain/group_manager.nim

This PR modifies the `ready` behaviour of rln-relay's onchain mode. If the node is behind the tip of the blockchain by `window` blocks, it should still be marked as ready IMO.

chore(rln-relay): health check should account for window of roots

---

tests/node/test_wakunode_store.nim
tests/waku_store/test_client.nim
tests/waku_store/test_rpc_codec.nim
tests/waku_store/test_waku_store.nim
tests/waku_store/test_wakunode_store.nim
waku/node/waku_node.nim
waku/waku_archive/archive.nim
waku/waku_archive/common.nim
waku/waku_store/common.nim
waku/waku_store/rpc_codec.nim

This PR is meant to unblock Waku Sync work.
Before Store v3 did not return the pubsub topics messages were sent on, now it does.
Follows updated https://github.com/vacp2p/rfc/pull/665/commits/5d69ab58b34d32af99e60b109ad784ad1dd9e345

feat: store v3 return pubsub topics

---

tests/node/test_wakunode_store.nim

Temporary workaround to avoid having flaky tests in MacOS

fix: adding wait after starting node to avoid segfault

---

tests/test_message_cache.nim
waku/waku_api/message_cache.nim

Fixes a crash in message cache because the code assumed messages to be removed were ordered.
I also added a basic fuzzing test.
Closes https://github.com/waku-org/nwaku/issues/2680

fix: message cache unordered removal

---

apps/chat2/chat2.nim
tests/waku_store_legacy/test_resume.nim
waku/common/ratelimit.nim
waku/common/tokenbucket.nim
waku/common/waku_service_metrics.nim
waku/factory/node_factory.nim
waku/node/waku_node.nim
waku/waku_api/rest/admin/handlers.nim
waku/waku_api/rest/legacy_store/handlers.nim
waku/waku_lightpush/protocol.nim
waku/waku_store/protocol.nim
waku/waku_store_legacy/client.nim
waku/waku_store_legacy/common.nim
waku/waku_store_legacy/protocol.nim

Also added rate and traffic metrics.
This PR addresses most of the weakness of phase1 implementation and extend it with bandwidth metrics for the protocols.
For convenience it fixes some nuances on other aspects.
Will be applied in a separate PR:
- Rate limiting Filter
- It might need a bit different approach due to its nature of subscribe and ping
- Trace top contributor peers of over limit use and ban them 
https://github.com/waku-org/nwaku/issues/2589
https://github.com/waku-org/nwaku/issues/2032

feat: Added flexible rate limit checks for store, legacy store and lightpush

---

.gitignore
examples/mobile/App.tsx
examples/mobile/android/app/build.gradle
examples/mobile/android/app/src/main/java/com/mobile/MainActivity.kt
examples/mobile/android/app/src/main/java/com/mobile/MainApplication.kt
examples/mobile/android/app/src/main/java/com/mobile/ReactNativePackage.kt
examples/mobile/android/app/src/main/java/com/mobile/WakuModule.kt
examples/mobile/android/app/src/main/jni/.gitignore
examples/mobile/android/app/src/main/jni/Android.mk
examples/mobile/android/app/src/main/jni/Application.mk
examples/mobile/android/app/src/main/jni/waku_ffi.c
examples/mobile/android/build.gradle
examples/mobile/build-nwaku.js
examples/mobile/package.json
examples/mobile/yarn.lock

In this PR, the default react native example app is modified to use libwaku. 
The app looks kinda bare, and some values like the pubsub topic as well as the attributes to publish a message are hardcoded, but that's something that could be improved in a separate PR, as the main focus here is to get waku to run in a mobile device!
This only works in Android, as the swift code for IOS has not been coded yet.
To execute the example app:
```
yarn
yarn run start
```
The WakuModule is created adhoc for this example. I read that it is possible to create a `.aar` file to package both the shared libraries and the module itself so it's easier for other apps to just include the file and not have to write their own WakuModule.kt. This is something i'll investigate and attempt to improve in a separate …

feat(mobile-android): waku example app

---

tests/node/peer_manager/test_peer_manager.nim
tests/node/test_wakunode_legacy_store.nim
tests/node/test_wakunode_lightpush.nim
tests/node/test_wakunode_store.nim
tests/waku_archive/test_driver_queue_query.nim
tests/waku_filter_v2/test_waku_client.nim
tests/waku_store/test_wakunode_store.nim
tests/wakunode_rest/test_rest_store.nim

In async functions, we should use `await` instead of `waitFor`. The usage of `waitFor` in async tests can generate crashes.

fix: use await instead of waitFor in async tests

---

tests/waku_archive/test_driver_postgres_query.nim
waku/waku_archive/driver/postgres_driver/partitions_manager.nim
waku/waku_archive/driver/postgres_driver/postgres_driver.nim

This PR enhances the case where, for any reason, there are old empty partitions. In that case of empty partitions, they are not considered when getting the oldest timestamp. Instead, the oldest timestamp was only considered from the oldest row.
Therefore, when "time" retention policy is applied, we should also consider those old-empty partitions so that they can get erased properly.
closes https://github.com/waku-org/nwaku/issues/2689

chore: Postgres enhance get oldest timestamp

---

waku/node/waku_node.nim

We're opening ping streams every 2 minutes but not closing them. This means we get an ever increasing amount of stale streams. Therefore, closing the stream after the ping.
Tested it by calling https://github.com/waku-org/nwaku/blob/a37c9ba91158a90879a9e78f124a6e11e1900279/waku/node/peer_manager/peer_manager.nim#L655-L671 and https://github.com/waku-org/nwaku/blob/a37c9ba91158a90879a9e78f124a6e11e1900279/waku/node/peer_manager/peer_manager.nim#L673-L685
inside `keepaliveLoop()` and logging the outputs
The conclusions were:
- without calling `conn.close()`, the output of `getNumStreams()` grew indefinitely
- calling `conn.close()`, the output of `getNumStreams()` varied but was stable
- calling `conn.close()`did not affect the output of `connectedPeers()`, which means that indeed it didn't …

chore: closing ping streams

---

tests/node/peer_manager/peer_store/utils.nim
tests/node/test_all.nim
tests/node/test_wakunode_peer_manager.nim
tests/node/utils.nim
tests/test_peer_manager.nim
tests/testlib/comparisons.nim
tests/testlib/futures.nim
tests/testlib/simple_mock.nim
tests/testlib/wakunode.nim
tests/waku_archive/archive_utils.nim
tests/waku_discv5/utils.nim
waku/node/peer_manager/peer_manager.nim

Implement tests for peer and connection management

test(peer-and-connection-management): Implement tests

---

tests/node/test_wakunode_relay_rln.nim
tests/node/test_wakunode_sharding.nim
tests/testlib/assertions.nim
tests/testlib/futures.nim
tests/waku_core/topics/test_pubsub_topic.nim
tests/waku_core/topics/test_sharding.nim
tests/waku_enr/test_sharding.nim
tests/waku_relay/utils.nim

test(sharding): Implement sharding tests

---

apps/wakunode2/wakunode2.nim
library/waku_thread/waku_thread.nim
tests/testlib/wakunode.nim
waku/factory/waku.nim

This PR moves some initialization logic from `apps/wakunode2/wakunode2.nim` to `waku/factory/waku.nim`, aiming to achieve same behaviour between `wakunode2` and `libwaku`.

chore: move code from wakunode2 to a more generic place, waku

---

tests/node/test_wakunode_sync.nim
tests/waku_sync/sync_utils.nim
tests/waku_sync/test_protocol.nim
waku/node/waku_node.nim
waku/waku_store/client.nim
waku/waku_sync/common.nim
waku/waku_sync/protocol.nim
waku/waku_sync/raw_bindings.nim
waku/waku_sync/session.nim

Add a callback to query the store of the other node for the missing messages and then add them to our own.

feat: message transfer mechanism

---

waku/factory/internal_config.nim

When running the invalid configuration
```
./build/wakunode2 --pubsub-topic=/waku/2/rs/2/0 --pubsub-topic=/waku/2/rs/3/0 --cluster-id=2
```
I get
```
Error: unhandled exception: Trying to access value with err Result: use shards with the same cluster Id. [ResultDefect]
```
Refactoring the code to avoid this unhandled exception and handle the error gracefully.

fix: refactor shard parsing

---

tests/waku_store/test_client.nim
tests/waku_store_legacy/test_client.nim

Simple PR to help debug flaky crashes on mac-os tests.
This is based on previous studies made by @gabrielmer

chore: test_client - add nil error handling after serverSwitch.start() clientSwitch.start()

---

waku/discovery/waku_discv5.nim
waku/node/peer_manager/peer_manager.nim

Add more logs to help debugging `discoveryv5` issues

chore: waku_discv5, peer_manager - add more logs help debug discovery issues

---

Makefile
scripts/build_rln.sh

This PR includes the new zerokit release v0.4.4, which brings a speedup of ~50% while running tests and deserialization for the circuit logic.
While running `tests/waku_rln_relay/test_all.nim` with RLN_V2 enabled
Without arkzkey: `[Summary] 68 tests run (377.2s): 68 OK, 0 FAILED, 0 SKIPPED`
With arkzkey: `[Summary] 68 tests run (219.9s): 68 OK, 0 FAILED, 0 SKIPPED`

feat(rln-relay): use arkzkey variant of zerokit

---

apps/wakunode2/wakunode2.nim
examples/cbindings/waku_example.c
examples/cpp/waku.cpp
examples/filter_subscriber.nim
examples/golang/waku.go
examples/lightpush_publisher.nim
examples/nodejs/waku.js
examples/publisher.nim
examples/python/waku.py
examples/rust/src/main.rs
examples/subscriber.nim
examples/wakustealthcommitments/wakustealthcommitments.nim
waku.nimble
waku/common/logging.nim
waku/factory/waku.nim

- Set compilation flags to properly compile chronicles for `libwaku`
- Unify the code in the sense that we only expose one proc from the `logging` module and have a standard logging setup.
- The log is configured in `waku.nim` within `init` proc.
- In `wakunode2` we also set the log before "waku.init" is invoked because we need to setup the logs properly for the "essential rest server" that we start at the beginning
closes https://github.com/waku-org/nwaku/issues/2411

chore: libwaku - allow to properly set the log level in libwaku and unify a little

---

library/libwaku.nim
library/waku_thread/inter_thread_communication/requests/debug_node_request.nim
library/waku_thread/inter_thread_communication/requests/node_lifecycle_request.nim
library/waku_thread/inter_thread_communication/requests/peer_manager_request.nim
library/waku_thread/inter_thread_communication/requests/protocols/relay_request.nim
library/waku_thread/inter_thread_communication/requests/protocols/store_request.nim
library/waku_thread/waku_thread.nim

Simple cleanup to remove unused imports and duplicated code in `library/waku_thread/inter_thread_communication/requests/node_lifecycle_request.nim`

chore: simple library cleanup of unused imports and duplicated code

---

examples/cbindings/waku_example.c
library/libwaku.h
library/libwaku.nim
library/waku_thread/inter_thread_communication/requests/discovery_request.nim
library/waku_thread/inter_thread_communication/requests/node_lifecycle_request.nim
library/waku_thread/inter_thread_communication/waku_thread_request.nim
waku/discovery/waku_discv5.nim

Finalizing the addition of discovery features to `libwaku`.
- Extension of `libwaku` with discovery capabilities.
- Extension of `cwaku_example` so that we can check how the new exposed functions work.
- Enhancement in `node_lifecycle_request.nim` for better error control. That helps to determine when a wrong JSON config parameter is passed to the library.
closes https://github.com/waku-org/nwaku/issues/2455

chore: Discovery in libwaku

---

tests/waku_archive/test_driver_postgres_query.nim
tests/waku_archive/test_driver_queue_query.nim
tests/waku_archive/test_driver_sqlite_query.nim
waku/waku_api/rest/store/types.nim
waku/waku_archive/driver/postgres_driver/postgres_driver.nim
waku/waku_core/message/digest.nim

Various bug fixes.
For https://github.com/waku-org/nwaku/issues/2717
I just remove the `assert` and the code handle the error just fine.
For https://github.com/waku-org/nwaku/issues/2715
I turn off the plus sign for url de/encoding and change to base 64 for json.
For https://github.com/waku-org/nwaku/issues/2716
I added a cursor check before the main query.
For https://github.com/waku-org/nwaku/issues/2719
I change the serde for REST api

fix: store v3 misc bugs

---

library/libwaku.nim

fix: use `when` instead of `if` for adding soname on linux

---

waku/common/databases/dburl.nim

When there's an error with the dbUrl, the logs will contain the full url, and this is a bad idea, since the connection string might contain the user/password, thus, revealing too much information on the logs
cc: @jakubgs

fix: do not print the db url on error

---

apps/wakucanary/wakucanary.nim

While checking availability of nodes, I noticed the filter protocol cannot be matched and that wakucanary does not know about store v3
1. `make wakucanary`
1. `./build/wakucanary -p=relay -p=filter -p=lightpush -p=store -p=storev3 -a=/dns4/waku.myrandomdemos.online/tcp/8000/wss/p2p/16Uiu2HAmKfC2QUvMVyBsVjuEzdo1hVhRddZxo69YkBuXYvuZ83sc`

chore(wakucanary): fix fitler protocol, add storev3

---

tests/waku_store/test_waku_store.nim
tests/waku_store_legacy/test_waku_store.nim

Very simple PR that aims to better catch where a flaky test is actually failing. That flaky test only happens on CI MacOS

chore: test_waku_store.nim - add logs to better analyse uncertain flaky tests

---

docs/contributors/release-process.md

Adding a step to make it clearer the kind of merge that needs to be applied after a release has been completed.
Notice that this is needed to make sure the following command retrieves the appropriate information when running from `master`:
```code
git describe --abbrev=6 --always --tags
```
In other words, we need to use the following merge option when merging the release branch into master:
But, it is important to bear in mind that we should use the "Squash and merge" option for the regular PR's:

docs: release-process.md - add step to merge the release branch back to master

---

waku/waku_archive/driver/postgres_driver/postgres_driver.nim

After deploying `v0.28.0` it has been detected that the _Status_ app cannot retrieve stored messages as usual.
This PR fixes an issue related to the number of attributes that are expected to be retrieved from the queries.
Particularly, the following statement should always be fulfilled to make the _Store_ queries to function: https://github.com/waku-org/nwaku/blob/217dc7a07836aa496fe8959155daec24ab57cfbd/waku/waku_archive/driver/postgres_driver/postgres_driver.nim#L164

fix: Status cannot retrieve store messages

---

waku/waku_archive/driver/postgres_driver/postgres_driver.nim

Solution of #2744 "chore: extract select to a const"
Refactored similar query select parts into a constant for clarity.

chore: extract common prefixes into a constant for multiple query

---

apps/liteprotocoltester/statistics.nim

Running `liteprotocoltester`, we have seen lately in the `receivernode` periodic stats that there seems to be a message loss.
For example
```
receivernode-1  | *-----------------------------------------------------------------------------*
receivernode-1  | |  Expected  |  Reveived  |    Loss    |  Misorder  |    Late    |  Duplicate |
receivernode-1  | |        120 |         16 |        104 |          0 |          0 |          0 |
receivernode-1  | *-----------------------------------------------------------------------------*
receivernode-1  | | Latency stat:                                                               |
receivernode-1  | |    avg latency: 0ns                                                         |
receivernode-1  | |    min latency: 0ns …
```

chore: Improving liteprotocolteseter stats

---

apps/liteprotocoltester/tester_config.nim
tests/test_waku_metadata.nim
tests/testlib/wakunode.nim
waku/common/envvar_serialization/reader.nim
waku/common/envvar_serialization/utils.nim
waku/factory/external_config.nim
waku/factory/internal_config.nim
waku/factory/networks_config.nim
waku/node/config.nim
waku/node/waku_node.nim
waku/waku_core/topics/sharding.nim
waku/waku_enr/sharding.nim

Simple PR to make `clusterId` and `shardId` of type `uint16` everywhere to simplify the code and avoid casts.
Helps the deprecation of named sharding in https://github.com/waku-org/nwaku/issues/2163

chore: unifying clusterId and shardId types to uint16

---

tests/all_tests_waku.nim
tests/waku_archive/test_partition_manager.nim
waku/waku_archive/driver/postgres_driver/partitions_manager.nim
waku/waku_archive/driver/postgres_driver/postgres_driver.nim

Also, skip the error "partition already exists" because that happens when multiple nodes interact with the same database.
- Skip the error if the creation of a partition failed
- Perform partition creation considering o'clock time ranges and partition length of one hour each
closes https://github.com/waku-org/nwaku/issues/2766
closes https://github.com/waku-org/nwaku/issues/2769

fix: postgres partitions: ensure the partition ranges are o'clock

---

migrations/message_store_postgres/content_script_version_5.nim
migrations/message_store_postgres/pg_migration_manager.nim
waku/waku_archive/driver/postgres_driver/migrations.nim

Postgres optimization related to the `ORDER BY`
In a session with @cammellos and @richard-ramos , @cammellos recommended to add this index after seeing that `EXPLAIN ANALYZE SELECT ...` spent too much time in the sorting part. Then, after adding the offended index, the query time was enhanced.
We don't have clear evidence that this PR will fix the following issue but it helps to have better query performance
https://github.com/waku-org/nwaku/issues/2783

chore: add new index to optimize the order by storedAt

---

.gitmodules
Makefile
scripts/build_rln.sh

Bumps the zerokit submodule to v0.5.1

chore(submodule): update zerokit submodule to v0.5.1

---

.github/workflows/ci.yml
waku/waku_node.nim

Simple change in the CI to avoid cancelling matrixed jobs when one of their variants fails

chore: setting fail-fast to false in matrixed github actions

---

waku/waku_archive/driver/postgres_driver/postgres_driver.nim

Add additional protection, in the shape of an advisory lock, when adding new partitions to the database.
This is interesting from the PoV of multiple nodes accessing the same database.
Not evidence that this PR will fix the following issue but it will help
https://github.com/waku-org/nwaku/issues/2783

chore: postgres_driver - acquire/release advisory lock when creating partitions

---

waku/node/peer_manager/peer_manager.nim

Adds more information to the log, allowing users to differentiate shards and their connections.
Example :- 
If shards match the peer, the previous log entry would be :- "reason = no shards in common"  
Now it's look like this :- "reason = no shards in common: my_shards =  [ x, y, z ]  others_shards = [ a, b, c ]"
where the number within brackets represents the shard number.

fix: more detailed logs to differentiate shards with peers

---

Makefile
waku/node/waku_node.nim
waku/waku_archive/archive.nim
waku/waku_filter_v2/protocol.nim
waku/waku_lightpush/protocol.nim
waku/waku_relay/protocol.nim

This is needed to help the Distributed Systems Testing team, DST, to have less logs when analysing thousands of nodes. With that, the DST team will set the log level to NOTICE and that will avoid printing too many logs.
- set log level to `notice` when logging `msg_hash`.
- add error string in case of validation failure in `waku/waku_relay/protocol.nim`
closes https://github.com/waku-org/nwaku/issues/2678

chore: set msg_hash logs to notice level

---

waku/factory/external_config.nim

Just found this anomaly in the code while looking up answers during our meeting...
It is a leftover, nowhere used config option, related to legacy filter that was removed versions before.
also in docs: https://github.com/waku-org/docs.waku.org/pull/200

chore: Remove filter-timeout configuration option as it remained after removing legacy filter where it belong to.

---

.github/workflows/ci.yml
waku/common/utils/nat.nim

In case nat setup found proper device to make the port mapping (that does not happens in jenkins CI) could cause multiple initilalization of nim-eth/nat module.
That module is not designed for that and changing this needs a bigger rework of that module.
The root cause of the issue with multiple initialization inside one application run leads to multiple remapping thread created. That thread is responsible for refreshing the port mapping on the router if needed.
As such multiple thread created but only the last one tracked caused dead lock in the shut down mechanism of it as the used Channel[bool] single module variable locking mechanism do not handle such situation and remains blocked.
Simple workaround is applied: waku nat module prevents multiple initialization of nim-eth/nat module and …

fix: multi nat initialization causing dead lock in waku tests + serialize test runs to avoid timing and port occupied issues

---

tests/wakunode_rest/test_rest_admin.nim
tests/wakunode_rest/test_rest_cors.nim
tests/wakunode_rest/test_rest_debug.nim
tests/wakunode_rest/test_rest_filter.nim
tests/wakunode_rest/test_rest_health.nim
tests/wakunode_rest/test_rest_lightpush.nim
tests/wakunode_rest/test_rest_store.nim

Found that some of the random failures in CI comes from old fashioned REST API tests that use fixed ports for test setup.
Now this changed to OS selected random free ports all remaining places.
I expect more stable CI tests from this change. No functionality changed.
1. Just run all tests

fix: Use random ports in rest tests instead of fixed ones

---

waku/node/waku_node.nim
waku/waku_relay/protocol.nim

Adding observers so the hash and origin/destination of every message sent and received is logged. This will help with our reliability simulation efforts.
This adds lots of logs, so there's always the option to have it under a compilation flag. Let me know if that's preferable or if it's ok for now and we'll make them optional at a later stage.
We're finally adding observers only for messages received, as no additional valuable information is currently added by logging sent messages. If necessary at any point, they can be easily activated.
Example output:

chore: adding observers for message logging

---

waku/waku_archive/driver/postgres_driver/partitions_manager.nim
waku/waku_archive/driver/postgres_driver/postgres_driver.nim

With the previous approach it happened cases where one connection acquired the lock and other connection tried to release the same lock, causing an unrecoverable failure which made the node to end.
closes https://github.com/waku-org/nwaku/issues/2783

fix: postgres_driver - better sync lock in partition creation

---

apps/wakucanary/README.md
apps/wakucanary/wakucanary.nim
waku/node/peer_manager/peer_manager.nim

closes https://github.com/waku-org/nwaku/issues/2720
Add cluster ID and shards in the Wakucanary configuration, and then mount this metadata information to Wakunode.

fix: mount metadata in wakucanary

---

waku/node/waku_node.nim
waku/waku_relay/protocol.nim

This reverts commit b52286524b243feb70ae5f08cafae26f95b0bf50.
The approach of using observers for logging seems to be extremely inefficient, as observers are triggered before checking whether we have received a message or not. This implies that they get triggered for repeated messages.
On the other hand, increasing the metrics in the observer is a bug, as repeated messages would be counted.
We will need then to create special versions with extra logs for simulations in a branch separate from master.
Thanks @Ivansete-status for raising the issue!
CC @AlbertoSoutullo

fix: revert "chore: adding observers for message logging (#2800)"

---

waku/node/peer_manager/peer_manager.nim

Checking if the ENR of an incoming peer is the same as the one we have saved and if not, update it in the peer store.
closes #2817

fix: update peers ENRs in peer store in case they are updated

---

ci/Jenkinsfile.release

Currently tags used in the project are a mix of annotated and non-annotated/lightweight tags. Without `--tags` flag `git describe` will not take into account annotated tags.
Depends on:
- [`status-jenkins-lib#100c24ee`](https://github.com/status-im/status-jenkins-lib/commit/100c24ee) - git: allow adding flags to git.describe()

fix(ci): use --tags to match non-annotated tags

---

CHANGELOG.md
waku/node/waku_node.nim
waku/waku_relay/protocol.nim

- Update the changelog
- bump the `nim-libp2p`. This, amongst other things, adds log enhancements that will help to debug how the peer score evolves.
- The changes in `node/waku_node.nim` and `waku_relay/protocol.nim` come from cherry-picking the following commit: a7d2dfd0aabf70e71bd0eb804d45e086a5d297e7

chore: merging release v0.29 into master

---

waku/factory/node_factory.nim

As soon we receive peers in Peer Exchange, we currently try to connect to all of them directly in a very aggressive way.
This does not take into account our connection targets and limits. Therefore, we should first add the peers to the Peer Store, and the connectivity loop will be in charge to choose and connect to the amount of peers necessary to reach its targets.
We saw this case happen and potentially cause issues in #2780

fix: adding peer exchange peers to the peerStore

---

CHANGELOG.md
waku/node/waku_node.nim
waku/waku_relay/protocol.nim

In this PR, I need to use the following merging option so that the `master` branch is written correctly:
This PR is a repetition of the following one: https://github.com/waku-org/nwaku/pull/2802, where I didn't use the correct merge option.

chore: simple PR from release/v0.29 to fix the tag history 

---

waku/node/peer_manager/peer_manager.nim

We're currently attempting establish more `out connections` than our target. We are trying to connect 10 peers at a time, and we still dial 10 even if our target is less than 10.
When investigating https://github.com/waku-org/nwaku/issues/2780, I noticed that the issue started right after we tried to connect to more nodes than we could.
Making a small fix so we stick more precisely to our targets.

chore: stop connecting to out peers until target is reached

---

tests/waku_core/test_namespaced_topics.nim
tests/wakunode_rest/test_rest_relay.nim
waku/factory/node_factory.nim
waku/waku_core/topics/content_topic.nim

Previously, there was confusion in distinguishing between the content and the pubsub topic in logs. Now, the logs are more descriptive, clearly specifying which content-topic pair has the issue.

chore: better descriptive log

---

waku/node/peer_manager/peer_manager.nim

Small fix to only set `disconnectTime` when a node is actually disconnecting
advances https://github.com/waku-org/pm/issues/172

fix: only set disconnect time on left event

---

tests/waku_rln_relay/test_waku_rln_relay.nim
waku/waku_rln_relay/rln_relay.nim

Fixes an edge case where the nullifier log was cleared when maxEpochGap == nullifierLog.len

fix(rln-relay): clear nullifier log only if length is over max epoch gap

---

waku/waku_filter_v2/protocol.nim

close #2320 
PR Description:
We identified a duplicate issue in the filter node service, which has been resolved in this fix.

fix: duplicate message forwarding in filter service

---

tests/waku_archive/test_waku_archive.nim
waku/waku_archive/archive.nim

The _Status_ app tend to perform _Store_ queries multiple content topics. In this tiny PR we are increasing the max number of content topics in a query from 10 to 100
cc @chaitanyaprem

chore: archive.nim - increase the max limit of content topics per query to 100

---

Makefile
waku/discovery/waku_discv5.nim
waku/factory/waku.nim
waku/node/peer_manager/peer_manager.nim

Adding logs when discv5 finds new peers and when the node connects to new peers. These logs will be under the compilation flag `DEBUG_DISCV5` so it is used for DST simulations.
It can be tested in the following image:
```
harbor.status.im/wakuorg/nwaku:discv5-debug-logs
```
Example logs
```
nwaku-1  | NTC 2024-06-25 12:07:43.869+00:00 Received discv5 node                       topics="waku discv5" tid=1 file=waku_discv5.nim:197 addrs=/ip4/195.201.172.178/tcp/30304/p2p/16Uiu2HAmKQAGsUAoUVMt6j7FLRWmou2z3a1WE6CGUiG1YKxWtq2u enr=enr:-LW4QK7dmsv43R2qQknllshhYx9IDEu1cD1t6Ao601ppx8oWYr_joTyfKXjoxQAST1iuGTXfs0ETtJ1fCrZef-GYHrsBgmlkgnY0gmlwhMPJrLKKbXVsdGlhZGRyc4CCcnOTAAEIAAAAAQACAAMABAAFAAYAB4lzZWNwMjU2azGhA2Q1UTaE09UZWli2y5AZFwE-3RGoGGvwrQ_9B5YAy_VWg3RjcIJ2YIN1ZHCCIy2Fd2FrdTIP …
```

chore: adding discv5 logs

---

tests/waku_rln_relay/test_waku_rln_relay.nim
waku/factory/networks_config.nim

* Add The Waku Network parameters for RLN v2.
* Set epoch size in seconds.
* Set amount of messages allowed per epoch.
* Set new contract, present in Polygon zkEVM testnet.

chore: add TWN parameters for RLNv2

---

waku/waku_enr/multiaddr.nim

This would allow reading the `multiaddrs` key and not fail if one of the values encoded in that key is not a multiaddress.
The reason why this change is being proposed is that it would allow storing some data which can be translated to multiaddresses, for example circuit relay addresses which could be stored with this format:
```
- 4 bytes for the IP address
- 2 bytes for the Port
- 33 bytes for a secp256 compressed public key
```
which would mean storing 39 bytes compared to storing 50 bytes which would be the bytes encoding of a multiaddress containing the same information. (In ENRs the less bytes we use the better)
cc: @fryorcraken

chore: ignore arbitrary data stored in `multiaddrs` enr key

---

apps/liteprotocoltester/monitoring/configuration/dashboards/nwaku-monitoring.json
waku/common/ratelimit.nim
waku/common/waku_service_metrics.nim
waku/waku_lightpush/protocol.nim
waku/waku_relay/protocol.nim
waku/waku_store/protocol.nim
waku/waku_store_legacy/protocol.nim

Calculation of relay network traffic per served shards for better understanding network usage for operators.
As part of this, DST log analytics support logs are also added as the necessary solution must converge.
Therefore solution implemented in https://github.com/waku-org/nwaku/pull/2832 is applied here.
This helps testing with lite-protocol-tester and waku-simulator.
https://github.com/waku-org/nwaku-compose/pull/99
https://github.com/waku-org/nwaku/issues/1945

feat: Added proper per shard bandwidth metric calculation

---

waku/waku_rln_relay/rln_relay.nim

* Fixes bug in `nullifierLog`. Now instead of counting elements in the table and removing when > `epochGap`, we ensure that they correspond to the current epoch +- `epochGap`. Anything than that we remove. This protects the node from messages arriving out-of-order.
* Fixes bug in `validateMessageAndUpdateLog`. The `nullifierLog` table was updated with new epochs no matter if the message was rate-limited or not, and no matter if the message even contained a valid proof. This allowed an attacker to attack the `nullifierLog` table, that in conjunction with the previous bug caused rate-limited messages to be accepted. The attacker at no cost could fill the table with unused epochs, bypassing the rate-limit protection.

fix(rln): nullifierlog vulnerability

---

tests/waku_rln_relay/test_rln_group_manager_onchain.nim
tools/rln_keystore_generator/rln_keystore_generator.nim
waku/factory/external_config.nim
waku/factory/networks_config.nim
waku/factory/node_factory.nim
waku/factory/waku.nim
waku/waku_rln_relay/group_manager/on_chain/group_manager.nim
waku/waku_rln_relay/rln_relay.nim

As requested by @alrevuelta to restrict chainId usage and waku node initialization should fail if user erroneously passes in an rpc url for another chain.

chore(rln-relay): add chain-id flag to wakunode and restrict usage if mismatches rpc provider

---

tests/node/test_wakunode_peer_manager.nim
waku/node/peer_manager/peer_manager.nim

Filling `ProtoVersionBook` and `AgentBook` in the peer store
closes #2591

chore: saving agent and protoVersion in peerStore

---

CHANGELOG.md
waku/factory/networks_config.nim

This is needed to update master so that we keep the same decisions that we made in release/v30 to keep using Sepolia and also, use new node keys
We will keep using Sepolia testnet because the zkEVM didn't work properly, i.e., the nonce attribute wasn't consistent during different transactions.

chore: Update master from release v30

---

waku/factory/networks_config.nim

* Set rln message limit to 100

chore(rln): rln message limit to 100

---

waku/waku_archive/driver/postgres_driver/postgres_driver.nim

This PR is inspired by the following article: https://supabase.com/blog/postgres-dynamic-table-partitioning
With that, we aim to avoid having database `ACCESS EXCLUSIVE` operations, that use to happen when a new partition is created.
We are currently suffering from quite frequent and severe blocks in the `postgres` database, which in turn, blocks the connected `nwaku` nodes. This currently impacts `shards.test` fleet and _Status_ app.
closes https://github.com/waku-org/nwaku/issues/2783

fix: postgres_driver - better partition creation without exclusive access

---

tests/waku_rln_relay/test_rln_group_manager_onchain.nim
tools/rln_keystore_generator/rln_keystore_generator.nim
waku/waku_rln_relay/group_manager/on_chain/group_manager.nim
waku/waku_rln_relay/group_manager/on_chain/retry_wrapper.nim

The `rln_keystore_generator` previously did not pass in an `onFatalErrorHandler`, which was leading to segfaults since we don't have a `not nil` check on the callback. Now, this PR introduces the `not nil` check, and also provides an `onFatalError` callback to the `OnchainGroupManager` when it is constructed.

fix(rln_keystore_generator): improve error handling for unrecoverable failure

---

waku/waku_archive_legacy/archive.nim

Simple PR to reduce the stress on the database and only count the number of messages every 30 minutes instead of each minute.

chore: archive legacy run report metrics every 30 minutes instead of 1

---

CHANGELOG.md
waku/factory/networks_config.nim
waku/waku_archive/driver/postgres_driver/postgres_driver.nim

This PR is needed to aggregate the changes and enhancements made in the `release/v0.30` branch for the version `v0.30.2`.
I'm using a separate branch because a merge from `master` was required and I didn't want to pollute the `v0.30.2` branch.
In other words, we are retrieving the following changes to `master`:
- set max limit to 100 messages per epoch in RLN
- skip Postgres feedback errors that can be caused when another nwaku instance accesses the same database, as in Status.

chore: Update master from release v0.30

---

waku/waku_filter_v2/protocol.nim

Setting filter handler logs to trace for cases in which we don't have anywhere to push the messages.
closes #2907

chore: setting filter handling logs to trace

---

Makefile
README.md
waku.nimble

While chating with @fryorcraken, he popped up, why don't we have an easy way of running single tests.
We all do this in different ways, like me I'm using some alias to achieve this.
So I made this little experiment to add custom targets to our makefile to ease and make common and available this task.
While it's a bit tricky to achieve such with make and nimscript I found a usable solution.
So the target is to check if a single file you're working on builds or you may write unit test and want to run first separately from other tests.
With this enhancement, you just need to run
`make build/<path-to-your-file>` or `make test/<path-to-your-file>`
Why is it good?
- no prerequisite knowledge needed how we build our software. All knowledge is coded into Makefile and waku.nimble files.
- It will …

chore: Add new custom built and test target to make in order to enable easy build or test single nim modules

---

apps/sonda/monitoring/configuration/dashboards/sonda-monitoring.json

Improving Sonda's Grafana dashboard
closes #2904

chore: improve sonda dashboard

---

.github/workflows/ci.yml
config.nims
examples/wakustealthcommitments/node_spec.nim
examples/wakustealthcommitments/stealth_commitment_protocol.nim
tests/incentivization/test_all.nim
tests/waku_rln_relay/test_rln_group_manager_onchain.nim
tools/rln_keystore_generator/rln_keystore_generator.nim
waku/common/rate_limit/per_peer_limiter.nim
waku/incentivization/rpc.nim
waku/incentivization/rpc_codec.nim
waku/waku_api/rest/filter/types.nim
waku/waku_api/rest/store/types.nim
waku/waku_rln_relay/constants.nim
waku/waku_rln_relay/contract.nim
waku/waku_rln_relay/conversion_utils.nim
waku/waku_rln_relay/group_manager/on_chain/group_manager.nim
waku/waku_rln_relay/group_manager/static/group_manager.nim
waku/waku_rln_relay/protocol_types.nim

Adding a lint job in the CI checking for equality with the output of nph v0.5.1, and running nph on files that weren't properly linted
Using [nim-libp2p's CI](https://github.com/vacp2p/nim-libp2p/blob/b5fb7b3a97d8977d969d786633f70c4094cd0eaf/.github/workflows/ci.yml) as reference

chore: adding lint job to the CI

---

tests/wakunode_rest/test_rest_admin.nim
waku/waku_api/rest/admin/handlers.nim

Currently [GET `/admin/v1/peers`](https://waku-org.github.io/waku-rest-api/#get-/admin/v1/peers) has additional logic to build a list of peers service node is connected to. 
It does go through each group of protocols and builds a list:
https://github.com/waku-org/nwaku/blob/6d385cefef88ad80f41e830d904d68da596cbbde/waku/waku_api/rest/admin/handlers.nim#L43 
We can directly return list of connected peers as it more aligned with description of the endpoint: 
> Retrieve information about connected peers.

chore: return all connected peers from REST API

---

waku/discovery/waku_discv5.nim
waku/node/peer_manager/peer_manager.nim

I noticed that waku discv5 metrics were not used so I added them back.

fix: add back waku discv5 metrics

---

tests/waku_store/test_all.nim
tests/waku_store/test_resume.nim
waku/factory/external_config.nim
waku/factory/node_factory.nim
waku/node/waku_node.nim
waku/waku_store/resume.nim

Adds a way to save a timestamp periodically so that we can know when the node was last online.
At node start, call a store node and ask for the messages since the last local online timestamp.

feat: store resume

---

apps/networkmonitor/README.md
apps/networkmonitor/docker-compose.yml
apps/networkmonitor/networkmonitor.nim
apps/networkmonitor/networkmonitor_metrics.nim
apps/networkmonitor/prometheus.yaml
waku/waku_metadata/protocol.nim

Wanted to run network monitor to get an idea of status network with clusterID 16 especially to debug peer discovery and connectivity.
Noticed that peer filtering was not happening and it was trying to connect to all peers even from TWN and made changes.

fix: network monitor improvements

---

.github/ISSUE_TEMPLATE/prepare_release.md

Simple PR to make the CCs dogfooding point less strict in the sense that is not blocking. We should inform and advise other CCs to use _Status_ app against `status.staging` but that shouldn't block the expected release date.

chore: prepare_release.md simplify and relax CCs usage in status.staging

---

examples/wakustealthcommitments/node_spec.nim
waku/factory/external_config.nim
waku/factory/node_factory.nim
waku/factory/waku.nim

Adding the `discv5-only` CLI flag for bootstrap/discovery nodes that only run discv5. In those cases, we don't mount the libp2p switch nor additional protocols to avoid unnecessary connections
Notice that I changed the approach from `bootstrap-only` to `discv5-only` because bootstrap nodes can use `waku-peer-exchange`, and that protocol does use the nim-libp2p switch. So this optimization works only in the case that it's running Discv5 and nothing else.
closes #2892

chore: optimizations for discv5 only nodes

---

tests/node/test_wakunode_lightpush.nim
waku/waku_lightpush/callbacks.nim
waku/waku_lightpush/protocol.nim

Give better feedback in case the lightpush server node cannot relay messages to other peers
closes https://github.com/waku-org/nwaku/issues/2950

chore: lightpush better feedback if lightpush service node without peers

---

waku/factory/external_config.nim
waku/factory/node_factory.nim

This PR upgrades the mounting scheme for peer_exchange. With this update, a specific node address is no longer required when mounting peer_exchange from the node side.

chore: upgrade peer exchange mounting 

---

apps/networkmonitor/networkmonitor.nim

I other PRs we have the following error:

fix: networkmonitor compilation issue

---

waku/waku_archive/archive.nim

Avoids logging a `message archived` log line when a message failed to be inserted

fix: return on insert error

---

waku/waku_archive/archive.nim
waku/waku_archive/driver/postgres_driver/postgres_driver.nim

There are occasions where the concurrently-detach partition query didn't complete successfully. In those cases, the database shows an error hint recommending to perform a "finalize" detach partition. This PR aims at applying this approach when that error happens
closes https://github.com/waku-org/nwaku/issues/2890

fix: faster retention policy when error and use of detach finalize when needed

---

waku/node/peer_manager/peer_manager.nim

Pruning excess relay connections to respect our relay connection targets
closes #2929

chore: pruning excess in relay connections

---

waku/node/waku_node.nim
waku/node/waku_switch.nim
waku/waku_api/rest/relay/handlers.nim

As reported on https://github.com/vacp2p/nim-libp2p/issues/1176, using `msg` as a key in `chronicles` causes duplicate keys when parsing the logs, as the main log message is also saved under the `msg` key.
Fixing the instances of this bug in nwaku

fix: avoid using the msg key in chronicles

---

waku/waku_core/message/digest.nim

Currently message hashes are printed like this:
```
topics="waku store" tid=1 file=protocol.nim:58 peerId=16U*BGaw4B requestId=75cbe84cac46075074bcb95cc1920703a7b4bc2aba306959c11085b5379ffef8 request="(requestId: \"75cbe84cac46075074bcb95cc1920703a7b4bc2aba306959c11085b5379ffef8\", includeData: false, pubsubTopic: none(string), contentTopics: @[], startTime: none(CompiledIntTypes), endTime: none(CompiledIntTypes), messageHashes: @[[129, 203, 114, 194, 222, 123, 86, 228, 156, 248, 29, 51, 153, 77, 232, 234, 124, 205, 98, 87, 59, 33, 178, 231, 153, 98, 190, 112, 172, 251, 129, 170], [171, 5, 26, 138, 98, 133, 28, 211, 242, 130, 235, 135, 150, 206, 79, 16, 204, 114, 139, 103, 124, 102, 40, 96, 73, 103, 59, 102, 210, 152, 66, 229], [105, 227, 97, 110, 122, 72, 36, 150, 98, 112, 239, 37, 220, …
```

chore: print WakuMessageHash as hex strings

---

tests/wakunode2/test_validators.nim
waku/factory/external_config.nim
waku/factory/node_factory.nim
waku/factory/validator_signed.nim

Deprecating `--protected-topic` in favor of `--protected-shard` and modifying it to only support static sharding.
We currently support both configurations and their respective formats, and after two releases we can completely remove the `--protected-topic` config
Advances #2806

chore: deprecating protected topics in favor of protected shards

---

waku/node/waku_node.nim
waku/waku_api/rest/relay/handlers.nim
waku/waku_relay/protocol.nim

Logging information related to received messages by using one of the new `onValidated` `nim-libp2p` observers. This is improves our current approach of logging via the `traceHandler`, which does not provide information on who sent the message a node received.
Notice that a "message received" log were added to the REST endpoints that publish messages. This is per DST's request, so they can easily tag the node that published a message to the network as a node that has seen the message.
CC @AlbertoSoutullo

chore: logging received message info via onValidated observer

---

apps/liteprotocoltester/.env
apps/liteprotocoltester/Dockerfile.liteprotocoltester
apps/liteprotocoltester/Dockerfile.liteprotocoltester.compile
apps/liteprotocoltester/README.md
apps/liteprotocoltester/diagnose_connections.nim
apps/liteprotocoltester/docker-compose-on-simularor.yml
apps/liteprotocoltester/docker-compose.yml
apps/liteprotocoltester/filter_subscriber.nim
apps/liteprotocoltester/lightpush_publisher.nim
apps/liteprotocoltester/liteprotocoltester.nim
apps/liteprotocoltester/nim.cfg
apps/liteprotocoltester/run_service_node.sh
apps/liteprotocoltester/run_tester_node.sh
apps/liteprotocoltester/statistics.nim
apps/liteprotocoltester/tester_config.nim
apps/liteprotocoltester/tester_message.nim
waku/waku_api/rest/builder.nim

This PR contains changed to lite-protocol-tester for integration with waku-simulator
- Log self connectivity
- Refined lost and duplicate message detection and reporting.
- separate docker image is built for easy reuse.
see: README.md

chore: liteprotocoltester for simulation

---

waku/waku_archive/driver/builder.nim
waku/waku_archive/driver/postgres_driver/postgres_driver.nim

In a pair session with @richard-ramos, thanks for it :partying_face: :raised_hands: !, we've discovered that the database wasn't using the proper indexes for certain query scenarios.
After applying `ANALYZE messages` to a database we've noticed that the query execution time went from ~1second to ~100ms.
Therefore, we considered that it is interesting to `ANALYZE messages` regularly in the database so that the stats are properly updated and the planner can pick up the optimum indexes for each case.
- Run `ANALYZE messages` once a day.
That was the query under analysis:
```code
SELECT contentTopic, payload, pubsubTopic, version, timestamp, id, messageHash, meta FROM messages WHERE contentTopic IN ('/waku/1/0x9a3fcc34/rfc26','/waku/1/0xc9b649fe/rfc26','/waku/1/0x678be1ba/rfc26','/waku/1/0x87c …
```

chore: ANALYZE messages query should be performed regularly

---

examples/golang/waku.go
library/libwaku.h
library/libwaku.nim
library/waku_thread/inter_thread_communication/requests/debug_node_request.nim

Add new "get ENR" method available in libwaku
- new `waku_get_my_enr` available in `libwaku`
- adapt Golang example to use the new `waku_get_my_enr` function

chore: libwaku retrieve my enr and adapt golang example

---

Dockerfile

We shouldn't assume it exists on the host.
Introduced by:
- https://github.com/waku-org/nwaku/pull/2403

fix: copy libnegentropy.so from nim-build image

---

waku/waku_peer_exchange/protocol.nim

closes #2414 
This implementation will enhance the reliability of the peers shared by the peer-exchange protocol with its clients. because now the cache updates every 5 min.
After the resolution of the peer_manager issue #2905, the reliability of peer exchanges has also been improved.

fix: peer-exchange issue

---

waku/factory/external_config.nim

The config defaults were flipped.

fix: waku sync config defaults

---

library/libwaku.h
library/libwaku.nim
library/waku_thread/inter_thread_communication/requests/discovery_request.nim
library/waku_thread/inter_thread_communication/requests/protocols/lightpush_request.nim
library/waku_thread/inter_thread_communication/requests/protocols/store_request.nim
library/waku_thread/inter_thread_communication/waku_thread_request.nim
waku/waku_relay/protocol.nim

Step further to make nwaku completely accessible from libwaku. Still pending to expose some features such as peer exchange, or filter.
- Allow to start or stop discv5
- Expose lightpush request operation
- Expose list of connected and mesh peers
- Expose store client

chore: libwaku - exposing discv5 store-client and relay connected and mesh peers

---

tests/waku_store_legacy/test_client.nim
tests/waku_store_legacy/test_waku_store.nim
waku/common/databases/db_postgres/pgasyncpool.nim
waku/node/waku_node.nim
waku/waku_archive/archive.nim
waku/waku_archive/common.nim
waku/waku_archive/driver.nim
waku/waku_archive/driver/postgres_driver/postgres_driver.nim
waku/waku_archive/driver/queue_driver/queue_driver.nim
waku/waku_archive/driver/sqlite_driver/sqlite_driver.nim
waku/waku_archive_legacy/archive.nim
waku/waku_archive_legacy/common.nim
waku/waku_archive_legacy/driver.nim
waku/waku_archive_legacy/driver/postgres_driver/postgres_driver.nim
waku/waku_archive_legacy/driver/queue_driver/queue_driver.nim
waku/waku_archive_legacy/driver/sqlite_driver/sqlite_driver.nim
waku/waku_store/client.nim
waku/waku_store_legacy/client.nim
waku/waku_store_legacy/common.nim
waku/waku_store_legacy/protocol.nim

Better track the `requestId` that comes from `store` requests to lower layers (archive/database) so that we can link requests with slow queries
- Pass down the `requestId` value from store layer to the database layer.
- `pgasyncpool.nim`: Print information for queries slower than 2 seconds.
- `client.nim`: allow sending custom `requestId`.
- Adapt tests a little because now some tests checks the returned `requested` vs the sent `requestId` and they failed because we are adding the `requestId` field in the `ArchiveQuery` object.

chore: Better timing and requestId detail for slower store db queries 

---

Makefile
library/callback.nim
library/libwaku.nim
library/waku_thread/inter_thread_communication/requests/protocols/store_request.nim
library/waku_thread/waku_thread.nim

This PR enhances libwaku and is inspired by SP's comment: https://github.com/waku-org/nwaku/pull/3003#discussion_r1736035500
- Add negentropy reference in cwaku_examples
- New `checkLibwakuParams` in libwaku.nim
- Rename `Context` to `WakuContext` to make it a little bit more explicit
- Remove callback from library/waku_thread/inter_thread_communication/requests/protocols/store_request.nim because not needed.

chore: libwaku better params validation and a bit more clarity

---

waku/waku_archive/driver/postgres_driver/postgres_driver.nim

Postgres driver now split queries with more than 100 hashes into multiple ones.
Closes #3006

chore: per limit split of PostgreSQL queries

---

waku/common/databases/db_postgres/dbconn.nim
waku/common/databases/db_postgres/pgasyncpool.nim
waku/waku_store/protocol.nim
waku/waku_store/protocol_metrics.nim

Have better libpq data retrieval. In this PR we are starting to register the underlying socket FD into the chronos selectors so that we have a more optimized time management.
Also adding a metric to allow measuring the time spent in database queries and the time spent returning the response to the store client.
This is inspired by @Menduist 's comment: https://github.com/waku-org/nwaku/pull/1631/files#r1153293945

chore: enhance libpq management

---

CHANGELOG.md
Dockerfile
Makefile
waku/factory/external_config.nim

Merging the v0.32.0 release branch back to Master

chore: update master from release/v0.32

---

metrics/waku-fleet-dashboard.json

Noticed that our grafana dashoard (https://grafana.infra.status.im/) is diverged from our nwaku repository a lot while there is no real git/vcs friendly comparison possibility for it to decide about changes.
So while adding Bandwidth per shards, req/resp protocol request rates and traffic metrics I made a copy from grafana's v142 of fleets Nim-Waku V2 
Contains all up to date changes had been made to https://grafana.infra.status.im + 
Added panels: 
- per shard in(gross/net) and out traffic 
- store: request rate, generated in/out traffic 
- filter: request rate, generated message push (out) traffic of all subs 
- lightpush: request rate, inbound traffic for lightush (output appears in relay) 
Removed row and panels: 
- legacy filter as had been removed from nwaku for a long time.	
> …

chore: Update waku-fleet-dashboard from latest (v142) Grafana + bw per shard + req/resp req rate and traffic metrics

---

tests/node/test_wakunode_lightpush.nim
waku/waku_lightpush/callbacks.nim
waku/waku_lightpush/protocol_metrics.nim

Avoid having a too-variable metric by preventing adding the msg_hash on it. In that case, we are just adding a fixed string, _not_published_to_any_peer_, when the condition "_Lightpush request has not been published to any peers_" is met.
Thanks for the detailed description @jakubgs :raised_hands: 
bug: absurdly high cardinality of waku_lightpush_errors metrics
closes https://github.com/waku-org/nwaku/issues/3019

chore: lightpush - error metric less variable by only setting a fixed string

---

tests/waku_rln_relay/test_waku_rln_relay.nim

This is to avoid too long test logs such as:

test: avoid too verbose rln test

---

library/libwaku.nim

This is inspired by SP's suggestion: https://github.com/waku-org/nwaku/pull/3026#discussion_r1750892090

chore: libwaku reduce repetitive code by adding a template handling resp returns

---

apps/wakunode2/wakunode2.nim
tests/wakunode2/test_app.nim
waku/factory/waku.nim

We currently modify a copy of our configurations when initializing a node in https://github.com/waku-org/nwaku/blob/1713f562353476235a2076941775a1f150d7c615/waku/factory/waku.nim#L104-L106
However, we don't use this modified configuration when setting up the protocols and initializing the node, which causes mismatches between them.
Added a fix to use the same version of the configuration at the`wakunode2` application layer.

fix: setting up node with modified config

---

Dockerfile
Makefile
apps/liteprotocoltester/Dockerfile.liteprotocoltester
apps/liteprotocoltester/Dockerfile.liteprotocoltester.compile
docker/binaries/Dockerfile.bn.amd64
waku/waku_sync/raw_bindings.nim

Due to various link issues with libnegentropy build as shared object, this PR is an experimental/proposal to switch to static linkage. 
<!--
1. All tests, must work same
https://github.com/waku-org/nwaku/issues/3040

chore: Switch libnegentropy library build from shared to static linkage

---

library/waku_thread/inter_thread_communication/requests/discovery_request.nim
tests/common/test_all.nim
tests/common/test_ratelimit_setting.nim
tests/common/test_requestratelimiter.nim
tests/node/test_wakunode_peer_exchange.nim
tests/waku_filter_v2/test_waku_filter_dos_protection.nim
tests/waku_peer_exchange/test_protocol.nim
tests/waku_peer_exchange/test_rpc_codec.nim
waku/common/rate_limit/service_metrics.nim
waku/common/rate_limit/setting.nim
waku/factory/builder.nim
waku/factory/external_config.nim
waku/factory/node_factory.nim
waku/node/waku_node.nim
waku/waku_filter_v2/protocol.nim
waku/waku_filter_v2/subscriptions.nim
waku/waku_lightpush/protocol.nim
waku/waku_peer_exchange.nim
waku/waku_peer_exchange/protocol.nim
waku/waku_peer_exchange/rpc.nim
waku/waku_peer_exchange/rpc_codec.nim
waku/waku_store/protocol.nim
waku/waku_store_legacy/protocol.nim

As part of [DOS protection for req-res protocols and metrics](https://github.com/waku-org/pm/issues/66)  Waku PeerExchange protocol must be protected just as Lightpush/Store and Filter.
The last bullet point introduces a refactored rate limit configuration over CLI/TOML file.
This was necessary as identified different needs for different protocols (out of dogfooding and dashboard data)
This change will break former CLI as removed two former rate-limit option and replaced them by one - formatted string - that can be repeated. 
> As rate-limit configuration is not yet used this breaking change shall not cause trouble, just we need to handle upgrades with care.
New CLI option is `--rate-limit` which has to be set as string in a proper format.
Examples:
- `--rate-limit="lightpush:13/10s"` 
- …

chore: rate limit peer exchange protocol, enhanced response status in RPC

---

waku/waku_enr/sharding.nim

@jakubgs reported a large amount of logs:
We want to avoid that

chore: sharding - reduce log level for a too spammy message

---

library/callback.nim
library/libwaku.nim
metrics/waku-fleet-dashboard.json
waku/common/databases/db_postgres/dbconn.nim
waku/common/databases/db_postgres/query_metrics.nim
waku/waku_store/protocol.nim
waku/waku_store/protocol_metrics.nim
waku/waku_store_legacy/protocol.nim
waku/waku_store_legacy/protocol_metrics.nim

Brings new metrics to analyse the time spent by store.
In a store request, we have these time components:
1. database-time: time spent by the query itself within the database.
2. communication-with-database: time spent by libpq while waiting for response.
3. store-lpstream-resp-time: time spent while returning the response to the store-client.
We will have stats for (1 + 2) and (3)
From nwaku we don't have means to measure the database time, which should be manually measured by analysing `pg_stat_statemets` table with queries like `SELECT calls, total_exec_time, mean_exec_time, max_exec_time, left(query, 80) rows FROM pg_stat_statements ORDER BY total_exec_time DESC LIMIT 100;`.
- New store and database metrics are added
- New grafana panels aiming to better describe query time …

chore: extending store metrics

---

metrics/waku-fleet-dashboard.json
waku/common/databases/db_postgres/dbconn.nim
waku/waku_archive/driver/postgres_driver/postgres_driver.nim
waku/waku_archive_legacy/driver/postgres_driver/postgres_driver.nim

- Printing more exhaustive query logs
- Simplify logging code a little bit in postgres driver
- Use of logarithmic scale to make seeing time values at different ranges more comfy. e.g.:

chore: Better database query logs and logarithmic scale in grafana store panels

---

waku/waku_peer_exchange/protocol.nim
waku/waku_peer_exchange/rpc_codec.nim

With v0.33.0-rc2 on status.staging it was obvious that client using PeerExchange RPC the old way - on request they completely leave out response field (not even default is added) - cause decode error on nwaku side - that now implements changed protocol.
- PeerExchangeRpc will not handle missing response field as error.
- By adding Peer Exchange metrics to grafana dashboard it is better to use counters instead of gauge for better dashboard stats.
https://github.com/waku-org/nwaku/issues/3054

fix: px protocol decode - do not treat missing response field as error

---

.github/workflows/pre-release.yml
.github/workflows/release-assets.yml

Updating upload and download artifact actions to v4 as versions used by us fail because they're deprecated

chore: updating upload and download artifact actions to v4

---

tests/node/peer_manager/peer_store/utils.nim
tests/node/test_wakunode_peer_manager.nim
tests/testlib/testutils.nim
waku/node/peer_manager/peer_manager.nim
waku/node/waku_node.nim

Enhance reconnect logic and fix reconnect tests.
The important point is that it is necessary to set a port different than zero in tests.
closes
- https://github.com/waku-org/nwaku/issues/2592

chore: test peer connection management

---

waku/waku_peer_exchange/protocol.nim
waku/waku_peer_exchange/rpc_codec.nim

lite-protocol-tester implementation started using PX from the receiver side and found that node that implements old style PeerExchange protocol does not containing status_code and status_desc can cause decode failure.
To handle this false assumption of making status_code for response mandatory, if not included the value is derived from the response enr list length.
+1
I found that PeerExchange tries to aggressively fill the ENR cache at startup. It takes a minimum 60 Peers to fill in the cache. But if there is not many this loop will run - async - till end of program at every 5.secs, instead of running at every 10 minutes as designed.
So to break the loop I added a max 10 times trial of aggressive filling.

fix: PeerExchange rpc decode in order not to take response's status_code mandatory - for support old protocol implementation

---

waku/factory/external_config.nim

As suggested by @weboko , it is interesting to add the current nwaku version within the `identify` protocol response.
This PR achieves that. f.e.:

chore: append current version in agentString which is used by the identify protocol

---

metrics/waku-fleet-dashboard.json

After added DOS protection for Peer Exchange protocol, this PR saves the latest version of fleet grafana dashboard.
v.152-153-154 contains the dashboard extended with new PeerExchange row and panels for metrics.
No code change in this PR!
- grafana -> status.staging with v0.33.0-rc3 deployed -> Peer Exchange row

chore: Extend fleet dashboard with PeerExchange metrics

---

waku.nimble
waku/waku_core/time.nim
waku/waku_rln_relay/protocol_metrics.nim

When running a node using libwaku, we repeatedly get the following error
```
metrics error: New label values must be added from same thread as the metric was created from - observation dropped: libp2p_gossipsub_peers_per_topic_gossipsub collector
metrics error: New label values must be added from same thread as the metric was created from - observation dropped: libp2p_gossipsub_peers_per_topic_fanout collector.
metrics error: New label values must be added from same thread as the metric was created from - observation dropped: libp2p_gossipsub_peers_per_topic_mesh collector.
```
Disabling by default the metrics for libwaku until the root cause is taken care of
#3039

chore: disabling metrics for libwaku

---

apps/liteprotocoltester/diagnose_connections.nim
apps/wakucanary/wakucanary.nim
examples/publisher.nim
examples/subscriber.nim
library/waku_thread/inter_thread_communication/requests/peer_manager_request.nim
tests/node/test_wakunode_peer_exchange.nim
tests/node/test_wakunode_peer_manager.nim
tests/test_peer_manager.nim
tests/test_peer_store_extended.nim
tests/test_waku_dnsdisc.nim
waku/node/peer_manager/peer_manager.nim
waku/node/peer_manager/waku_peer_store.nim
waku/node/waku_node.nim
waku/waku_api/rest/admin/handlers.nim
waku/waku_core/peers.nim
waku/waku_filter_v2/protocol.nim
waku/waku_peer_exchange/protocol.nim

Refactored the peer manager to improve stale peer management.
-  [ abstract the peer_store functionality by using waku_peer_store] --> This allows for extending features in waku_peer_store without modifying the core peer_store.
- [ Improved WakuPeerStore: unified peer data, enhanced queries, and added Waku-specific features for better management. ]

refactor: wrap peer store 

---

waku/node/peer_manager/peer_manager.nim

Rejecting incoming Relay connections whenever we reached our `in` connections target.
Currently, we accept connections and prune the excess connections periodically. However, this approach is not working out properly, as nodes can reconnect to us right after we disconnect to them, making no difference.
This makes the node vulnerable to attacks, as other nodes can fill all our connections without leaving libp2p connections to serve non-Relay nodes.
This PR addresses the issue, disconnecting from a Relay node right after receiving their request, in case we already reached our target.
The content of this PR was actually proposed by @Ivansete-status some weeks ago :) Thanks so much!
closes #3063

fix: rejecting excess relay connections

---

tests/waku_archive/test_driver_postgres.nim
waku/common/databases/db_postgres/dbconn.nim
waku/common/databases/db_postgres/pgasyncpool.nim
waku/node/waku_node.nim
waku/waku_archive/driver/postgres_driver/postgres_driver.nim

We have three big-time consumption components in `store`:
1. database
2. communicate with database
3. return a response to store-client
This PR enhances the point 2, because we've been applying an incorrect `async` approach, which was to wait for a certain state with the following technique:
```
while pool.isBusy():
await sleepAsync(0.milliseconds)
```
or
```
while not dataAvailable:
await sleepAsync(timer.milliseconds(1))
```
Doing that has a very big impact on performance because we were adding a massive amount of future objects to the async queue. @arnetheduck - correct me if that statement is not accurate.
Therefore, in this PR we are starting to apply a better `async` approach to properly coordinate tasks.
----
Aside from that, we are simplifying `pgasyncpool.nim` and suggesting a …

chore: Optimize store

---

library/libwaku.nim

In `libwaku`, we are not properly handling errors and returning responses for `waku_start` and `waku_stop` requests
#3039

chore: adding missing error handling in libwaku

---

.gitmodules
waku/node/peer_manager/peer_manager.nim
waku/node/waku_node.nim

Once we started promptly disconnecting from excess `in` connections, we began seeing our nodes significantly exceeding their `out` connections targets.
The root cause was a race condition in our keep alive loop https://github.com/waku-org/nwaku/blob/643ab20fc67f251987d594cfb5aa4abb60ccc5b2/waku/node/waku_node.nim#L1241-L1258
The case is the following:
1. A node receives incoming connections beyond its target, and it takes a small amount of time from the moment `nim-libp2p` accepts the connection until our peer manager notices that it's beyond our `in` target and disconnects
2. In the time while we're connected to this `in` connection, we start running the keep alive loop and have that peer in the list of connected peers that we should ping
3. While we're pinging other peers, we disconnect …

fix: out connections leak

---

waku/node/peer_manager/peer_manager.nim

Refactored peer_manager.nim by organizing functions according to their responsibilities.

refactor: re-arrange function based on responsibility of peer-manager

---

tests/waku_rln_relay/test_wakunode_rln_relay.nim

For quite a while, the test `WakuNode - RLN relay::clearNullifierLog: should clear epochs > MaxEpochGap` has been extremely flaky in the CI.
I added in this PR a small fix to make the test more deterministic, however I still see that it's a bit flaky anyways.
So I propose to skip this test in the meantime until we get to work on it, and opened the following issue to track it https://github.com/waku-org/nwaku/issues/3095

chore: improving and temporarily skipping flaky rln test

---

library/waku_thread/inter_thread_communication/requests/debug_node_request.nim

In libwaku, when processing a `RETRIEVE_MY_ENR` request we are adding an extra `"` in the beginning and in the end of the string.
This is necessary for `RETRIEVE_LISTENING_ADDRESSES` because we have to convert a sequence to a string, but for`RETRIEVE_MY_ENR` which already has a return type of type string, this ends up adding extra quotes.
#3039

fix: remove quotes from libwaku's returned enr string

---

library/libwaku.nim

For some reason, when immediately chaining `sendRequestToWakuThread`'s response with the `handleRes` template, there's cases in which the errors are not handled properly. See this [message](https://discord.com/channels/1110799176264056863/1197844654218039387/1291722090847670292) for a more detailed description of the issue.
It's probably due to some misusage of Nim templates, but until we further understand what's wrong with out chaining approach, modifying to a working version.
The template usage was wrong - changed it to a proc and now works great :)
#3039

fix: changing libwaku's error handling format

---

library/events/json_message_event.nim
library/libwaku.nim
library/waku_thread/inter_thread_communication/requests/discovery_request.nim
library/waku_thread/inter_thread_communication/requests/node_lifecycle_request.nim
library/waku_thread/inter_thread_communication/requests/protocols/lightpush_request.nim
waku.nimble
waku/common/rate_limit/per_peer_limiter.nim
waku/factory/waku.nim
waku/node/delivery_monitor/recv_monitor.nim
waku/node/delivery_monitor/send_monitor.nim
waku/node/delivery_monitor/subscriptions_observer.nim
waku/waku_archive/archive.nim
waku/waku_archive/common.nim
waku/waku_archive_legacy/archive.nim
waku/waku_archive_legacy/driver/queue_driver/index.nim
waku/waku_filter_v2/common.nim
waku/waku_filter_v2/subscriptions.nim
waku/waku_lightpush/callbacks.nim
waku/waku_peer_exchange/protocol.nim
waku/waku_peer_exchange/rpc_codec.nim
waku/waku_rln_relay/protocol_metrics.nim
waku/waku_store/common.nim
waku/waku_store_legacy/rpc.nim

While attempting to compile libwaku from within status-desktop, even tho I'm using the same nim version, it failed to compile with some warnings like: 
```
/home/richard/status/status-desktop/vendor/status-go/third_party/nwaku/waku/waku_archive_legacy/archive.nim(227, 23) Error: getMessagesV2 is deprecated [Deprecated]
stack trace: (most recent call last)
/home/richard/status/status-desktop/vendor/status-go/third_party/nwaku/vendor/nimbus-build-system/vendor/Nim/lib/system/nimscript.nim(421, 18)
/home/richard/status/status-desktop/vendor/status-go/third_party/nwaku/waku.nimble(169, 3) libwakuDynamicTask
/home/richard/status/status-desktop/vendor/status-go/third_party/nwaku/waku.nimble(69, 5) buildLibrary
/home/richard/status/status-desktop/vendor/status-go/third_party/nwaku/vendor/nimbus-b …
```

chore: remove warnings

---

library/waku_thread/inter_thread_communication/requests/peer_manager_request.nim

In libwaku's `GET_ALL_PEER_IDS` requests, stop converting the peerId's to hex and returning them in their original base 64 form
#3039

fix: returning peerIds in base 64 in GET_ALL_PEER_IDS

---

library/waku_thread/inter_thread_communication/requests/peer_manager_request.nim

Currently, libwaku's `GET_PEER_IDS_BY_PROTOCOL` returns the peer ids of peers that have an open libp2p stream associated with a given protocol.
However, what's most interesting for us is the capabilities of our connected peers and not which protocols are we actually using.
For example, for req-res protocols such as Store, most of the time we don't have an open stream associated with the Store protocol - which means that with the current approach `GET_PEER_IDS_BY_PROTOCOL` won't return anything.
Therefore, changing the approach so we return all our connected peers that support a given protocol, even if we don't have open streams for that protocol in specific.
#3039

chore: improving get_peer_ids_by_protocol in libwaku

---

.github/workflows/ci.yml
waku/common/databases/db_postgres/dbconn.nim

Addition of more debug information to the database logs.
It is pending to add requestId to prepared statements and that would require deeper refactor.
Let's see if is enough with that to fine-tune the arbitrary queries

chore: dbconn - add requestId info as a comment in the database logs

---

library/waku_thread/inter_thread_communication/requests/debug_node_request.nim
library/waku_thread/inter_thread_communication/requests/discovery_request.nim

In libwaku, when returning sequences as outputs, in some places we are returning the sequence as a comma-separated string such as in https://github.com/waku-org/nwaku/blob/18c375a5deea569e4bbef09d1f9376ad92190bc5/library/waku_thread/inter_thread_communication/requests/peer_manager_request.nim#L79-L90
while in others we return a string wrapped with the `[ ]` characters, representing an array
For the sake of simplicity and consistence - and mainly so the parsing client-side can be the same in all cases - I propose to return all sequences as comma-separated strings
#3115

chore: returning seqs in libwaku as comma separated strings

---

waku/factory/node_factory.nim
waku/waku_peer_exchange/protocol.nim

When using Peer Exchange in nwaku, we are setting the number of peers requested by using a Relay-specific parameter, which isn't set if we use nwaku as a light client and produces a segfault.
Therefore, defined a `DefaultPXNumPeersReq` constant with a value of 5 to use whenever no argument is provided or whenever Relay is not mounted 
#3115

fix: avoid segfault by setting a default num peers requested in PX

---

waku/waku_archive/archive.nim

Adds the same restriction we had on waku archive legacy of a maximum of 10 content topics per query as it currently was limitless. We have seen that the store query performance drops the more content topics we add so adding a limit of 10 will help avoid this situation as well as comply with the current assumptions of status-go

fix: add a limit of max 10 content topics per query

---

library/libwaku.h
library/libwaku.nim
library/waku_thread/inter_thread_communication/requests/debug_node_request.nim

Adding to libwaku a proc to retrieve our own peerId
#3115

chore: add to libwaku peer id retrieval proc

---

waku/node/peer_manager/peer_manager.nim

PR aimed to prevent the node from running a very intense CPU loop. With that, at least we set a delay of one second, in case no peers are connected.
I came across that the node was running 100% CPU while testing local nodes without peers.

chore: peer_manager - prevent too intense loop when no peers connected

---

Makefile
README.md
config.nims
scripts/build_rln.sh
scripts/windows_setup.sh

This pull request (PR) introduces official Windows support for nwaku. Our ultimate goal is to achieve parity with Linux and macOS, allowing Windows users to build and run nwaku using familiar `make` targets, with minimal platform-specific steps.
The current setup procedure is as follows:
1. Clone the repository and checkout the `windows_support` branch
2. Ensure prerequisites are installed (Make, GCC, MSYS2/MinGW)
3. Run `scripts/windows_setup.sh`
4. Execute `make wakunode2` (additional targets coming soon)
Note: This procedure will be updated as we progress towards our goal of making the windows build process similar to linux and mac. Eventually, users will be able to use standard `make` targets without additional setup steps.
- Successfully building wakunode2 on Windows
- Unit tests …

feat: windows support 

---

apps/networkmonitor/networkmonitor.nim
apps/networkmonitor/networkmonitor_config.nim

This PR fixes NetworkMonitor to work with latest underlying implementation of protocols.

chore(networkmonitor): add missing field on RlnRelay init, set default for num of shards

---

library/waku_thread/inter_thread_communication/requests/discovery_request.nim

The current way of parsing the Peer Exchange's responses in libwaku always returned an error, even if the call was successful. It also ignored the number of peers received.
Fixed the handling of `fetchPeerExchangePeers`'s response
#3115

fix: peer exchange libwaku response handling

---

waku/waku_peer_exchange/protocol.nim

On startup we attempt to populate the Peer Exchange cache once every 5 seconds for the first 50 seconds. We found that in tests from the moment that a node finds a peer until we can share it in PX, we had to wait those 5 seconds.
Updating the strategy so we update the cache once every second for those 50 seconds, as it is a lightweight operation and will help us have PX properly set much quicker.
#3115

chore: decreasing wait time for updating px cache on startup

---

tests/test_waku_enr.nim
tests/waku_core/test_peers.nim
tests/waku_discv5/test_waku_discv5.nim
waku/discovery/waku_discv5.nim
waku/factory/node_factory.nim
waku/waku_core/codecs.nim
waku/waku_core/peers.nim
waku/waku_enr/capabilities.nim
waku/waku_filter_v2/common.nim
waku/waku_lightpush/common.nim
waku/waku_metadata/protocol.nim
waku/waku_peer_exchange/protocol.nim
waku/waku_relay/protocol.nim
waku/waku_store/common.nim
waku/waku_store_legacy/common.nim
waku/waku_sync/common.nim

When adding peers, we used to ignore the protocols advertised in the ENR and would fill the protocols in the Peer Store only after performing Identify.
We're now initializing the protocols with the advertised capabilities and will get updated once Identify is performed.
When mapping the ENR's capabilities to the supported protocols, we assume that the peers use the same version of the protocol as ours. If that's not the case, we'll find out during Identify, update the information and act accordingly.
In addition to that, started adding the Discv5 bootstrap nodes to the Peer Store.
I moved all the Waku protocols codec definitions to a separate file, as in the current state we had to import most of a protocol even if we only needed a codec, which caused circular dependency issues. Protocol …

chore: saving peers enr capabilities

---

library/libwaku.h
library/libwaku.nim
library/waku_thread/inter_thread_communication/requests/ping_request.nim
library/waku_thread/inter_thread_communication/waku_thread_request.nim

Adds a function to ping peers via bindings
```
int waku_ping_peer(void* ctx,
const char* peerAddr,
int timeoutMs,
WakuCallBack callback,
void* userData);
```
This is required in status-go for the storenode cycle, in which a storenode is selected based on ping RTT

feat(libwaku): ping peer

---

apps/sonda/.env.example
apps/sonda/Dockerfile.sonda
apps/sonda/docker-compose.yml
apps/sonda/sonda.py

Referenced issue: https://github.com/status-im/infra-hq/issues/135
Adapted Sonda script and docker setup to work both for local use and for deployment.
- added CLI flag to Sonda script to specify metrics port and node rest address
- refactored a bit the docker-compose and dockerfile
- added new variables to env vars example file
1. Run the sonda setup locally
https://github.com/status-im/infra-hq/issues/135

refactor: adapt sonda setup for deployment

---

Makefile
apps/liteprotocoltester/.env
apps/liteprotocoltester/Dockerfile.liteprotocoltester.compile
apps/liteprotocoltester/README.md
apps/liteprotocoltester/diagnose_connections.nim
apps/liteprotocoltester/docker-compose.yml
apps/liteprotocoltester/filter_subscriber.nim
apps/liteprotocoltester/lightpush_publisher.nim
apps/liteprotocoltester/liteprotocoltester.nim
apps/liteprotocoltester/lpt_metrics.nim
apps/liteprotocoltester/monitoring/configuration/dashboards/liter-protocol-test-monitoring.json
apps/liteprotocoltester/monitoring/prometheus-config.yml
apps/liteprotocoltester/run_tester_node.sh
apps/liteprotocoltester/service_peer_management.nim
apps/liteprotocoltester/statistics.nim
apps/liteprotocoltester/tester_config.nim
ci/Jenkinsfile.lpt
waku/factory/external_config.nim
waku/node/waku_node.nim

A greater upgrade for liteprotocoltester.
A new repository https://github.com/waku-org/lpt-runner created to ease the usage and run against various waku networks and fleets.
https://github.com/waku-org/nwaku/issues/2999

chore: easy setup fleets for lpt

---

.github/workflows/ci.yml
apps/liteprotocoltester/liteprotocoltester.nim
apps/wakunode2/wakunode2.nim
examples/wakustealthcommitments/node_spec.nim
library/waku_thread/inter_thread_communication/requests/node_lifecycle_request.nim
tests/factory/test_node_factory.nim
tests/test_peer_manager.nim
tests/test_waku_switch.nim
tests/test_wakunode.nim
tests/wakunode2/test_app.nim
tests/wakunode_rest/test_rest_admin.nim
waku/common/utils/nat.nim
waku/discovery/autonat_service.nim
waku/discovery/waku_discv5.nim
waku/factory/builder.nim
waku/factory/external_config.nim
waku/factory/node_factory.nim
waku/factory/waku.nim
waku/node/waku_node.nim
waku/node/waku_switch.nim
waku/waku_core/peers.nim
waku/waku_relay/protocol.nim

Allow a node to act as a circuit-relay client/server. Also, start the _Hole Punch_ server.
This is useful for nodes that are behind a NAT or firewall and hence are not reachable.
Special kudos to @richard-ramos , @lchenut and @diegomrsantos. This PR is yours and also inspired by this PR: https://github.com/waku-org/nwaku/pull/1766
- Undo installation of libpcre because we forced ubuntu 22.04 (unrelated change.)
- Make `Waku` a `ref object` so that it's always passed as by ref.
- Move autonat service code into a separate module, `autonate_service` and check self-reachability every 30 sec instead of every 2 min.
- New external parameter, `relay-client`, which allows setting the node as a circuit-relay client. (we will need to document that.)
- Update ENR when a circuit-relay-client reserves …

chore: Circuit relay

---

Makefile

Due that vscode nph extension is taking nph binary from the path, to avoid possible discrepancies - maybe of having other nph version avail from somewhere else - this chore aims to build nph binary only if needed and move it next to nim binary - into vendor/nimbus-build-system/vendor/Nim/bin/ directory, which is inherently added to the path with the .env.sh script.
Only Makefile changes

chore: Enhancement on building nph and made it available naturaly on the path

---

library/waku_thread/inter_thread_communication/requests/discovery_request.nim

Fixing the returned multiaddresses by libwaku's `waku_dns_discovery` procedure, which were missing the `p2p`
prefix
#3076

fix: libwaku's dns discovery multiaddresses

---

tests/node/test_wakunode_peer_exchange.nim
tests/test_peer_manager.nim
tests/test_wakunode.nim
tests/waku_peer_exchange/test_protocol.nim
tests/waku_relay/test_protocol.nim
tests/waku_relay/test_wakunode_relay.nim
tests/wakunode2/test_validators.nim
tests/wakunode_rest/test_rest_admin.nim
waku/factory/node_factory.nim
waku/node/peer_manager/peer_manager.nim
waku/node/waku_node.nim
waku/waku_api/rest/admin/handlers.nim

Looking deeper at the code, I noticed that the `connectRelay` procedure uses the `nim-libp2p` `connect` procedure that connects to a node without setting a protocol. `connectRelay` was a misnomer and it's more correct to call it`connectPeer`

chore: naming connect procedure

---

library/libwaku.h
library/libwaku.nim
library/waku_thread/inter_thread_communication/requests/peer_manager_request.nim
waku/node/peer_manager/peer_manager.nim

Adding new procedures to libwaku to be able to dial peers using a specific protocol and to be able to retrieve the peerIds of all connected nodes
#3076

feat: adding waku_dial_peer and get_connected_peers to libwaku

---

waku/factory/external_config.nim

Removing protected-topic CLI flag
closes #2984

chore: removing protected-topic cli flag

---

library/libwaku.nim
library/waku_thread/inter_thread_communication/requests/protocols/store_request.nim

nim-libp2p should choose then which multiaddr to use when dialing the peer. This is useful since for example in status-go the storenode list contains both the multiaddress with a DNS, and also another with an IP (for the cases in which for some reason the nameserver fail to resolve the dns name).
It also fixes a parameter name in the ping requests

refactor(libwaku): allow several multiaddresses for a single peer in store queries

---

apps/networkmonitor/networkmonitor_metrics.nim
library/libwaku.nim
library/waku_thread/waku_thread.nim

While playing with [waku-rust-bindings](https://github.com/waku-org/waku-rust-bindings) I noticed that the `waku_destroy` function left a node running forever.
The test that helped to detect the issue is `cargo test default_echo -- --nocapture` from `waku-rust-bindings` repo.
This PR aims to enhance the destroy procedure and avoid deadlocks when `waku_destroy` is invoked.
Also, we carry on with the philosophy of zero acceptance to the use of the `discard` keyword ;P
( there was an nph issue in `apps/networkmonitor/networkmonitor_metrics.nim` )

chore: libwaku - better error handling and better waku thread destroy handling

---

tests/test_waku_rendezvous.nim
tests/test_waku_switch.nim
waku/node/waku_node.nim

Due to the issues arose in https://github.com/waku-org/nwaku/pull/3096
We decided to make a partial version bumping of vendor libs for v0.34.0-rc1.
Due to the huge refactorings in nim-web3 and nim-eth modules:
Code changes:
https://github.com/waku-org/nwaku/issues/3087

chore: Partial version bumps for v0.34.0-rc.1

---

apps/liteprotocoltester/Dockerfile.liteprotocoltester
apps/liteprotocoltester/Dockerfile.liteprotocoltester.compile
apps/liteprotocoltester/run_tester_node_on_fleet.sh

In agreement with infra team to ease the deployment of the liteprotocoltester it is better to embed the specific runner script (which existed in lpt-runner repository) right into the image. 
This is due they will use their own docker-compose setup thus by modifying the entrypoint and command, it is easier to run the official liteprotocoltester image directly.

chore: Adding lpt-runner script and assemble into liteprotocoltester image - to ease infra deployment

---

apps/chat2/chat2.nim
apps/networkmonitor/networkmonitor.nim
library/waku_thread/inter_thread_communication/requests/discovery_request.nim
tests/test_waku_dnsdisc.nim
waku/discovery/waku_discv5.nim
waku/discovery/waku_dnsdisc.nim
waku/factory/node_factory.nim
waku/factory/waku.nim

Instead of exiting if DNS Discovery fails at startup, we now create a loop that attempts to perform DNS Discovery every 30 seconds until it succeeds.
Run `wakunode2` configuring discv5 and dns-discovery with the internet connection off, then turn it on after some time and see that DNS Discovery is performed and Discv5 finds peers
#3076

feat: making dns discovery async

---

metrics/waku-network-monitor-dashboard.json
tests/waku_rln_relay/test_wakunode_rln_relay.nim
waku/waku_rln_relay/group_manager/group_manager_base.nim
waku/waku_rln_relay/protocol_metrics.nim

This PR adds two Grafana panels: one displays the total number of RLN proofs generated till now, and the other shows the remaining RLN proofs per epoch. These panels enable users to monitor the available proofs for the upcoming minutes effectively.
Added two panels:
1. Total Generated Proofs Since Node Start - This value only increases over time.
2. Remaining Proofs Per Epoch - Displays how many proofs can still be generated until the next epoch; it resets with each new epoch.
close #3024

chore: added metrics for total proofs and remaining proofs per epoch.

---

.github/workflows/pre-release.yml
CHANGELOG.md
apps/networkmonitor/networkmonitor_metrics.nim
tests/test_waku_rendezvous.nim
tests/test_waku_switch.nim
waku/factory/external_config.nim
waku/node/waku_node.nim

Changelog for v0.34.0
Please read through and add any highlight for this release as needed.

chore: CHANGELOG.md for v0.34.0

---

tests/factory/test_node_factory.nim
tests/test_waku_rendezvous.nim
tests/testlib/wakunode.nim
tests/wakunode2/test_app.nim
waku/factory/external_config.nim
waku/factory/node_factory.nim
waku/factory/waku.nim
waku/node/waku_node.nim
waku/waku_rendezvous.nim
waku/waku_rendezvous/common.nim
waku/waku_rendezvous/protocol.nim

I've wrapped libp2p rendezvous protocol so that at the waku layer we can register at rdv points and also request peer records.
spec -> https://github.com/waku-org/specs/blob/master/standards/core/rendezvous.md

feat: waku rendezvous wrapper

---

apps/liteprotocoltester/tester_message.nim
waku/waku_api/rest/admin/types.nim
waku/waku_api/rest/debug/types.nim
waku/waku_api/rest/filter/types.nim
waku/waku_api/rest/health/types.nim
waku/waku_api/rest/lightpush/types.nim
waku/waku_api/rest/relay/types.nim
waku/waku_api/rest/serdes.nim

To unstuck waku-sync v2 we need to move to latest nim version.
Currently it is 2.0.12
Currently, this new nim version breaks our code. We need to investigate if it is possible to adjust nim flags for backward compatible build or we can easily adjust our code.
Example error appears with latest nim version:
```
/home/nzp/dev/status/nwaku/waku/waku_api/rest/debug/types.nim(50, 31) template/generic instantiation of `unrecognizedFieldWarning` from here
/home/nzp/dev/status/nwaku/vendor/nim-chronicles/chronicles.nim(380, 10) template/generic instantiation of `log` from here
/home/nzp/dev/status/nwaku/waku/waku_api/rest/serdes.nim(28, 50) Warning: a new symbol 'value' has been injected during template or generic instantiation, however overloads of value will be used instead; either enable …
```

chore: Bump nimbus and nim to latest available - nim-2.0.12

---

library/events/json_message_event.nim
library/libwaku.nim
library/utils.nim
library/waku_thread/inter_thread_communication/requests/protocols/store_request.nim

The Protocol Buffers JSON Specification for 64 bit numbers, recommends serializing numbers as strings to avoid loss of precision when working with 64-bit integers in JavaScript environments. This causes issues as some json serializers like Go's respect the specification when serializing a protobuffer into Json.
To avoid this issue, in this PR will allow accepting both integers and numeric strings for those cases in which this spec is not followed

fix(libwaku): support string and int64 for timestamps

---

library/libwaku.nim
library/waku_thread/inter_thread_communication/requests/node_lifecycle_request.nim
waku/factory/app_callbacks.nim
waku/factory/node_factory.nim
waku/factory/waku.nim
waku/factory/waku_callbacks.nim

We noticed that libwaku doesn't automatically configure a callback for receiving Relay messages when creating a node. Currently, the user has to manually subscribe to each topic providing their callback.
In order to make libwaku more user friendly, we need to be able to register all the event-emitting callbacks automatically when creating a node. Therefore, I added a `WakuCallbacks` type where a user can pass all the different callbacks they need when creating a node. Currently, only `relayHandler` is defined in the type, but in a following PRs new callbacks will be added (for example, a callback that runs every time a topic health changes)
#3076

feat: allowing configuration of application level callbacks

---

examples/rust/src/main.rs

Simple PR to perform `waku_start` in the Rust example
( Sorry for format changes. I just installed new Rust extension in VSCode )

chore: extend rust example with waku_start

---

library/events/json_message_event.nim
library/libwaku.nim
library/waku_thread/inter_thread_communication/requests/protocols/store_request.nim
library/waku_thread/waku_thread.nim

This PR was initially meant for enhancing how store protocol worked but it ended up collecting other enhancements
- `%` not needed in `library/events/json_message_event.nim` because we want the messageHash be returned as a sequence, .e.g `[121, 9, ..., 98]`.
- `libwaku.nim`: avoid passing `WakuRelayHandler(onReceivedMessage(ctx)),` in `waku_relay_publish` because it doesn't make sense.
- simple refactor in `store_request.nim`.
- `waku_thread.nim`: addition of reqReceivedSignal to make sure every request is received (not processed) by _The Waku Thread_ before the next request is sent to _The Waku Thread_.
Can be tested by using the `toy-chat` app. See https://github.com/waku-org/waku-rust-bindings/pull/105
- https://github.com/waku-org/nwaku/issues/3076

chore: enhance libwaku store protocol and more

---

library/libwaku.h
library/libwaku.nim
library/waku_thread/inter_thread_communication/requests/protocols/relay_request.nim

- https://github.com/waku-org/nwaku/issues/3076

feat(libwaku): add protected shard

---

library/events/json_connection_change_event.nim
library/libwaku.nim
waku/factory/app_callbacks.nim
waku/factory/waku.nim
waku/node/peer_manager/peer_manager.nim

Adding a connection health change event which gets triggered every time a peer connects or disconnects. When the event is triggered, a new app callback named `connectionChangeHandler` is called. This PR also integrates the event to libwaku.
#3076

feat: connection change event

---

library/alloc.nim
library/libwaku.nim
library/waku_thread/inter_thread_communication/requests/protocols/lightpush_request.nim
library/waku_thread/inter_thread_communication/requests/protocols/relay_request.nim
library/waku_thread/inter_thread_communication/requests/protocols/store_request.nim
waku/node/waku_node.nim
waku/waku_lightpush/client.nim
waku/waku_lightpush/self_req_handler.nim

- Avoid the use of `string` type in libwaku. In fact, we should avoid any GC'ed type (`string`, `ref`, `closure`, `seq`) when performing ffi operations. Instead, we can only allocate/deallocate memory manually
- Initialize default `cstring` params with `nil` instead of an empty `string` (`""`)
- library/alloc.nim: reserve an empty cstring when `nil` is passed to `alloc` proc
- lightpush_request.nim, self_req_handler.nim: return a `msg_hash` when successful publish
- library/waku_thread/inter_thread_communication/requests/protocols/store_request.nim: rm extra `deallocShared`

chore: Libwaku tweaks

---

examples/golang/README.md
examples/golang/waku.go
waku/common/databases/db_postgres/dbconn.nim
waku/common/databases/db_postgres/pgasyncpool.nim
waku/waku_api/rest/origin_handler.nim
waku/waku_archive/driver/postgres_driver/postgres_driver.nim
waku/waku_archive_legacy/driver/postgres_driver/postgres_driver.nim

- examples/golang/waku.go: Stop linking against negentropy in cgo example.
- Add README.md for golang example.
- In the other files: avoid dependency with `libpcre` library by avoid importing `re` and `nre` and instead, import regex. With that, we will only have dependency with `libpq` (for Postgres client) library.
( thanks @AYAHASSAN287 for the help testing and validating the golang example requirements :partying_face: )

chore: golang example end using negentropy dependency plus simple readme.md

---

waku/factory/node_factory.nim

Avoiding double db migration when both Store and Legacy Store are mounted and sqlite is used.
When both store protocols are mounted, two db migrations are performed: one according to Legacy Store's migration definition and then other according to the newer Store. At the end, we end up having the DB schema set by the newer store.
However, in sqlite the schemas of Store and Legacy Store are different (Legacy Store has a `storedAt` field).Therefore, Legacy Store can't work properly with Store's schema.
Given that Legacy Store is planned to be deprecated and removed soon, instead of creating new migrations and making significant changes in the legacy archive driver to stop using the `storedAt` field, I'm introducing a pretty dirty workaround so we make sure that we don't get to a point of …

fix: avoid double db migration for sqlite

---

Makefile
ci/Jenkinsfile.release

Adding a `DEBUG` flag to the Makefile to create non-release builds.
Additionally, updading `Jenkinsfile.release` to consider this new option and using `1` and `0` consistently accross the Makefile instead of `true` and `false`
#3236

chore: adding debug flag to makefile

---

tests/waku_store_sync/sync_utils.nim
tests/waku_store_sync/test_codec.nim
tests/waku_store_sync/test_storage.nim
waku/waku_store_sync/codec.nim
waku/waku_store_sync/storage/range_processing.nim
waku/waku_store_sync/storage/seq_storage.nim
waku/waku_store_sync/storage/storage.nim

Second PR for new Waku store sync 2.0
Include everything Storage related and tests
[Specification](https://github.com/waku-org/specs/blob/feat--waku-sync-2/standards/core/sync.md)
[Research issue](https://github.com/waku-org/research/issues/102)
N.B. Cannot be merged before #3213
Followed by #3216 
- https://github.com/waku-org/nwaku/issues/3221

feat: waku store sync 2.0 storage and tests

---

tests/waku_store_sync/sync_utils.nim
tests/waku_store_sync/test_protocol.nim
waku/waku_archive/archive.nim
waku/waku_store_sync/codec.nim
waku/waku_store_sync/protocols_metrics.nim
waku/waku_store_sync/reconciliation.nim
waku/waku_store_sync/transfer.nim

Third PR for the new Waku store sync 2.0
Include the protocols themselves.
Transfer protocol does not have tests yet.
[Specification](https://github.com/waku-org/specs/blob/feat--waku-sync-2/standards/core/sync.md)
[Research issue](https://github.com/waku-org/research/issues/102)
N.B. Cannot be merged before #3215 
Followed by #3217 
- https://github.com/waku-org/nwaku/issues/3221

feat: waku store sync 2.0 protocols & tests

---

Makefile
ci/Jenkinsfile.release

Debug builds currently include heaptrack. In this PR, we separate heaptrack from debug builds, and rename the Dockerfile `debug` target to `prod-with-heaptrack` which is more accurate.
#3236

chore: separating heaptrack from debug build

---

tests/node/test_wakunode_legacy_store.nim
tests/node/test_wakunode_store.nim
tests/waku_archive/test_waku_archive.nim
tests/waku_rln_relay/test_rln_group_manager_onchain.nim
waku/waku_archive/archive.nim
waku/waku_store_sync.nim

Simple PR to limit to 24h the max time ranges in store queries.
closes https://github.com/waku-org/nwaku/issues/3170

chore: waku_archive add protection against queries longer than 24h

---

waku/factory/node_factory.nim

This is needed to make a quick creation of the `messages` table, before the event-rln sync kicks off. With that, we avoid having errors from postgres-exporter (nwaku-compose) complaining about non-existing messages table.
closes https://github.com/waku-org/nwaku/issues/3239

chore: move mount store before relay and rln relay

---

library/events/json_message_event.nim
library/waku_thread/inter_thread_communication/requests/protocols/store_request.nim
tests/wakunode_rest/test_rest_store.nim
waku/waku_api/rest/store/client.nim
waku/waku_api/rest/store/handlers.nim
waku/waku_api/rest/store/types.nim
waku/waku_core/message/digest.nim
waku/waku_store/common.nim

As previously discussed, it makes more sense for application clients to use message hashes as hex strings instead of a string representation of a byte array.
In this PR, we're modifying the usage of message hashes in libwaku and in the REST API to receive and return the message hashes as hex strings. This change only applies for the interactions with the message hashes and with pagination cursors (which are themselves message hashes). Everything else remains untouched and other fields such as payload and meta are still sent as base64 strings.
A PR updating the REST API's docs will be opened once this PR is merged. Or shall we define a new endpoint for backward compatibility? Another option is to accept both byte arrays and hex strings in the API and check in the endpoint which one it is …

chore: sending msg hash as string on libwaku message event

---

README.md

While original issue https://github.com/waku-org/nwaku/issues/2087 problem seems not applicable anymore. @Ivansete-status found that nimbus build system rely on `which` utility that is not included into the fedora distribution.
Installing it additionally as pre-req solves the build issue.
https://github.com/waku-org/nwaku/issues/2087

chore: Update notice of build from source pre-requisites for successful fedora builds

---

tests/waku_store_sync/sync_utils.nim
tests/waku_store_sync/test_protocol.nim
waku/node/waku_node.nim
waku/waku_store_sync/codec.nim
waku/waku_store_sync/common.nim
waku/waku_store_sync/reconciliation.nim

Add a check so that peers supporting different shards don't sync.

feat: waku sync shard matching check

---

tests/node/test_wakunode_filter.nim
waku/node/peer_manager/peer_manager.nim
waku/waku_filter_v2/protocol.nim
waku/waku_filter_v2/subscriptions.nim

@fbarbu15 reported that `waku-interop-tests` started to fail.
The problem appeared when one filter-client completely disconnects, e.g., node shutdown. In this case, the `waku_filter_2/subscriptions.nim` module was still keeping an incorrect `Connection` instance. 
Therefore, the `subscriptions` module should listen for peer left events in order to completely remove all the subscription data for that peer.
closes: https://github.com/waku-org/nwaku/issues/3263
closes: https://github.com/waku-org/nwaku/issues/3254

chore: filter remove all subscription from a peer that is leaving

---

tests/incentivization/test_poc.nim
waku/incentivization/eligibility_manager.nim

This is a continuation of the work started in https://github.com/waku-org/nwaku/pull/3166 with associated deliverable https://github.com/waku-org/pm/issues/245.
The overall task is to implement a proof-of-concept service incentivization mechanism, where clients submit txids alongside their requests, and servers check eligibility of those txids as proofs of payment.
This PR adds a check against double-spending. A client is prevented from submitting the same txid twice. The server keeps track of txids it has seen, and checks every txid against that set. If the txid is in the set, the eligibility check fails. 
Note the assumption: a transaction once deemed ineligible will never become eligible in the future, even (for example) in a scenario where a transaction underpaid, and later the server …

feat: incentivization POC: add double-spend check for txid-based eligibility

---

library/waku_thread/inter_thread_communication/requests/node_lifecycle_request.nim

When we attempt to start a node with Relay disabled using libwaku, the node creation fails because we attempt to set Relay app callbacks while having Relay disabled.
We should not attempt to configure Relay related callbacks if Relay is disabled.
Added a fix to send `nil` for the Relay related callbacks in case Relay is disabled.
Notice that I override the callbacks instead of configuring them to `nil` in the first place, and that's because when we set the callbacks, we still don't have the configuration parsed and it's not trivial to parse. I also attempted to set the callbacks after parsing the configuration but I got into a circular dependency error.
Therefore, I'm just adjusting which callbacks to actually send the moment we have the configuration parsed.
#3076

fix: avoid sending relay callbacks if relay is disabled

---

waku/incentivization/eligibility_manager.nim
waku/node/peer_manager/peer_manager.nim
waku/waku_filter_v2/protocol.nim

Better control when the remote peer closes the WakuFilterPushCodec stream remotely.
For example, go-waku closes the stream for every received message. On the other hand, js-waku keeps the stream opened. Therefore, we support both scenarios.
closes https://github.com/waku-org/nwaku/issues/3271

chore: refactor filter to react when the remote peer closes the stream

---

tests/node/test_wakunode_legacy_store.nim
tests/node/test_wakunode_store.nim
tests/waku_archive/test_waku_archive.nim
tests/waku_rln_relay/test_rln_group_manager_onchain.nim
waku/incentivization/eligibility_manager.nim
waku/waku_archive/archive.nim
waku/waku_store_sync.nim

Reverts waku-org/nwaku#3256
See the detail of the decision in: https://github.com/waku-org/nwaku/issues/3170#issuecomment-2637755080

Revert "chore: waku_archive add protection against queries longer than 24h"

---

examples/filter_subscriber.nim
examples/lightpush_publisher.nim

While running lightpush and filter examples connectivity to peers was failing. Realized that metadata is not mounted and hence connectivity keeps failing randomly. 
Updating the same to mount metadata and also use waku sandbox fleet.
Thanks @richard-ramos for helping with this.
Note that i had specified default shard as 0 and clusterID as 1 for metadata support to work. But this is not ideal, maybe we should have a way for the user to not specify shards and just use autosharding API.

chore: update lightclient examples to use waku prod fleet and readme 

---

waku/common/databases/db_postgres/dbconn.nim

libpq sometimes gives extremly long error messages. This PRs limits that
closes https://github.com/waku-org/nwaku/issues/3282

chore: dbconn truncate possible too long error messages

---

.gitmodules

The waku-rlnv2-contract commit (a576a89) that is being added is the one the currently used by _The Waku Network_

chore: add waku-rlnv2-contract as vendor dependency

---

waku/waku_lightpush/protocol.nim

Enhance lightpush log and show `my_peer_id` and the `receivedTime`
That will help @AlbertoSoutullo

chore: lightpush enhance log when handling request

---

library/libwaku.nim
library/waku_thread/waku_thread.nim

Adding a lock so multiple requests sent by different threads can be handled in parallel.
The lock applies only from the moment a task enters the queue to the moment it starts getting handled. Many requests can be handled in parallel, however, the requests are communicated to the Waku Thread one at a time.
This is the same PR as https://github.com/waku-org/nwaku/pull/3273 but I wasn't able to reopen it, so created this one instead.
This is a temporary solution until https://github.com/waku-org/nwaku/issues/3295 is completed
- #3076

chore: supporting parallel libwaku requests

---

tests/testlib/wakucore.nim
tests/waku_rln_relay/test_rln_group_manager_onchain.nim
tests/wakunode_rest/test_rest_lightpush.nim
waku/waku_api/rest/relay/types.nim
waku/waku_api/rest/serdes.nim
waku/waku_store_sync.nim

Investigating another REST lightpush issue reported by @AlbertoSoutullo in the `v0.35.0-rc.1` I noticed that we weren't supporting the example shown in https://waku-org.github.io/waku-rest-api/#post-/lightpush/v1/message
This PR aims to support that example.
It is exptected that the `waku-interop-tests` are failing. The following `waku-interop-tests` PR was submitted to fix that: https://github.com/waku-org/waku-interop-tests/pull/105 and this issue shouldn't happen in upcoming PRs.

chore: better proof handling in REST

---

library/events/json_message_event.nim
library/libwaku.nim

Checking if required `WakuMessage` fields exist before trying to access them and returning an error in case they are not present in the message.
Additionally, fixing double dealloc in case of failure.
- #3076

fix: libwaku's invalid waku message error handling

---

apps/chat2/chat2.nim
apps/chat2/config_chat2.nim
apps/networkmonitor/networkmonitor.nim
examples/cbindings/waku_example.c
library/waku_thread/inter_thread_communication/requests/discovery_request.nim
waku/discovery/waku_dnsdisc.nim
waku/factory/external_config.nim
waku/factory/waku.nim

Deprecating the `--dns-discovery` CLI flag and activating DNS Discovery if `--dns-discovery-url` has a value.
cc @Ivansete-status @plopezlpz 
#3236

chore: deprecating dnsDiscovery flag

---

library/waku_thread/inter_thread_communication/requests/protocols/relay_request.nim
waku/node/waku_node.nim

In libwaku nodes, messages aren't being saved in Store for dynamically-subscribed shards. This happens because when subscribing dynamically via libwaku, we weren't setting the `defaultRelayHandler` we rely on for Store and other protocols.
We need to subscribe to the default handler when dynamically subscribing to topics too.
#3076

fix: subscribing to RelaydefaultHandler in libwaku

---

tests/waku_rln_relay/test_wakunode_rln_relay.nim
tests/waku_store/test_waku_store.nim
tests/waku_store_legacy/test_waku_store.nim

https://github.com/waku-org/nwaku/pull/3227 introduced a serie of debug logs to tackle flaky tests. This PR is about to remove those polluting logs out of scope now.
Removed only tracking debug logs.
Only test code changed.

chore: remove flaky test debug logs from rln tests

---

waku/common/databases/db_postgres/dbconn.nim
waku/common/databases/db_postgres/query_metrics.nim
waku/waku_store/client.nim
waku/waku_store/protocol.nim
waku/waku_store/protocol_metrics.nim
waku/waku_store_legacy/protocol_metrics.nim

* Bound the metrics-label-values in arbitrary queries.
* The metrics-label-values for prepared statements are kept as
they already represent a fixed set.
* Store error metrics labels simplification to avoid overwhelm prometheus
* waku/waku_store_legacy/protocol_metrics.nim: change the metrics' names to separate store-v2 (legacy) metrics from store-v3
closes https://github.com/waku-org/nwaku/issues/3282

chore: more efficient metrics usage

---

library/libwaku.nim
waku.nimble

Compiling libwaku with `--nimMainPrefix` to avoid conflicts with other Nim libraries or applications
#3076

fix: using nimMainPrefix in libwaku

---

waku/waku_lightpush/common.nim

... this helps rest api while makes no harm on protocol level
Lightpush v3 status codes inherently tried to be aligned with HTTP codes as much as possible.
While creating REST API reference it turned out that SERVICE NOT AVAILABLE is used with wrong code.
This small change fixes it.

chore: Make lightpush status code better align with http codes

---

tests/incentivization/test_poc_reputation.nim
tests/waku_lightpush/lightpush_utils.nim
tests/waku_lightpush/test_client.nim
waku/factory/external_config.nim
waku/factory/node_factory.nim
waku/incentivization/reputation_manager.nim
waku/node/waku_node.nim
waku/waku_lightpush/client.nim

This PR integrates a reputation system designed as part of the incentivization PoC into the Lightpush protocol behind a feature flag (`reputation`).
A Lightpush client uses the reputation manager to keep track of peers it used previously to publish messages. Peers that had failed at publishing a message get assigned a negative reputation and will not be chosen for future requests. If, however, a neutral- or positive-reputation peer isn't selected by the peer manager after a maximum number of attempts (`10`), a negative-reputation peer is still used.
This is a countinuaton of https://github.com/waku-org/nwaku/pull/3166, https://github.com/waku-org/nwaku/pull/3264, and https://github.com/waku-org/nwaku/pull/3293 with associated deliverable https://github.com/waku-org/pm/issues/245.

feat: integrate reputation manager into Lightpush behind a feature flag

---

waku/node/waku_node.nim

@jm-clius noticed that Waku sync protocols are not mounted to the switch.
This fixes this problem.

fix: waku sync mounting

---

waku/waku_rln_relay/group_manager/group_manager_base.nim
waku/waku_rln_relay/protocol_metrics.nim
waku/waku_rln_relay/rln_relay.nim

I discovered a bug while monitoring Grafana metrics in PR #3181 Currently, the **waku_rln_proof_remining** counter is reset inside the **generateProof** function. This approach fails in the following scenario:
If a new epoch starts but no proofs are generated (i.e., no messages are sent), the counter doesn't reset. Ideally, the counter should reset immediately when a new epoch begins, regardless of whether any messages are sent.
This PR addresses the issue by implementing an independent epoch monitoring task that ensures the counter is reset as soon as a new epoch starts.
Note: The spike should occur around 23:50, but it happens around 23:53 because the user does not generate any RLN proof ( msg ) within the 3-minute timeframe.

chore: improve epoch monitoring

---

tests/incentivization/test_poc_reputation.nim
tests/test_peer_manager.nim
tests/waku_lightpush/lightpush_utils.nim
tests/waku_lightpush/test_client.nim
waku/incentivization/reputation_manager.nim
waku/node/peer_manager/peer_manager.nim
waku/node/waku_node.nim
waku/waku_lightpush/client.nim

This PR moves and adapt the logic related to client-side reputation (in the context of Lightpush) to the PeerManager. This logic has been developed in the Lightpush context (see https://github.com/waku-org/nwaku/pull/3293), now it needs to be moved over to peer manager (to avoid tight coupling with Lightpush) and perhaps generalized.

feat: introduce reputation in PeerManager

---

waku/waku_rendezvous/common.nim
waku/waku_rendezvous/protocol.nim

In order to stop spammy rendez-vous errors, errors are now pooled and when an error is encountered the interval between tries is increased.
@fryorcraken

chore: less logs for rendezvous

---

tests/node/test_wakunode_lightpush.nim
waku/node/waku_node.nim
waku/waku_api/rest/lightpush/handlers.nim
waku/waku_lightpush/protocol.nim

During presentation prep I noticed with lightpush v3 rest api always returns 0 as relayed peers even if with success.
This should not be the case.
1. send successful lightpush v3 with rest
2. relayPeerCount must be greater than 0

fix:lightppush v3 not returning relayed peers count

---

.github/workflows/ci.yml
.github/workflows/windows-build.yml

The "ci / build-windows (pull_request)" workflow verifies compatibility of changes with Windows machines by building the project on Windows using MSYS2 whenever a pull request is made.
Note:- We can't directly run the windows build script since it requires two different terminals (MSYS and Git Bash). However, replicating this setup in a CI action isn’t possible due to both terminal running isolation. To work around this, I run all commands within the MSYS terminal with some trick, that's why it's little different than scripts !
- https://github.com/waku-org/nwaku/issues/2473

chore: CI for windows build

---

waku/waku_peer_exchange/protocol.nim

Simple change to avoid annoying log "ENR cache populated".
Suggested by https://github.com/igor-sirotin

chore: set one log to trace in waku_peer_exchang

---

waku/waku_api/rest/builder.nim

From https://github.com/waku-org/nwaku/issues/3288 and from Build with Waku presentation it is obvious misleading usage of configuration that REST endpoints of lightpush and filter are only available if --lightpushnode/--filternode arguments are defined.
As lightpush/filter clients are always mounted and can handle service peers from other sources there no reason to restrict respective REST endpoints availability connected to filternode and lightpushnode cli arguments -they can accelerate accessing service nodes from the client side. Still, they shall not be mandatory as discovery methods can provide suitable peers.
1. Start a node with discovery enabled but no relay or other services
1. Issue filter ping with REST. It should not say "REST endpoint not available" but either No service …

chore: enable filter and lightpush REST endpoints without having filternode/lightpushnode configured

---

Dockerfile
docker/binaries/Dockerfile.bn.amd64

when i try to build docker image in my macos, it gives a warning due to incorrect case usage. 
fixed wherever i have noticed.
` => WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 30)                                                                                       0.0s
`

fix: docker gives warning while building 

---

apps/wakucanary/wakucanary.nim

This is motivated by @jakubgs 
The PR's purpose is to simplify the usage of `wakucanary` and not force setting cluster-id nor shards.
For example, the following should work without complaint:
```
./build/wakucanary --address=/dns4/store-02.do-ams3.status.prod.status.im/tcp/30303/p2p/16Uiu2HAm9aDJPkhGxc2SFcEACTFdZ91Q5TJjp76qZEhq9iF59x7R
```

chore: relax wakucanary parameters

---

waku.nimble

When working in waku-rust-bindings I've noticed that setting the `logLevel` to `DEBUG` didn't change anything. After applying the suggested change, I could set it to `DEBUG` properly (or `TRACE`.)

chore: waku.nimble force libwaku compile logs with TRACE log level by default

---

waku/common/rate_limit/request_limiter.nim
waku/common/rate_limit/service_metrics.nim
waku/common/rate_limit/single_token_limiter.nim

For the final stage of #3069 under #3060 we would like to test and visualize cross-effect of the different non-relay protocol performances. This can help fine tune rate limiting of those protocols and also to make recommendations for node operator configuration.
Following point finally tracked in a separate repository: https://github.com/waku-org/waku-protocol-perf-test
- Create new node performance monitoring dashboard for non-relay protocols
- Add histograms of processing times per protocol next to each other
- Add panels of request rate graphs
- Possible add bandwidth / message size rates.
- Define some stress test sequence that uses non-relay protocols parallel. (possibly using sonda and lite-protocol-tester tools)    
#3060

chore: non-relay protocols cross performance measurement metrics

---

tests/all_tests_waku.nim
tests/factory/test_config.nim
waku/factory/external_config.nim
waku/factory/internal_config.nim
waku/factory/networks_config.nim
waku/factory/node_factory.nim
waku/factory/waku.nim

Introduce `--preset` configuration to explicitly override a set of config value based on the target Waku network (e.g. TWN, Status, Railgun).
Adding more preset will be done in separate PR.
Overwriting config from cluster-id will be deprecated as a second step.
1. Run `wakunode2` with `--preset=twn` and confirms it can connect to The Waku Network
2. Run `wakunode2` with `--cluster-id=1` and confirms it can **still** connect to The Waku Network (to be deprecated)
3. Run `wakunode2` with Status network parameters and cofirm it can still connect to Status network
A redo of #2859 but with a smaller scope.
I added a number of TODO that I will address in follow-up PRs.

feat: introduce `preset` option

---

library/libwaku.h
library/libwaku.nim
library/waku_thread/inter_thread_communication/requests/protocols/relay_request.nim
waku/waku_relay/protocol.nim

Adding `waku_relay_get_connected_peers` in libwaku
https://github.com/waku-org/nwaku/issues/3076

feat: add waku_relay_get_connected_peers to libwaku

---

library/libwaku.h
library/libwaku.nim
library/waku_thread/inter_thread_communication/requests/protocols/relay_request.nim
waku/waku_relay/protocol.nim

Adding `waku_relay_get_peers_in_mesh` in libwaku
https://github.com/waku-org/nwaku/issues/3076

feat: waku_relay_get_peers_in_mesh to libwaku

---

library/libwaku.h
library/libwaku.nim
library/waku_thread/inter_thread_communication/requests/peer_manager_request.nim

Adding a `waku_get_connected_peers_info` function to libwaku, which returns a json-string with all the connected nodes peerId's as keys, and an object with an array of their protocols supported and and an array of their multiaddresses as values.
#3076

feat: add waku_get_connected_peers_info to libwaku

---

waku/waku_keystore/keystore.nim

While working with a keystore created by js-waku team, we've realized that the nwaku complained as it wasn't able to access the keystore file. What was happening was that the keystore file couldn't be parsed at all and the reason was that the keystore content should be given in one single line.
This PR simply adds a small protection to make sure the keystore file is always passed in a compact way to the parse phase.
This is motivated by @danisharora099 while working with a tailored keystore file.

chore: better keystore management

---

apps/liteprotocoltester/diagnose_connections.nim
apps/liteprotocoltester/service_peer_management.nim
apps/wakucanary/wakucanary.nim
examples/publisher.nim
examples/subscriber.nim
library/waku_thread/inter_thread_communication/requests/peer_manager_request.nim
tests/all_tests_waku.nim
tests/node/peer_manager/peer_store/utils.nim
tests/node/test_wakunode_peer_exchange.nim
tests/node/test_wakunode_peer_manager.nim
tests/test_peer_manager.nim
tests/test_peer_store_extended.nim
tests/test_waku_dnsdisc.nim
tests/waku_discv5/test_all.nim
tests/waku_discv5/test_waku_discv5.nim
waku/node/peer_manager/peer_manager.nim
waku/node/peer_manager/waku_peer_store.nim
waku/node/waku_node.nim
waku/waku_api/rest/admin/handlers.nim
waku/waku_core/peers.nim
waku/waku_filter_v2/protocol.nim
waku/waku_peer_exchange/protocol.nim

- Simplify `PeerStore` management. We should only deal with one `PeerStore` instance.
- Remove the type `WakuPeerStore` in `waku/node/peer_manager/waku_peer_store.nim`. Suggest to only use raw `PeerStore` type.
- Properly update the protocols list when a peer is discovered. The previous implementation just overrode the protos list. In this PR, we update the current protocols list with new discovered protocols. ( see  `addPeer` from `peer_manager.nim` .)
- Changes in `tests/waku_discv5/test_waku_discv5.nim`:
- Activate discv5 unit test list. They were implemented but we didn't run them in our CI.
- Add new discv5 unittest to validate the discovery of "exotic" protocols such as "peer-exchange" or "rendezvous".
- Add new test in `tests/test_peer_manager.nim`
closes
- …

chore: retrieve protocols in new added peer from discv5

---

.github/workflows/pre-release.yml

This PR aims to avoid the following issue in pre-release gh action:
The fix suggestion is inspired by the hint given in the link https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/ (see above picture.) In that link, we have the following recommendation:
closes:
- https://github.com/waku-org/nwaku/issues/3203

fix: Update the upload-artifact from v3 to v4 in pre-release.yml

---

tests/waku_discv5/test_waku_discv5.nim
tests/waku_rln_relay/test_wakunode_rln_relay.nim

Simple PR to skip flaky tests because they need some time to run properly. They are useful for local debug operations but annoying in CI.
- `find random peers with instance predicate`
- `clearNullifierLog: should clear epochs > MaxEpochGap`

chore: skip two flaky tests

---

library/libwaku.nim

When using libwaku, from some languages it's not necessary to set `userData` (in C for example).
Removing the null check for userData in libwaku before our event callbacks. The client should be responsible to set `userData` if their language requires it - or in other words, clients such as `waku-go-bindings` and `waku-rust-bindings` should take care of it.
https://github.com/waku-org/nwaku/issues/3236

fix: avoid performing nil check for userData

---

README.md

Add `rustc` and `cargo` as prerequisite to README (required for RLN compilation).
I've recently built nwaku on a clean Ubuntu installation and noticed a missing prerequisite in the README.

docs: update prerequisites

---

tests/waku_lightpush/lightpush_utils.nim
tests/waku_lightpush/test_client.nim
tests/waku_relay/test_wakunode_relay.nim
tests/waku_rln_relay/test_wakunode_rln_relay.nim
waku/waku_lightpush/client.nim
waku/waku_lightpush_legacy/client.nim
waku/waku_relay/protocol.nim

Make sure `timestamp` is always set to `now` when publishing. 
Notice that `tests/waku_rln_relay/test_wakunode_rln_relay.nim` needs to be adapted because we cannot directly compare `WakuMessage` objects in tests that originally create `WakuMessages` without timestamp because in that case, the published message will get added a timestamp.
closes https://github.com/waku-org/nwaku/issues/3344

chore: Timestamp now in publish

---

library/libwaku.nim

Removing redundant memory allocations in `libwaku.nim`
The shared memory is always allocated in the corresponding requests' modules
#3236

fix: libwaku's redundant allocs

---

README.md

We need to keep reference for interop test suit instruction on nwaku repo side.
Added link to `js-waku` for interop instructions.
Resolves: https://github.com/waku-org/js-waku/issues/2368

chore: add js-waku link to readme for interop tests

---

tests/node/test_wakunode_relay_rln.nim
tests/waku_rln_relay/rln/waku_rln_relay_utils.nim
tests/waku_rln_relay/test_rln_group_manager_onchain.nim
tests/waku_rln_relay/utils_static.nim
waku/waku_api/rest/relay/handlers.nim
waku/waku_lightpush_legacy/callbacks.nim
waku/waku_rln_relay/conversion_utils.nim
waku/waku_rln_relay/group_manager/group_manager_base.nim
waku/waku_rln_relay/group_manager/on_chain/group_manager.nim
waku/waku_rln_relay/protocol_metrics.nim
waku/waku_rln_relay/protocol_types.nim
waku/waku_rln_relay/rln/rln_interface.nim
waku/waku_rln_relay/rln_relay.nim

This PR deprecates the sync strategy by removing the need for each node to maintain a local Merkle tree. Previously, every node independently managed a Merkle tree and used it to generate Merkle proofs for RLN proof generation. However, constructing a local Merkle tree required syncing a large amount of blockchain data, which was highly time-consuming.
With the latest RLN contract update, we can now fetch Merkle proofs directly from the smart contract, eliminating the need for local Merkle tree maintenance.
<p align="center">
</p>
Changes
closes
- #2924

feat: deprecate sync / local merkle tree 

---

apps/chat2/chat2.nim
apps/chat2/config_chat2.nim
apps/networkmonitor/networkmonitor.nim
apps/networkmonitor/networkmonitor_config.nim
tests/factory/test_external_config.nim
tests/waku_rln_relay/test_rln_group_manager_onchain.nim
tests/waku_rln_relay/utils_onchain.nim
tools/rln_keystore_generator/rln_keystore_generator.nim
waku/factory/conf_builder/rln_relay_conf_builder.nim
waku/factory/external_config.nim
waku/factory/node_factory.nim
waku/factory/waku.nim
waku/factory/waku_conf.nim
waku/waku_rln_relay/group_manager/on_chain/group_manager.nim
waku/waku_rln_relay/rln_relay.nim

In the RLN context, nwaku needs to interact with Smart Contracts. For that, it uses Eth clients.
This PR gives the user the opportunity to the user to use multiple Eth clients and therefore, give the node more estability.
Notice that having a valid/alive Eth client connection is a strong constraint to RLN and therefore, before this PR, if the connection to the single Eth client failed, the whole node got stopped.
closes https://github.com/waku-org/nwaku/issues/3126

chore: allow multiple rln eth clients

---

waku/node/peer_manager/waku_peer_store.nim

As found in #3400 connectedness info of the peer is not follows its real status.
During debugging it turned out, that by calling addPeer with a default initialized RemotePeerInfo can clean up metadata previously stored for the peer. 
Usually peer event connected and joined precedes finishing discv5 peer management.
So peer with all info already stored with joined (new peer) event will be wiped out by discv5 adding peer with RemotePeerInfo initialized with only from ENR - yet having all metadata to default.
This explains why connectedness shown always NotConnected but also other issue discovered by LiteProtocolTester, that many times agent information is empty.
Follow the reproduction steps in https://github.com/waku-org/nwaku/issues/3400
https://github.com/waku-org/nwaku/issues/3400

fix: addPeer could unintentionally override metadata of previously stored peer with defaults and empty

---

Dockerfile

This PR fixes the following issue
```nim
04:32:51  0.887 error: failed to parse lock file at: /app/vendor/zerokit/Cargo.lock
04:32:51  0.887 
04:32:51  0.887 Caused by:
04:32:51  0.887   lock file version `4` was found, but this version of Cargo does not understand this lock file, perhaps Cargo needs to be updated?
04:32:51  0.888 make: *** [Makefile:177: librln_v0.7.0.a] Error 101
04:32:51  ------
04:32:51  Dockerfile:25
04:32:51  --------------------
04:32:51    23 |     
04:32:51    24 |     # Build the final node binary
04:32:51    25 | >>> RUN make -j$(nproc) ${NIM_COMMIT} $MAKE_TARGET LOG_LEVEL=${LOG_LEVEL} NIMFLAGS="${NIMFLAGS}"
04:32:51    26 |     
04:32:51    27 |     
04:32:51  --------------------
```

Update Dockerfile rust image

---

.gitignore
flake.nix
nix/default.nix

This change is only modifying the way libwaku is packaged for Android in the Nix flake. For us is beneficial so later on when we reference it in status-go and status-mobile it is already an `.aar` archive.
- output format of the libwaku-android-arm64 nix package

feat: nix libwaku output package in .aar archive

---

tests/waku_rln_relay/test_waku_rln_relay.nim
tests/waku_rln_relay/test_wakunode_rln_relay.nim
tests/wakunode_rest/test_rest_relay.nim
waku/waku_rln_relay/rln_relay.nim

This PR updates the message validation logic from using epoch to timestamp.
The reason for this change is that the current epoch duration is too long, which allows spammers to resend the same message multiple time to bypass gossipsub.
Note:
Message validation is only upgraded to use the timestamp; the nullifier still relies on rlnMaxEpochGap. This means that currently,  the node stores logs of every message to monitor each user’s message rate. But once the epoch gap exceeds 1, those message longer requires storing messages. To prevent excessive storage usage, we’re continuously deleting those messages from the logs.
closes #2972

fix: timestamp based validation

---

.github/workflows/ci.yml

In `nwaku` repo `js-waku` interop pipeline is very noisy. 
This PR removes debug parameter from interop pipeline as it is most likely not needed for `nwaku` team to investigate problems. And if it is the case interop should be run locally with appropriate debugging level. 
Example of a noisy pipeline: https://github.com/waku-org/nwaku/actions/runs/15188070450/job/42713899348?pr=3419
Resolves: https://github.com/waku-org/js-waku/issues/2388

chore: supress debug for js-waku

---

tests/waku_relay/test_wakunode_relay.nim
waku/node/waku_node.nim

When a node attempts to subscribe to a shard it's already subscribed, we shouldn't return an error and just "ignore" the request.
closes #3414

chore: don't return error on double relay subscription/unsubscription

---

library/libwaku.h
library/libwaku.nim
library/waku_thread/inter_thread_communication/requests/peer_manager_request.nim

Adding a `waku_disconnect_all_peers` function to libwaku, which disconnects from all currently connected peers.
#3076

feat: add waku_disconnect_all_peers to libwaku

---

.github/workflows/ci.yml

Simple PR to update `nph` to latest `master`.
@waku-org/nwaku make sure you recompile `nph` with:
1. rm the current nph binary
2. make build-nph
offtopic - I'm also removing extra line ( nitpick change .) in ci.yml

chore: bump nph and nitpick change

---

waku/factory/external_config.nim
waku/waku_api/rest/builder.nim

This is a small PR to eliminate hard-coded values for rest-relay-cache-capacity.
close #3444

chore: rest-relay-cache-capacity 

---

Makefile
scripts/install_anvil.sh
scripts/install_pnpm.sh
scripts/install_rln_tests_dependencies.sh
tests/waku_rln_relay/test_rln_group_manager_onchain.nim
tests/waku_rln_relay/utils_onchain.nim
tools/rln_keystore_generator/rln_keystore_generator.nim
waku/factory/networks_config.nim
waku/waku_rln_relay/group_manager/on_chain/group_manager.nim

This PR is part of the feature to update the contract abi code used in nwaku and needs to be merged with https://github.com/waku-org/nwaku/pull/3390 before it can be merged with master.
- Update the commit of the waku-rlnv2-contract submodule to the latest
- Replace the `uploadRLNContract` method in the `utils_onchain.nim` with a new contract deployment using the forge deploy scripts
- Update rln dependencies that need to be installed for tests (add pnpm)
- Update all related tests that are broken by the updates in https://github.com/waku-org/nwaku/pull/3390
- Change the tests in `test_rln_group_manager_onchain.nim` to run synchronously, to avoid test failures due to Anvil port connections maxing out
The way to test is to run the `Onchain group manager::should initialize successfully'` …

feat: Update rln contract deployment and tests

---

waku/factory/conf_builder/dns_discovery_conf_builder.nim
waku/factory/external_config.nim

The `wakunode2` could not properly start because the dns servers list was not passed properly
We avoid the issue discovered by @siddarthkay and mentioned in:
- https://github.com/status-im/infra-role-nim-waku/pull/40#issuecomment-2969029505

fix: dnsName servers is not properly set to waku node

---

waku.nimble

Fixing library name for non-windows builds. Without this fix, we get `liblibwaku.so` as output
#3236

fix: libwaku.so compilation

---

waku/waku_lightpush_legacy/protocol.nim

DST team needs unintentionally removed my_peer_id back for legacy-lightpush for their analysis tool
This was change unfortunately while implementing lightush v3 (which inherited the correct log btw)
https://github.com/waku-org/nwaku/issues/3236

fix: correct legacy lightpush handling request log

---

waku/factory/conf_builder/store_service_conf_builder.nim
waku/factory/external_config.nim

Disabling legacy store by default. Our current default of sqlite+legacy is broken and we've decided not to invest much in that combination as both are about to be removed.
We should have both store and legacy store removed by default, and the node operator should explicitly set them to true if they want any of those protocols to be supported.
closes #3479

chore: don't support legacy store by default

---

waku/factory/waku.nim

When setting up the Relay libwaku callback when a node is using static sharding, node setup fails with
```
Could not get autoshards: Static sharding used, cannot get shards from content topics
```
Adding a fix so we don't attempt to get shards from content topics if autosharding isn't enabled
Thanks @fryorcraken for the fix!
#3483

fix: static sharding setup

---

library/waku_thread_requests/requests/peer_manager_request.nim
tests/test_peer_manager.nim
waku/node/peer_manager/peer_manager.nim

Simplifying connection operation in libwaku and removing 5 second sleep in `connectToNodes`. If a sleep is needed, it's the responsibility of the caller to add it or to check if their node is connected.
Note: if tests fail because of removing this sleep, will add the sleep to the tests
- #3483

chore: improve connection proc

---

tests/waku_rln_relay/test_rln_group_manager_onchain.nim
waku/factory/external_config.nim

During RLN related updates some functionality was changed and it is now needed to add a `waitFor` when calling the `fetchMerkleRoot` function, because it returns a `Future`.
This fix is needed for 1 test passing without actually doing anything. (`register: should register successfully`) 
In this test the `waku/waku_rln_relay/group_manager/on_chain/group_manager.nim` `register` function being called was:
```
method register*(
g: OnchainGroupManager, rateCommitment: RateCommitment
): Future[void] {.async: (raises: [Exception]).} =
```
but this if statement was never true:
```
if g.registerCb.isSome():
```
Other tests also needed updates, but were running and passing properly. (`trackRootChanges: should sync to the state of the group` and `trackRootChanges: should fetch history correctly`) …

fix: tests using fetchMerkleRoot

---

waku/waku_api/rest/lightpush/handlers.nim

Simple PR to avoid extremely large log lines in REST lightpush, and only leaving in `trace` log level in case needed for debugging this particular feature.

chore: avoid too large log lines in rest lightpush

---

Makefile

Found a bug during testing: if the test name contains any special characters, it doesn’t match correctly.

chore: test config

---

waku/node/health_monitor/node_health_monitor.nim

Only stopping health monitor components that aren't nil
#3483

fix: only stop health monitor components if not nil

---

waku/discovery/waku_discv5.nim
waku/node/peer_manager/peer_manager.nim
waku/waku_archive/archive.nim
waku/waku_archive/archive_metrics.nim
waku/waku_relay/protocol.nim
waku/waku_rln_relay/protocol_metrics.nim
waku/waku_store/client.nim
waku/waku_store/protocol_metrics.nim

As discussed in #3306, I’ve introduced 7 new metrics, listed below:
1. waku_discv5_discovered_per_shard – [ Discv5 discovered peers per shard ]
2. waku_connected_peers_per_shard – [ Connected peers per shard ]
3. waku_archive_messages_per_shard – [ Archived messages per shard ]
4. waku_relay_max_msg_bytes_per_shard – [ Maximum message size per shard ]
5. waku_relay_avg_msg_bytes_per_shard – [ Average message size per shard ]
6. waku_relay_fleet_store_msg_size_bytes – [ Total message size in the store fleet ]
7. waku_relay_fleet_store_msg_count – [ Total message count in the store fleet ]
I’ve also raised a PR to add a new panel for these metrics:
🔗 https://github.com/waku-org/nwaku-compose/pull/165 
I’ve tested everything to the best of my knowledge. Let me know if you notice any issues …

feat: shard-specific metrics tracking

---

waku/waku_core/topics/sharding.nim

It seems that the suggested operation is not equivalent for all cases.
For example, the following don't give the same results:
```nim
echo "25 mod 7 == " & $(25.uint64 mod 7.uint64)
echo "25 and (7 - 1) == " & $(25.uint64 and uint64(7 - 1))
```

fix: apply modulus in sharding

---

waku/factory/node_factory.nim
waku/waku_api/rest/admin/handlers.nim

Now the rest will see sync-related protocol also while facing details.
Close #3492
@SionoiS 
Test Instructions
1. Start two nodes:  [ Node 1: Should have store and store-sync protocols enable ] [Node 2: A standard relay-enabled node is sufficient]
2. Run nodes using the following commands: [ ./build/wakunode2 --config-file="../config/peer1.txt" ] [ ./build/wakunode2 --config-file="../config/peer2.txt" ] seperate terminal.
3. Ensure both nodes are connected via static node configuration.
4. Once connected, send a REST request from Node 2 to Node 1 to verify peer status: [curl -X GET "http://127.0.0.1:46422/admin/v1/peers" -H "accept: application/json" ]
Note :- 
Node 1 - configuration
nodekey = "6dcae22a737a01541b2852ebe5c5157f936042e79a7fcec87d5b1559701c0e7f"
staticnode = …

fix: rest fix for sync protocol

---

waku/waku_archive/driver/postgres_driver/postgres_driver.nim

The fleet nodes in waku.sandbox cannot properly reduce the database size. See the related issue for further details.
Consider another possible error from the database `already pending detach in part` for performing a `ALTER TABLE messages DETACH PARTITION ... FINALIZE;`
closes https://github.com/waku-org/nwaku/issues/3534

fix: detach partition

---

Dockerfile
apps/liteprotocoltester/Dockerfile.liteprotocoltester.compile
docker/binaries/Dockerfile.bn.amd64
nix/shell.nix

Seems with debian:stable-slim now points to Debian Bookworm and that made libpcre3 deprecated we have a failing docker build
As we already removed std/re dependencies and moved to using nim-regex lib that does not depend on pcre external lib.
As libpcre3 is reported to be vulnerable, it is betterto  completely remove it.

fix remove libpcre lib dependency used for docker builds 

---

Dockerfile
Makefile
docs/tutorial/heaptrack.md
docs/tutorial/nim.2.2.4_heaptracker_addon.patch

With the latest nimbus-build-system we started using along with Nim 2.2.4
The breaking change coming with nimbus-build-system is that we moved away Status's fork of Nim but now use the main repository, thus we can not push our patched branch.
To circumvent the new situation with patching Nim:
- added patch file that can be easily used to make Nim core library heaptrack supporting.
- Updated heatrack.md description
- Updated Dockerfile to apply the patch on the fly when needed.
- Updated Makefile: removed un-necessary NIM_COMMIT and adapted arguments for docker builds.
- checkout nwaku
- issue `make HEAPTRACKER=1 docker-image` or `make HEAPTRACKER=1 docker-quick-image`
- run as described in heaptracker.md document

chore: Adapt heaptrack support builds and description to latest nim 2.2.4 compiler

---

Makefile
waku.nimble

I noticed that I cannot run a single file test with `make test <nim source file>` command without specifying test case name or pattern
This PR fixes the argument passing from Makefile to nimble `executeTest` task.
It will always pass at least empty quotes when no test case specified. Also `executeTest` task will take care of handling that situation properly.
This way it should be possible to run:
`make test`
`make test tests/<test file name>.nim`
and `make test tests/<test file name>.nim "<test case name>"`

fix: make test <nim source file>

---

tests/test_peer_manager.nim
waku/common/callbacks.nim
waku/node/peer_manager/peer_manager.nim
waku/node/waku_node.nim
waku/waku_metadata/protocol.nim

An attempt to address #3539. Comments/suggestions are welcome :)
Rendezvous changes would be taken up in a separate PR.

chore: use a callback to get latest shards for metadata

---

tests/wakunode_rest/test_rest_relay.nim
waku/node/waku_node.nim
waku/waku_api/rest/relay/handlers.nim

https://discord.com/channels/1110799176264056863/1412567451333562498
Recently reported js-waku autosharding tests were failing with latest master.
Finally it is revealed that https://github.com/waku-org/nwaku/pull/3545 changed the shard management with using Relay's subscripbed topics.
That turned out js-waku was using wrong REST api endpoint for Auto sharding relay subscribe.
--> https://github.com/waku-org/js-waku/pull/2625
It's made possible to subscribe with content topics as pubsub topics on Gossipsub level also. 
This PR intends to forbid such case by validating pubsub topic inputs on REST endpoint level.

fix: Do not allow invalid pubsub topic subscription via relay REST api

---

waku/waku_rln_relay/group_manager/on_chain/group_manager.nim

Merkle proof elements are not needed when a node is not registered for RLN. However, the current trackRootChanges function still requires the merkle proof, causing the node to break. This change resolves the issue.

chore: fix node break issue when RLN is unregistered

---

examples/cbindings/waku_example.c
library/waku_context.nim

Avoid crash in cwaku_example, and any other app using libwaku, due to not having chronicles log properly set up.
That issue started to happen ever since we started to use nim-chronicles `v0.12.1` and I assume is because it got more strict.

Fix log libwaku
