waku-org/nwaku

Makefile
Since we can't set this at run time(see #22) then we should build Docker image with it by default.
=> use -d:chronicles_colors:none when creating docker image

docs/api/v2/node.md
Started thinking about how the reduced API could look (issue https://github.com/status-im/nim-waku/issues/39), but I quickly started struggling with how the Waku topics, issue https://github.com/vacp2p/specs/issues/156, system would work in `Floodsub` or `Gossipsub`. 
I'm guessing it can't work and we need to have a separate protocol for lightnode functionality (similar like what we will probably need for historic messages). And perhaps also for bloom filters functionality, if we still want that. Perhaps there is no need for the latter when we have `GossipSub`
=> Start adding waku v2 api calls

docs/api/v2/node.md, waku/node/v2/wakunode2.nim
This simplifies the Node API into five main functions. Depending on the desired privacy/resource constraints, a node will choose how they use it.
Addresses https://github.com/status-im/nim-waku/issues/61
Also stubbed these out in `wakunode` module.
Removed JSONRPC so we can nail this first, then create a mirror based on it.
=> Simplify Node API

docs/api/v2/node.md, examples/v2/basic2.nim, waku/node/v2/wakunode2.nim
Addresses https://github.com/status-im/nim-waku/issues/86
However, this is still using Message as seq[byte] / data field. This needs to be addressed at protocol level; separate issue to come.
Running examples we can see that basic loopback publish/subscribe works.
```
INF 2020-07-28 13:15:21+08:00 Listening on                               tid=10712 full=/ip4/0.0.0.0/tcp/60000/p2p/16Uiu2HAmDaf6KPnZD6GpriEow4tbFNu8AN51baJSLGdNkSxcC2ux
DBG 2020-07-28 13:15:21+08:00 subscribe                                  tid=10712 topic=WakuSub
DBG 2020-07-28 13:15:21+08:00 publish                                    tid=10712 topic=WakuSub
INF 2020-07-28 13:15:21+08:00 Hit subscribe handler                      tid=10712 topic=foobar data="@[104, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100]" …
```
=> Node API: Implement publish

Makefile, waku.nimble
`make test2` runs Waku v2 tests now. `make test` still runs all tests for CI.
=> Refactor Makefile and remove old task

examples/v2/basic2.nim, tests/v2/test_wakunode.nim, waku/node/v2/rpc/wakurpc.nim, waku/node/v2/waku_types.nim, waku/node/v2/wakunode2.nim
- Remove wakuRelayProto as wakuRelay is initiated as part of switch PubSub
- Move WakuNode type into waku_types to avoid circular references
- Make necessary adjustments to get tests and sim to work
=> Waku v2: Simplify Waku Relay references

examples/v1/example.nim, tests/v2/test_wakunode.nim, waku/node/common.nim, waku/node/v1/waku_helpers.nim, waku/node/v1/wakunode.nim, waku/node/v2/wakunode2.nim
fixes https://github.com/status-im/nim-waku/issues/116 and some `setupNat` reuse between v1 and v2
=> WakuNode init without WakuNodeConf

docs/api/v2/node.md, examples/v2/basic2.nim, tests/all_tests_v2.nim, tests/v2/test_wakunode.nim, waku/node/v2/rpc/wakurpc.nim, waku/node/v2/waku_types.nim, waku/node/v2/wakunode2.nim, waku/protocol/v2/waku_relay.nim
Fixes https://github.com/status-im/nim-waku/issues/118
Partially addresses https://github.com/status-im/nim-waku/issues/121
Builds on https://github.com/status-im/nim-waku/pull/123
---
Running examples we can see:
````
DBG 2020-09-01 13:32:43+08:00 publish                                    tid=24041 topic=WakuRelay contentTopic=foo
INF 2020-09-01 13:32:43+08:00 Hit subscribe handler                      tid=24041 topic=foobar payload="hello world" contentTopic=foo
```
=> Add support for WakuMessage and merge publish function

tests/v2/test_wakunode.nim, waku/node/v2/rpc/wakurpc.nim, waku/node/v2/waku_types.nim, waku/node/v2/wakunode2.nim, waku/protocol/v2/waku_relay.nim
Fixing https://github.com/status-im/nim-waku/issues/114 and adding test cases for WakuNode.
Could use further clean-up on the Filters part and a default relayHandler should probably be available for WakuNode
Also need to implement still the key part of the Filters table.
=> Move filter.notify to WakuRelay handler and add test

waku/node/v2/wakunode2.nim, waku/protocol/v2/waku_relay.nim
CI got broken because of two PR merges without rebasing first the second. 
Fixes this as does https://github.com/status-im/nim-waku/pull/131, but by just removing filters from WakuRelay completely.
=> Remove filter parts from relay as this is obsolete (moved to WakuNode)

waku/node/v2/rpc/wakurpc.nim, waku/node/v2/wakunode2.nim
This will allow import of wakunode2 in wakurpc so that https://github.com/status-im/nim-waku/issues/143 can be done.
Fixes https://github.com/status-im/nim-waku/issues/149, but could decide to further split it in two files. Basically it is just a matter then of moving everything under `when isMainModule:` to a new file (and adding the additional imports)
=> Minimal changes of splitting API and CLI code to make import in wakurpc work

Dockerfile, Makefile
To deploy Waku node v2 I added `MAKE_TARGET` argument to the `Dockerfile` to allow for building of separately tagged images.
Related to: https://github.com/status-im/nim-waku/issues/144
=> parametrize Dockerfile to make wakunode2

waku/node/v2/rpc/rpc_publish.nim, waku/node/v2/rpc/wakucallsigs.nim, waku/node/v2/rpc/wakurpc.nim
Fixes https://github.com/status-im/nim-waku/issues/143
This means it is using WakuMessage and going through Node API.
Can be cleaned up further with JSON type encoding and replacing old usage in simulation etc, but this is good enough for testnet!
=> JSON RPC: Use WakuNode instead of WakuRelay

waku/node/v2/rpc/wakurpc.nim
Instead, log stringified version. (This is used for other PoC right now.)
=> Don't crash on non WakuMessage in rpc subscribe

Dockerfile
This is necessary because `COPY` creates a directory for some reason. Also upgraded Alpine image.
Resolves: #166
=> fix Dockerfile by symlinking the wakunode binary

Makefile, docs/tutorial/dingpu.md, docs/tutorial/nangang.md, examples/v2/chat2.nim, waku.nimble
Closes https://github.com/status-im/nim-waku/issues/177
Basic interactive chat app works.
Start two chat apps:
```
./build/chat2 --ports-shift=0
./build/chat2 --ports-shift=1
```
Type `/connect` then paste address of other node.
Then type messages to publish.
General dump of things that can be improved. More targeted issues to be created. In general, enhancements should be based on getting us closer to closing Dingpu testnet https://github.com/vacp2p/research/issues/48
```
##
```
=> Basic end to end chat for Dingpu

Makefile, docs/api/v2/node.md, waku.nimble, waku/node/v2/rpc/rpc_info.nim, waku/node/v2/rpc/wakucallsigs.nim, waku/node/v2/rpc/wakurpc.nim, waku/node/v2/waku_types.nim, waku/node/v2/wakunode2.nim
Closes https://github.com/status-im/nim-waku/issues/201
- Adds a Info API call and JSON RPC call
- Fixes some unrelated errors in query rpc and makefile
- Update node api docs
This allows one to get the listen string by JSON RPC, which is needed for cluster health check.
(Further enhancements can be done to display more diagnostic information)
```
> ./build/rpc_info 
DBG 2020-10-05 13:18:07.528+08:00 Message sent to RPC server                 topics="JSONRPC-HTTP-CLIENT" tid=22956 file=httpclient.nim:188 address=127.0.0.1:8545 msg_len=57
Waku info res: /ip4/0.0.0.0/tcp/60000/p2p/16Uiu2HAmUehj5XstFP41SEmtmbxjkYjogtL3G14Rn4Tsj1ya2nQh
> 
```
=> Node Info API call and JSON RPC

examples/v2/chat2.nim, waku.nimble, waku/node/v2/wakunode2.nim
Fixes https://github.com/status-im/nim-waku/issues/221
Fixes #215 
The problem is the timing of subscribe and connection of nodes. In theory it shouldn't matter I suppose, but in practice it does. Additionally, there seems to be a need for a sleep before subscribe being called. Otherwise, a GRAFT message isn't sent. This means the number of peers in the relevant mesh is zero. For two nodes this isn't visible because of `floodPublish` setting.
It is unclear when or how this was introduced, but it didn't seem to impact wakunode2 because we call `rpc_subscribe` after the node "has settled".
This also means the default subscribe mechanism appears to be faulty in here https://github.com/status-im/nim-waku/commit/03895ffaf559c9c3f8f3cc360dd9af746a3d9ed8 - issue needed to fix this.
It'd be …
=> Fix timing issue with subscribe in chat2

tests/all_tests_v2.nim, tests/v2/test_waku_pagination.nim
This PR fixes a bug in `test_waku_pagination.nim` and also adds `test_waku_pagination` to waku v2 tests.
=> fixes a bug related to contentTopic type mismatch

waku/node/v2/waku_types.nim, waku/node/v2/wakunode2.nim, waku/protocol/v2/waku_store.nim, waku/protocol/v2/waku_swap.nim
Closes https://github.com/status-im/nim-waku/issues/260
Start of accounting PoC bookkeeping and keeping track of balance with peer. See  and https://github.com/vacp2p/specs/blob/master/specs/waku/v2/waku-swap-accounting.md
Ready to review. Changes under flag so no functional code changes. With flag on, it prints accounting stats to STDOUT:
```
NF 2020-11-16 11:43:02.860+08:00 mounting store                             topics="wakunode" tid=7524
hi
hi
INF 2020-11-16 11:43:04.105+08:00 Hit store handler                          tid=7524
DBG 2020-11-16 11:43:04.105+08:00 Using SWAPAccounting query                 topics="wakunode" tid=7524
INF 2020-11-16 11:43:05.363+08:00 Accounting for                             topics="wakuswap" tid=7524 peerId=16*3q4YjS n=2
```
I.e. it has received two …
=> Minimal accounting

examples/v2/chat2.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_store.nim, waku/v2/protocol/waku_swap.nim, waku/v2/waku_types.nim
Addresses https://github.com/status-im/nim-waku/issues/269 to keep accounting state.  Starts to introduce WakuSwap protocol.
Future enhancements:
- End to end https://github.com/status-im/nim-waku/issues/270
- Config flag fix https://github.com/status-im/nim-waku/issues/269
- Better tests (probably as part of 270)
Tested with chat2 as PoC and flag on:
```
INF 2020-11-18 14:47:49.393+08:00 mounting store                             topics="wakunode" tid=10675
INF 2020-11-18 14:47:49.394+08:00 mounting swap                              topics="wakunode" tid=10675
INF 2020-11-18 14:47:49.394+08:00 wakuSwap init 2                            topics="wakunode" tid=10675
INF 2020-11-18 14:47:49.394+08:00 wakuSwap init 1                            topics="wakuswap" tid=10675
Hello
I am writing …
```
=> Minimal accounting state PoC

examples/v2/chat2.nim, tests/v2/test_waku_swap.nim, waku/v2/node/config.nim, waku/v2/node/wakunode2.nim
Addresses https://github.com/status-im/nim-waku/issues/271 and adds a test for updating accounting state after store operations.
Flag is `--swap` and works like other protocol flags. It is off by default.
Also fixes a minor bug where store query was called twice when flag was enabled.
Future issues added:
- https://github.com/status-im/nim-waku/issues/285
https://github.com/status-im/nim-waku/issues/284
=> Accounting: Move flag to config and add basic test for accounting state

Jenkinsfile
Adds a `Jenkinsfile` so we can run CI builds when `master` gets updated.
Build URL: https://ci.status.im/job/nim-waku/job/master/
Necessary for: https://github.com/status-im/infra-nim-waku/issues/2
=> add Jenkinsfile and some Makefile targets for CI

tests/v2/test_waku_swap.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_swap/waku_swap.nim, waku/v2/protocol/waku_swap/waku_swap_types.nim
Addresses end to end in a minimal fashion https://github.com/status-im/nim-waku/issues/270
- Defines threshhold for payment
- Upon reaching this threshhold a cheque is sent
- The cheque updates accounting state for both peers
- Also defines and logs disconnect threshhold
Out of scope of PR (to come in future issues/prs):
- Handshakes
- Authentication
- More parameters
- Smart peer selection
- Disconnect policy
=> Accounting end to end

CHANGELOG.md, examples/v2/basic2.nim, examples/v2/chat2.nim, tests/v2/test_jsonrpc_waku.nim, tests/v2/test_wakunode.nim, waku/v2/node/jsonrpc/relay_api.nim, waku/v2/node/rpc/wakurpc.nim, waku/v2/node/wakunode2.nim
Relates to #146 and #299 
Rather `await` underlying GossipSub `publish` than `discard` it. This allows API calls to also `await` a result and raise an exception on error.
=> Await WakuRelay publish on node

tests/v2/test_jsonrpc_waku.nim, waku/v2/node/jsonrpc/filter_api.nim, waku/v2/node/jsonrpc/jsonrpc_callsigs.nim
A further incremental PR towards #299
This adds a simple way to poll a content topic for new messages on the Filter API. Messages are cached in-memory and cleared after every call.
- **Must have**: a proper way to limit cache size to prevent memory leaks
- **Could have**: a limit on the number of messages returned per call
- **Could have**: moving the message cache from RPC server setup code to a better place. Perhaps the node itself?
- **Should have**: Admin API
- **Should have**: Private API
=> Added content topic polling on FilterAPI

.github/workflows/test.yml
Fixes Windows CI. Problem first reported in https://github.com/status-im/nim-waku/pull/310. Binary target was renamed from `wakunode` -> `wakunode1`.
=> Fix Windows CI: binary reference

tests/v2/test_jsonrpc_waku.nim, waku/v2/node/jsonrpc/filter_api.nim, waku/v2/node/jsonrpc/relay_api.nim
This PR adds minor improvements for #299, specifically the Filter and Relay APIs:
- limit number of messages cacheable per topic/content topic
- modify a copy rather than the underlying data structure (this split should make it easier to eventually move the cache somewhere else, or even make it global)
=> Limit cache size on Filter API and Relay API

docs/tutorial/jsonrpc-api.md, waku/v2/node/config.nim, waku/v2/node/wakunode2.nim
This PR:
- integrates the JSON-RPC API with `wakunode2`.
- configures Admin and Private APIs to be disabled by default
- adds a basic tutorial for the JSON-RPC API covering debug and pub/sub functionality
=> Integrate API and add tutorial

tests/v2/test_jsonrpc_waku.nim, waku/v2/node/wakunode2.nim
This PR relates to #339.
It changes `info` to prefer the latest announced address as returned `listenStr`.
There is currently no way to manually specify an external port while performing [NAT setup](https://github.com/status-im/nim-waku/blob/master/waku/common/utils/nat.nim#L23-L24). The current implementation assumes the external port is the same as the bind port if only an external IP is configured. Unless this was by design, we should probably allow for manual `extPort` configuration that defaults to the bind port if no port mapping is configured.
=> Prefer announced addrs in listenStr

waku/v2/README.md, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_filter/waku_filter.nim, waku/v2/protocol/waku_relay.nim, waku/v2/protocol/waku_store/waku_store.nim, waku/v2/protocol/waku_swap/waku_swap.nim
This PR addresses #324 
It adds a number of metrics for `wakunode2` and related protocols.
1. All waku-related metric names are prefixed `waku_` to make group queries easier (and sorting on Prometheus).
2. Message counters are labelled according to protocol ("relay", "filter" and "store"). For debugging, we could consider adding topic/content topic labels. If the number of topics grow excessively large, however, there will be a corresponding label explosion, so I've avoided this approach for now.
3. There is a single `error` counter per protocol, with different labels for different error types. It's easier to build dashboards/query metrics this way, though care must of course be taken when defining new error types to avoid a label explosion.
4. I've also added a number of gauges to keep …
=> Added waku metrics

metrics/waku-grafana-dashboard.json
Relates to #324 
Updates the grafana dashboard to show Waku v2 metrics.
Since the JSON diff is difficult to interpret, an example of what the updated dashboard looks like below. Many metrics aren't showing as they were simply not logged by the simulation I was running, but it should illustrate the general idea.
=> Updated grafana dashboard to show Waku v2 metrics

CHANGELOG.md, tests/v2/test_waku_filter.nim, waku/v2/node/peer_manager.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_filter/waku_filter.nim, waku/v2/protocol/waku_filter/waku_filter_types.nim
This is a further increment towards #358
It adds the following to the Waku peer manager:
- duplicate handling (a requirement for `filter`, `store` and `swap` peers that are dialed on an ad-hoc basis)
- first step towards integration with `filter` protocol. Since the peer manager includes basic error handling for dialing failures, this has the side effect of improving error handling for the `filter` protocol.
1. Peer selection per protocol in peer manager (eventually using scoring mechanisms to select most appropriate peer).
2. Integrate manager with other Waku v2 protocols: `store` and `swap`
3. Remove local `set` of `peers` for `filter`, `store` and `swap` protocols (i.e. use only `peer manager` for peer storing and selection)
4. Keep track of waku-related metadata for peers (incl. their …
=> Peer manager: improvements; waku_filter integration

CHANGELOG.md, tests/v2/test_jsonrpc_waku.nim, tests/v2/test_waku_store.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_store/waku_store.nim, waku/v2/protocol/waku_store/waku_store_types.nim, waku/v2/protocol/waku_swap/waku_swap.nim, waku/v2/protocol/waku_swap/waku_swap_types.nim
This is a further increment towards #358
It integrates the Waku peer manager with the `store` and `swap` protocols.
1. Peer selection per protocol in peer manager (eventually using scoring mechanisms to select most appropriate peer).
2. Remove local `set` of `peers` for `filter`, `store` and `swap` protocols (i.e. use only `peer manager` for peer storing and selection)
3. Keep track of waku-related metadata for peers (incl. their connection status and behaviour) in an extended peer store.
=> Integrate peer manager with Swap and Store

tests/v2/test_waku_swap_contracts.nim
No functional code changes. Tests for independent SWAP module,  see https://github.com/status-im/nim-waku/issues/360
- Sets up SWAP contracts, etc
-  Issues cheques
- Redeems it
- Verifies ERC20 balance has increased
Continuation of https://github.com/status-im/nim-waku/pull/369, also see changes in https://github.com/vacp2p/swap-contract-module
Uses JSON and STDOUT as interface to a running node.
Hardcoded stuff, lack of error handling etc, but good enough for a basic e2e PoC.
=> Swap contracts use JSON interface and test redeem cheque e2e

tests/all_tests_v2.nim, tests/v2/test_waku_swap_contracts.nim, waku/v2/protocol/waku_swap/waku_swap.nim, waku/v2/protocol/waku_swap/waku_swap_contracts.nim
Previously it was swallowing errors and crashing when not running.
This will allow tests to be enabled by default, albeit without a working running node certain settlement behavior won't be triggered (though these tests can be separated better than the p2p paths)
- Use results, raise defect, exception handling
- JSON used more consistently
- Re-enable waku swap tests (not crashing, just not settling if node interaction isn't working)
=> Better error handling with Results from interactions with swap-contracts-module

Dockerfile
Fixes:
```
15:01:12  Building: Nim compiler
15:01:14  HEAD is now at a80f5d0 move member index to auth object
15:01:14  bash: cargo: command not found
```
=> ci: add rust and cargo to fix builds

.gitignore, examples/v2/chat2.nim, waku.nimble
This is an incremental PR towards #399
It adds the following improvements to the `chat2` application:
1. Logs are now written to a file (`chat2.log`) rather than to `stdout`. The latter is now only used for the chat app itself.
2. Added a chat prompt (`>> `).
3. A nickname can now be set before starting a chat session and changed using the `/nick` command. This is prepended to each published message.
4. Each message in the chat is now prepended by a UTC timestamp.
5. If no static node is set, one will now be selected (at random) from the list of `wakuv2.test` nodes published at `https://fleets.status.im`. (In order to test this, simply run `./build/chat2` with no `--staticnode` argument. `--storenode` unfortunately still needs to be configured - I ran into some issues while trying to …
=> chat2 improvements

docs/tutorial/chat2.md, examples/v2/chat2.nim, waku/v2/protocol/waku_store/waku_store.nim
This is a further incremental PR towards #399
This PR adds the following improvements/fixes to `chat2`:
1. Short date now also prepended to chat messages, in addition to UTC time and nickname.
2. Fixed `metrics error`.
3. Random `storenode` now auto-selected if `store` set to `true` and no `storenode` specified.
4. A basic tutorial.
In principle it should now be possible to run a `chat2` application that auto-selects both a `relay` and `store` peer from the test cluster by simply running the command
```
./build/chat2 --store:true
```
However, see existing issue re historical messages below ->
> TL;DR: Basically something strange is happening on the test cluster, likely to do with connectivity or a bug in the `store` protocol. Use …
=> Further chat2 improvements

Dockerfile
@jakubgs now that the rln library is included as a nim-waku submodule, I can fix the Docker image and specifically the error: `Error loading shared library vendor/rln/target/debug/librln.so: No such file or directory`
Just copying the missing file to the image works for me locally. This may violate a dozen best practices, though, so lmk if there's a better way.
The aim is to have the Jenkins jobs `deploy-v2-test` and `deploy-v2-prod` point to the `nim-waku` `master` branch again.
Thanks!
=> Fix Docker image - missing librln.so file

CHANGELOG.md, tests/v2/test_jsonrpc_waku.nim, waku/v2/node/jsonrpc/admin_api.nim, waku/v2/node/jsonrpc/jsonrpc_callsigs.nim
As part of addressing status-im/nim-waku#408, we require a method within the Admin API that will trigger ad-hoc dialing of peers from a running node. This PR forms the implementation counterpart of this task. Specification change in https://github.com/vacp2p/specs/pull/298.
=> Add post method to Admin API for ad-hoc peer dialing

tests/v2/test_jsonrpc_waku.nim, waku/v2/node/jsonrpc/relay_api.nim, waku/v2/node/wakunode2.nim
This PR closes #411
It fixes a bug in the Relay API where messages on topics previously subscribed to are never handled. The fix adds a handler for each topic already existing (subscribed to) on the node when the Relay API handlers are installed.
=> Fix Relay API: handle messages on previously subscribed topics

tests/v2/test_wakunode.nim
Addresses https://github.com/vacp2p/specs/issues/255
This is just a test to see how we can filter messages in the relay protocol using libp2p topic validators. In subsequent PRs re rln-relay, the validators will implement the zkSNARKs proof verification logic.
=>  Filtering messages in the relay protocol using libp2p topic validators

tests/all_tests_v2.nim, tests/v2/test_waku_bridge.nim, tests/v2/test_waku_rln_relay.nim, waku/common/wakubridge.nim
This PR is a further increment towards #205
Implementation is based on the [Waku bridge specification](https://specs.vac.dev/specs/waku/v2/waku-bridge).
It modifies the Waku bridge script that previously ran a Waku v1 and Waku v2 node in a single process with message bridging, and:
- Introduces the `WakuBridge` node containing both a Waku v1 and Waku v2 node under the hood:
- The Waku v1 node has `Waku` protocol enabled by default
- The Waku v2 node mounts `relay` by default and listens/publishes on a default PubSub topic specifically for bridging (currently: `"/waku/2/default-bridge/proto"`)
- The `WakuBridge` transfers envelopes from Waku v1 to Waku v2 and `WakuMessages` from Waku v2 to Waku v1:
- envelope `topic` corresponds to `WakuMessage` `contentTopic`
- envelope `data` corresponds …
=> Add WakuBridge and test

waku/v1/node/rpc/hexstrings.nim, waku/v2/node/jsonrpc/jsonrpc_utils.nim
This PR closes #417 and addresses the implementation portion of #415
It
1. improves marshalling of `WakuMessage` payloads to JSON: a `seq[byte]` is now marshalled into a hex-format `JString`.
Previously:
```
{
"payload": [
1,
1,
1
],
"contentTopic": 0,
"version": 3
}
```
Now:
```
{
"payload": "0x010101",
"contentTopic": 0,
"version": 3
}
```
2. removes old marshalling code for hex data strings. This has the side-effect of making the `0x` prefix for hex data strings optional in JSON-RPC calls.
=> Fix marshalling of message payloads

tests/v2/test_waku_rln_relay.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_rln_relay/rln.nim, waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
An incremental PR towards https://github.com/status-im/nim-waku/issues/395 and closes https://github.com/status-im/nim-waku/issues/388 and https://github.com/status-im/nim-waku/issues/387. I have also done some clean up and reorganization for the sake of code readability and reusability. 
- Adds Nim bindings for the Merkle tree operations with their unit tests: `get_root`, `update_next_member`, and `delete_member`.
- The prior Nim bindings names are updated to match their original name in the rln Rust lib.
- Removes the untested rln Nim wrappers. 
- The signature of `new_circuit_from_params` is also updated. 
- Updates rln submodule.
- It separates the rln instance creation procedure from the `membershipKeyGen` function.  It is now defined under `createRLNInstance`. The reason for this …
=> Adds Merkle tree Nim bindings

CHANGELOG.md, tests/v2/test_message_store.nim, tests/v2/test_peer_storage.nim, tests/v2/test_waku_store.nim, waku/v2/node/storage/message/message_store.nim, waku/v2/node/storage/message/waku_message_store.nim, waku/v2/node/storage/peer/waku_peer_storage.nim, waku/v2/node/storage/sqlite.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_store/waku_store.nim, waku/v2/protocol/waku_store/waku_store_types.nim
This PR introduces persistent peer storage for Waku v2. It is an increment towards #432. 
Persistence was original deprioritised as a feature for the PoC Waku peer manager in #358, while waiting for a more complete implementation in https://github.com/status-im/nim-libp2p/issues/537.
However, in order to ensure stability in our testnets, and specifically the single network cluster deployments (`test` and `prod`), persisting connected peers across restarts has become more urgent. This is especially necessary for [Waku v2 dogfooding](#399) using the `chat2` app and `test` cluster.
- Integrate persistent storage with peer manager and test
Relates to #358 #399
=> Added persistent storage for peers

waku/v2/node/wakunode2.nim
This PR fixes #439.
It addresses the issue where a `storenode` or `filternode` could be set on a `wakunode2` without mounting the relevant `store` or `filter` protocol. This resulted in a nil storage access error.
=> Fix `nil` error when starting wakunode2 with store/filter node

docs/tutorial/chat2.md
Now that [more Waku implementations](https://github.com/status-im/js-waku/issues/15) are interfacing with the `test` cluster and other `chat2` nodes, it has become necessary to specify the `chat2` message format explicitly. This will allow individual implementations to handle messages and their properties (`timestamp`, `nick` and `payload`) consistently.
=> Specify chat2 message format

tests/v2/test_wakunode.nim, waku/v2/node/wakunode2.nim
This PR fixes #445
It ensures that `relay` protocol, and the underlying `gossipsub`, is started on a `wakunode2`.
This fix assumes the following:
1. A `node` can be started and `relay` protocol mounted in any order.
2. When `relay` is mounted, it should start if and only if the `node` was already started. Otherwise it should start on `node` start.
**Note**: I'm not sure if the original intention was to be somewhat more strict in terms of the ordering above, e.g. that protocols should always be mounted _before_ the node starts listening. In our current examples, tests and scripts, the `mount()`<->`start()` order seems to be interchangeable, which allows for mounting protocols on live nodes.
=> Start relay protocol on wakunode2

tests/v2/test_waku_store.nim, waku/v2/protocol/waku_store/waku_store.nim, waku/v2/protocol/waku_store/waku_store_types.nim
This is an incremental PR towards vacp2p/research#64. 
Two new fields of `startTime` and `endTime` are added to the `HistoryQuery` to enable time-window queries. 
**Some notes:**
The initial thought was to add time-window queries and the relevant fields to the pagination logic i.e., add them to https://github.com/status-im/nim-waku/blob/683577f04552f4fd22f2b302584f23abd3f0e3d4/waku/v2/protocol/waku_store/waku_store_types.nim#L33 , but inspired by  the Twitter pagination technique https://developer.twitter.com/en/docs/twitter-api/pagination, I found it more meaningful to treat the query process separate from the pagination part.  The idea is that we query a history based on the combination of time-window and topics, then we segment the result into pages in case that the number of retrieved …
=> Adds startTime and endTime to the HistoryQuery

waku/v2/protocol/waku_message.nim
Addresses https://github.com/vacp2p/rfc/pull/325#pullrequestreview-628565224
This is to change the field number of proof and timestamp fields in the waku message protobuf schema. 
- The field number of proof is changed from 4 to 21, this is because the proof is related to RLN which is yet an experimental feature. Thus, for now `proof` is an optional field. 
- Following this update, the timestamp field number is shifted to 4.
=> Updates the field number of proof and timestamp

examples/v2/basic2.nim, examples/v2/chat2.nim, tests/v2/test_jsonrpc_waku.nim, tests/v2/test_message_store.nim, tests/v2/test_waku_bridge.nim, tests/v2/test_waku_filter.nim, tests/v2/test_waku_pagination.nim, tests/v2/test_waku_store.nim, tests/v2/test_waku_swap.nim, tests/v2/test_wakunode.nim, waku/common/wakubridge.nim, waku/v2/node/jsonrpc/admin_api.nim, waku/v2/node/jsonrpc/jsonrpc_utils.nim, waku/v2/node/quicksim2.nim, waku/v2/node/scripts/rpc_publish.nim, waku/v2/node/scripts/rpc_query.nim, waku/v2/node/scripts/rpc_subscribe_filter.nim, waku/v2/node/storage/message/waku_message_store.nim, waku/v2/protocol/waku_message.nim
This PR addresses #447 
It changes the `WakuMessage` `contentTopic` back to `string`. Spec changes done in https://github.com/vacp2p/rfc/pull/337
- The "default" content topic is now `"waku/2/default-content/proto"`. This is a rather arbitrary choice and may change once we spec [namespacing for content topics](https://github.com/vacp2p/rfc/issues/227)
- For now, `WakuBridge` maps v2 content topics to v1 topics by selecting the first four bytes. This will change when we introduce [namespacing](https://github.com/vacp2p/rfc/issues/227)
- Note that changing the `contentTopic` type as argument in JSON-RPC calls affects users of the API (cc @D4nte)
- `WakuStore` [index computation for messages](https://github.com/status-im/nim-waku/blob/master/waku/v2/protocol/waku_store/waku_store.nim#L44) …
=> Change contentTopic to string

tests/v2/test_waku_store.nim, waku/v2/protocol/waku_store/waku_store.nim
The way the direction is being encoded right should be roughly equivalent to this code. The direction is a Protobuffer, instead of being an enum/uint32 value:
```js
message PagingInfo {
int64 pageSize = 1;
Index cursor = 2;
Direction direction = 3;
}
Direction {
uint32 value = 1
}
```
To match the [spec description](https://rfc.vac.dev/spec/13/#protobuf), in this PR the `PagingInfo` message encoding/decoding is modified, so its 3rd field (`direction`) contains an uint32 value instead of a encoded message
=> fix: direction encoding

waku/v2/protocol/waku_store/waku_store.nim
As discussed in https://github.com/vacp2p/rfc/issues/326, the order of fields in the `HistoryQuery` protobuf does not match the specs. Specs dictates that fields number should start from `2` , while in the implementation, fields are numbered starting from `1`. This PR is to match the implementation with the specs.
=> Fix the issue in the order of fields of HistoryQuery 

tests/v2/test_jsonrpc_waku.nim, tests/v2/test_waku_store.nim, waku/v2/node/jsonrpc/filter_api.nim, waku/v2/node/jsonrpc/relay_api.nim, waku/v2/protocol/waku_store/waku_store.nim
This PR fixes #477
Windows CI has been failing since `contentTopic` changed to `string`. There were two unrelated failures.
This failure was caused by two factors:
- **A difference in message sorting order in the `store` protocol between platforms**: This only affected the `store` unit tests. Sorting order is supposed to prioritise timestamps to achieve chronological ordering, followed by `digest`. Due to a difference in the result/speed of the `epochTime()` function between platforms/OSs, in the `windows-latest` virtual environment the timestamps were exactly equal for all messages. An artificial delay between message notifications in the `store` test solved this problem.
- **A bug in `store` protocol in determining the start/end index of stored messages**:  The start/end indexes were …
=> Fix Windows CI

tests/v2/test_waku_store.nim, waku/v2/protocol/waku_store/waku_store.nim, waku/v2/protocol/waku_store/waku_store_types.nim
An incremental PR towards https://github.com/vacp2p/research/issues/64 and https://github.com/status-im/nim-waku/issues/458.
As part of enabling a fault-tolerant store protocol, peers must be able to retrieve history messages based on a time range (during which they were absent). In this PR, the logic for handling temporal history queries is added to the store protocol. The unit tests are also included.
=> Enabling time window history query

tests/v2/test_waku_pagination.nim, waku/v2/protocol/waku_store/waku_store.nim
Closes https://github.com/status-im/nim-waku/issues/471
The pagination fails to handle initial paging requests when the store node holds only one message. See details in https://github.com/status-im/nim-waku/issues/471. 
In this PR, further test scenarios are developed to cover the identified corner cases.
=> Handling initial paging requests over a message history of size one

CHANGELOG.md, tests/v2/test_wakunode.nim, waku/v2/node/wakunode2.nim
This PR fixes #480 
It adds a default handler for all newly subscribed PubSub topics to ensure that the node's `subscriptions` and `filters` are notified of all new messages. This ensures that content filtering works for messages received on any subscribed topic, not just the `waku` default.
Content filters can still optionally specify a pubsub `topic`, which will narrow matches down to only messages published on that `topic`.
=> Fix: `filter` protocol only works on default `topic`

docs/tutorial/chat2.md, examples/v2/chat2.nim, waku/v2/node/wakunode2.nim
This PR fixes #455 and partially addresses #487
It adds graceful shutdown procedures on Ctrl-C and SIGTERM for `wakunode2`.
`chat2` can now be shut down gracefully by issuing an `/exit` command.
=> Implement graceful shutdown for `wakunode2` and `chat2`

waku/v2/node/peer_manager/peer_manager.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_relay.nim
This PR addresses #487 
It does the following:
- ensures that peers do not add themselves to their own peer managers
- introduces a backoff period on _reconnection_ to graft persistent peers without violating GossipSub specifications as per below.
Since GossipSub specifies a backoff period for pruned peers before re-grafting, we have to respect this period when reconnecting to peers from persistent storage. Waiting for at least the backoff period before subscribing seems to be the simplest way to address this for now.
1. It should be possible to manually set the backoff period for mesh peers loaded from storage and inform remote peers that you're backing off using a `PRUNE` message. This implies a fairly serious intervention in the default behaviour, though, as it requires altering mesh …
=> Add backoff period before subscribing to persistent peers

examples/v2/chat2.nim, tests/v2/test_waku_store.nim, tests/v2/test_waku_swap.nim, tests/v2/test_wakunode.nim, waku/v2/node/jsonrpc/store_api.nim, waku/v2/protocol/waku_store/waku_store.nim, waku/v2/protocol/waku_store/waku_store_types.nim
This PR is an increment towards https://github.com/status-im/nim-waku/issues/485
It modifies the structure of the `HistoryRequest`  by replacing the `topics` field  with a sequence of `HistoryContentFilter`s.
Each `ContentFilter` encapsulates a single content topic (later on, more fields can be embedded inside a `HistoryContentFilter`). 
- The protobuf's encode and init procedures are modified accordingly.
- A unit test is developed to check the correct retrieval of historical messages for queries with more than one `HistoryContentFilter`.
- Other parts of codebase which relied on `HistoryQuery` are refined.
- This change also affected the store json rpc api. The internals of "get_waku_v2_store_v1_messages" is changed to convert the set of input `topics` to their `HistoryContentFilter` …
=> Update store protocol interface: add history content filter

tests/v2/test_peer_storage.nim, waku/v2/node/config.nim, waku/v2/node/peer_manager/peer_manager.nim, waku/v2/node/peer_manager/waku_peer_store.nim, waku/v2/node/storage/peer/peer_storage.nim, waku/v2/node/storage/peer/waku_peer_storage.nim, waku/v2/node/wakunode2.nim
This PR addresses #487. It is an alternative approach to persisting statically-defined peers than #495.
- It adds a persistent backoff period for peers after disconnection based on the `pruneBackoff` and `BackoffSlackTime` defined for [GossipSub 1.1](https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md#prune-backoff-and-peer-exchange).
- Peer persistence is now a separately configurable option. Since this is a specialised use case, it is disabled by default.
=> Add persistent backoff for peers

examples/v2/chat2.nim, tests/v2/test_jsonrpc_waku.nim, tests/v2/test_waku_filter.nim, tests/v2/test_wakunode.nim, waku/v2/node/jsonrpc/filter_api.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_filter/waku_filter.nim, waku/v2/protocol/waku_filter/waku_filter_types.nim
This PR is a first increment towards fixing #498 and fixes #500
It does the following:
- helps separate `FILTER` from `RELAY` by removing light node notification logic from default `RELAY` topic handlers. Light nodes are now only notified about new filter messages in the filter push message handler. Since `RELAY` is mounted on light nodes, this double `notify()` also caused duplicate messages on the light node (#500).
- fixes full `FILTER` node logic that would previously only push messages to a light node if it had defined a `pubSubTopic` in the filter. `12/WAKU-FILTER`, however, specifies that a `FilterRequest` only optionally needs to specify a `pubsubTopic` - an empty `pubsubTopic` implies that matching should only be done on the `contentFilter`.
- changes ambiguous `topic` variable …
=> Fix filter notifications

waku/v2/node/config.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_relay.nim
This PR provides a workaround fix for #504 and addresses #487.
It adds an optional 5 min `keepAlive` for `WakuRelay` mesh peers. This is to work around the known `libp2p` behaviour where a `chronosstream` will time out after 10 minutes of inactivity.
The `keepAlive` itself sends a `GRAFT` message every 5 minutes to the mesh peers for an idle topic. Since the local node is in the remote peer's mesh already, the remote simply ignores the `GRAFT` but resets the activity timer thus keeping the connection alive. A longer-term solution would use a more appropriate keep-alive mechanism, e.g. [libp2p ping-protocol](https://docs.libp2p.io/concepts/protocols/#ping).
Since this functionality is only necessary where peers must maintain a stable connection while idle for long periods of time (e.g. the …
=> Add optional keepAlive for relay peers

examples/v2/chat2.nim
Simple change to apply `keep-alive` config to `chat2` applications. This way `chat2` clients can be configured to remain connected if idle for a long time.
=> Apply keep-alive for chat2

tests/v2/test_jsonrpc_waku.nim, waku/v2/node/jsonrpc/jsonrpc_callsigs.nim, waku/v2/node/jsonrpc/store_api.nim, waku/v2/node/scripts/rpc_query.nim
Closes https://github.com/status-im/nim-waku/issues/505
No unit test is developed on the nim side due to the issue discussed in https://github.com/status-im/nim-waku/issues/505#issuecomment-828796350
However, the json rpc api is tested through `curl` and the result is as expected i.e., omitting optional arguments results in a valid response with no error. 
The corresponding specs PR: https://github.com/vacp2p/rfc/pull/361
=> Makes the arguments of the store jsonrpc api optional

docs/tutorial/chat2.md, docs/tutorial/store.md, examples/v2/chat2.nim, tests/v2/test_jsonrpc_waku.nim, tests/v2/test_peer_manager.nim, tests/v2/test_waku_swap.nim, tests/v2/test_wakunode.nim, waku/common/config_bridge.nim, waku/common/wakubridge.nim, waku/v2/node/config.nim, waku/v2/node/wakunode2.nim
Addresses https://github.com/status-im/nim-waku/issues/494
It introduces `persist-messages` flag to activate the store protocol  in the light mode. It defaults to `false`.
This flag impacts wakunode2 and disables persisting messages in a database. 
However, as far as I know, in chat2  there is no option to persist messages. Please correct me if I am mistaken @jm-clius @oskarth .
In chat2, the store protocol is mounted in https://github.com/status-im/nim-waku/blob/7e9dac67c8927c953687ee6391c63286377bb9c9/examples/v2/chat2.nim#L280
which invokes this proc whose `store` field is Nil by default
https://github.com/status-im/nim-waku/blob/7e9dac67c8927c953687ee6391c63286377bb9c9/waku/v2/node/wakunode2.nim#L362
=> Enables perssist-message flag in the store protocol for wakunode2

CHANGELOG.md, tests/v2/test_wakunode.nim, waku/v2/node/wakunode2.nim
This PR closes #498. It follows the same approach as https://github.com/status-im/nim-waku/pull/518, but fixes the issue in a more general way to apply to any `light` protocol.
(Also sneaked in an unrelated CHANGELOG.md entry, which I forgot about earlier 😄.)
Currently `nim-libp2p` requires the same `PubSub` protocol used in full nodes (in our case, `RELAY`) to be mounted on light nodes for protocol negotiation to succeed. Detailed explanation [here](https://github.com/status-im/nim-waku/issues/498#issuecomment-828543874).
However, once a light node with `RELAY` mounted has connected to a full node (say, to `subscribe` a content filter or to perform a `lightpush`), it will be considered a "normal" PubSub peer in the full node, undergo grafting and pruning and generally behave like a full …
=> Fix: light-mode relay for all light protocols

Makefile, examples/v2/chat2.nim, examples/v2/matterbridge/chat2bridge.nim, examples/v2/matterbridge/config_chat2bridge.nim, waku.nimble, waku/common/README.md, waku/common/utils/matterbridge_client.nim, waku/v2/node/wakunode2.nim
This is an incremental PR towards https://github.com/status-im/nim-waku/issues/404.
It introduces a bridge between `chat2`  and a configurable [`matterbridge`](https://github.com/42wim/matterbridge) instance. Matterbridge can then be separately configured to support bridging from `chat2` (over Waku v2) to a large number of protocols, including Discord.
This basic implementation includes:
1. A Matterbridge Client utility class that interfaces with a Matterbridge API. It provides the ability to `post` new messages, `poll` for new messages and perform health checks
2. A bridge between `chat2` and Matterbridge that translates between `chat2` messages and Matterbridge
3. A chat2-Matterbridge configuration file
I've tested this locally and can confirm that, with a correctly configured …
=> Add chat2-matterbridge

docs/tutorial/chat2.md, examples/v2/matterbridge/chat2bridge.nim, examples/v2/matterbridge/config_chat2bridge.nim
This is a further increment towards #404 
It adds the following `chat2` bridge to matterbridge improvements:
1. Better logging and error handling
2. Duplicate message filtering
3. Easier configuration
4. Tutorial on how to configure and use `chat2bridge`
=> General chat2bridge improvements

examples/v2/chat2.nim, examples/v2/matterbridge/chat2bridge.nim, examples/v2/matterbridge/config_chat2bridge.nim, waku/common/config_bridge.nim, waku/common/wakubridge.nim, waku/v2/node/config.nim, waku/v2/node/wakunode2.nim
This PR partially addresses #540. It fixes some inconsistencies in the naming of Waku v2 config items. It is the first of three steps necessary to change CLI parameters without breaking existing deployments.
Add new, consistent config items in such a way that we still support the current items. In other words, keep the old CLI parameters intact. Refactor existing field names by postfixing them with `_depr`. This will mark them for removal in `Step 3`.
Propagate changes to existing deployments:
Remove deprecated config items from the codebase.
I've tried adhering to the following conventions:
1. config items with similar semantics should follow similar naming conventions (e.g. `persist-peers` should look similar to `persist-messages`)
2. where a config item is composed of more than one …
=> Fix nim-waku config inconsistencies

examples/v2/chat2.nim, waku/common/config_bridge.nim, waku/common/wakubridge.nim, waku/v2/node/config.nim, waku/v2/node/wakunode2.nim
This PR closes #540 
It is the final step towards fixing config inconsistencies in a backwards compatible manner, as set out in https://github.com/status-im/nim-waku/pull/543.
Fleet nodes were switched over to the new config items in https://github.com/status-im/infra-nim-waku/pull/10.
=> Remove deprecated config items

CHANGELOG.md
This PR addresses https://github.com/status-im/nim-waku/issues/542. It adds the release notes for the `v0.3` release.
Note that this is still a draft PR and I have not pushed a release tag yet, as there will likely still be changes.
I know of the following that still require attention:
- this release adds support for the `alpha` versions of `rln-relay`, `lightpush` and `swap`. Calling these "initial implementations" (as I have done below) may be ambitious/misleading at this early stage. I have indicated that these specs are still in `raw` state towards the end of the release notes. WDYT? @staheri14 @oskarth 
- `STORE` indicates protocol id `/vac/waku/store/2.0.0-beta2` in [the spec](https://rfc.vac.dev/spec/13/), but supports `/vac/waku/store/2.0.0-beta3` in [the …
=> Added v0.3 release notes

tests/v2/test_waku_store.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_store/waku_store.nim, waku/v2/protocol/waku_store/waku_store_types.nim
This is to close https://github.com/status-im/nim-waku/issues/512
- In this basic implementation,  when a restart occurs, the wakunode2 which has the store protocol mounted attempts to fetch the history of message since his last on-time. 
- The last on-time is considered to be the timestamp of the most recent message in the nodes message db.
- A historical time query for that time period is made and the fetched messages get stored in the db as well as in the memory. 
- An offset of 20 second is added to the time window due to the assumption that nodes may be out of sync by at most 20 seconds.
The applied changes are not yet integrated in wakunode2 and  just a placeholder to run the `resume` proc is included in the code (waiting for hackathon to finish to make the changes effective). 
- …
=> Fault tolerant store protocol: resume message history

tests/v2/test_waku_store.nim, waku/v2/protocol/waku_store/waku_store.nim, waku/v2/protocol/waku_store/waku_store_types.nim
This PR closes https://github.com/status-im/nim-waku/issues/513 and closes https://github.com/status-im/nim-waku/issues/458
A list of candidate peers is passed to the resume proc from which the history of messages is going to be retrieved. Such candidates should be found through a discovery method (to be developed in the future).  Passing this list to the resume proc is optional, and if left empty then the underlying peer manager unit of the store protocol will pick one of the current connections randomly to fetch the history from.
=> Ft-store: Peer management

tests/v2/test_waku_bridge.nim, waku/common/wakubridge.nim
This PR closes #554
It adds duplicate filtering to the Waku v1 <> v2 bridge.
Duplicate messages occurred because the default relay handler, registered on the bridge for the default bridge topic, will be triggered after publishing the message bridged from v1. This in turn triggers the v2 -> v1 bridge with a duplicate.
This only happens in direction v1 -> v2.
PR includes general improvements to unit test.
=> Duplicate filtering for `bridge`

.github/workflows/add-issue-to-project.yml
Same as https://github.com/vacp2p/rfc/pull/372 but for nim-waku - thanks @D4nte for idea!
=> Automatically add new issues to project board

examples/v2/matterbridge/chat2bridge.nim, waku/common/wakubridge.nim, waku/v2/node/wakunode2.nim
Minor improvements to `bridge` and `chat2bridge`:
1. Sets the `relay` property `triggerSelf` to `false`, to avoid the bridge triggering a callback for a message it has just bridged to Waku v2. Also see https://github.com/status-im/nim-waku/issues/562.
2. Lower logs to more realistic levels
=> Minor bridge improvements

CHANGELOG.md, docs/api/v2/node.md, tests/v2/test_wakunode.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_store/waku_store.nim
This is to close https://github.com/status-im/nim-waku/issues/557
- The `resume` method is introduced to the `wakunode2` API to capture the node's offline period and fetch historical messages for that time.
- The `resume` proc is executed on `wakunode2` after each restart (given that the the store protocol is enabled in the full mode). 
- Also included some more logs  for the sake of debugging.
=> Add resume to waku node api

CHANGELOG.md, waku/v2/protocol/waku_swap/waku_swap.nim
references #573 
Bumped the Swap Protocol to `beta-1` as a result of the Swap Account Soft mode implementation. 
More on #524
=> Bump swap protocol to beta1

waku/v2/node/wakunode2.nim
This is just a temporary patch for the current issue in the master branch https://github.com/status-im/nim-waku/issues/577. 
The cause of the issue as explained by @jm-clius is: 
> The issue here is that `relay` is not yet mounted when `store` attempts to resume during [`wakunode2` startup procedures](https://github.com/status-im/nim-waku/blob/master/waku/v2/node/wakunode2.nim#L707) (and in order to dial you need to have `relay` mounted first). You could move the resume functionality till after you've mounted `relay`, but that would (currently) mean that you start relaying messages before you've properly resumed your history, which is not ideal. To delay starting `relay` until you've finished resuming history is also not an option as it stands, since this is tied in with starting the …
=> A quick fix to the master issue

examples/v2/chat2.nim, tests/all_tests_v2.nim, tests/v2/test_waku_keepalive.nim, waku/v2/node/peer_manager/peer_manager.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_keepalive/waku_keepalive.nim, waku/v2/protocol/waku_keepalive/waku_keepalive_types.nim, waku/v2/protocol/waku_relay.nim
This PR fixes #586
It does so by introducing a simple (and optional) ping-like protocol for `nim-waku` that periodically sends an empty message to connected peers. This a temporary workaround until `libp2p` ping protocol has been implemented, as set out in https://github.com/status-im/nim-libp2p/issues/567. Ping protocol is currently prioritised on the nim-libp2p side, but will likely not be finished before the [planned testnet](https://github.com/status-im/nim-waku/issues/555) for `nim-waku`. Waku v2 dogfooding has also commenced and some `keepalive` mechanism is necessary to maintain stable fleet connections and bridge `toy-chat` messages to Discord.
It is simpler in at least two ways:
- the keepalive messages do not carry any payload (as opposed to 32-byte ping messages), and
- it does …
=> Fix keepalive for connected peers

examples/v2/matterbridge/chat2bridge.nim, waku/common/wakubridge.nim, waku/v2/node/wakunode2.nim
Mounts new keepalive protocol on `bridge` and `chat2bridge`.
This has now been extensively tested locally and is ready for deployment to `prod`.
=> Mount keepalive on chat2bridge and bridge

CHANGELOG.md, examples/v2/chat2.nim, examples/v2/config_chat2.nim, waku/v2/node/config.nim, waku/v2/node/wakunode2.nim
closes #570  and https://github.com/status-im/nim-waku/issues/516
A `wakunode2` can now fully participate in a network with only `lightpush` and` filter` protocols mounted (i.e. with no `relay` capabilities). 
The toy chat (`chat2`) has been modified to showcase this ability. Just set a `filternode` and `lightpushnode` when running `chat2` and specify `relay=false`.
```
./build/chat2 --filternode=/ip4/8.210.222.231/tcp/30303/p2p/16Uiu2HAm4v86W3bmT1BiH6oSPzcsSr24iDQpSN5Qa992BCjjwgrD --lightpushnode=/ip4/8.210.222.231/tcp/30303/p2p/16Uiu2HAm4v86W3bmT1BiH6oSPzcsSr24iDQpSN5Qa992BCjjwgrD --relay=false
```
=> Filter and lightpush showcase

Makefile, tests/all_tests_v2.nim, tests/v2/test_waku_rln_relay.nim, tests/v2/test_wakunode.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_rln_relay/rln.nim, waku/v2/protocol/waku_rln_relay/waku_rln_relay_types.nim, waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
This PR isolates rln, disables it by default unless proper flags are set.
- rln-related codes and tests will not be compiled unless the `rln` flag is set (i.e., `nim c -d:rln`). 
- all of the rln-related build/dependency targets in the Make file are conditioned to the `RLN` variable being true. This variable affects two targets: namely, `rlnlib` that fetches and builds the rln dynamic library, and `installganache` that spins up ganache-cli.  When the `RLN` var also controls the rln compilation flag.
- Run `make <target> -RLN=true` to enable compilation of rln and to resolve its dependencies. 
It is also a  workaround for https://github.com/status-im/nim-waku/issues/546
=> Make rln optional (dependencies and compilation)

Dockerfile
Since 2fe53c3, the Jenkins [deployment job](https://ci.status.im/job/nim-waku/job/deploy-v2-test/) has been failing with error log:
```
21:10:26  Step 19/22 : COPY --from=nim-build /app/vendor/rln/target/debug/librln.so vendor/rln/target/debug/librln.so
21:10:26  COPY failed: stat app/vendor/rln/target/debug/librln.so: file does not exist
```
This PR fixes that by removing the librln file copy from the `Dockerfile`.
=> Fix: Remove rln file from Docker image

examples/v2/matterbridge/chat2bridge.nim, waku/common/wakubridge.nim, waku/v1/node/wakunode1.nim, waku/v2/node/wakunode2.nim
Fix required by changes in `metrics` submodule.
This is necessary where compiling with `-d:insecure` Nim flag, such as during deployment to fleet nodes.
For this reason the `test` deployment for Waku v1 has been [failing](https://ci.status.im/job/nim-waku/job/deploy-v1-test/162/)
=> Fix: metrics-server use after submodule update

CHANGELOG.md
Adds the release notes for [v0.4](https://github.com/status-im/nim-waku/issues/571)
This is currently in draft, while waiting for
- https://github.com/status-im/nim-waku/pull/594
- https://github.com/status-im/nim-waku/pull/593
to be merged.
It will be rebased on `master` once that is done.
@oskarth @staheri14 @EbubeUd could you review the draft release notes and LMK if there are any glaring omissions? Also let me know if there are any outstanding work/PRs that you would like to have merged before the release (other than those mentioned above).
=> Release v0.4

waku/v2/protocol/waku_swap/waku_swap.nim, waku/v2/protocol/waku_swap/waku_swap_types.nim
closes #626
`Issuer` has been added to the cheque object. The essence Of this is to enable the signatures to be verified by the recipient using the Issuer's public key.
=> Add Issuer to Cheque Object 

CHANGELOG.md, tests/v2/test_wakunode.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_relay.nim
This PR forms the implementation counterpart of the spec update in https://github.com/vacp2p/rfc/pull/410. Relates to https://github.com/vacp2p/rfc/issues/406.
It adds support for the `stable` version of the specified relay protocol, with protocol id `/vac/waku/relay/2.0.0`.
> **NOTE:** Once this is merged, the Waku v2 `test` fleet will be updated to support only the stable protocol id. The `prod` fleet, currently extensively used for dogfooding, and other Waku v2 clients should be updated with stable support in a coordinated manner. cc @D4nte @siphiuel @richard-ramos
=> Support for stable version of relay protocol

ci/Jenkinsfile.prs
Because of space issues described in https://github.com/status-im/nim-waku/pull/652#issuecomment-871205562.
The build folders take up 3.7 GB and 6.6 GB on linux and windows respectively. That's just too much to keep for multiple PR builds.
=> ci: cleanup workspaces after every build to save space

ci/Jenkinsfile.prs
This is a pretty cute regex-based test, but should work.
Without any changes that would trigger builds the CI run looks like this:
But with only the v1 path triggered it looks like this:
For the diff to work this refspec needs to be added to the fetch: `+refs/heads/master:refs/remotes/@{remote}/master`
=> ci: build and test only what changed

waku/v2/protocol/waku_store/waku_store.nim
It is an incremental PR towards the checklist of track1 of the refactor week https://hackmd.io/1imOGULZRsed2HpgmzGleA?view
All the `result`s are replaced with explicit `return`s.
In the follow-up PRs, will cover other protocols.
=> Waku store: explicit return instead of result

examples/v2/basic2.nim, examples/v2/chat2.nim, examples/v2/matterbridge/chat2bridge.nim, tests/v2/test_jsonrpc_waku.nim, tests/v2/test_message_store.nim, tests/v2/test_peer_manager.nim, tests/v2/test_peer_storage.nim, tests/v2/test_waku_bridge.nim, tests/v2/test_waku_keepalive.nim, tests/v2/test_waku_rln_relay.nim, tests/v2/test_waku_swap.nim, tests/v2/test_wakunode.nim, waku/common/wakubridge.nim, waku/v2/node/jsonrpc/filter_api.nim, waku/v2/node/peer_manager/peer_manager.nim, waku/v2/node/storage/message/message_store.nim, waku/v2/node/storage/message/waku_message_store.nim, waku/v2/node/storage/peer/peer_storage.nim, waku/v2/node/storage/peer/waku_peer_storage.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_filter/waku_filter.nim, waku/v2/protocol/waku_filter/waku_filter_types.nim, waku/v2/protocol/waku_lightpush/waku_lightpush.nim, waku/v2/protocol/waku_store/waku_store.nim, waku/v2/utils/peers.nim, wrappers/libwaku.nim
This PR focuses on refactoring `wakunode2.nim` according to the [Track 1 refactoring checklist](https://hackmd.io/1imOGULZRsed2HpgmzGleA?view)
As a result multiple referenced modules required similar refactoring and improvements, especially related to error handling.
The first step towards improved error handling is being explicit about what exceptions we raise, and to avoid generic types such as `Exception` or `CatchableError`. A next step is to determine which of these raised exceptions we should catch, though such changes fall outside the scope of this single PR.
- Some underlying modules, especially utils, still raise `Exception` where they should more properly return a `Result`. This will be addressed in follow-up PRs, once those modules undergo Track 1 refactoring.
- `import`s are …
=> Refactor wakunode2.nim

.github/workflows/add-action-project.yml
Now we have a project board for nim-waku, no longer cross-org, so should be simpler. Based on js-waku workflow.
=> Add GH project board automation

examples/v2/chat2.nim, examples/v2/matterbridge/chat2bridge.nim, tests/v2/test_migration_utils.nim, tests/v2/test_namespacing_utils.nim, tests/v2/test_peer_manager.nim, tests/v2/test_waku_bridge.nim, waku/common/utils/matterbridge_client.nim, waku/common/utils/nat.nim, waku/common/wakubridge.nim, waku/v2/node/jsonrpc/admin_api.nim, waku/v2/node/jsonrpc/filter_api.nim, waku/v2/node/jsonrpc/relay_api.nim, waku/v2/node/jsonrpc/store_api.nim, waku/v2/node/peer_manager/peer_manager.nim, waku/v2/node/storage/message/waku_message_store.nim, waku/v2/node/storage/migration/migration_types.nim, waku/v2/node/storage/migration/migration_utils.nim, waku/v2/node/storage/peer/peer_storage.nim, waku/v2/node/storage/peer/waku_peer_storage.nim, waku/v2/node/storage/sqlite.nim, waku/v2/node/waku_payload.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_store/waku_store.nim
This PR refactors `nim-waku` according to [Track 1 refactoring checklist](https://hackmd.io/1imOGULZRsed2HpgmzGleA?view)
It covers all modules not addressed in the existing/closed PRs: https://github.com/status-im/nim-waku/pull/664 #667.
Not everything on the Track 1 checklist is necessary for modules in `/test`-directory, so I've mostly focused on `import` cleanup.
Once all Track 1 refactoring PRs are merged, another pass of code maintenance (especially `import` cleanups) will be necessary to account for the effect of new `export`s and other improvements.
=> General refactoring: `nim-waku`

waku/v2/node/jsonrpc/jsonrpc_utils.nim, waku/v2/protocol/waku_store/waku_store.nim, waku/v2/protocol/waku_store/waku_store_types.nim
Addresses the following for the waku_store module. 
Partially addresses https://github.com/status-im/nim-waku/issues/639.
May need to clean up further if circular imports happen.
**Next:**
Working on the other modules imports/exports.
=> Cleaning imports of the waku store module

CHANGELOG.md, waku/v2/protocol/waku_store/waku_store.nim
This is to fix the mismatch between the implementation and the store specs regarding the order of fields of History Response protobuf. 
The store specs indicate that the first field of `HistoryResponse` is reserved for future use (as an identifier to match up queries with their corresponding requests). However, the nim-waku implementation does not comply with this specification.
=> Fixes the order of fields of History Response protobuf

waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_rln_relay/waku_rln_relay_types.nim, waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
Likely as a result of recent [refactoring efforts](https://hackmd.io/beMbu_fdRymYvaXDANukIw), compiling `wakunode2` with `rln` defined started failing.
This PR fixes the regression. We may want to add a CI test to avoid this from happening in future. @staheri14
=> Fix compilation with `rln` defined

CHANGELOG.md, tests/v2/test_waku_bridge.nim, waku/common/wakubridge.nim
This PR brings v1 <> v2 topic conversion in the `waku_bridge` in line with the [recommendations in RFC 23](https://rfc.vac.dev/spec/23/#bridging-waku-v1-and-waku-v2).
The bridge converts v1 topics (4-byte arrays) to v2 content topics using the scheme:
`/waku/1/<4bytes-waku-v1-topic>/rlp`, where `<4bytes-waku-v1-topic>` is the hex representation of the v1 topic.
This PR ensures that the `<4bytes-waku-v1-topic>` uses a `0x` prefix.
This scheme was previously supported, but not the default behaviour (in other words, `/waku/1/007f80ff/rlp` and `/waku/1/0x007f80ff/rlp` would both have been accepted as valid content topic representations of the same v1 topic, but `/waku/1/007f80ff/rlp` would have been the preferred default.)
cc @richard-ramos
=> Fix topic conversion in bridge

CHANGELOG.md
Adds the release notes for [v0.5](https://github.com/status-im/nim-waku/issues/672)
As far as I can tell there are no urgent outstanding refactoring work, PRs, features or fixes.
Please review the release notes and LMK if there are any glaring omissions or stuff that should be merged before the release.
@EbubeUd, I had "`swap` docs" as a separate item, but the [tutorial](https://github.com/status-im/nim-waku/commit/82bad26e0287234fe55f6a5318209634d4350e12) seems to have been removed?
cc @oskarth @staheri14 @EbubeUd
=> Release v0.5

CHANGELOG.md, tests/v2/test_peer_manager.nim, waku/v2/node/peer_manager/peer_manager.nim, waku/v2/node/wakunode2.nim
This PR is a patch for [release v0.5](https://github.com/status-im/nim-waku/releases/tag/v0.5)
It adds support for multiple protocol IDs when reconnecting to previous peers in the peer manager.
Although multiple protocol IDs is supported by the protocols as per https://github.com/status-im/nim-waku/pull/652, the peer manager would only reconnect to peers that previously matched the current mounted protocol ID.
The impact is that a fleet system, being upgraded to the stable version of the `relay` protocol, will not reconnect to previously connected peers if they were not previously registered with the stable protocol ID.
This is a blocker for installing the latest v0.5 release on the `prod` fleet, an outstanding task on https://github.com/status-im/nim-waku/issues/672
The issue affects …
=> Patch release v0.5.1 - fix multiple protocol IDs in persistent storage

CHANGELOG.md, waku/v2/protocol/waku_relay.nim
Relates to https://github.com/vacp2p/rfc/pull/451
It reverts a `nim-waku`-specific change to GossipSub parameters that were made earlier.
Specifically, the PRUNE backoff period was set to 30 seconds (50% of the default 1 minute). Although this theoretically shortens the restart-and-reconnect time for clients implementing peer persistence, this is not a good enough reason to deviate from the recommended default and may result in inconsistencies between client implementations.
This PR ensures the `nim-waku` implementation follows the recommendations set out in `29/WAKU2-CONFIG`.
cc @richard-ramos @D4nte to confirm that prune backoff is set to `1 min` in `go` and `js` implementations respectively
=> Revert PRUNE backoff period to default

.gitmodules, CHANGELOG.md, tests/all_tests_v2.nim, tests/v2/test_waku_dnsdisc.nim, waku/v2/node/config.nim, waku/v2/node/dnsdisc/waku_dnsdisc.nim, waku/v2/node/wakunode2.nim
Addresses #452.
This PR is a step towards integration of DNS discovery for Waku v2 nodes.
For now DNS discovery is disabled by default and the resolver returns an empty string.
Importantly, merging this integration will allow existing nodes (especially in the `prod` and `test` fleets) to create and announce signed ENR using their configured node keys. This is necessary to start building DNS node lists.
~~### Why is this PR in draft?~~ UPDATE: This PR is now ready for review.
- Some required submodule changes are still in an [`unstable` branch](https://github.com/status-im/nim-dnsdisc/pull/8)
- DNS resolver is awaiting [merging in libp2p](https://github.com/status-im/nim-libp2p/pull/580)
- Still want to add proper unit tests (local tests work well, but is not yet suitable for CI)
- Need to …
=> Waku v2 Node Discovery via DNS: Integration

tests/v2/test_waku_dnsdisc.nim, waku/v2/node/dnsdisc/waku_dnsdisc.nim, waku/v2/node/wakunode2.nim
Minor improvement:
There's no reason for a Waku DNS discovery client to cache its own ENR (yet), so I've removed it. It is still cached and logged by the `wakunode2`.
=> Remove unnecessary ENR caching

metrics/waku_fleet_dashboard.json
This PR closes #701
It adds multiple improvements to the Waku v2 fleet Grafana dashboard. The dashboard was previously not under `nim-waku` version control.
The live dashboard can be viewed [here](https://grafana.infra.status.im/d/qrp_ZCTGz/nim-waku-v2).
Improvements in this PR include:
- Added per-protocol metrics
- Fixed several outdated/obsolete Prometheus queries
- Added at-a-glance overview
- Added panels for several missing metrics
etc.
Some example screenshots:
_**At a glance**_ view added
Per-protocol metrics
=> Added waku v2 fleet dashboard

CHANGELOG.md, docs/contributors/waku-fleets.md
Adds a rudimentary guide to Waku v2 fleet monitoring and management.
It includes:
- an overview of the purpose and deployed services of each fleet (`wakuv2.test` and `wakuv2.prod`).
- an introduction to the most important fleet management and monitoring tools
- quick links to said tools
Still to do:
1. Add typical workflow tutorials, e.g. "Deploying a non-`master` branch to a fleet" or "Filtering for a specific log message on Kibana".
2. Add clarifying screen grabs of each service/workflow.
cc @michaelsbradleyjr @siphiuel @richard-ramos as the `wakuv2.prod` fleet is becoming especially important for the integration efforts.
=> Add Waku v2 fleet monitoring and management docs

waku/v1/node/start_network.nim, waku/v2/node/start_network2.nim
This PR relates to #717 
It fixes the network simulations for Waku v1 and Waku v2, and adds some minor tweaks to make it more useful for benchmarking.
Waku v2 simulation is now configurable from the CLI.
=> Fix network simulations

examples/v2/basic2.nim, examples/v2/chat2.nim, tests/v2/test_waku_rln_relay.nim, waku/v2/node/config.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_relay.nim, waku/v2/protocol/waku_rln_relay/waku_rln_relay_types.nim, waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
An increment towards https://github.com/status-im/nim-waku/issues/714
Summary of changes:
- Decouples the rlnrelay mounting process from the relay mount and start procedures, and makes rln the prerequisite of rlnrelay. This will simplify the future devs and debugging process. This update resulted in cleaner interfaces for both relay and rln and enhanced code readability.
- Adds a command-line option to get pubsub topic on which rln-relay will get mounted (instead of the prior version which was static).
=> Restructuring Rln-Relay mounting process

.gitmodules, CHANGELOG.md, examples/v2/chat2.nim, tests/v2/test_jsonrpc_waku.nim, tests/v2/test_peer_manager.nim, tests/v2/test_waku_bridge.nim, tests/v2/test_waku_filter.nim, tests/v2/test_waku_keepalive.nim, tests/v2/test_waku_lightpush.nim, tests/v2/test_waku_store.nim, tests/v2/test_waku_swap.nim, tests/v2/test_wakunode.nim, waku/v2/node/dnsdisc/waku_dnsdisc.nim, waku/v2/node/jsonrpc/admin_api.nim, waku/v2/node/peer_manager/peer_manager.nim, waku/v2/node/peer_manager/waku_peer_store.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_filter/waku_filter.nim, waku/v2/protocol/waku_filter/waku_filter_types.nim, waku/v2/protocol/waku_lightpush/waku_lightpush.nim, waku/v2/protocol/waku_lightpush/waku_lightpush_types.nim, waku/v2/protocol/waku_store/waku_store.nim, waku/v2/protocol/waku_store/waku_store_types.nim, waku/v2/protocol/waku_swap/waku_swap.nim, waku/v2/protocol/waku_swap/waku_swap_types.nim, waku/v2/utils/peers.nim
This PR updates submodules and is a prerequisite for the [upcoming release](https://github.com/status-im/nim-waku/issues/725)
The most significant submodule change is the removal of `PeerInfo` from `nim-libp2p` for anything but the _local_ peer information on the `switch`, constructed using the private key.
Since `nim-waku` (perhaps wrongly) constructed `PeerInfo` for every remote peer, I introduced a type `RemotePeerInfo` to differentiate these from the local information.
=> Update submodules: differentiate between local and remote `PeerInfo` 

tests/v2/test_message_store.nim, tests/v2/test_waku_discv5.nim, tests/v2/test_waku_store.nim, waku/v2/node/config.nim, waku/v2/node/storage/message/message_store.nim, waku/v2/node/storage/message/waku_message_store.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_store/waku_store.nim, waku/v2/protocol/waku_store/waku_store_types.nim
This PR closes #702. It is a prerequisite for the [next release](https://github.com/status-im/nim-waku/issues/725)
It adds the following fixes for `store`:
- limiting the number of messages that can be queued ("stored") in-memory
- priming the in-memory storage with a limited set returned from the persistent database
- making this maximum store capacity configurable
- lowering per-message log rates
Note that the store will be initialised from persistent storage by reading only the _most recent_ records from the database, up to the configured capacity. No records are deleted from persistent storage (yet).
This is a minimal fix for the current `store` capacity issues. We can still improve by:
- replacing the capacity-limited `StoreQueue` buffer with a circular/ring buffer. This way each …
=> Fix: store dimensioning issues

CHANGELOG.md
This PR relates to https://github.com/status-im/nim-waku/issues/725
It adds the release notes for `nim-waku` release `v0.6`.
Please go through the changelog and LMK if there are any missing items. @staheri14 there were a couple of commits related to RLN, but I'm not sure if there's anything concrete to add to the changelog?
cc @oskarth @rshiv
=> Release v0.6

waku/v2/README.md, waku/v2/node/config.nim
This PR appends to the README section of waku v2 on how to create a self signed key and enable websockets transport.
Closes issue #762
=> Adds readme for websockets

tests/v2/test_wakunode.nim, waku/v2/node/wakunode2.nim
This PR closes #783 
It adds a workaround for https://github.com/status-im/nim-libp2p/issues/429 where the bound addresses (instead of externally significant addresses) are announced by a `nim-libp2p` switch, specifically as part of the `identify` procedure.
This allows other clients to use the info received during `identify` to update local addresses, where necessary. One example where this is necessary is for status-go integration of Waku v2, where a table with remote peer info is populated after DNS discovery using `identify` (https://github.com/status-im/status-go/pull/2438).
cc @richard-ramos
=> Update announced addrs in switch

tests/all_tests_v2.nim, tests/v2/test_enr_utils.nim, tests/v2/test_wakunode.nim, waku/v2/node/discv5/waku_discv5.nim, waku/v2/node/dnsdisc/waku_dnsdisc.nim, waku/v2/node/wakunode2.nim, waku/v2/utils/wakuenr.nim, waku/v2/utils/wakuswitch.nim
This PR closes #755
As a side-effect it fixes https://github.com/status-im/nim-waku/issues/794
It introduces support for RFC31 compliant ENR creation for Waku v2 nodes.
Changes include:
- support and tests for `multiaddrs` field creation
- support and tests for `multiaddrs` field decoding
- support and tests for `waku2` flag field
- refactoring of address management in wakunode2 to improve readability
- bugfix for `listenStr` when there are no external addresses
@rshiv in order to populate the ENR `multiaddrs`, I've had to refactor the way announcedAddresses gets populated.
I think we can probably simplify things much more still, but for now I've done the minimal required for this PR.
See if the changes make sense to you.
Changes include:
- making sure we announce host addresses if no …
=> Add support for RFC31 ENR

waku/v2/node/storage/migration/migrations_scripts/message/00002_addSenderTimeStamp.up.sql, waku/v2/node/storage/sqlite.nim, waku/v2/node/waku_setup.nim
This PR addresses https://github.com/status-im/nim-waku/issues/791
It ensures that a DB migration fails if it finds no scripts to run for a particular migration.
In addition:
- some extra/more detailed logging, to assist with debugging
- stricter column name requirement in `Message` migration script
=> Fix empty scripts condition. Logging.

Dockerfile
PR addresses https://github.com/status-im/nim-waku/issues/791
It fixes the underlying issue causing DB migration failure, by adding the migration scripts to the docker image.
=> Fix migration failure

waku/v2/README.md
Nim web-socket cannot handle encryption in key for SSL verification, hence Readme should add nodes flag
Closes issue #793
=> Solves issue 793

CHANGELOG.md, tests/v2/test_waku_filter.nim, waku/v2/node/config.nim, waku/v2/node/peer_manager/peer_manager.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_filter/waku_filter.nim, waku/v2/protocol/waku_filter/waku_filter_types.nim
This PR closes #781
The PR deletes the peer info if after timeout period the peer is not available. We maintain a map of peerid and first unavailable time to determine its departure.
This PR achieves
- Store the map of the failed peers and its first failure epoch
- Receives the config for timeout from user in float, by default 24 hours.
- Removal of subscriber if failure continues.
- Test to check the above features.
=> Handles stale clients in FILTER protocol

CHANGELOG.md, waku/v2/protocol/waku_filter/waku_filter.nim, waku/v2/protocol/waku_lightpush/waku_lightpush.nim, waku/v2/protocol/waku_store/waku_store.nim, waku/v2/protocol/waku_swap/waku_swap.nim
Adds a counter for protocol messages (e.g. counting the number of store/filter queries received).
We currently have no visibility in how often these protocols get invoked, especially in fleet nodes. There are still some unexplained CPU spikes in the `prod` fleet, for example, and being able to see if this correlates to e.g. a store query will go a long way towards prioritising improvements.
=> Added protocol message counters

CHANGELOG.md, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_filter/waku_filter.nim, waku/v2/protocol/waku_filter/waku_filter_types.nim, waku/v2/protocol/waku_lightpush/waku_lightpush.nim, waku/v2/protocol/waku_lightpush/waku_lightpush_types.nim, waku/v2/protocol/waku_message.nim, waku/v2/protocol/waku_store/waku_store.nim, waku/v2/protocol/waku_store/waku_store_types.nim, waku/v2/protocol/waku_swap/waku_swap.nim, waku/v2/protocol/waku_swap/waku_swap_types.nim
This PR closes #787
I've decided against the initial proposed solution of varying page size based on some unrelated maximum response size.
Rather, I've explicitly set the `MaxWakuMessageSize` (corresponds to the recommended PubSub default) and derived the input stream limit by multiplying with `MaxPageSize`. A safety factor of 64kB is built in to account for protocol overhead. This seems much simpler than what I originally proposed. LMK what you think @staheri14?
I've used the same approach to find a sensible read limit for other protocols. All protocols, other than `Swap` use an RPC message for request/response, so I've adjusted the limit to whichever of the Request or Response are likely the largest, together with a significant safety factor.
=> Fix incorrect store read buffer limit

CHANGELOG.md, tests/v2/test_jsonrpc_waku.nim, tests/v2/test_waku_store.nim, waku/v2/protocol/waku_store/waku_store.nim
Small but significant change.
It ensures that, even with no paging info specified in the store query, the store will never return a response that exceeds the specified `MaxPageSize`. In other words, _all HistoryResponses will now be auto-paginated_.
This is necessary, because:
- https://github.com/status-im/nim-waku/pull/800 will not work properly if we don't limit _all_ response sizes
- at least some of the performance issues on the fleet is caused by un-paginated query responses attempting to stream the entire history in a single HistoryResponse (https://github.com/status-im/nim-waku/issues/736)
More store changes coming up: https://github.com/status-im/nim-waku/issues/805
@staheri14, keen to know what you think and if there are any gotchas that I've missed. LMK if you think this should …
=> Ensure store response never exceeds `MaxPageSize`

CHANGELOG.md, examples/v2/chat2.nim, tests/v2/test_jsonrpc_waku.nim, tests/v2/test_peer_manager.nim, tests/v2/test_waku_bridge.nim, tests/v2/test_waku_dnsdisc.nim, tests/v2/test_waku_keepalive.nim, tests/v2/test_waku_swap.nim, tests/v2/test_wakunode.nim, tests/v2/utils.nim, waku/v2/node/wakunode2.nim
Closes #744
Removes the local `peerInfo` instance/node property and replaces all uses of this copy with the underlying libp2p `switch.peerInfo`.
A local copy on the node is a bad idea, as the underlying addresses may be manipulated by the `switch` under certain circumstances. The `wakunode2` is not the authority on local peer information.
=> Remove node peerInfo copy

CHANGELOG.md, waku/v2/protocol/waku_store/waku_store.nim
This closes https://github.com/status-im/nim-waku/issues/805 (albeit using a slightly different approach than envisioned in that issue).
It is a prerequisite for the release (https://github.com/status-im/nim-waku/issues/808) and likely addresses https://github.com/status-im/nim-waku/issues/736 as well, though longer term testing will be required to confirm.
It significantly decreases store query times, especially for large message stores as in our fleets.
Recently fleet performance has deteriorated resulting in unusably slow response times.
In local tests query response time improved from >10min to under 100ms.
- tries to limit calls to more computationally expensive procs (such as `findIndex`)
- extracts all query criteria before filtering, and then filters only once as a single …
=> Improved `store` query performance

CHANGELOG.md, waku/v2/protocol/waku_store/waku_store.nim
This PR provides a (very) minimal solution for https://github.com/status-im/nim-waku/issues/813
It does two things:
1. ensures that the receiver timestamp in `WakuMessage` indices are consistently millisecond resolution
2. uses stored `receiverTimestamp` when loading from persistent storage rather than system time (this keeps the index consistent after restarts)
- Timestamps should be `int64` epoch milliseconds rather than `float64`, which is bound to lead to precision errors. Since this requires a data scheme change, protocol change and an update in other Waku v2 clients, I'll postpone this change until after the release.
- I would still propose that the index itself be a simple, time-sortable hash over receiver timestamp and message content. If prepended by the epoch received timestamp, …
=> Ensure consistent resolution of receiver timestamp

ci/Jenkinsfile.prs
Should fix errors like:
```
clang: error: the clang compiler does not support '-march=native'
```
Caused by hitting the Apple M1 `arm64` host.
=> ci: add architecture specification to agent label

CHANGELOG.md
This PR relates to #808
It adds the release notes for nim-waku release v0.7. Please go over the list and LMK if there's anything that I've missed. As with the previous release, I've added a short description of the main benefits users can expect from the release.
=> Release v0.7

CHANGELOG.md, docs/api/v2/node.md, tests/v2/test_waku_store.nim, waku/v2/protocol/waku_store/waku_store.nim
This PR addresses https://github.com/status-im/nim-waku/issues/809
- updates `resume` and `queryLoop` implementing the logic described in https://github.com/status-im/nim-waku/issues/809
- updates the existing resume test and adds a test for resuming from an empty `peerList`
- updates the [changelog](https://github.com/status-im/nim-waku/blob/master/CHANGELOG.md)
- updates the waku v2 API [description](https://github.com/status-im/nim-waku/blob/master/docs/api/v2/node.md)
The code for awaiting the futures in `resume` is clunky. I could not find a version of `allFutures` that returns a `Future[seq[T]]`.
What I ended up using is `allFinished*[T](futs: varargs[Future[T]]): Future[seq[Future[T]]]` which requires to go through the already finshed futures again.
At least, this allows the …
=> result aggregation in resume API

waku/v2/node/wakunode2.nim
This PR resolves a naming collision for the following identifiers: `ValidationResult` and `Address`.  They were common in two separate modules and needed to be disambiguated. The collision does not occur  except when the RLN flag is set to true.
=> Resolves naming conflict

tests/v2/test_waku_store.nim
This PR closes switches after use in test_waku_store.
[Stopping switches](https://github.com/status-im/nim-libp2p/blob/58f383e661521314df314e7096c24db5a7490372/libp2p/switch.nim#L209) frees the transport resources, which means closing TCP ports in waku_store_test.
(A TCP-based switch holds a set of `StreamServer`s in its `TcpTransport` object, which when [stopped](https://github.com/status-im/nim-chronos/blob/519ca463dfd060dfec64a221b8e39e06a70860d3/chronos/transports/stream.nim#L1753),
waits to be [closed](https://github.com/status-im/nim-chronos/blob/519ca463dfd060dfec64a221b8e39e06a70860d3/chronos/transports/stream.nim#L1806), which then [closes](https://github.com/status-im/nim-chronos/blob/519ca463dfd060dfec64a221b8e39e06a70860d3/chronos/transports/stream.nim#L1804) the socket.)
=> stop sockets after use in test_waku_store.nim

tests/v2/test_jsonrpc_waku.nim, waku/v2/node/wakunode2.nim
Minor PR towards #828 
It adds:
1. A dimension to the message counter to keep track of the number of `contentTopic`s in the network. This should enable us to build Prometheus queries to view i.a. the number of applications using the network.
2. A metric to track the number and type of connections initiated by the nwaku node. This will allow us to monitor number of connections initiated due to static configuration, dns discovery, discv5, API calls, and more.
3. Some error handling for failed connections initiated by this node.
For (2) it was necessary to clean up the `connect` and `dial` API in `wakunode2` (somewhat).
There is some parallel work ongoing to update the bundled Grafana dashboard accordingly.
=> Improve node metrics

metrics/waku_fleet_dashboard.json
This PR contains many tweaks, additions and updates to the default "fleet" metrics dashboard for `nwaku`.
It forms a part of https://github.com/status-im/nim-waku/issues/828, and most changes are aimed at making the dashboard more operator-focused. Some changes are aimed at improved memory monitoring.
1. Message counter is now displayed as a rate per minute, rather than just an ever-increasing total:
2. Panels showing the total number of content topics and the message rate for the top content topics. _Note this metric is not available on `prod` yet._
3. Detailed memory and heap stats
And many more! Live version of the dashboard can be found [here](https://grafana.infra.status.im/d/qrp_ZCTGz/nim-waku-v2?orgId=1&var-host=.*&var-fleet=wakuv2.test&var-fleet=wakuv2.prod&var-dc=All)
=> Update default fleet metrics dashboard

waku/v2/README.md
See the investigation done in https://github.com/status-im/js-waku/issues/50
An operator needs to use a proper domain certificate or the user's browser will silently reject any connection to it.
=> Update websocket documentation to use domain certificates

CHANGELOG.md, tests/v2/test_wakunode.nim, waku/v2/node/config.nim, waku/v2/node/wakunode2.nim, waku/v2/utils/peers.nim, waku/v2/utils/wakuswitch.nim
This PR closes #521
It adds support for parsing and resolving dns-type `multiaddrs`, i.e. protocol schemes [`dns`, `dns4`, `dns6`, `dnsaddr`](https://github.com/multiformats/multiaddr/blob/b746a7d014e825221cc3aea6e57a92d78419990f/protocols.csv#L8-L11).
By default a `nwaku` node would attempt resolution against the Cloudflare name servers `1.1.1.1` and `1.0.0.1`, but this is configurable via the `dns-addrs-name-server` config option. DNS resolution can also be disabled completely by setting `dns-addrs` to `false`.
The next step would be to add a domain name config for a `nwaku` node which it can advertise. This is necessary, for example, to generate and sign a discoverable ENR containing a dns-type `multiaddr`.
cc @D4nte @dao
=> Support for dns `multiaddrs`

tests/all_tests_v2.nim, tests/v2/test_pagination_utils.nim, tests/v2/test_waku_pagination.nim, tests/v2/test_waku_store.nim, tests/v2/test_waku_store_queue.nim, tests/v2/test_wakunode.nim, waku/v2/protocol/waku_store/waku_store.nim, waku/v2/protocol/waku_store/waku_store_types.nim, waku/v2/utils/pagination.nim
This PR addresses https://github.com/status-im/nim-waku/issues/838, a critical blocker to continue with https://github.com/status-im/nim-waku/issues/828.
It aims to fix memory issues reported and investigated in https://github.com/status-im/nim-waku/issues/841
This PR changes the underlying `store` data structure to an indexed `sorted_set`. Previously the `store` would keep historical messages in an unsorted, unindexed sequence. This necessitated up to three copies of the entire history to service a Historical Query: one to apply any filter criteria, another to sort the response and a third to apply pagination. In the new implementation messages are sorted on input. This allows the `store` to _read only_ from history when populating a response to a Historical Query.
Pagination is now done …
=> Store performance improvements

CHANGELOG.md, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_store/waku_store.nim
In light of the store protocol update provided by https://github.com/status-im/nim-waku/pull/842 (timestamps now have nanosecond resolution), the `WakuStoreCodec` string in `waku_store` needs to be updated  to the most recent version `-beta4` in order to be aligned to the corresponding RFC https://rfc.vac.dev/spec/13/.
=> Update WakuStoreCodec string to beta4

tests/v2/test_wakunode.nim, waku/v2/node/config.nim, waku/v2/node/wakunode2.nim
This PR introduces the ability to configure a `nwaku` node with an (ipv4) domain name.
This allows for the node's publically announced `multiaddrs` to use the `/dns4/` scheme. In addition, nodes with domain name and secure websocket configured, will generate a discoverable ENR containing the `wss` `multiaddr` with `/dns4/` domain name. This is necessary to verify domain certificates when connecting to this node over secure websocket. 
Related issues: https://github.com/status-im/nim-waku/pull/848 https://github.com/status-im/nim-waku/issues/845
=> Domain name config for `nwaku` node

CHANGELOG.md, waku/v2/README.md
Adds documentation:
- explaining how to configure a `dns4` domain name for a `nwaku` node (see https://github.com/status-im/nim-waku/pull/852)
- linking the DNS discovery instructions in the separate tutorial to the main `README`
- listing the current available URLs for connecting to one of the existing fleets using DNS discovery
=> Add docs on configuring domain and DNS discovery

examples/v2/chat2.nim, examples/v2/config_chat2.nim
Closes https://github.com/status-im/nim-waku/issues/850
Removes the remaining reference to _fleets.status.im_ from the `nim-waku` codebase. This was used by `chat2` to select random nodes to connect to from a configured fleet. In the new implementation, `chat2` uses DNS discovery to discover and connect to fleet nodes (or any list of nodes published to a user-configurable `--dns-discovery-url`).
From a user's perspective the behaviour is the same as before: by default a `chat2` client will attempt to connect to `prod`, although this is configurable using the `--fleet` option and can be disabled using `--fleet:none`.
=> Remove ref to fleets.status.im

waku/v2/protocol/waku_message.nim
This is a fix to maintain retro-compatibility with `timestamp` protobuffer fields.
Timestamps now have `Timestamp` type (currently an alias for `int64`) and nanoseconds resolution. Their new protobuffer index is `10`.
Previous versions had timestamps as `float` with subseconds contained in the fractional part and protobuffer index `4`.
This PR is related to https://github.com/vacp2p/rfc/pull/491, https://github.com/status-im/nim-waku/pull/842 and https://github.com/vacp2p/rfc/pull/483.
=> Moved PB Timestamp index to 10

examples/v2/chat2.nim
This PR fixes the message echoed when connecting to a fleet.
It used to say "No static peers configured [...]".
However, the corresponding branch will be executed regardless if static peers are configured or not.
This PR also adds an echo printing a message when connecting to static nodes, because a similiar messages is printed when connecting to nodes learned via other methods.
=> fix: message when connecting to fleet nodes

tests/v2/test_pagination_utils.nim, tests/v2/test_waku_pagination.nim, waku/v2/node/storage/message/waku_message_store.nim, waku/v2/node/storage/migration/migration_types.nim, waku/v2/node/storage/migration/migrations_scripts/message/00003_convertTimestampsToInt64.up.sql, waku/v2/node/storage/migration/migrations_scripts/message/00004_extendPrimaryKey.up.sql, waku/v2/protocol/waku_store/waku_store.nim, waku/v2/utils/pagination.nim
This PR updates the store data model (both in-memory and in the SQLite schema).
It is the last necessary step to close https://github.com/status-im/nim-waku/issues/838 and fix https://github.com/status-im/nim-waku/issues/841.
This required a minor change in the RFC, tracked in https://github.com/vacp2p/rfc/pull/492.
The data model defines an `index` for each message that defines:
This is necessary e.g. for deduplication, finding a message based on a `cursor` (an `index` provided in `HistoryQuery`), defining a suitable PRIMARY KEY in the database, etc:
A message is uniquely identified by the combination of `senderTimestamp`, `digest` (over both the message `payload` and `contentTopic`) and `pubsubTopic`. A `receiverTimestamp` is not part of the unique identifier of a message, but can be …
=> Store data model updates and fixes

docs/tutorial/bridge.md, waku/common/config_bridge.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_relay.nim
Adds a guide on how to configure a `wakubridge`.
A Waku v1 <> v2 bridge deployment is required for the effort to launch Status with Waku v2 integrated.
Other minor changes:
- a `wakubridge` should not have `store` enabled by default
- with bridging we'll see considerably higher message rates on the fleets. I think it's best if we lower the `debug` level logs for each published message to `trace`.
=> Add bridge docs and minor improvements

CHANGELOG.md, tests/v2/test_waku_bridge.nim, waku/common/config_bridge.nim, waku/common/wakubridge.nim
This PR introduces two minor improvements to the Waku v1 <> v2 bridge, that will improve its usability during the Status Waku v2 integration effort:
1. Bridge now supports resolving DNS addresses (useful for easy deployment)
2. Bridge now validates a Waku v2 message content topic before attempting to bridge the message to v1 (only messages with content topic pattern `/waku/1/*/*` are bridgeable).
(I also snuck in a single line re `timestamp` field number in the CHANGELOG that appears in the release notes for nim-waku `v0.8` but not in the CHANGELOG.)
=> Bridge improvements

.gitmodules
I got write access to [status-nim/eth](https://github.com/status-im/nim-eth)  and pushed a feature branch supporting `33/WAKU-DISCV5`. 
This PR updates the nim-eth submodule switching the branch from my fork to the [status-im/nim-eth feature branch](https://github.com/status-im/nim-eth).
It also bumps to the lastest version of nim-eth.
=> switch vendor/nim-eth branch

waku/v2/node/wakunode2.nim
Fixes https://github.com/status-im/nim-waku/issues/890
It removes `contentTopic` as a label dimension for the `waku_node_messages_total` metric. Since the introduction of a Waku v1 <> v2 bridge causes an explosion in the number of content topics, the cardinality becomes unsustainably high in Prometheus.
An alternative would be to extract only the `application` and `version` parts of the `contentTopic` (which would bundle all bridged messages under `/waku/1`). However, not all applications will have their content topics formatted in this way, decreasing the value of the metric in any case, and there will still not be any guaranteed upper limit in cardinality.
A better solution to measure the number of applications in the network, would therefore be to run a special node as part of the …
=> Remove content topic dimension from message metrics

.github/workflows/test.yml
Disable Windows CI for now, as it is currently failing on both Jenkins and as a Github workflow for reasons unrelated to the code.
This PR disables Windows CI in Github. It's also been manually [disabled in Jenkins](https://ci.status.im/job/nim-waku/job/prs/job/windows/configure).
This issue tracks re-enabling Windows CI: https://github.com/status-im/nim-waku/issues/896
> Note: let's use [semantic commit messages](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716) from now on.
=> ci(windows): disable windows CI

waku/v2/README.md
This PR addresses #866.
I also added a short explanation on how to run wakunod2 on the smaller DO droplet.
Not sure if this is too specific for the main README, but might help folks running into the same issue.
=> add RAM requirement to README

waku/v2/protocol/waku_message.nim
This PR is to update the type of the proof field of the waku message to rate limit proof. It was previously disabled under the rln  compiler flag due to which spam-protected messages would not be routed by relay nodes with no support for rln. This will aid the rln live testnet where the test fleets can merely act as a router for the spam-protected messages needless to compile the rln rust lib and other utility functions.
=> Updates the type of the `proof` field of wakumessage to `RateLimitProof`

tests/v2/test_waku_discv5.nim, waku/v2/node/discv5/waku_discv5.nim, waku/v2/node/wakunode2.nim, waku/v2/utils/peers.nim
This PR addresses #880.
The current draft implementation passed a test on an experimental fleet.
This fleet server can be used for testing:
`enrtree://AKRUVB7WRORHGL5IIHKHEXGALD5IWWAL7UIVOUZ2FKE4ORV5WOX76@waku.337.ovh`
(I will keep this running during the testing phase; might be down sometimes during update phases.)
The following explains my implementation choices.
(No strong opinion on these, and happy to change if desired :))
Bootstrap nodes are passed to the discv5 object during the `initialize node` phase while they are dialed by Waku relay in the `start node` phase.
To avoid retrieving bootstrap nodes twice, having a separate phase for retrieving them before `initialize node` seemed like a solution with not too much restructuring.
Also, the new `retrieve dynamic bootstrap nodes` …
=> discv5 dns bootstrap

tests/v2/test_message_store.nim, waku/v2/utils/time.nim
Fixes an issue in `time` utils, where an integer overflow could happen before converting that integer to an `int64` timestamp.
This issue causes the `wakubridge` to generate invalid Waku v2 timestamps for messages bridged from Waku v1.
cc @richard-ramos 
The `get...[T](timeInSeconds: T): Timestamp` functions should convert the integer input arguments to `int64` before multiplying, otherwise the multiplication output would still have the same width as the width of the argument. For example, if `getNanosecondTimestamp()` is called with an `int32` input of the current epoch time in seconds, the multiplication with `1000_000_000` would yield an invalid, overflowed `int32` result.
=> Fix: timestamp type could overflow before conversion

examples/v2/chat2.nim
Two improvements for `chat2`:
1. Do not print messages that are not on the `chat2` content topic (especially important once message rates for other applications increase).
2. Set the message `timestamp` for `store` consistency.
=> Chat2 improvements: remove noise, set sender timestamp

waku/v2/node/config.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
This PR:
- Introduces more trace level log which may be helpful for future debugging especially on fleets. 
- Converts some of the debug level logs to trace level mostly for the performance's sake, this change is important especially when the rln-relay protocol gets enabled on the fleets. 
- Changes the default rln-relay content topic.
=> Increase rln-relay logging

Makefile, docs/tutorial/rln-chat2-live-testnet.md
During the rln test, I got a compile error due to an outdated crate that did not get recompiled.
This PR 
* adds a trouble shoot section to the docu
* adds a `cleanrln` rule to the Makefile
* adds cleaning the rln crate to the `clean` rule
Rationale for separate `cleanrln` rule:  avoid having to rebuild the whole project.
Later, this could also be added to the `update` rule.
=> chore(rln): add cleanrln make rule + docu

Dockerfile
This change is needed to enable rln-relay protocol (which relies on rln lib) on waku test fleets. The rln lib is dynamically linked hence needs to be loaded separately. 
The `Copy` operation for the rln lib is made optional (by appending the `*` at the end of the source file) to account for the cases that the rln lib does not exist e.g., in waku prod fleets which are built with the rln compiler flag turned off hence the rln lib `librln.so` never gets produced.
=> Copy rln lib into wakunode2 docker container

Dockerfile
Reverts status-im/nim-waku#909 due to the error it causes on the test fleets https://ci.status.im/job/nim-waku/job/deploy-v2-test/321/execution/node/19/log/
The optional `COPY` that I added in the previous PR using `*` wildcard https://github.com/status-im/nim-waku/pull/909 works fine on my machine with Docker version 19.03.13, though it fails when building the image on the test fleets https://ci.status.im/job/nim-waku/job/deploy-v2-test/321/execution/node/19/log/
> Step 20/25 : COPY --from=nim-build /app*/vendor/rln/target/debug/librln.so vendor/rln/target/debug/librln.so
> COPY failed: no source files were specified
@jakubgs I suspect the error is due to the docker version, which docker version we are using?
=> Revert "Copy rln lib into wakunode2 docker container"

waku/v2/node/wakunode2.nim
This PR addresses #906.
This is a minimal fix printing the actually discoverable ENR managed by the discv5 subsystem.
Wakunode holds another ENR that got printed before.
I will look into consolidating these two ENR instances into one in the future (not critial for now).
This PR should be a minimal fix solving this `citical` issue.
(successfully tested setting up a local fleet using the printed ENR)
=> fix(discv5): info print ENR containing discv5 udp port

README.md
Adds a section to the `README.md` on bug reporting.
I've also added a [`critical`](https://github.com/status-im/nim-waku/labels/critical) label, which can be used on high-priority issues to assist with triaging. We could also consider adding a special column to [the project board](https://github.com/status-im/nim-waku/projects/1) to increase visibility of new critical issues/bug reports.
=> docs: added bug reporting section to main readme

config.nims
Apple's clang (v13) doesn't support "-march=native" on M1.
Checking `clang --print-supported-cpus` shows that it 
_does_ support `apple-m1`.
=> Fixed building on Apple clang and M1

CHANGELOG.md, tests/v2/test_message_store.nim, waku/v2/node/storage/message/message_store.nim, waku/v2/node/storage/message/waku_message_store.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_store/waku_store.nim, waku/v2/protocol/waku_store/waku_store_types.nim
This PR provides a simple solution to https://github.com/status-im/infra-status/issues/5 and https://github.com/status-im/nim-waku/issues/767
Currently, the DB grows boundless, and, while only a subset of messages is loaded into the in-memory store, an `ORDER-BY` operation is run on the whole DB.
This might lead to very long loading times https://github.com/status-im/infra-status/issues/5 
This PR adds `numMessages` (a message counter) and `maxMessages` (max number of messages to be held in the sqlite DB) to the `WakuMessageStore`.
When `put`ting a message into the store, it checks if `maxMessages` is reached and if so, deletes a configurable percentage of oldest messages.
This PR introduces two new config options:
* `--db-capacity` the maximum number of messages stored in the DB
* …
=> fix(store): capacity limit for persistent message store

tests/all_tests_v2.nim, tests/v2/test_peer_exchange.nim, waku/v2/node/config.nim, waku/v2/node/wakunode2.nim, waku/v2/utils/peers.nim, waku/v2/utils/wakuswitch.nim
Closes https://github.com/status-im/nim-waku/issues/902. Implements GossipSub peer exchange in the `relay` protocol for `nwaku` nodes.
GossipSub peer exchange has recently been introduced in nim-libp2p in https://github.com/status-im/nim-libp2p/pull/647
GossipSub PX is a prerequisite for [the next release](https://github.com/status-im/nim-waku/issues/903)
Peer exchange is made configurable but enabled by default, as it could greatly contribute to mesh stability.
=> feat(relay): add support for gossipsub peer exchange

docs/tutorial/jsonrpc-api.md
Fixes broken links in the JSON-RPC API tutorial.
Also used this opportunity to introduce semantic line breaks and update the example.
=> docs(rpc-api-tutorial): fix broken links in JSON-RPC API tutorial

Makefile, waku/v2/node/jsonrpc/debug_api.nim
This PR addresses #859.
There are other ways of getting access to the git version number from within Nim.
This requires minimal changes and no further build deps.
The current format is simple, just returing a single string of the form `<tag>-<commit-hash>` if there is a tag for the respective commit hash. (See output of `git describe --abbrev=6 --always --tags`).
If desired, I could split it into the format that is given as an example in the issue.
Either by
* calling `git describe` twice during `make`
* splitting the string in Nim
Alternatively, we could also print the most recent tag on any branch (this would require calling `git describe` twice).
Right now, this might be confusing, because we only have tags up to v0.6.
I chose to introduce a new call `get_waku_v2_debug_v1_version`, …
=> feat(jsonrpc): add call returning git version

.github/workflows/release-assets.yml
Fixes release assets not working.
The release asset were built using a Github Action, which sets the `CI` environment variable to `true`. This in turn enables `rln`, which causes the built release asset to require the dynamic rln library when running.
The fix sets `CI` to false.
=> fix: release assets do not work

waku/v2/node/storage/message/waku_message_store.nim
This PR addresses the vacuum part of #914
This significantly reduces the size of DB files, especially for DBs from before delete was introduced to the store.
=> feat(store): vacuum after delete

waku/v2/node/storage/message/waku_message_store.nim
This PR prints an info message after a delete operation containing related info that is not costly to retrieve.
The number of messages left is still only printed in a debug message, because it takes a additional query to retrieve.
=> feat(store): info message after delete

CHANGELOG.md
Addresses https://github.com/status-im/nim-waku/issues/903. 
Adds the release notes for nim-waku `v0.9.`
I know there are still a couple of outstanding PRs close to merging, so I'll rebase this branch on `master` once those PRs are merged.
=> docs(changelog): add release notes for v0.9

Dockerfile
Closes https://github.com/status-im/nim-waku/issues/921
Summary of changes:
- This PR introduces a docker file argument `RLN` (which mirrors the makefile `RLN`  argument) to control the waku-rln-relay compilation from the docker build command.
- The `RLN` argument defaults to `true` to make the waku-rln-relay protocol available in the resulting waku docker images/containers.
=> feat(docker):  introduce the `RLN` Dockerfile argument to control the compilation of waku-rln-relay protocol

tests/all_tests_v2.nim, tests/v2/test_waku_noise.nim, waku/v2/protocol/waku_noise/noise.nim
This PR adds support to the ChaChaPoly symmetric cipher for encrypting Waku payload message contents. 
Specifically, it adds:
- Encryption/Decryption primitives
- Some unit tests
It partially addresses https://github.com/status-im/nim-waku/issues/881.
=> feat(noise): add support to ChaChaPoly encryption

tests/v2/test_waku_store_queue.nim, waku/v2/protocol/waku_store/waku_store.nim, waku/v2/protocol/waku_store/waku_store_types.nim
Improves store integrity by adding two validity checks before storing a message:
1. The message sender timestamp may not be more than 20 seconds into the future (i.e. ahead of the receiver timestamp). This is to prevent messages from "jumping" the store queue by simply setting the `timestamp` to the future.
2. Once the store queue is at capacity, a message will not be store if its index is older than the oldest index currently in the queue.
=> Store timestamp validity checks

tests/all_tests_v2.nim, tests/v2/test_waku_noise.nim, waku/v2/node/waku_payload.nim, waku/v2/protocol/waku_noise/noise.nim
This PR introduces data structures and procedures to process Waku Message Payload with version 2. 
Specifically, it adds:
- Encode/decode payload functions
- Some unit tests
Implementation of Waku Payload with version 2 partially follows [35/WAKU2-NOISE](https://rfc.vac.dev/spec/35/#specification) (RFC will be updated accordingly once this PR is merged).
This PR extends https://github.com/status-im/nim-waku/pull/931 (which in turn extends https://github.com/status-im/nim-waku/pull/930) and partially addresses https://github.com/status-im/nim-waku/issues/881.
=> feat(noise): add support to Waku Payload V2

ci/Jenkinsfile.prs, waku/v2/protocol/waku_noise/noise.nim
Since version `2.343`, Jenkins implements a [security fix](https://issues.jenkins.io/browse/JENKINS-67173) which breaks the [Job Cacher](https://plugins.jenkins.io/jobcacher/) plugin used to cache dependencies like the Nim compiler.
In the meantime that the Job Cacher plugins is updated to address this fix, or other alternatives are found, this PR disables implemented Jenkins caching in `nim-waku`.
Related issues are https://github.com/status-im/status-desktop/pull/5560 and https://github.com/status-im/nimbus-eth2/pull/3594
=> fix(Jenkins): remove caching

waku/v2/node/storage/message/waku_message_store.nim
This PR addresses the missing part of #914 adding an index on `receiverTimestamp`.
cc @jakubgs
=> perf(store): add index on receiverTimestamp

waku/v2/node/config.nim, waku/v2/node/wakunode2.nim
Solves #969 in a minimal way.
Prints only the commit hash, if the current version has not been tagged with a version tag.
(That is true for the json RPC call, too.)
If desired, we could add the last version on the current branch as additional info. This would require a new compiler flag in the Makefile.
This PR just prints the info that is available via JSON rpc at the moment.
Example output for untagged version:
```
./build/wakunode2 --version
version / git commit hash: 062668
```
=> feat(info): add --version cmd flag

waku/v2/node/wakunode2.nim
This PR solves #964
`nwaku` assumed that when `--dns4-domain-name` is set, an external port is available.
This is not the case when `setupNat` cannot establish a port mapping.
The solution in this PR is simple: in this case, the dns domain name is treated as an external IP address, and port mapping is assumed to be manually resolved.
=> fix(dns4name): dns4name + unset port resolved

waku/v2/node/wakunode2.nim
This PR solves #966.
It minimally updates the current branching, but it gets a bit convoluted.
An alternative would be:
* load peer migration if `--persist-peers` is set
* load messages migration if `--persist-messages` is set
* remove the "if both" branch
(involves altering `runMigrations`, too)
Maybe, it was implemented like this to have to do two separate loads when loading both migration scripts types...
Let me know if you prefer the alternative.
=> chore(migration): avoid unnecessarily calling migration

.gitignore, tests/v2/test_waku_filter.nim, tests/v2/test_wakunode.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_filter/waku_filter.nim, waku/v2/protocol/waku_filter/waku_filter_types.nim
This PR resolves #937 
Now, nodes can combine store protocol either with the relay protocol or with filter protocol. Having the relay mounted is no longer a requirement to support store protocol.
=> feat(store): ability to decouple store from relay

waku/v2/node/storage/message/waku_message_store.nim, waku/v2/node/storage/peer/waku_peer_storage.nim, waku/v2/node/storage/sqlite.nim
This fixes https://github.com/status-im/nwaku/issues/978
Nodes with mounted SQLite databases were leaking (a lot) of memory, due to prepared statements being created (allocating memory) but never `finalized` (or disposed, freeing the allocated memory). This became apparent as the message rate in the fleets increased, with an "INSERT" statement created for each new message without that memory being freed.
Each statement _has_ to go through three phases:
1. `prepare` the statement (allocating memory)
2. Stepping through the statement to execute a specific query with a specific set of parameters. This step can be repeated if the same prepared statement is to be used multiple times, as long as the statement is `reset()` and bindings cleared after stepping through.
3. `finalize` the statement …
=> fix(sqlite): memory leak due to undisposed prepared statements

waku/v2/node/wakunode2.nim
Minimal PR to lower the period between keepalive `PING`s from `5.min` to `2.min`.
Libp2p TCP connections have an underlying timeout of `10.min`. The keepalive is meant to prevent these and other timeouts from happening, but once every `5.min` leaves very little room for error (if a node misses one `PING` for some reason it might still trigger a timeout).
Note that we do not necessarily want (or need to) make this period either configurable or dependent on a specific underlying constant (e.g. the TCP timeout), as this is mostly a workaround mechanism for fleet nodes to remain connected during idle periods.
=> chore: more regular keepalive pings

waku/v2/node/config.nim
Minimal PR to disable `swap` protocol by default.
`Swap` is not currently being used or investigated by anyone, yet it is enabled by default in `Soft` mode. Impact of keeping it enabled:
1. Many `INFO` level logs that record accounting state in all nodes.
2. Accounting state with no proper capacity management (i.e. a slow memory leak) being kept for each node involved in a `store` transaction.
We can reenable `swap` once it's used for incentivisation.
=> chore: disable swap by default

waku/v2/node/peer_manager/peer_manager.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_store/waku_store.nim
This minimal PR partially addresses https://github.com/status-im/nwaku/issues/983
It cleans up unnecessary logging, correct misleading `ERROR` logs and lower log levels where necessary.
Specifically, it:
- avoids the unnecessary error condition where the peer manager tries to store information for a connecting/disconnecting peer that is not tracked in the store (resulted in both error metrics and logs).
- lowers the per-message log level for nodes with RLN enabled, especially when few messages match the RLN content topic (currently RLN logs all messages at `DEBUG` level on the `wakuv2.test` fleet)
- avoids misleading `ERROR: Retrieving dynamic bootstrap nodes failed` by having an empty bootstrap list be an acceptable condition
- lowers error-level warning for `store` nodes starting with …
=> chore: reduce unnecessary logging

ci/Jenkinsfile.prs, ci/Jenkinsfile.release
We've seen a few jobs running on MacOS hosts stuck for days:
* https://ci.status.im/job/nim-waku/job/prs/job/macos/job/PR-982/ - [7 days 7 hr](https://ci.status.im/job/nim-waku/job/prs/job/macos/job/PR-982/buildTimeTrend)
* https://ci.status.im/job/nim-waku/job/prs/job/macos/job/PR-979/ - [5 days 7 hr](https://ci.status.im/job/nim-waku/job/prs/job/macos/job/PR-979/buildTimeTrend)
Which is not acceptable.
=> ci: add timeouts to Jenkins pipelines

waku/v2/node/wakunode2.nim
Continuation of #991
This PR adjusts the message printed when dynamic bootstrap nodes were found, differentiation between an INFO when no method was specified and a WRN if looking up dynamic bootstrap nodes failed.
We could print an ERR, if no bootstrap nodes are available at all (including static ones).
=> chore: adjust dyn bootstrap error message

tests/v2/test_message_store.nim, tests/v2/test_waku_store.nim, waku/v2/node/config.nim, waku/v2/node/storage/message/message_store.nim, waku/v2/node/storage/message/waku_message_store.nim, waku/v2/node/storage/sqlite.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_store/waku_store.nim, waku/v2/protocol/waku_store/waku_store_types.nim
This PR addresses #950.
(I am still working on performance improvments, but the functionality is ready for review.)
cc @jakubgs
I added both a new test suite that tests the sql store in isolation, and made the waku_store test compatible [f5d9e4822](https://github.com/status-im/nwaku/commit/f5d9e482271fd177471e5c32deae2048d5370c26).
Let's discuss if we want to include that, too. I ran the sql-store against these tests, too, and it worked.
I tested the sql only store on a droplet fleet with a large DB (1.6GB, >800k messages).
Connecting with chat2 takes a long a time, especially for backward queries.
The DB does not contain many messages with the chat2 content topic. So, the respective query has a sparse filter
which causes `getPage` to retrieve and filter a lot of DB pages in order to fill …
=> feat(store): sqlite only store

CHANGELOG.md
Adds the proposed release notes for Wednesday's scheduled release.
We are still waiting for
- https://github.com/status-im/nwaku/pull/988
- https://github.com/status-im/nwaku/pull/982
to be merged, but I have already added these items to the CHANGELOG.
=> docs: release v0.10 release notes

waku/v2/protocol/waku_filter/waku_filter.nim, waku/v2/protocol/waku_lightpush/waku_lightpush.nim, waku/v2/protocol/waku_message.nim, waku/v2/protocol/waku_rln_relay/waku_rln_relay_types.nim, waku/v2/protocol/waku_store/waku_store.nim, waku/v2/protocol/waku_swap/waku_swap.nim, waku/v2/utils/protobuf.nim
Currently protobuffers are being encoded using `proto2`, while on the specs `proto3` is the version meant to be used, This results in null/empty fields being written in the buffer. i.e: the following WakuMessage:
```
payload: @[1, 2, 3, 4],
contentTopic: "hola",
version:      0,
timestamp:    12345,
```
Is generating this byte array: 
```
[10, 4, 1, 2, 3, 4, 18, 4, 104, 111, 108, 97, 24, 0, 80, 242, 192, 1, 170, 1, 173, 3, 10, 128, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
```
=> fix: encode protobuffers using proto3

tests/all_tests_v2.nim, tests/v2/test_rest_relay_api.nim, tests/v2/test_rest_relay_api_serdes.nim, tests/v2/test_rest_relay_api_topic_cache.nim, waku/v2/node/rest/relay/api_types.nim, waku/v2/node/rest/relay/relay_api.nim, waku/v2/node/rest/relay/relay_api.yaml, waku/v2/node/rest/relay/topic_cache.nim, waku/v2/node/rest/serdes.nim, waku/v2/node/rest/server.nim, waku/v2/node/rest/utils.nim
The present PR adds support for the RPC Relay API (see [Relay RPC API](https://rfc.vac.dev/spec/16/#relay-api)) to the HTTP REST API. This PR resolves partially #727.
>    - [x] JSON serialization/deserialization using nim-json-serialization. Unit tests included test_tube
>    - [x] Extensible REST HTTP Server via install handlers methods using nim-presto.
>    REST HTTP Client methods using nim-presto rest pragma.
>    - [x] Implemented the "Relay namespace" control APIs: types serialization + unit tests, request handlers + E2E tests (client+server)
>    - [x] OpenAPI specificationfor the Relay REST API
>    - [x] Decoupled topic cache logic from the request handlers (+ added unit tests)
**NOTE:** There is still some integration work pending between these changes and the current Waku …
=> feat(rest): Add HTTP REST API (#727). Add Relay REST API

waku/v2/node/storage/message/waku_message_store.nim
This PR limits `dbPageSize` avoiding excessive use of memory in case of sparse or non-matching filters.
This PR partly solves #1017
=> fix(store): limit dbPageSize

tests/v2/test_waku_rln_relay_onchain.nim, waku/v2/node/wakunode2.nim, waku/v2/node/wakunode2_types.nim, waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
This PR closes https://github.com/status-im/nwaku/issues/998
As part of the code refactoring, a circular dependency occurred between the `waku_rln_relay_utils` module and the `wakunode2` module. To address that I moved the`WakuNode` type def to a separate module. For consistency, all the other types defs in wakunode2 are also moved to the same module.
=> Chore(rln-relay): decouples rln-relay and wakunode2 modules

waku/v2/node/storage/message/waku_message_store.nim
[Vacuum is an expensive operation](https://wiki.mozilla.org/Firefox/Projects/Places_Vacuum#Vacuum_timings).
This PR removes vacuum from the batch delete operation in the store.
For now, we rather vacuum "manually".
In the future we could run vacuum in a timer task.
See #1024
=> perf(store): remove vacuum

examples/v2/chat2.nim, tests/v2/test_jsonrpc_waku.nim, tests/v2/test_migration_utils.nim, tests/v2/test_waku_discv5.nim, tests/v2/test_waku_pagination.nim, tests/v2/test_waku_payload.nim, tests/v2/test_waku_rln_relay.nim, tests/v2/test_wakunode.nim, waku/common/wakubridge.nim, waku/v2/node/config.nim, waku/v2/node/discv5/waku_discv5.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_store/waku_store.nim, waku/v2/utils/wakuswitch.nim
Remove multiple `UnusedImport` warnings from the codebase:
```bash
/home/lorenzo/code/status/nwaku/waku/v2/protocol/waku_store/waku_store.nim(10, 6) Warning: imported and not used: 'algorithm' [UnusedImport]
/home/lorenzo/code/status/nwaku/waku/v2/utils/wakuswitch.nim(6, 7) Warning: imported and not used: 'byteutils' [UnusedImport]
/home/lorenzo/code/status/nwaku/waku/v2/utils/wakuswitch.nim(4, 6) Warning: imported and not used: 'sequtils' [UnusedImport]
/home/lorenzo/code/status/nwaku/waku/v2/utils/wakuswitch.nim(10, 23) Warning: imported and not used: 'dnsresolver' [UnusedImport]
/home/lorenzo/code/status/nwaku/waku/v2/node/config.nim(11, 3) Warning: imported and not used: 'web3' [UnusedImport]
/home/lorenzo/code/status/nwaku/waku/v2/node/discv5/waku_discv5.nim(4, 6) Warning: imported …
```
=> chore: remove unused imports

tests/v2/test_waku_rln_relay_onchain.nim, waku/v2/node/config.nim, waku/v2/protocol/waku_rln_relay/waku_rln_relay_types.nim, waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
The rln-relay nodes require to sign their registration transactions to authorize the fund deduction from their ethereum accounts. This PR integrates the signing feature alongside with a CLI option to pass the Ethereum private key. 
Note that passing the Ethereum account private key is an MVP solution just for testing purposes and in no way is secure, however, it is tolerable for now as all the interactions take place on the Ethereum testnet Goerli with no actual fund involved.
Note that as part of this PR, the on-chain rln-relay tests needed to be updated to account for the Eth private key requirement. 
Next Step: https://github.com/status-im/nwaku/issues/819
=> Feat (Rln relay): enabling signed tx

ci/Jenkinsfile.prs, ci/Jenkinsfile.release
Because they make things unreadable:
```
13:31:27  [0m[91m [0m[91m [0m[91mDownloaded[0m[91m [0m[91msubtle v1.0.0[0m[91m
13:31:27  [0m[91m [0m[91m [0m[91mDownloaded[0m[91m [0m[91marrayvec v0.4.12[0m[91m
13:31:27  [0m[91m [0m[91m [0m[91mDownloaded[0m[91m [0m[91mnodrop v0.1.14[0m[91m
```
=> ci: disable Nim compiler colors

tests/all_tests_v2.nim, tests/v2/test_message_store_queue_pagination.nim, tests/v2/test_utils_pagination.nim, tests/v2/test_waku_payload.nim
There is some test suite grooming work pending after the previous big PR merged. This is one PR related to that:
* Move the payload-related test cases under the right test suite
* Move the message store test cases (StoreQueue) under its own test suite file
* Group the pagination utils test cases under the same test suite
=> refactor(waku-store): reorganise pagination test cases

examples/v2/chat2.nim, waku/v2/node/wakunode2.nim
To continue the lightpush protocol code reorganization and module/imports untangling work:
* Remove the `waku_lightpush` export from `wakunode2.nim` to avoid future cyclic import issues
* Update all the imports of wakunode2 accordingly
This is a cleanup/code reorganization PR.
=> refactor(waku-lightpush): remove wakunode2 waku_lightpush exports

waku/v2/node/storage/message/message_store.nim, waku/v2/node/storage/message/waku_store_queue.nim, waku/v2/protocol/waku_store/protocol.nim
There is some test suite grooming work pending after the previous big PR merged. This is another PR related to that:
* Inherit from MessageStore in StoreQueue (a.k.a. in-memory store) implementation
* Unify the message store interface (add new methods that will replace the existing ones in the upcoming PRs)
This is work to accommodate the changes necessary for https://github.com/status-im/nwaku/issues/1026
=> refactor(waku-store): inherit from message_store in store_queue

CHANGELOG.md
Adds the proposed release notes for Monday's scheduled release.
~We are still waiting for~ https://github.com/status-im/nwaku/pull/1073 ~to be merged, but I have already added it to the CHANGELOG.~
=> docs: release v0.11 release notes

tests/v2/test_waku_store.nim, waku/v2/protocol/waku_store/protocol.nim
This is a code refactoring PR for the waku store protocol.
* Move to async procedures the request methods.
* Deprecate the callback version of the request methods.
* Some code cleanup.
* Update test cases accordingly.
This is an intermediate PR to make the `wakunode2.nim` refactoring simpler.
=> refactor(waku-store): deprecate waku store callback methods

tests/v2/test_peer_manager.nim, waku/v2/node/jsonrpc/admin_api.nim, waku/v2/node/wakunode2.nim
To continue the store protocol code reorganization and module/imports untangling work:
* Remove the `waku_store` export from `wakunode2.nim` to avoid future cyclic import issues
* Update all the imports of wakunode2 accordingly
This is a cleanup/code reorganization PR.
=> refactor(waku-store): remove wakunode2 waku_store exports

waku/v2/node/wakunode2.nim
Closes https://github.com/status-im/nwaku/issues/1086
This simple fix avoids unnecessary waiting for `connectToNodes` if no dynamic bootstrap nodes are found during the setup process.
=> fix: do not attempt connecting to empty dynamic bootstrap node list

docs/tutorial/onchain-rln-relay-chat2.md
This PR applies the updates on the chat2 tutorial to match the recent updates on the interface i.e., 1) the spam message warning and 2) the display of a link to the registration tx hash on the Goerli testnet.
Towards https://github.com/status-im/nwaku/issues/1069.
=> chore (rln-relay): updates rln-caht2 tutorial to match the implementation

waku/v2/node/peer_manager/peer_manager.nim
Implements the fix by @Menduist for https://github.com/status-im/nwaku/issues/948.
The peer manager no longer expects an address entry in the `switch` peer store when dialing existing peers. In some cases, such as on existing incoming connections from browser clients, there may be no stored addresses for the peer.
=> fix: peer manager dial logic when dialing an existing peer

examples/v2/chat2.nim, tests/v2/test_peer_manager.nim, waku/v2/node/jsonrpc/admin_api.nim, waku/v2/node/jsonrpc/filter_api.nim, waku/v2/node/wakunode2.nim
To continue the store protocol code reorganization and module/imports untangling work:
* Remove the `waku_filter` export from `wakunode2.nim` to avoid future cyclic import issues
* Update all the imports of wakunode2 accordingly
This is a cleanup/code reorganization PR.
=> refactor(waku-filter): remove wakunode2 waku_filter exports

tests/v2/test_rest_relay_api.nim, tests/v2/test_rest_relay_api_serdes.nim, waku/v2/node/rest/base64.nim, waku/v2/node/rest/relay/api_types.nim, waku/v2/node/rest/relay/relay_api.nim, waku/v2/node/rest/relay/relay_api.yaml, waku/v2/node/rest/serdes.nim
During Bologna's offsite, this issue was raised by @richard-ramos.
* Now the waku message payload is specified to be base64 encoded (see: [OpenAPI types](https://swagger.io/specification/#:~:text=string-,string,base64%20encoded%20characters,-string)).
* Base64 encoding wrapper.
* Encode/decode the waku messages payload when converted into/from with the Relay REST API types.
* Updated the test cases accordingly.
=> fix(rest): encode waku message payload in base64

tests/all_tests_v2.nim, tests/v2/test_message_cache.nim, waku/v2/node/config.nim, waku/v2/node/message_cache.nim, waku/v2/node/rest/relay/topic_cache.nim, waku/v2/node/wakunode2_setup_rest.nim
The current topic cache implementation can be made generic to support also the filter use case. Now it allows different types of keys:
* The key type for the relay is `string` (the type of PubSub topics)
* The key type for the filter should be a tuple of `PubsubTopicString` (aka `string`) and `ContentTopic`.
This work is necessary for #1076 (filter REST API)
=> feat(message-cache): make the topic cache generic

waku/v2/node/config.nim, waku/v2/node/wakunode2_setup_metrics.nim
Should resolve #984
- chore: enable metrics logging by default
- feat(logging): add additional logging metrics, change period to 30 seconds
We now log the following fields:
- Total connections initiated (peer count) since last log
- Total Messages
- Total SWAP peers
- Total FILTER peers
- Total errors since last log
- Total subscribed topics
Should the docs mention which fields refer to values over the last reporting period vs since the node setup?
=> Periodic logging for additional metrics

waku/v2/node/rest/filter/openapi.yaml
Implement the Waku filter Rest API for Waku node:
This PR covers partially issue #1076
=> feat(rest): add waku filter openapi rest api specification file

waku/v2/node/storage/sqlite.nim
1. n is already int
2. when val >= 1<<31, using sqlite3_bind_int should store it as negative value
=> Fixed handling of bindParam(uint32) in sqlite.nim

waku/v2/node/wakunode2.nim
The new methods are for convenience (mainly in test cases).
=> refactor(wakunode2): add convenience methods for adding protocol peers

waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_lightpush/protocol.nim, waku/v2/protocol/waku_store/protocol.nim
Continuing with the wakunode2 file refactoring and protocol refactoring:
* Removed the deprecated methods from the protocols
* Use the async version of the deprecated methods in wakunode2
* Deprecated the old handler (non-async) methods
This is part of the groundwork necessary for #1076
=> refactor(wakunode2): deprecate non-async protocol api methods

waku/v2/node/storage/message/waku_message_store_queries.nim, waku/v2/node/storage/migration/migration_types.nim, waku/v2/node/storage/migration/migrations_scripts/message/00005_updateIndex.up.sql
This PR contains surgical changes to unblock Status's waku store testing. Some deficiencies have been identified during the analysis and will be addressed shortly.
The existing SQLite index of the messages table, `i_rt`, was not helpful for the store queries. 
* Drop the previous `i_rt` index
* Create a new index, `i_msg`, that contains the fields relevant to the store query
=> fix(waku-store): added an index to improve messages query time

tests/all_tests_v2.nim, tests/v2/test_utils_peers.nim, tests/v2/test_wakunode.nim
This is a short PR of a series of changes that aim to split the `test_wakunode.nim` file in different files:
=> refactor(wakunode): split peer utils tests into a new file

tests/all_tests_v2.nim, tests/v2/test_wakunode.nim, tests/v2/test_wakunode_lightpush.nim
This is another short PR of a series of changes that aim to split the `test_wakunode.nim` file into different files:
=> refactor(wakunode): split wakunode lightpush tests into a new file

waku/v2/node/storage/message/waku_message_store.nim, waku/v2/node/storage/message/waku_message_store_queries.nim, waku/v2/node/storage/migration/migrations_scripts/message/00005_updateIndex.up.sql, waku/v2/protocol/waku_store/protocol.nim
This PR fixes a regression introduced in #1120, and solves the #1127 issue.
* Revert `i_rt` index. The index was dropped, translating into a heavy CPU load when a message was inserted.
* Replace `waku_message_store_queries.nim` templates with `proc` and remove `{.inline.}` as per [this discussion](https://github.com/status-im/nwaku/pull/1104#discussion_r959559319) in a previous PR and the [Status' nim styleguide](https://status-im.github.io/nim-style-guide/language.inline.html?highlight=inline#inline-functions-languageinline).
* Raise, temporarily, to debug the level of the insertion failures.
=> fix(store): add a table index to improve message insertion time

tests/all_tests_v2.nim, tests/v2/test_wakunode.nim, tests/v2/test_wakunode_store.nim
This is another short PR of a series of changes that aim to split the `test_wakunode.nim` file into different files:
=> refactor(wakunode): split wakunode store tests into a new file

tests/all_tests_v2.nim, tests/v2/test_wakunode.nim, tests/v2/test_wakunode_relay.nim
This is the last short PR of a series of changes that aim to split the `test_wakunode.nim` file into different files:
=> refactor(wakunode): split wakunode relay tests into a new file

ci/Jenkinsfile.prs, waku/v2/protocol/waku_rln_relay/waku_rln_relay_types.nim
Should resolve #1131.
Reverts the `nim-json-rpc` submodule update, which moved from `nim-websock` to `news` between updates. Relevant [diff](https://github.com/status-im/nim-json-rpc/compare/335f292a5816910aebf215e3a88db8a665133e0e...32ba2d16b919310a8c6797ac45747595f301a207)
This regression only affects macOS.
Experimentation can be done by updating to the latest version of `nim-json-rpc`, there seems to be some work done on this [PR](https://github.com/status-im/nim-json-rpc/pull/147) to better support macOS.
=> fix macos builds

.gitignore, tests/v2/test_waku_store.nim, waku/v2/protocol/waku_message.nim, waku/v2/protocol/waku_store/protocol.nim, waku/v2/utils/protobuf.nim
Should resolve #985.
Follows the RFC change described in [vacp2p/rfc](https://github.com/vacp2p/rfc/pull/532)
=> feat(store): Allow messages to be marked as "don't store"

examples/v2/config_chat2.nim, examples/v2/matterbridge/chat2bridge.nim, tests/v2/test_jsonrpc_waku.nim, tests/v2/test_peer_exchange.nim, tests/v2/test_peer_manager.nim, tests/v2/test_rest_debug_api.nim, tests/v2/test_rest_relay_api.nim, tests/v2/test_waku_discv5.nim, tests/v2/test_waku_rln_relay.nim, tests/v2/test_wakunode_lightpush.nim, waku/common/wakubridge.nim, waku/v2/node/config.nim, waku/v2/node/jsonrpc/admin_api.nim, waku/v2/node/jsonrpc/relay_api.nim, waku/v2/node/wakunode2.nim, waku/v2/node/wakunode2_setup_metrics.nim, waku/v2/node/wakunode2_setup_rpc.nim, waku/v2/node/wakunode2_setup_sql_migrations.nim, waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
Another multi-commit grooming PR. In this case, the goal is to continue removing the exports to avoid implicit and cyclic imports.
=> refactor(wakunode): remove exports from wakunode

waku/v2/protocol/waku_store/protocol.nim
After the conversation with @jakubgs, some improvements have been introduced to the recently added metrics to adhere to [prometheus naming good practices](https://prometheus.io/docs/practices/naming/):
* Renamed the histogram metrics to `*_duration_seconds`
* Values are inserted in _seconds_ and not _milliseconds_
=> fix(store): follow good practices in store insert and query metrics

waku/v2/node/config.nim, waku/v2/node/storage/sqlite.nim, waku/v2/node/wakunode2.nim
This PR partially covers #1154 
* Log some metrics related to SQLite database pages
* Added a flag to enable vacuuming. Disabled by default.
* Executes SQLite's `VACUUM` command during storage setup, right before running any DB migration.
=> feat(store): run sqlite database vacuum at node start

waku/v2/node/storage/message/message_store.nim, waku/v2/node/storage/message/sqlite_store/sqlite_store.nim, waku/v2/node/storage/message/waku_store_queue.nim, waku/v2/protocol/waku_store/protocol.nim
The present PR forms part of a series of refactoring PRs that aim to decouple the retention policy from the message store interface completely.
* Make message store interface `getMessagesCount` method fallible
* Do not cache SQLite's store message count
This is part of the groundwork necessary for #1155
=> refactor(store): don't cache the message count in sqlite message store

waku/v2/node/storage/message/message_store.nim, waku/v2/node/storage/message/sqlite_store/sqlite_store.nim, waku/v2/node/storage/message/waku_store_queue.nim
The present PR forms part of a series of refactoring PRs that aim to decouple the retention policy from the message store interface completely.
* Extend message store interface
* Implement the message store interface methods for `SqliteStore`
* Implement the message store interface methods for `StoreQueueRef`
**NOTE:** A couple of in-memory store methods have not been implemented. Some extra work is needed there to support message retention policies.
This is part of the groundwork necessary for #1155
=> refactor(store): extend message store interface with store manipulation methods

tests/v2/test_message_store_sqlite.nim, tests/v2/test_message_store_sqlite_query.nim, waku/v2/node/config.nim, waku/v2/node/storage/message/message_retention_policy.nim, waku/v2/node/storage/message/message_retention_policy_capacity.nim, waku/v2/node/storage/message/message_retention_policy_time.nim, waku/v2/node/storage/message/sqlite_store.nim, waku/v2/node/storage/message/sqlite_store/sqlite_store.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_store/protocol.nim
The present PR forms part of a series of refactoring PRs that aim to decouple the retention policy from the message store interface completely.
* Move retention policies one level up. Now it depends on the message store interface.
* As an intermediate step, and to avoid changing current behavior, move retention policy execution to WakuStore protocol initialization and message handling.
* Waku node's store protocol setup procedure cleanup.
* Update tests accordingly.
This is part of the groundwork necessary for #1155
=> refactor(store): invert retention policies dependency on message store interface

waku/v2/node/wakunode2.nim
One-liner fix for issue that prevented the node to reconnect to peers from the discv5 loop. Peers that appear in the `AddressBook` are not necessarily connected anymore (e.g. they may have restarted) and a reconnect should be attempted when they are discovered "again" via Discovery v5.
Can confirm improvement on my own deployed node - previously if the fleet restarted the running node would never attempt to reconnect.
=> fix: nodes in AddressBook are not necessarily connected

metrics/waku-fleet-dashboard.json, metrics/waku-single-node-dashboard.json
This PR does two things:
- brings the latest changes made to the [fleet Grafana dashboard](https://grafana.infra.status.im/d/qrp_ZCTGz/nim-waku-v2) under version control. This mostly serves as an occasional backup of the dashboard JSON descriptor, although we can consider automating committing dashboard changes to version control
- adds a stripped down dashboard that can serve as entry point for those monitoring a single nwaku instance (this will be included in a WIP "How to monitor your node" guide for operators).
It's difficult to visualise the JSON diffs below. The changes to `waku-fleet-dashboard.json` is already reflected in the [fleet Grafana dashboard](https://grafana.infra.status.im/d/qrp_ZCTGz/nim-waku-v2).
The `waku-single-node-dashboard.json` looks similar, but without any …
=> chore: update existing Grafana dashboards

docs/operators/how-to/monitor.md
This PR adds a basic guide on how to use Prometheus and Grafana to monitor a running nwaku node.
This is a prerequisite for launching the operator trial in https://github.com/status-im/nwaku/issues/828.
I've tried to avoid simply repeating Prometheus's and Grafana's instruction manuals and instead focused on nwaku-specific configuration choices. This also relates to the monitoring dashboard published in https://github.com/status-im/nwaku/pull/1166.
What is still outstanding:
=> docs: add monitoring guide for prometheus and grafana

tests/v2/test_waku_rln_relay.nim, waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
Should resolve #1049.
Note: There is no functionality for maintaining a window of acceptable tree roots. Should we track this in a separate issue? 
Edit: As @jm-clius pointed out in https://github.com/status-im/nwaku/pull/1158#discussion_r972237018, errors should be better handled when dealing with the `proofVerify` function. Instead of returning `false` when one of the rln libs throw errors, we throw errors. This PR also includes this change.
=> feat(rln-relay): validate the merkle root in the RateLimitProof

tests/v2/test_jsonrpc_waku.nim, tests/v2/test_waku_store.nim, tests/v2/test_waku_swap.nim, tests/v2/test_wakunode_store.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_store/protocol.nim
This PR resolves #1155: Reduce the message insertion duration by running the retention policy in a periodic task instead running it at insertion time.
* Execute retention policy after mounting the store protocol
* Start periodic tasks running every 30 min:
- Retention policy execution  
- Report stored messages count (just after executing the retention policy)
* Remove waku store `handleMessage()`'s unnecessary async pragma
* Update tests accordingly
As a result, stored messages count **ONLY** will be updated every 30 minutes (after the retention policy is executed).
=> feat(store): execute retention policies periodically (#1155)

examples/v2/chat2.nim, tests/v2/test_waku_swap.nim, tests/v2/test_wakunode_lightpush.nim, tests/v2/test_wakunode_store.nim, waku/v2/node/jsonrpc/store_api.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_store/protocol.nim
The present PR aims to remove the deprecated non-async methods from `wakunode2` module:
* Remove waku lightpush deprecated method
* Remove waku waku store query deprecated method
* Update tests and examples accordingly
=> refactor(wakunode): remove deprecated non-async methods

.github/workflows/test.yml
Skip tests workflow execution when only doc files (e.g., `README.md`) have been modified
=> chore(ci): skip test workflow execution for docs changes

docs/operators/droplet-quickstart.md, docs/operators/how-to/configure-dns-disc.md, docs/operators/how-to/run.md, examples/v2/chat2.nim, waku/v2/README.md
The keys used to sign the deployed Merkle tree node lists for `wakuv2.*` fleets have changed. See [this comment](https://github.com/status-im/infra-status/issues/17#issuecomment-1250860524) for more detail.
This PR updates the documentation to reflect the change and fixes the `chat2` application by using the new tree URLs. Since the keys are unlikely to change again (previous deployed ones were experimental, but process has now been formalised), there is no apparent need to automate this update process.
=> fix: signing key for wakuv2 DNS lists has changed

waku/v2/node/wakunode2.nim
Fixes regression introduced when submodules were updated.
In order for the node to "advertise" external, announced addresses during the `identify` procedure, the switch's addresses need to be explicitly updated.  However, the switch should be started on the bind address before this is done.
This resulted in `TransportError` being raised when starting the switch with an `extip`.
=> fix: fail to start switch with ext ip

examples/v2/config_chat2.nim, waku/v2/node/config.nim
Adds a small but important clarification to the description of the `eth-client-address` config option:  the supplied address should be a WebSocket address.
=> chore(rln-relay): specifies the address type for the eth-client-address config parameter

tests/v2/test_jsonrpc_waku.nim, tests/v2/test_message_store_queue.nim, tests/v2/test_message_store_sqlite.nim, tests/v2/test_message_store_sqlite_query.nim, tests/v2/test_waku_store.nim, tests/v2/test_wakunode_store.nim, waku/v2/node/storage/message/dual_message_store.nim, waku/v2/node/storage/message/message_store.nim, waku/v2/node/storage/message/sqlite_store/sqlite_store.nim, waku/v2/node/storage/message/waku_store_queue.nim, waku/v2/protocol/waku_store/protocol.nim, waku/v2/utils/pagination.nim
This PR aims to address the inconsistencies based [the discussion](https://github.com/vacp2p/rfc/pull/535#discussion_r973520241) about what should be considered a valid message based on the metadata and the payload.
The gist of the changes:
> As we now have more message store implementations, in this PR, I have changed the `MessageStore` interface dependence on the `Index` type when a message is inserted in the DB (see `message_store`'s interface `put()` API). And moved all the common insertion logic to the waku protocol module.
> 
> Now the messages digest is calculated before inserting it into the store. Calculating a hash is a computational "costly" operation, so the lesser number of times that we compute it, the better.
=> fix(store): move insert criteria logic to waku store protocol module

tests/v2/test_waku_rln_relay.nim, waku/v2/protocol/waku_rln_relay/waku_rln_relay_types.nim, waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
Should resolve https://github.com/status-im/nwaku/issues/1171
Minor refactors:
- Created `insertMember`, `removeMember` procs for the rln relay object so that we can track the acceptable roots. These 2 procs are to be used, rather than 
directly using the rlnInstance's procs (if one needs to validate roots)
- Moved the RLN result types to waku_rln_relay_types
- the `addAll` utility is now defined on the rln relay object, since it uses `insertMember` and `removeMember` procs
=> feat(rln-relay): multiple acceptable roots

tests/v2/test_message_store_sqlite_query.nim, waku/v2/node/storage/message/message_store.nim, waku/v2/node/storage/message/sqlite_store/queries.nim, waku/v2/node/storage/message/sqlite_store/sqlite_store.nim, waku/v2/node/storage/message/waku_store_queue.nim, waku/v2/node/storage/migration/migration_types.nim, waku/v2/node/storage/migration/migrations_scripts/message/00006_renameColumn.up.sql, waku/v2/protocol/waku_store/protocol.nim
This is a waku store follow-up PR for #1178.
* Rename `receiverTmiestamp` SQLite message store column to `storedAt`
* Update SQLite message store DB indexes
* Remove unnecessary SQLite query ordering criteria
* Move max page size limit checks to the waku store protocol module
* Change query max page size default value. Set it by default to 20 messages, not to the limit (100 messages).
* Extend test coverage and update tests accordingly
=> fix(store): rename store timestamp sqlite column

tests/v2/test_jsonrpc_waku.nim, tests/v2/test_message_store_queue.nim, tests/v2/test_message_store_queue_pagination.nim, tests/v2/test_message_store_sqlite.nim, tests/v2/test_message_store_sqlite_query.nim, tests/v2/test_waku_store.nim, tests/v2/test_waku_store_rpc_codec.nim, tests/v2/test_wakunode_store.nim, waku/v2/node/jsonrpc/jsonrpc_types.nim, waku/v2/node/jsonrpc/jsonrpc_utils.nim, waku/v2/node/jsonrpc/store_api.nim, waku/v2/node/storage/message/dual_message_store.nim, waku/v2/node/storage/message/message_retention_policy.nim, waku/v2/node/storage/message/message_retention_policy_capacity.nim, waku/v2/node/storage/message/message_retention_policy_time.nim, waku/v2/node/storage/message/queue_store/index.nim, waku/v2/node/storage/message/queue_store/queue_store.nim, waku/v2/node/storage/message/sqlite_store/queries.nim, waku/v2/node/storage/message/sqlite_store/sqlite_store.nim, waku/v2/node/wakunode2.nim, waku/v2/protocol/waku_store.nim, waku/v2/protocol/waku_store/message_store.nim, waku/v2/protocol/waku_store/pagination.nim, waku/v2/protocol/waku_store/protocol.nim, waku/v2/protocol/waku_store/rpc.nim, waku/v2/protocol/waku_store/rpc_codec.nim
This is a code reorganization PR to clear out the imports graph:
* Move pagination from utils to waku store protocol module
* Move message store interface module to waku store protocol module
The files are collocated with the waku protocol, so now the dependency graph is:
> Message Store Impl -> Waku Store Protocol
> Waku Node -> Waku Store Protocol
instead of:
> Waku Store Protocol -> Message Store Impl (module)
> Waku Node -> Waku Store Protocol
> Waku Node -> Message Store Impl
=> chore(store): collocate pagination and message store types

Makefile
This is necessary for Nix builds because the sandbox there does not contain `.git` directory or `git` command.
Also the quotes are pointless.
=> Makefile: allow overriding GIT_VERSION with env

tests/v2/test_message_store_sqlite.nim, waku/v2/node/storage/message/sqlite_store/queries.nim, waku/v2/node/storage/message/sqlite_store/sqlite_store.nim, waku/v2/node/storage/migration/migration_types.nim, waku/v2/node/storage/migration/migrations_scripts/message/00007_updatePrimaryKey.up.sql
This PR is part of the "fix waku store pagination" series:
In this PR:
- Update SQLite DB table primary key
- Rename `senderTimestamp` column to `timestamp`
- Extend history query order by clause for results consistency
- Decouple `sqlite_store/queries` module from `pagination` module types
- Update test cases accordingly
=> fix(store): update sqlite db table primary key and decouple queries module from pagination types

tests/v2/test_jsonrpc_waku.nim, tests/v2/test_message_store_queue.nim, tests/v2/test_message_store_queue_pagination.nim, tests/v2/test_message_store_sqlite.nim, tests/v2/test_message_store_sqlite_query.nim, tests/v2/test_waku_store.nim, waku/v2/node/storage/message/dual_message_store.nim, waku/v2/node/storage/message/queue_store/queue_store.nim, waku/v2/node/storage/message/sqlite_store/queries.nim, waku/v2/node/storage/message/sqlite_store/sqlite_store.nim, waku/v2/protocol/waku_store/message_store.nim, waku/v2/protocol/waku_store/protocol.nim
This PR is part of the "fix waku store pagination" series:
In this PR:
- Simplify the message store interface and update message store implementations accordingly
- Move paging info calculation to the protocol module
- Fix pagination logic: `Always search for _max page size_ + 1. If the extra row does not exist, do not return pagination info.` 
- Update test cases accordingly
=> fix(store): Move page info logic to waku store protocol

ci/Jenkinsfile.prs, shell.nix
Because we need Rust version newer than `1.62.0` and Ubuntu 22.04 only comes with `1.61.0`:
https://packages.ubuntu.com/jammy/rustc
And locking dependencies using Nix would make it easier for developers to track them and update them:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/rust/1_63.nix
=> [WIP] ci: use Nix shell to provide build dependencies

docs/tutorial/onchain-rln-relay-chat2.md, examples/v2/config_chat2.nim, waku/v2/node/config.nim, waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
Should resolve https://github.com/status-im/nwaku/issues/1196
This PR namespaces few flags that are exclusively used with rln-relay. This will 
unblock https://github.com/status-im/infra-role-nim-waku/pull/5 and 
https://github.com/status-im/infra-nim-waku/pull/61
=> chore(rln-relay): namespaced flags

waku/v2/node/storage/message/sqlite_store/sqlite_store.nim, waku/v2/node/storage/peer/waku_peer_storage.nim, waku/v2/node/wakunode2.nim
Fixes https://github.com/status-im/nwaku/issues/1188
Currently enabling store without setting an explicit `--db-path` leads to a crash with message [`SIGSEGV: Illegal storage access.`](https://github.com/status-im/nwaku/issues/1188). This is because both the sqlite-only store and dual message store requires a functioning, initialised database. It should be possible to configure nwaku with an in-memory store only.
This PR:
- enables configuring nwaku without an external db-path (in-memory only)
- ensures DB misconfiguration leads to an init error and not a failure/crash (both for message and peer stores)
Note that this simply fixes operation using the existing config items. Reworking `store` config is being tracked in https://github.com/status-im/nwaku/issues/1217
=> fix: store config without db-path causes SIGSEGV crash

Dockerfile
Necessary to fix errors like:
```
error: package `ethers-core v0.17.0 (https://github.com/gakonst/ethers-rs#454449b0)` cannot be built
because it requires rustc 1.62 or newer, while the currently active rustc version is 1.60.0
```
Also upgraded Alpine from `3.15` to `3.16`.
Related:
* https://github.com/status-im/nwaku/pull/1216
=> ci: install 1.64 rust in Docker image

waku/v2/node/jsonrpc/debug_api.nim, waku/v2/node/wakunode2.nim
Closes https://github.com/status-im/nwaku/issues/1125.
Publishes the nwaku `git_version` to a metric with the label value matching the version. For now the label format matches the `git describe` format, though we should consider more explicit, parsed versioning information similar to nimbus in future.
=> chore: publish nwaku version to metric

waku/v2/protocol/waku_store/protocol.nim
Fix the constant definition. Seems that using chronos' `seconds` and `nanoseconds` procs set the constant to 0. The changes revert to the original way of defining the constant.
=> fix(store): fix store validity timestamp variance constant

CHANGELOG.md
The proposed release notes for [Release v0.12.0](https://github.com/status-im/nwaku/milestone/4).
Once the last open PRs are merged, I'll rebase this on the release candidate on `master`.
=> docs: release notes for v0.12.0

waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
Does 3 things:
- Logs out when eth node connections are dropped
- Keeps track of last seen block so that when the connection is reinitiated the tree is not repopulated
- Heartbeat newHead subscription
In a follow up PR:
- Reconnection logic
=> test(rln-relay): setup heartbeat ws subscription and log when connection drops

Makefile, README.md, tools/README.md, tools/wakucanary/wakucanary.nim, waku.nimble
closes #754
* Creates a tool that allows to check if i) a given node is reachable and ii) it supports a set of protocols.
* See README for usage instruction.
=> chore(wakucanary): add canary tool

docs/tutorial/onchain-rln-relay-chat2.md, examples/v2/chat2.nim, tests/v2/test_waku_rln_relay_onchain.nim, waku/v2/protocol/waku_rln_relay/waku_rln_relay_types.nim, waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
Should resolve https://github.com/status-im/nwaku/issues/1116 and by extension #1221 
This PR removes the need to always pass in an account address. While it can be derived from the private 
key, we use field temporarily. It will be removed in a subsequent PR.
Now, while restarting chat2/wakunode2 with persisted credentials, you can omit `rln-relay-eth-account-address` and 
`rln-relay-eth-private-key`.
Additionally, some consistent naming has been introduced.
=> chore(rln-relay): make account address optional

waku/v2/node/wakunode2_setup_metrics.nim, waku/v2/protocol/waku_rln_relay/waku_rln_relay_metrics.nim, waku/v2/utils/collector.nim
This PR serves as the initial groundwork to allow metric logging on chat2 (https://github.com/status-im/nwaku/issues/1203)
Creates a `startRlnMetricsLog` procedure which periodically logs out certain counter-based metrics, like -
- total messages
- total spam messages
- total invalid messages
- total valid messages
- total errors
- total proofs verified
Also creates a template to avoid reuse of logic to get the metrics only for the last `period`
This proc is then imported into `wakunode_setup_metrics`, and called after.
=> feat(rln-relay): periodically log metrics

tools/README.md, tools/wakucanary/wakucanary.nim
* Allows wakucanary tool to be used with dns names, instead of just IPs for `--address` flag.
* Related #754 #1205
* Fixes [comment](https://github.com/status-im/nwaku/pull/1205#issuecomment-1270435941)
=> chore(wakucanary): resolve dns

Makefile, apps/chat2/chat2.nim, apps/wakunode2/wakunode2.nim, waku.nimble
Closes #1197 
Problem:
* Without `-d:chronicles_runtime_filtering:on` flag `setLogLevel` does not work.
* `setLogLevel` only works with levels less verbose than `-d:chronicles_log_level=xxx`, i.e. `setLogLevel(TRACE)` won't work if `-d:chronicles_log_level=INFO`.
* More info [here](https://github.com/status-im/nwaku/issues/1197#issuecomment-1271489622).
Solution:
* Add `-d:chronicles_runtime_filtering:on` when compiling all binaries
* Set `-d:chronicles_log_level=TRACE` to all nwaku `app` and `wakunode2`
Now the following works as expected. Note that default is `INFO`.
```
$ ./build/wakunode2 --log-level=TRACE
$ ./build/wakunode2 --log-level=DEBUG
$ ./build/wakunode2 --log-level=WARN
```
=> fix: log-level being ignored

tests/all_tests_v2.nim
As the test has been failing for a month, causing many inconveniences, no clear root cause has been identified so far, and the resume store is a second-priority functionality; this PR disables it temporarily, and the following issue has been created to track the investigation/fix:
- #1282
=> chore(store): disable temporarily the store resume flaky test case

apps/wakunode2/wakunode2_setup_metrics.nim, tests/all_tests_v2.nim, tests/v2/test_waku_store.nim, tests/v2/test_waku_store_client.nim, waku/v2/protocol/waku_store/client.nim, waku/v2/protocol/waku_store/protocol.nim, waku/v2/protocol/waku_store/protocol_metrics.nim
The waku store protocol is a request-response/client-server protocol. These changes decouple the client logic from the request-handling logic. So now it should be possible to do waku store history queries without mounting the store protocol handling/server part.
Remaining work:
- Use the waku store client in `wakunode2`/`waku_node`.
- Remove waku store protocol deprecated methods.
=> feat(store): add waku store client module

tests/v2/test_message_cache.nim, tests/v2/test_message_store_queue_index.nim, tests/v2/test_message_store_queue_pagination.nim, tests/v2/test_message_store_sqlite.nim, tests/v2/test_message_store_sqlite_query.nim, tests/v2/test_rest_relay_api.nim, tests/v2/test_waku_filter.nim, tests/v2/test_waku_lightpush.nim, tests/v2/test_waku_rln_relay.nim, tests/v2/test_waku_store.nim, tests/v2/test_waku_store_client.nim, tests/v2/test_waku_store_resume.nim, tests/v2/test_waku_store_rpc_codec.nim, tests/v2/test_waku_swap.nim, tests/v2/test_wakunode_lightpush.nim, tests/v2/test_wakunode_relay.nim, tests/v2/test_wakunode_store.nim, tests/v2/testlib/common.nim, tests/v2/testlib/switch.nim
These changes move all the common test helpers under `testlib` folder.
This PR resolves #1173
=> chore: extract test procedures and constants into a common module

tests/all_tests_v2.nim, tests/v2/test_waku_lightpush.nim, tests/v2/test_wakunode_lightpush.nim, tests/v2/testlib/common.nim, waku/v2/node/waku_metrics.nim, waku/v2/node/waku_node.nim, waku/v2/protocol/waku_lightpush/client.nim, waku/v2/protocol/waku_lightpush/protocol.nim, waku/v2/protocol/waku_lightpush/protocol_metrics.nim, waku/v2/protocol/waku_lightpush/rpc_codec.nim, waku/v2/protocol/waku_store/client.nim
This refactoring was hastened due to the upcoming Dandelion++ support for the waku lightpush protocol.
=> feat(lightpush): add waku lightpush protocol client

ci/Jenkinsfile.prs
The `NIMFLAGS` pipeline parameter was ignored previously in Jenkins' CI PR pipeline. I have added it back, together with the `MAKEFLAGS` parameter, to the _build_ and _test_ stages.
=> ci(jenkins): use MAKEFLAGS and NIMFLAGS pipeline params in build and test stages

apps/wakunode2/config.nim, shell.nix
The first part of the work simplifies the store configuration. Added new configuration options and deprecated the old ones.
Check for more details: #1103
The refactoring of the `wakunode2` setup sequence to support the new simplified store and persistence configuration options will be performed as part of the subsequent PR.
=> feat(store): simplify wakunode2 configuration options

apps/chat2/chat2.nim, apps/wakubridge/wakubridge.nim, examples/v2/basic2.nim, waku/v2/node/waku_node.nim
This is a gardening PR 🌳🧑‍🌾
NOTE: These changes are necessary for the coming protocol client PRs
=> chore(node): waku node code reorganization

tests/v2/testlib/testutils.nim
Following Javascript's Jest idea of _disabling a test by adding an 'x' before/after the test keyword_ (see [Jest docs](https://jestjs.io/docs/next/api#describeskipname-fn:~:text=Also%20under%20the%20aliases%3A%20it.skip(name%2C%20fn)%2C%20xit(name%2C%20fn)%2C%20and%20xtest(name%2C%20fn))):
> When you are maintaining a large codebase, you may sometimes find a test that is temporarily broken for some reason. If you want to skip running this test, but you don't want to delete this code, you can use test.skip to specify some tests to skip.
So in our case this is how to use the new test debug utils:
1. Import the `./testlib/testutils` module in your test suite file
2. Add a 'x' either before or after the test case/suite keyword: `xtest`, `xasyncTest`, `xsuite`, `xprocSuite`, etc.
3. Run the …
=> feat(testlib): add enable/disable test debug utils

apps/wakunode2/config.nim, apps/wakunode2/wakunode2.nim, tests/v2/test_wakunode.nim, waku/v2/node/waku_node.nim, waku/v2/node/wakuswitch.nim
Closes #1242
Description:
* Set `nwaku` as default libp2p `UserAgent` used by `identify` protocol.
* This parameter can be changed with a CLI flag.
* If the flag is not provided, the default libp2p value is used (the one we currently had)
* Tests testing the change
=> feat(wakunode2): add nwaku agent-string to switch

apps/wakunode2/wakunode2.nim, tests/v2/test_message_store_sqlite.nim, tests/v2/test_message_store_sqlite_query.nim, tests/v2/test_peer_manager.nim, tests/v2/test_peer_storage.nim, tests/v2/test_waku_store.nim, tests/v2/test_waku_store_client.nim, tests/v2/test_waku_store_resume.nim, tests/v2/test_wakunode_store.nim, waku/common/sqlite.nim, waku/v2/node/storage/message/sqlite_store/queries.nim, waku/v2/node/storage/message/sqlite_store/sqlite_store.nim, waku/v2/node/storage/migration.nim, waku/v2/node/storage/peer/waku_peer_storage.nim
=> chore(common): move sqlite module to common module

tests/v2/test_waku_rln_relay.nim, waku/v2/protocol/waku_rln_relay/waku_rln_relay_constants.nim, waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
This should resolve the broken ci tests for the epoch comparison in rln-relay.
Compares the epochs and returns the appropriate value.
=> fix(rln-relay): RangeDefect test

apps/wakunode2/wakunode2.nim, tests/v2/test_waku_peer_exchange.nim, waku/v2/node/waku_node.nim, waku/v2/protocol/waku_peer_exchange.nim, waku/v2/protocol/waku_peer_exchange/client.nim, waku/v2/protocol/waku_peer_exchange/protocol.nim
For consistency with the other protocols:
=> refactor(peer-exchange): move peer management to waku_node module

apps/chat2/chat2.nim, apps/wakunode2/wakunode2.nim, tests/v2/test_jsonrpc_waku.nim, tests/v2/test_peer_manager.nim, tests/v2/test_waku_filter.nim, tests/v2/test_wakunode_filter.nim, tests/v2/test_wakunode_store.nim, waku/v2/node/jsonrpc/filter_api.nim, waku/v2/node/waku_metrics.nim, waku/v2/node/waku_node.nim, waku/v2/protocol/waku_filter.nim, waku/v2/protocol/waku_filter/client.nim, waku/v2/protocol/waku_filter/protocol.nim, waku/v2/protocol/waku_filter/protocol_metrics.nim, waku/v2/protocol/waku_filter/rpc_codec.nim
* No more subscription management in waku node module
* Simplified and renamed the expose APIs
=> feat(filter): split waku filter protocol into server and client

apps/chat2/config_chat2.nim, apps/chat2bridge/config_chat2bridge.nim, apps/wakubridge/config_bridge.nim, apps/wakunode2/config.nim, examples/v1/config_example.nim, tools/wakucanary/wakucanary.nim, waku/v1/node/config.nim, waku/v2/node/discv5/waku_discv5.nim, waku/v2/protocol/waku_swap/waku_swap_contracts.nim
Fixes for the following warnings:
> /Users/runner/work/nwaku/nwaku/apps/wakunode2/config.nim(439, 49) Warning: Deprecated since 1.5; TaintedString is deprecated [Deprecated]
=> fix: replace TaintedString type deprecated in nim 1.5

.gitmodules, apps/wakunode2/config.nim, waku.nimble
Nim's standard library `std/nre` loads at runtime (via `dlopen()`) the `libpcre.so.3`. 
This is not portable enough. This shared library name differs depending on the Linux distributions (e.g., in Linux Arch, the shared object is named `libpcre.so.0`).
For more context, check [this forum thread](https://forum.nim-lang.org/t/6008) and [this comment](https://forum.nim-lang.org/t/6008#:~:text=We%20could%20maybe%20adopt%20nim%2Dregex%20into%20the%20stdlib%20and%20deprecate%20both%20re%20and%20nre...)
=> fix: replace nim's std/nre with nim-regex library

apps/wakunode2/config.nim
The `wakunode2` binary was not starting due to an invalid _message retention policy_ configuration value. This fixes the bad regex (a copy-paste error 😅).
=> fix(wakunode2): fix message retention policy config validation regex

apps/wakunode2/config.nim, apps/wakunode2/wakunode2.nim, examples/v2/basic2.nim
In my road to support configuring `wakunode2` via environment variables, I bring this gardening PR 🌳
=> refactor(wakunode2): move configuration load logic to config module

tests/v2/test_enr_utils.nim, tests/v2/test_jsonrpc_waku.nim, tests/v2/test_peer_exchange.nim, tests/v2/test_utils_peers.nim, tests/v2/test_waku_bridge.nim, tests/v2/test_waku_discv5.nim, tests/v2/test_waku_dnsdisc.nim, tests/v2/test_waku_keepalive.nim, tests/v2/test_waku_peer_exchange.nim, tests/v2/test_waku_rln_relay.nim, tests/v2/test_waku_rln_relay_onchain.nim, tests/v2/test_wakunode.nim, tests/v2/test_wakunode_relay.nim, tests/v2/test_wakunode_rln_relay.nim
Test cases have been failing with `[LPError] Address in use` because most of the test cases' nodes were using port 60000. 
This is a temporary patch to decouple the test cases until we support getting a random port when initializing the waku node.
=> chore: randomize waku tcp ports in tests

tests/v2/testlib/testutils.nim
Previosly, the test cases were removed from the execution, and there was no way to notice if any test case was still commented. 
Now, the test cases marked to be skipped with an ✖️ will appear as `[SKIPPED]` in the execution logs.
=> feat(testlib): mark commented test cases as skipped

apps/wakunode2/config.nim, apps/wakunode2/wakunode2.nim, tests/all_tests_v2.nim, tests/v2/test_confutils_envvar.nim, tests/v2/test_envvar_serialization.nim, waku/common/confutils/envvar/defs.nim, waku/common/confutils/envvar/std/net.nim, waku/common/envvar_serialization.nim, waku/common/envvar_serialization/reader.nim, waku/common/envvar_serialization/utils.nim, waku/common/envvar_serialization/writer.nim
As part of the effort to conform to the [twelve-factor app](https://12factor.net/) principles. And regarding the configuration, [the III principle](https://12factor.net/config), this PR adds support to configure the `wakunode2` app via environment variables.
This PR resolves #1198 
------
Environment variables should be prefixed by the app's name. For example, to set the `--tcp-port` configuration we should call `wakunode2` binary as follows:
```bash
WAKUNODE2_TCP_PORT=65000 ./build/wakunode2
```
And this is the configuration precedence order (each item takes precedence over the item below it):
1. Commandline options/flags
2. Environment variables
3. Configuration file (currently, only TOML is supported)
4. Default value
This precedence order also aligns with other languages' de facto …
=> feat(wakunode2): support configuration via environment variables

apps/wakunode2/wakunode2.nim, apps/wakunode2/wakunode2_setup_rest.nim, apps/wakunode2/wakunode2_setup_rpc.nim, tests/v2/test_peer_manager.nim, tests/v2/test_peer_storage.nim, waku/v2/node/peer_manager/peer_manager.nim, waku/v2/node/peer_manager/peer_store/migrations.nim, waku/v2/node/peer_manager/peer_store/peer_storage.nim, waku/v2/node/peer_manager/peer_store/waku_peer_storage.nim
As part of the work done under #1293, the peer persistence database was decoupled from the message store database connection. This PR continues that work:
=> refactor(peer_manager): move peer_store under peer_manager module

Dockerfile
Broken by moving the `migrations_scripts` folder:
- https://github.com/status-im/nwaku/pull/1330
=> ci: fix path to migrations in Dockerfile

tools/README.md, tools/wakucanary/wakucanary.nim
* listening port for wakunode was hardcoded to 60000
* remove hardcoding and add a new cli flag `--node-port` to configure the port
=> chore(wakucanary): remove port hardcoding + add cli config

Makefile, apps/chat2/nim.cfg, apps/chat2bridge/nim.cfg, apps/wakubridge/nim.cfg, apps/wakunode2/nim.cfg, examples/v1/nim.cfg, examples/v2/nim.cfg, tests/nim.cfg, tools/wakucanary/nim.cfg
This is a gardening 🌳 and CI optimization PR:
This PR resolves #1313
----
There is some work pending to decouple the `NIM_PARAMS` as @s1fr0 pointed out in #1313, but this work should be taken in a separate piece for the sake of simplicity.
=> chore: build rln dependecies only when building v2

apps/chat2/chat2.nim, apps/wakunode2/wakunode2.nim, waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
This PR resolves #1222, the issue tracking the "imports rule violation". Previously, the code did not respect the [coding guide import rules](https://hackmd.io/5oIVOuQcSM2WKrnDLUPcpg#Importsexports). It imported an application module from a library (protocol, in this case) module.
I expect this PR to be very easy to review and merge. I have made some surgical changes trying to fix the dependency issue and reduce the impact in the PR that @staheri14 is working on to the maximum.
=> fix(rln-relay): remove dependency on applications' configuration

apps/chat2/chat2.nim, apps/chat2bridge/chat2bridge.nim, apps/wakubridge/wakubridge.nim, tests/v2/test_peer_exchange.nim, tests/v2/test_rest_relay_api.nim, tests/v2/test_waku_filter.nim, tests/v2/test_waku_lightpush.nim, tests/v2/test_wakunode_lightpush.nim, tests/v2/test_wakunode_store.nim, tests/v2/testlib/common.nim, tools/simulation/quicksim2.nim, waku/v2/node/jsonrpc/filter_api.nim, waku/v2/node/message_store/queue_store/index.nim, waku/v2/node/message_store/queue_store/queue_store.nim, waku/v2/node/message_store/sqlite_store/queries.nim, waku/v2/node/message_store/sqlite_store/sqlite_store.nim, waku/v2/node/waku_node.nim, waku/v2/protocol/waku_filter/client.nim, waku/v2/protocol/waku_filter/protocol.nim, waku/v2/protocol/waku_filter/rpc_codec.nim, waku/v2/protocol/waku_lightpush/client.nim, waku/v2/protocol/waku_lightpush/protocol.nim, waku/v2/protocol/waku_lightpush/rpc_codec.nim, waku/v2/protocol/waku_message.nim, waku/v2/protocol/waku_relay.nim, waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim, waku/v2/protocol/waku_store/client.nim, waku/v2/protocol/waku_store/message_store.nim, waku/v2/protocol/waku_store/pagination.nim, waku/v2/protocol/waku_store/protocol.nim
This is a gardening PR 🌳 A long-awaited refactoring to unify the `PubsubTopic` type and some default constants:
=> refactor: unify pubsub topic type and default value

tests/v2/test_message_cache.nim, tests/v2/test_rest_relay_api.nim, tests/v2/test_rest_relay_api_serdes.nim, waku/v2/node/jsonrpc/jsonrpc_utils.nim, waku/v2/node/rest/relay/api_types.nim, waku/v2/node/rest/relay/relay_api.nim, waku/v2/node/rest/relay/topic_cache.nim, waku/v2/node/waku_node.nim, waku/v2/protocol/waku_message.nim, waku/v2/protocol/waku_relay.nim, waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
* Resolves [comment1](https://github.com/status-im/nwaku/pull/1352/files#r1016901351) from #1352
* Resolves [comment2](https://github.com/status-im/nwaku/pull/1352/files#r1016897936) from #1352
Summary:
* General refactor using `PubsubTopic` and `ContentTopic` fields.
* Reuse default values for both fields introduced in #1352
* Removes `PubsubTopicString` and its usages.
* Enforce `defaultPubsubTopics` instead of `defaultTopics`
As a general note, which I think @LNSD agrees with me, we should be specific using `pubsub` or `content` instead of just using `topic`. As it may be confusing.
=> refactor: continue pubsub/content types started in #1352

Makefile, tests/v2/test_enr_utils.nim, tools/README.md, tools/networkmonitor/networkmonitor.nim, tools/networkmonitor/networkmonitor_config.nim, tools/networkmonitor/networkmonitor_metrics.nim, tools/networkmonitor/networkmonitor_utils.nim, tools/networkmonitor/nim.cfg, waku.nimble, waku/v2/utils/wakuenr.nim
Related to #1010
Description:
* Adds a tool that constantly tries to discover new peers in the network.
* It also tries to connect to them.
* See `README.md` for instructions and available metrics.
* Goal is to run a long lived instante of this tool, with a grafana dashboard we can monitor.
* Some metrics are exposed to prometheus to be fetched. Labels are constrained according do @jakubgs feedback.
* Other metrics, related to individual peers information are exposed directly via a rest api, ready to be accessed by i.e. Grafana. Note that these metrics are not exposed to prometheus.
Limitations:
* Naive implementation, with all data stored in memory. If the network scales to thousands of node the performance might be an issue.
* Routing table is not emptied.
Usage:
```console
$ make …
```
=> chore(networkmonitor): tool to discover and provide metrics on peers

tools/README.md, tools/networkmonitor/networkmonitor.nim, tools/networkmonitor/networkmonitor_config.nim, tools/networkmonitor/networkmonitor_metrics.nim
New feature for `networkmonitor`:
Notes:
* In the future we may want to count a message rate, measured in msg per unit of time. A simple counter will overflow at some point.
* Everything is in memory, which might be inviable depending on the number of content topics existing in the network. Note that there table has a limit. When exceeded, it removes the content topics with the least messages as protection.
Related #1010 
Depends on #1290
=> chore(networkmonitor): add metric listing content topics + messages

apps/wakunode2/config.nim, docs/operators/how-to/configure-store.md
Opening this suggestion as a PR, because I believe it should be done before the release if we agree upon it.
Disables `store` protocol by default.
One of the most important considerations for configuration is to have good defaults. I believe the default for `store` (which now implies actually persisting historical messages) should be `false`:
- the 95% use case for running a nwaku node is "run a `relay`-only node" - this should be the reasonable default
- this use case should not preclude such nodes from querying store nodes as a client. This is now always the case, even with `store` disabled.
- previously persisting messages would have been disabled by default (via the now deprecated `persist-messages` option)
- operators who upgrade their relay nodes and previously didn't care about or …
=> chore: disable store protocol by default

CHANGELOG.md
Adds the release notes for [Release v0.13.0](https://github.com/status-im/nwaku/milestone/5)
I believe everything necessary for the release has been merged already.
=> docs: release v0.13.0

apps/wakubridge/wakubridge.nim, apps/wakunode2/wakunode2_setup_rpc.nim
This PR resolves #1381 
This fix affects to `wakunode2` and `wakubridge` apps.
=> fix: store clients with `--store=false` does not install Store Client JSON-RPC API handlers

tests/v2/test_waku_store_rpc_codec.nim, waku/common/protobuf.nim, waku/v2/node/jsonrpc/jsonrpc_utils.nim, waku/v2/protocol/waku_store/client.nim, waku/v2/protocol/waku_store/protocol.nim, waku/v2/protocol/waku_store/rpc.nim, waku/v2/protocol/waku_store/rpc_codec.nim
To follow the [Waku store `2.0.0-beta4` protobuf definition](https://github.com/vacp2p/waku/blob/main/waku/store/v2beta4/store.proto):
This is a dependency of the _Make `waku_message.nim` comply with the protobuf definition_ task.
=> fix(store): waku store rpc codec support optional fields

waku/v2/node/waku_node.nim, waku/v2/protocol/waku_relay.nim
This refactoring of the Waku relay protocol was pending.
This is a dependency of the _Make `waku_message.nim` comply with the protobuf definition_ task.
=> refactor(relay): collocate relay protocol initialization logic

waku/common/protobuf.nim, waku/v2/protocol/waku_filter/client.nim, waku/v2/protocol/waku_filter/protocol.nim, waku/v2/protocol/waku_filter/rpc.nim, waku/v2/protocol/waku_filter/rpc_codec.nim
> ~~Waiting for https://github.com/vacp2p/waku/pull/9~~
To follow the [Waku filter `2.0.0-beta1` protobuf definition](https://github.com/vacp2p/waku/blob/main/waku/filter/v2beta1/filter.proto):
This is a dependency of the _Make `waku_message.nim` comply with the protobuf definition_ task.
=> fix(filter): waku filter rpc codec support optional fields

waku/v2/protocol/waku_lightpush/client.nim, waku/v2/protocol/waku_lightpush/protocol.nim, waku/v2/protocol/waku_lightpush/rpc.nim, waku/v2/protocol/waku_lightpush/rpc_codec.nim
> ~~Waiting for https://github.com/vacp2p/waku/pull/8~~
To follow the [Waku lightpush `2.0.0-beta1` protobuf definition](https://github.com/vacp2p/waku/blob/main/waku/lightpush/v2beta1/lightpush.proto):
This is a dependency of the _Make `waku_message.nim` comply with the protobuf definition_ task.
=> fix(lightpush): waku lightpush rpc codec support optional fields

apps/chat2/chat2.nim, tests/v2/test_waku_rln_relay.nim, tests/v2/test_wakunode_rln_relay.nim, waku/v2/protocol/waku_message.nim, waku/v2/protocol/waku_rln_relay/utils.nim
From this comment https://github.com/status-im/nwaku/pull/1386#discussion_r1025370353 related to the cyclic import issues in RLN:
> We need to break that cycle. And it should be done this way:
> 
> 1. Waku message's `proof` field should be changed to `seq[byte]` type. With that, we break the `waku_rln_relay -> waku_message` dependency.
> 2. Consequently, we'll have to decode that buffer within the `waku_rln_relay` module. The buffer should be decoded whenever you need to access the `proof` field.
> 
> Given the current RLN code layout, this last part will be cumbersome. But this is what we need.
=> refactor(rln): decouple rln types from waku message type

tests/v2/testlib/common.nim, tests/v2/waku_archive/test_driver_queue_query.nim, tests/v2/waku_archive/test_driver_sqlite_query.nim
To ensure that we are not testing only the "happy path" of the different queries, some randomness has been added to the test fixtures to verify the message ordering.
=> test(archive): randomize archive driver query test suites' fixtures

apps/wakunode2/config.nim, apps/wakunode2/wakunode2.nim, examples/v2/publisher.nim, examples/v2/subscriber.nim, tests/v2/test_peer_manager.nim, tests/v2/test_peer_store_extended.nim, tests/v2/test_waku_dnsdisc.nim, tools/wakucanary/wakucanary.nim, waku.nimble, waku/v2/node/jsonrpc/admin_api.nim, waku/v2/node/jsonrpc/store_api.nim, waku/v2/node/peer_manager/peer_manager.nim, waku/v2/node/peer_manager/waku_peer_store.nim, waku/v2/node/waku_node.nim, waku/v2/node/wakuswitch.nim, waku/v2/protocol/waku_peer_exchange/protocol.nim, waku/v2/protocol/waku_store/client.nim
=> refactor: reuse nim-libp2p peerstore + move peermanager logic

waku/common/sqlite/database.nim
This is a temporary patch until the SQLite library is improved. Making the SQLite manage a copy is far from ideal. Binding the parameters with this "destructor configuration" option,  implies that SQLite is making a copy of the buffer. This is inefficient. A more performant solution should be investigated.
From SQLite C documentation ([link](https://www.sqlite.org/c3ref/bind_blob.html)):
> The fifth argument to the BLOB and string binding interfaces controls or indicates the lifetime of the object referenced by the third parameter. These three options exist: 
> 1. A destructor to dispose of the BLOB or string after SQLite has finished with it may be passed. It is called to dispose of the BLOB or string even if the call to the bind API fails, except the destructor is not called if the …
=> fix(archive): patch the sqlite driver to solve results inconsistencies

waku/v2/protocol/waku_store/protocol.nim, waku/v2/protocol/waku_store/protocol_metrics.nim
These metrics were moved to the `waku_archive_` namespace. Removing those that are obsolete.
=> chore(store): remove obsolete metrics and error labels

waku/v2/protocol/waku_archive/archive.nim
Reverting the changes done in the Waku archive durations metrics since the `nim-metrics` template rounds the duration to seconds. We need sub-second precision.
=> fix(archive): restore query and insert metrics duration precision

tests/all_tests_v2.nim, tests/v2/test_circuitrelay.nim, tests/v2/test_waku_switch.nim, waku/v2/node/wakuswitch.nim
Closes #1402 
Enables two features on the nwaku switch and tests each functionality:
nwaku can serve as a libp2p circuit-relay server. Using a nwaku node as a circuit-relay server is an intermediate step within the NAT hole punching procedure. See [this document](https://status-im.github.io/nim-libp2p/docs/circuitrelay/) for more on circuit relay.
Peers can request dialbacks from nwaku nodes to verify that they are publicly reachable. This is the first step before attempting a NAT hole punching procedure. AutoNAT is also a requirement towards: https://github.com/waku-org/nwaku/issues/1206
For now I don't see a good reason to make either protocol configurable. A node can enable circuit relay and AutoNAT with default configuration by default.
See [this …
=> feat: enable AutoNAT and libp2p circuit relay

tests/v2/test_waku_bridge.nim
PR to partially address https://github.com/waku-org/nwaku/issues/1357.
This fix seems to at least make things better. If we still get intermittent failures, we can consider reworking this test or coming up with a different Future/Result mechanism that will circumvent the need for async sleeps. Let's monitor in conjunction with other CI tests.
=> fix: waku bridge test timing

apps/wakunode2/wakunode2.nim
* Handles `sigsegv` signal.
* Shuts down wakunode gracefully.
Note that the stacktrace won't be printed in `release` mode (default one in `make wakunode2`) but it can be enabled as follows. See `--stacktrace:on --linetrace:on`:
```
nim c --out:build/wakunode2 -d:chronicles_log_level=TRACE --verbosity:0 --hints:off -d:git_version:"v0.13.0-28-g3474be" --stacktrace:on --linetrace:on apps/wakunode2/wakunode2.nim
```
Related #1391
=> chore(wakunode): handle sigsegv signal

metrics/waku-fleet-dashboard.json
Some notes on bitrate calculation:
* `nim-libp2p` has a metric enabled by default with the `libp2p_network_bytes_total` in/out.
* The bitrate is divided by 1000000 to get MB and multiplied by 8, to get Mbits
* Using Grafana `increase` over `[15m]` we calculate the tx/rx Mb in this time.
* Then we divide this by 15*60=900 seconds, to get the final `Mbps`.
=> chore(metrics): add plot with traffic + update to latest grafana

tests/v2/test_peer_manager.nim, waku/v2/node/peer_manager/peer_manager.nim, waku/v2/node/peer_manager/waku_peer_store.nim, waku/v2/node/wakuswitch.nim
Useful for debugging. A reachable node should have some `Inbound` peers.
```console
$ curl localhost:8003/metrics | grep waku_connected_peers
waku_connected_peers{direction="Outbound"} 12.0
waku_connected_peers_created{direction="Outbound"} 1669729760.0
```
Related https://github.com/waku-org/nwaku/issues/1206
=> feat(peerstore): store peer direction

waku/v2/node/jsonrpc/hexstrings.nim, waku/v2/node/jsonrpc/jsonrpc_utils.nim
Turns out waku v2 imports waku v1
This PR fixes that.
```sh
$ cp waku/v1/node/rpc/hexstrings.nim waku/v2/node/jsonrpc/
$ # do some things
$ diff waku/v1/node/rpc/hexstrings.nim waku/v2/node/jsonrpc/hexstrings.nim
```
```diff
23d22
<     * Topic
29c28
<   ../../protocol/waku_protocol
---
>   ../../../whisper/whisper_types
94,97d92
< func isValidTopic*(value: string): bool =
<   # 4 bytes for Topic plus 1 byte for 0x prefix
<   result = value.isValidHexData(10)
< 
137,139d131
< proc `%`*(value: waku_protocol.Topic): JsonNode =
<   result = %("0x" & value.toHex)
< 
157,159d148
< proc toTopic*(topic: string): waku_protocol.Topic {.inline.} =
<   hexToByteArray(topic[2 .. ^1], result)
< 
205,211d193
< 
< proc fromJson*(n: JsonNode, argName: string, result: var waku_protocol.Topic) =
< …
```
=> Decouple waku v2 from waku v1

apps/wakunode2/wakunode2.nim
* Import `libbacktrace` and prints `getBacktrace()` after a `SIGSEGV`.
* Note that this requires `--debugger:native` which is enabled by default [but in mac](https://github.com/waku-org/nwaku/blob/master/config.nims#L51).
* This should help debug segfaults, providing a more complete stacktrace.
=> chore: print getBacktrace() after sigsegv

Dockerfile, Makefile, waku/v2/protocol/waku_rln_relay/rln.nim
Splitting the Makefile/Dockerfile changes in a separate PR from #1385:
+ We are keeping `RLN=true` for local development purposes.
+ The `test2-experimental` CI job is already passing the `EXPERIMENTAL=true` env variable.
=> chore(build): simplify project makefile and update dockerfile

Dockerfile, ci/Jenkinsfile.prs, ci/Jenkinsfile.release
Recently the `EXPERIMENTAL` flag was added to the `Makefile` to compile the experimental features into the nwaku node binary conditionally.
-------
The problem is that we have been deploying EXPERIMENTAL images to the production/test fleets. Causing the fleets to fail with the following error:
```
could not load: /app/vendor/zerokit/target/release/librln.so
```
=> ci(jenkins): support experimental flag in the pr and release pipelines

Dockerfile, Makefile, ci/Jenkinsfile.release
With the new `EXPERIMENTAL` build argument, as the `librln` artifacts are not built, the docker image build fails with the following error:
```
COPY failed: stat app/vendor/zerokit/target/release/librln.so: file does not exist
```
=> ci(jenkins): split dockerfile into production and experimental stages

waku/v2/protocol/waku_rln_relay/protocol_types.nim, waku/v2/protocol/waku_rln_relay/utils.nim
Root validation was disabled due to intermittent connections with ethereum nodes, which was preventing nodes from updating their local merkle tree of memberships. Since the underlying issue has been resolved, we can re-enable the check.
- fix(rln-relay): enable root validation
- fix(rln-relay): unused import
=> chore(rln-relay): re-enable root validation

ci/Jenkinsfile.release
Fixes typo in Jenkins release which prevents deployment with Experimental features enabled.
=> fix(jenkins): fix typo

Makefile
In the past 6 months, the simulation binaries have not been used nor updated. We are building them as part of the `v2` target four times every push in the CI pipelines consuming extra time.
=> ci: don't build waku v2 simulation binaries

.github/workflows/ci.yml
dorny/paths-filter needs the repo to be checked out for push events
=> fix(ci): repo not cloned on startup

waku/v2/node/peer_manager/peer_manager.nim, waku/v2/node/waku_node.nim
Refactors as part of the networking roadmap.
* Remove metric label `waku_peers_errors.inc["conn_init_failure"]` as its duplicated from `waku_peers_dials.inc(labelValues = ["failed"])`
* Unify `dialPeer` functions where all end up calling the same one but with a different input: `peerInfo`, `peerId`.
* Remove `connectToNode`, as its duplicated from `dialPeer`.
* Merge all two `connectToNodes` into a single one.
* Modify `DefaultDialTimeout` to 10 seconds.
=> chore(networking): unify dialpeer functions

tests/v2/test_jsonrpc_waku.nim, waku/v2/node/jsonrpc/admin_api.nim
Closes #1469
Summary:
* When trying to connect to a i) peer not listening or ii) malformed multiaddress via the RPC, the api was returning `result:true` which is missleading since no connection was made.
* Moreover `connectToNodes` was used with a timeout but `dialPeer` already has a timeout. And note that `connectToNodes` discards the dialing result, so we can't know if the connection failed.
* This PR uses `dialPeer` instead and raises an exception if we can't connect to the peer and adds a unit test for the bug it fixes.
* Relevant for `wakurtosis` testing efforts.
=> fix(rpc): return error if peer cant be connected

waku/v2/node/peer_manager/peer_manager.nim
- Instead of awaiting on each `dialPeer` individually, this pr triggers all dials, stores the futures in an array and then waits for the futures to be completed. This substantially decreases the time it takes for a nwaku node to reach a reasonable number of connections.
- In several runs, attempting to connect **12 peers** with `connectToNodes` I could verify that the time it tool to connect to all of them decreased from 43/44 seconds to 4/5 seconds. Note that it was tested against our fleets
=> refactor(networking): wait for all futures together in connectToNodes

waku/v2/node/waku_node.nim, waku/v2/node/wakuswitch.nim
Closes https://github.com/waku-org/nwaku/issues/1206
**Summary:**
This PR integrates the brand new `AutonatService` added in `nim-libp2p`. This service runs in the background asking other outbound connected peers to dial us, informing us if we are `Reachable` or `NotReachable` by them.
* Reachability state is logged every 2 minutes: `Reachable`/`NotReachable`.
* `nim-libp2p` metric can be reused. See:
```
libp2p_autonat_reachability_confidence{reachability="Reachable"} 1.0
libp2p_autonat_reachability_confidence{reachability="NotReachable"} 0.0
```
Done:
Note that this is an experimental feature that was never tested in `nim-libp2p` in a production environment, but it only impact logs and one metric, so its impact is really low.
=> feat(networking): integrate autonat service to request if we are dialable

tests/v2/waku_archive/test_waku_archive.nim, waku/v2/protocol/waku_archive/archive.nim, waku/v2/protocol/waku_archive/common.nim
Specifying and implementing the new Waku store protocol will take some time. We have implemented an intermediate limit to mitigate DoS caused by queries with a content topics list greater than 10. 
**:warning: The Waku store v2 client will perceive this as an `INVALID_CURSOR` error.**
This issue resolves #1292
=> feat(archive): respond with error on more than 10 content topics query

apps/chat2/chat2.nim
Warns the user when chat2 has rln-relay options passed in, but was not compiled with the appropriate rln flags. Addresses https://github.com/waku-org/nwaku/issues/1201
=> fix(chat2): warn when rln relay is enabled but not compiled

CHANGELOG.md
Adds the release notes for [Release v0.14.0](https://github.com/status-im/nwaku/milestone/6)
I believe everything necessary for the release has been merged already. I will do a last sanity check before merging this PR to close the last open issues.
=> docs: release v0.14.0

tests/test_helpers.nim, tests/v2/test_peer_manager.nim, tests/v2/test_peer_store_extended.nim, waku/v2/node/discv5/waku_discv5.nim, waku/v2/node/peer_manager/peer_manager.nim, waku/v2/node/peer_manager/waku_peer_store.nim, waku/v2/node/waku_node.nim
Closes https://github.com/waku-org/nwaku/issues/1414
**Summary:**
After failing to dial a peer, it adds a backoff to it so that we don't attempt to dial the same peer again during some time. The time to wait depends on the amount of consecutive failures, calculated with the following formula:
```
initialBackoffInSec*(backoffFactor^(failedAttempts-1))
```
Note that `initialBackoffInSec` and `backoffFactor` are configurable values that allow to configure how aggressive the backoffs are. Using `initialBackoffInSec=120` and `backoffFactor=4` the times to wait would be:
```
120s, 480s, 1920, 7680s
```
This PR helps nodes to rapidly increase their number of connections, since less time is wasted in trying to connect to nodes that fail. This improvement is even more noticeable in networks whith …
=> feat(networking): add backoff period after failed dial

waku/v2/protocol/waku_archive/driver/sqlite_driver/queries.nim
A small optimization for the "find messages by" query.
Source: https://stackoverflow.com/a/3074846/1099999
> The OR operator needs a much more complex evaluation process than the IN construct because it allows many conditions, not only equals like IN.
Source: https://stackoverflow.com/a/73079261/1099999
> IN may be significantly faster. E.g. table with ~23M rows.
> OR -> Execution Time: 4540.829 ms
> IN -> Execution Time: 855.743 ms
With 20 million message archive sizes, I think this query optimization will have a significant impact helping us to squeeze the Sqlite lemon a little bit more 🍋
=> refactor(archive): sqlite query optimization. replace or-ed equal conditions list with in-list

tests/v2/waku_archive/test_driver_queue_query.nim, tests/v2/waku_archive/test_driver_sqlite_query.nim, tests/v2/waku_archive/test_waku_archive.nim, waku/v2/protocol/waku_archive/archive.nim, waku/v2/protocol/waku_archive/driver/queue_driver/queue_driver.nim, waku/v2/protocol/waku_archive/driver/sqlite_driver/sqlite_driver.nim
This regression was introduced during the Waku archive and the Waku store code split. The Waku archive test did not cover the query chain responses. And the regression was not detected by the Status app since they only use the forward pagination.
This PR resolves #1502 regression.
=> fix(archive): reverse the db query results in the waku archive front-end

apps/wakunode2/wakunode2.nim, tests/v2/test_peer_manager.nim, tests/v2/test_peer_store_extended.nim, waku/v2/node/jsonrpc/store_api.nim, waku/v2/node/peer_manager/peer_manager.nim, waku/v2/node/peer_manager/waku_peer_store.nim, waku/v2/node/waku_node.nim, waku/v2/protocol/waku_peer_exchange/protocol.nim, waku/v2/protocol/waku_store/client.nim
Related https://github.com/waku-org/nwaku/issues/1461
Background:
* Until we further decentralise the waku network, service peers (peers supporting service protocols such as store, lightpush, etc) have to be treated differently than relay peers.
* For example, looking at this from the store protocol perspective, since we don't have any consensus on the data that is stored, there is some level of trust on the node we are quering. So in most cases we wan't to specify the nodes that are used for these services. Note that this feature already exists, but this PR fixes some of the issues around this.
Summary of changes:
* This PR adds the concept of `serviceSlots`, which contains a set of "slotted" or "preferred" peers for the services, or in other words, any protocol that is not …
=> feat(networking): add service slots to peer manager

tests/v2/test_jsonrpc_waku.nim, waku/v2/node/jsonrpc/admin_api.nim
Closes https://github.com/waku-org/nwaku/issues/1505
Summary:
* `get_waku_v2_admin_v1_peers` was crashing the node when a given peer contained no multiaddress (`[0]` out of bound)
* Add test case reproducing the error.
* Fix by checking the size to avoid accesing `[0]` in an empty seq.
=> fix(rpc): rpc crashes when a peer has no addresses

.gitmodules
Removes kilic's rln submodule since we've switched entirely over to zerokit.
=> fix(rln): remove kilic submodule

waku/v2/protocol/waku_store/rpc_codec.nim
This regression was introduced during the Waku archive and the Waku store code split.
This PR potentially resolves issue #1514
=> fix(store): set store rpc codec pagesize type to uint64

tests/v2/test_peer_manager.nim, waku/v2/node/peer_manager/peer_manager.nim
Closes https://github.com/waku-org/nwaku/issues/1504
**Summary**: Every `PrunePeerStoreInterval` the peerstore is pruned, removing peers from it if we have exceeded its capacity. The criteria is the following: peers that failed in the past are removed first, and if we are still over the capacity, not connected peers are removed.
Other changes:
* New metric to track peerstore size.
* Asserts that capacity > maxConnections, fails otherwise.
=> feat(networking): prune peers from peerstore exceeding capacity

apps/wakunode2/config.nim, apps/wakunode2/wakunode2.nim, waku/v2/node/waku_node.nim, waku/v2/node/wakuswitch.nim
* add safe default values for peer-store-capacity. If not set, just take 1.25 times the max number of connections.
* the lack of this safe default value currently breaks the current infra config.
=> fix: add safe default values for peer-store-capacity

tests/v2/test_waku_filter.nim
Partially addresses https://github.com/waku-org/nwaku/issues/1357
Currently the most common cause for test failures in the `CI` pipeline, seems to be related to filter tests.
This is caused by a race condition between a subscribing client and a publishing filter service node. In each case I looked at, the race condition was a matter of ~100ms or less, so extra time padding should improve this.
Longer term this race condition should be avoided by using [the improved filter specification](https://github.com/waku-org/nwaku/issues/1357) and waiting for the subscribe transaction to be complete.
NB: I think .editorconfig changed quite a lot on this one! Please ignore whitespace to see the diff.
=> fix: improve filter test race condition

waku/v2/node/waku_node.nim, waku/v2/utils/time.nim
Hopefully an easy fix for https://github.com/waku-org/nwaku/issues/1394
Improves relay trace logging on publishing and receiving a message, to log:
- a hash of the message
- publish/arrival timestamp
- pubsubTopic
@Daimakaimura my understanding is that this will cover your needs? Anything else that would be required/nice to have?
This will result in the following example trace log on the relaying node:
```
TRC 2023-02-01 14:48:52.270+02:00 waku.relay received                        topics="waku node" tid=22467 file=waku_node.nim:310 pubsubTopic=/waku/2/default-waku/proto hash=0x1220b9cb650d6af10c34d9d882a609d9aa6d506b0831f8f01a8e27be3c665d889974 receivedTime=1675255732000000000
```
and on the publishing node
```
TRC 2023-02-01 14:48:52.270+02:00 waku.relay published …
```
=> chore: add better e2e trace logging for relay

tests/v2/00002_test.up.sql
=> chore: remove unused test fixture file

apps/chat2/chat2.nim, apps/chat2/config_chat2.nim, apps/wakunode2/config.nim, apps/wakunode2/wakunode2.nim, examples/v2/publisher.nim, examples/v2/subscriber.nim, tests/v2/test_waku_switch.nim, tools/wakucanary/wakucanary.nim, waku/v2/node/waku_node.nim, waku/v2/node/wakuswitch.nim
As a follow up to #1522, this method is more surgical, and does not make use of global variables (sort of).
Makes the rng required by all the procs which consume it, except for WakuNode.new(), because refactoring this will require updating a lot of tests, which can be done in a follow up PR.
=> fix(rng): create rng only within isMainModule blocks

apps/chat2/chat2.nim, tests/all_tests_v2.nim, tests/v2/test_jsonrpc_waku.nim, tests/v2/test_utils_compat.nim, tests/v2/test_waku_bridge.nim, tests/v2/test_waku_noise.nim, tests/v2/test_waku_noise_sessions.nim, tools/wakucanary/wakucanary.nim, waku/v2/node/jsonrpc/jsonrpc_utils.nim, waku/v2/node/jsonrpc/private_api.nim, waku/v2/protocol/waku_message.nim, waku/v2/utils/compat.nim, waku/v2/utils/noise.nim
The `waku_payload` is an odd module inside the `node` module. This is an intermediate and temporary refactoring to isolate the backward compatibility code.
This is another gardening PR 🪴, part of the upcoming MUID implementation.
=> refactor(utils): moved noise/compat payload encryption code to utils

examples/v2/publisher.nim, examples/v2/subscriber.nim, tests/v2/test_wakunode_relay.nim, waku/v2/protocol/waku_relay.nim
**Summary**
* Add new libp2p validator to `WakuRelay`, so that messages that are not `WakuRelay` (aka fail to decode into pb) are rejected and not further gossiped.
* Add unit test testing this new feature.
=> feat: add WakuMessage validation in gossipsub

tests/v2/test_wakunode_relay.nim, waku/v2/node/waku_node.nim, waku/v2/protocol/waku_relay.nim
A code cleanup and API improvements PR for the Waku Relay protocol implementation.
This PR is a dependency for the upcoming JSON-RPC/Rest improvement PRs.
=> refactor(relay): improve wakuy relay api

apps/wakunode2/wakunode2.nim, tests/v2/test_waku_peer_exchange.nim, tests/v2/test_wakunode.nim, waku/v2/node/peer_manager/waku_peer_store.nim, waku/v2/node/waku_node.nim, waku/v2/protocol/waku_peer_exchange/protocol.nim, waku/v2/protocol/waku_peer_exchange/rpc.nim, waku/v2/protocol/waku_peer_exchange/rpc_codec.nim
Last item to close https://github.com/waku-org/nwaku/issues/1463
Some refactoring in the px protocol + more tests + moving the "what to do with the peers we got via px" logic to the application. Some discussions started in https://github.com/waku-org/nwaku/issues/1463 and this prepares the ground for https://github.com/waku-org/nwaku/issues/1521.
**Summary of changes**:
* Improve error handling using `Result` and catch exceptions (mainly `readLp` and `writeLp` since can raise an Exception if the stream is prematurely closed)
* No longer handle the px response on the protocol. The response should be handled by the application, which now adds the peers to the peerstore intead of trying to connect to them.
* Changes `respond` proc, reusing the existing connection instead of attempting to …
=> refactor(px): refactor peer exchange + tests

apps/wakubridge/message_compat.nim, apps/wakubridge/wakubridge.nim, tests/all_tests_v2.nim, tests/all_tests_wakubridge.nim, tests/v2/test_namespacing_utils.nim, tests/wakubridge/test_message_compat.nim, tests/wakubridge/test_wakubridge.nim
During the JSON-RPC, Rest APIs and the Waku message refactorings, I found an unexplainable and unrelated failure in the Wakubridge tests. This PR solves this issue:
=> refactor(wakubridge): split message compatibility from wakubridge

tests/v2/test_peer_exchange.nim, tests/v2/test_rest_relay_api.nim, tests/v2/test_wakunode_rln_relay.nim, tests/v2/wakunode_jsonrpc/test_jsonrpc_relay.nim, waku/v2/node/waku_node.nim
As part of the scaling initiative, requirements have changed. This PR removes the `wakunode2`'s implicit subscription to the default pub-sub topic. If the CLI argument is not specified, the node will subscribe to the default pub-sub topic.
This PR resolves #1545.
=> fix(node): remove subscription to waku default network topic (#1545)

tests/v2/test_peer_exchange.nim, tests/v2/test_peer_manager.nim, tests/v2/test_waku_keepalive.nim, tests/v2/test_waku_rln_relay.nim, tests/v2/test_waku_rln_relay_onchain.nim, tests/v2/test_wakunode_filter.nim, tests/v2/test_wakunode_lightpush.nim, tests/v2/test_wakunode_rln_relay.nim, tests/v2/waku_relay/test_wakunode_relay.nim, tests/v2/waku_store/test_resume.nim, tests/v2/waku_store/test_wakunode_store.nim, tests/v2/wakunode_jsonrpc/test_jsonrpc_debug.nim, tests/v2/wakunode_jsonrpc/test_jsonrpc_filter.nim, tests/v2/wakunode_jsonrpc/test_jsonrpc_relay.nim, tests/v2/wakunode_jsonrpc/test_jsonrpc_store.nim
This PR should help mitigate the _"LPError: Address already in use"_ issues reported in #1357.
From [this](https://discord.com/channels/864066763682218004/865466680129880074/1052594544400678983) conversation at discord: 
> FWIW. The issue could be solved by allowing the Waku node/switch to be configured with a `/ip4/0.0.0.0/tcp/0` (then it would look for a free TCP/UDP port and bind to it). Then each test case would use its own TCP port, avoiding the "port reuse".
=> fix(tests): do not specify port number

apps/wakubridge/wakubridge.nim, apps/wakunode2/wakunode2.nim, apps/wakunode2/wakunode2_setup_rpc.nim, tests/v2/test_waku_keepalive.nim, tests/v2/waku_relay/test_waku_relay.nim, tests/v2/waku_relay/test_wakunode_relay.nim, tests/v2/wakunode_jsonrpc/test_jsonrpc_debug.nim, tests/v2/wakunode_jsonrpc/test_jsonrpc_filter.nim, tests/v2/wakunode_jsonrpc/test_jsonrpc_relay.nim, waku/v2/node/jsonrpc/filter/handlers.nim, waku/v2/node/jsonrpc/store/handlers.nim, waku/v2/node/peer_manager/peer_manager.nim, waku/v2/protocol/waku_peer_exchange/protocol.nim, waku/v2/protocol/waku_store/client.nim, waku/v2/protocol/waku_store/protocol.nim
Another 🪴 PR. Removed the unused import warnings (except the `chronicles` one).
=> fix: remove unused imports

waku/v2/protocol/waku_relay.nim
The existing `messageIdProvider` in nwaku uses `Multihash` format, while in go-waku straightforward `sha256` hashes are used. This implies that message IDs (e.g. in the seen cache, in control messages, etc.) do not match between go-waku and nwaku, resulting in a lot of duplication and unnecessary control messages.
Since nwaku is more easily upgraded than go-waku, this quickfix changes nwaku message IDs to match those of go-waku.
A longer term solution is to specify a hashing scheme in an RFC.
=> fix: change message ID provider to match go-waku

tests/v2/test_peer_manager.nim, waku/v2/node/peer_manager/peer_manager.nim
* Fixes flaky test in peer manager reported by @LNSD.
* Was removing an element from a table while iterating it.
* Before the issue showed up every 20 runs.
* With the fix, after 100 runs I couldn't reproduce it, should be solved.
=> fix(networking): fix flaky peerstore test

CHANGELOG.md
Adds the changelog for [Release v0.15.0](https://github.com/status-im/nwaku/milestone/7)
@LNSD I have tentatively added release notes for the Relay RPC changes, in case the corresponding PR is merged before the release. If not, we can simply remove these items from the release notes before cutting the release.
Note the final release notes will include Upgrade Instructions:
- for the Relay RPC API breaking change
- to explain the impact of changing how message IDs are computed (e.g. running older versions of nwaku on the same network will cause duplication)
=> docs: release v0.15.0

tests/all_tests_common.nim, tests/common/test_protobuf_validation.nim, tests/v2/test_waku_noise_sessions.nim, waku/common/protobuf.nim, waku/v2/protocol/waku_filter/rpc_codec.nim, waku/v2/protocol/waku_lightpush/rpc_codec.nim, waku/v2/protocol/waku_message/codec.nim, waku/v2/protocol/waku_message/message.nim, waku/v2/protocol/waku_store/rpc_codec.nim
At this moment, no protobuf max field length validation is performed. In 14/WAKU2-MESSAGE RFC, no maximum length for the `content_topic` attribute is specified. This is potentially problematic. Additionally, this is not supported by _libp2p's minprotobuf_ implementation.
This requirement motivates the present PR to add support in the `common/protobuf` wrapper module for validating the protobuf field length.
Note that the validation is only executed during the deserialization phase. The content topic length is assumed to be valid in the serialisation phase.
Initially, the minprotobuf's `getRequirefField` was also considered. But as there isn't a max length validation equivalent, for homogeneity, I discarded its usage and added also the "required field missing" error variant.
=> feat(protobuf): added error wrappers for invalid length validation

apps/chat2/chat2.nim, tests/v2/test_waku_rln_relay.nim, waku/v2/protocol/waku_rln_relay/rln/rln_interface.nim, waku/v2/protocol/waku_rln_relay/rln/wrappers.nim
Changes and optimizations included in zerokit's bump - https://github.com/vacp2p/zerokit/compare/005393d...master
This included ffi changes -
```diff
-proc hash*(ctx: ptr RLN,
-           input_buffer: ptr Buffer,
-           output_buffer: ptr Buffer): bool {.importc: "hash".}
+#-------------------------------- Hashing utils -------------------------------------------
+
+proc sha256*(input_buffer: ptr Buffer,
+             output_buffer: ptr Buffer): bool {.importc: "hash".}
+
+proc poseidon*(input_buffer: ptr Buffer,
+               output_buffer: ptr Buffer): bool {.importc: "poseidon_hash".}
+## it hashes (poseidon) the plain text supplied in inputs_buffer
+## this proc is used to compute the identity secret hash, and external nullifier
+## inputs_buffer holds the hash input as a byte …
```
=> chore(rln-relay): bump zerokit and update ffi

tests/common/test_base64_codec.nim, tests/v2/wakunode_jsonrpc/test_jsonrpc_relay.nim, tests/v2/wakunode_rest/test_rest_relay.nim, tests/v2/wakunode_rest/test_rest_relay_serdes.nim, waku/common/base64.nim, waku/v2/node/jsonrpc/message.nim, waku/v2/node/jsonrpc/relay/handlers.nim, waku/v2/node/rest/base64.nim, waku/v2/node/rest/relay/types.nim
This PR includes code and API cleanup and adds tests covering the `base64` module. A typical gardening PR 🪴
> **Note**
> The v0.15.0 is working as expected: **Payload must be encoded using regular base64 (with padding).**
----
Regarding the RFC discussion about the JSON-RPC message payload encoding using base64 ([here](https://github.com/vacp2p/rfc/pull/574#issuecomment-1440393179)):
> Ok... There was some confusion on my side: I thought the payload was encoded in base64 URL-friendly format without padding. This is not what was happening. It is encoded in regular base64 with padding. It seems I implemented it the right way from the very beginning.
> 
> So the v0.15.0 is working as expected: Payload must be encoded using regular base64 (with padding).
> 
> I have updated this PR so it is …
=> fix(jsonrpc): use padded-base64 for payload encoding

waku/v2/node/waku_node.nim
Logs the peer ID when trace logging relay messages.
Requested by Wakurtosis as a requirement/improvement when scraping logs.
=> chore: log node peer ID with relay trace logging

apps/chat2/chat2.nim, apps/chat2bridge/chat2bridge.nim, apps/wakubridge/wakubridge.nim, tests/v2/test_peer_manager.nim, tests/v2/wakunode_jsonrpc/test_jsonrpc_admin.nim, tests/v2/wakunode_jsonrpc/test_jsonrpc_filter.nim, tests/v2/wakunode_jsonrpc/test_jsonrpc_store.nim, waku/v2/node/peer_manager/peer_manager.nim, waku/v2/node/waku_node.nim, waku/v2/protocol/waku_swap/waku_swap.nim
Changes:
* Uses `addServicePeer` where needed
* Removes unused code.
* Removes `proto` from `addPeer`. From now on that is populated by `Identify`.
* Move to `TRACE` adding peer to peermanager, since it was quite spammy.
* Split `connectToRelayPeers` into function + loop.
=> refactor(networking): peermanager refactor and cleanups

.gitmodules
Remove unused submodule `news`. This was an old "Nim Easy Websockets" library, which has since been replaced by `nim-websock`
=> chore: removed unused submodule

waku/v2/protocol/waku_message/codec.nim, waku/v2/protocol/waku_message/message.nim
The current PR introduces support for the `meta` attribute:
It depends on the following RFC and Protobuf PRs:
- https://github.com/vacp2p/rfc/pull/573
- https://github.com/vacp2p/waku/pull/13
=> feat(message): added meta attribute to waku message

tests/common/test_base64_codec.nim
Based on [@alrevuelta's comment](https://github.com/waku-org/nwaku/issues/1564#issuecomment-1432666277), I have extended the test coverage for the `base64` common module.
This PR rules out the base64 encoding/decoding functions from the equation. The issue could be in the JSON-RPC parsing itself. A deeper investigation is necessary.
=> tests(common): extend base64 test coverage

tests/all_tests_v2.nim, tests/v2/test_waku_message_digest.nim, tests/v2/testlib/waku2.nim, waku/v2/protocol/waku_message.nim, waku/v2/protocol/waku_message/digest.nim
This PR adds support to calculate a Waku messages' hash following the [14/WAKU2-MESSAGE](https://rfc.vac.dev/spec/14/#deterministic-message-hashing) RFC:
=> feat(message): added waku message deterministic hashing

tests/v2/waku_filter_v2/test_waku_filter_v2.nim, waku/v2/protocol/waku_filter_v2.nim, waku/v2/protocol/waku_filter_v2/common.nim, waku/v2/protocol/waku_filter_v2/protocol.nim, waku/v2/protocol/waku_filter_v2/protocol_metrics.nim, waku/v2/protocol/waku_filter_v2/rpc.nim, waku/v2/protocol/waku_filter_v2/rpc_codec.nim
This is a first increment towards the server-side implementation of the filter protocol changes proposed in https://github.com/vacp2p/rfc/pull/562 with wire protocol in https://github.com/vacp2p/waku/pull/16.
It only covers basic subscriber request handling.
Note that this is still an incomplete feature and isolated in code. Once feature-complete, the old `filter` implementation will be removed and replaced by this one (with simultaneous merging of the RFC). Test cases are also still mainly focused on happy-path cases, to keep this increment as simple as possible.
The major outstanding features are:
Dogfooding can likely start without a client implementation in nwaku, as nwaku is most often configured as a service node only.
Further steps, roughly in order:
=> feat: new filter protocol increment - subscribe request handling

waku/v2/node/jsonrpc/admin/handlers.nim, waku/v2/node/jsonrpc/debug/client.nim, waku/v2/node/jsonrpc/debug/handlers.nim, waku/v2/node/jsonrpc/filter/client.nim, waku/v2/node/jsonrpc/filter/handlers.nim, waku/v2/node/jsonrpc/message.nim, waku/v2/node/jsonrpc/relay/client.nim, waku/v2/node/jsonrpc/relay/handlers.nim, waku/v2/node/jsonrpc/store/client.nim, waku/v2/node/jsonrpc/store/handlers.nim, waku/v2/node/jsonrpc/store/types.nim, waku/v2/node/peer_manager/peer_manager.nim, waku/v2/node/rest/debug/handlers.nim, waku/v2/node/rest/debug/types.nim, waku/v2/node/rest/relay/client.nim, waku/v2/node/rest/relay/handlers.nim, waku/v2/node/rest/relay/topic_cache.nim, waku/v2/protocol/waku_swap/waku_swap.nim
From discord (@arnetheduck):
> hm, looks like some waku imports are a bit off - take for example https://github.com/waku-org/nwaku/blob/master/waku/v2/node/peer_manager/peer_manager.nim#L15 - the ../.. works because of an unfortunate quirk in Nim when compiling a top-level project in a suitable folder, but the file is actually not available in that location - instead, it actually resides in ../../../../waku/v2/protocol/waku_relay (or simply ../protocol/waku_relay) preventing the use of the module from "outside", ie when importing waku in a stand-alone application - I think this might be the leftover of some refactoring? cc @LNSD 
This PR aims to fix this issue.
=> fix: clean and normalize module imports

apps/wakunode2/wakunode2.nim, examples/v2/publisher.nim, examples/v2/subscriber.nim, tests/v2/test_waku_discv5.nim, tests/v2/test_waku_enr.nim, tests/v2/test_waku_peer_exchange.nim, tools/networkmonitor/networkmonitor.nim, waku/v2/node/waku_node.nim, waku/v2/protocol/waku_discv5.nim, waku/v2/protocol/waku_enr.nim
This is part of the ENR and discovery refactoring groundworks for static sharding:
=> refactor(enr): node capabilities code clean up and reorganization

tests/v2/test_peer_manager.nim, tests/v2/test_peer_storage.nim, tests/v2/test_peer_store_extended.nim, waku/v2/node/jsonrpc/admin/handlers.nim, waku/v2/node/peer_manager/peer_manager.nim, waku/v2/node/peer_manager/peer_store/peer_storage.nim, waku/v2/node/peer_manager/peer_store/waku_peer_storage.nim, waku/v2/node/peer_manager/waku_peer_store.nim, waku/v2/node/waku_node.nim, waku/v2/utils/peers.nim
Summary:
* `RemotePeerInfo` and `StoredInfo` store very similar content, being totally redundant.
* Back and forth conversions between both types are all over the codebase.
* This PR unifies `RemotePeerInfo` and `StoredInfo`, removing the later leaving only `RemotePeerInfo`.
=> refactor(networking): unify peer data models, remove StoredInfo

tests/all_tests_common.nim, tests/common/test_enr_builder.nim, tests/v2/testlib/waku2.nim, waku/common/enr.nim, waku/v2/protocol/waku_enr.nim
Following, and respecting, the [Open-close SOLID principle](https://www.digitalocean.com/community/conceptual-articles/s-o-l-i-d-the-first-five-principles-of-object-oriented-design#open-closed-principle):
> Open-closed Principle (OCP) states:
> 
> > Objects or entities should be open for extension but closed for modification.
> 
> This means that a class should be extendable without modifying the class itself.
I added an extensible EnrBuilder type that will replace the `Record.init()` constructor:
After merging this, I will add the extensions for the existing Waku ENR fields (`waku2` and `multiaddr`).
=> feat(common): added the enr builder

tests/common/test_enr_builder.nim, tests/v2/test_waku_enr.nim, waku/v2/protocol/waku_enr.nim
This PR introduces the Waku ENR capabilities field extension to the `EnrBuilder` type.
=> feat(enr): added enr builder waku capabilities extension

tests/v2/waku_rln_relay/test_waku_rln_relay.nim, waku/v2/protocol/waku_rln_relay/conversion_utils.nim, waku/v2/protocol/waku_rln_relay/protocol_types.nim, waku/v2/protocol/waku_rln_relay/rln/wrappers.nim, waku/v2/protocol/waku_rln_relay/rln_relay.nim
This PR fixes https://github.com/waku-org/nwaku/issues/1451
Functional changes in rln-relay:
- instead of using the `epoch` as the key, we now use the `external_nullifier`, which is a combination of the `epoch`, and the `rlnIdentifier`. This fixes the case when rln-relay was erroneously storing messages from multiple rln apps (linked to rlnIdentifiers) (which run on the same content topic/pubsub topic combination) which had the same epoch
=> chore(rln-relay): msg validation according to new circuit

config.nims
Fixes https://github.com/waku-org/nwaku/issues/1607
Only pass `-msse3` to the compiler (and linker) if `i386` or `amd64` and not `macosx`.
Cf. [nimbus for similar logic](https://github.com/status-im/nimbus-eth2/blob/stable/config.nims#L93-L123)
=> fix: only pass -msse3 if i386 or amd64

CHANGELOG.md
Adds the changelog for [Release v0.16.0](https://github.com/status-im/nwaku/milestone/8)
This will be a small maintenance release and I will reduce the milestone scope accordingly.
=> docs(changelog): release v0.16.0 release notes

docs/contributors/release-process.md
This adds some minor clarifications to the release process instructions for contributors:
- ensuring that CI against js-waku passes against the release candidate
- clarified the manual process by which the tagged Docker image should be published
=> docs(release): added regression checking and clarifications

.gitignore, Makefile, build_rln.sh, scripts/build_rln.sh
This PR introduces a script, `build_rln.sh` that extracts the host triple, checks if a zerokit release asset exists for it, and if not, builds zerokit from scratch.
Zerokit supports 6 target architectures at the moment, and it is possible that some users will need to build it manually when compiling nwaku with experimental features enabled. I propose that we continue to use zerokit as a submodule for this reason.
=> feat(rln-relay): fetch release from zerokit ci, or build

tests/common/test_enr_builder.nim, tests/v2/test_waku_enr.nim, waku/common/enr.nim, waku/common/enr/builder.nim, waku/common/enr/typed_record.nim, waku/v2/protocol/waku_enr.nim
The `TypedEnr` type from _nim-eth_ modules is not extensible enough. Here I introduce an alternate implementation that allows extending the field access via "getter" functions.
> **Note**
> Due to nim not having an "Any" type (the `Object` class in Java, or `interface{}` in Go), having an extensible field value caching mechanism using a `Table` is not trivial. I am leaving it for the future.
=> feat(common): added enr typed record replacement

waku/v2/node/waku_node.nim
* Uses the message `digest` to calculate the message hash when logging it.
=> bug: fix hash size greater than 32

tests/v2/test_peer_manager.nim, tests/v2/test_wakunode.nim, tests/v2/waku_relay/test_waku_relay.nim, tests/v2/waku_relay/test_wakunode_relay.nim, waku/v2/node/jsonrpc/admin/handlers.nim, waku/v2/node/peer_manager/peer_manager.nim, waku/v2/node/waku_node.nim
* As detected by @lchenut we were using`dial` for connecting to relay peers.
* Using `dial` creates a stream (that can be used to read and write data)
* However since relay is based on gossipsub, the streams are created under the hood for us by libp2p. And since we just use the protocol, there is no need to create new streams, since we don't write/read data for the relay protocol.
* This PR now enforces usig `connect` when using relay protocol and `dial` for the rest.
As a rule of thumb:
* Use `dial` when a stream to read/write is required (eg all protocols but relay)
=> fix: connect instead dial relay peer

apps/chat2/chat2.nim, apps/chat2/config_chat2.nim, apps/wakunode2/config.nim, apps/wakunode2/wakunode2.nim
=> fix(wakunode2): fix main warnings and drop swap support

examples/v2/publisher.nim, examples/v2/subscriber.nim, tests/v2/test_waku_discv5.nim, tests/v2/test_waku_enr.nim, tests/v2/test_waku_peer_exchange.nim, waku/v2/protocol/waku_discv5.nim, waku/v2/protocol/waku_enr.nim
This PR ports the waku multiaddress ENR field from the old non-extensible approach to the new builder/typed record extensible approach:
> **Note**
> Removal of the deprecated `Record.init()` method will be part of a follow-up PR.
=> refactor(enr): move waku enr multiaddr to typedrecod and builder extensions

tests/v2/test_waku_message_digest.nim, waku/v2/protocol/waku_message/message.nim
Related https://github.com/vacp2p/rfc/pull/589
* Increases the maximum size if the `meta` field from 32 to 64 bytes.
* Adds a test vector the the 64 bytes case, since it has a very specific use case.
* Adds a test to ensure the message can't be decoded if `meta` field is over the limit.
=> chore: increase meta size to 64 bytes + tests

scripts/build_rln.sh
Copies the binary from the repo/target instead of package/target
=> fix(rln-relay): buildscript bad cp

apps/wakubridge/wakubridge.nim, apps/wakunode2/config.nim, apps/wakunode2/wakunode2.nim, tests/v2/waku_rln_relay/test_rln_group_manager_onchain.nim, tools/networkmonitor/networkmonitor.nim, tools/networkmonitor/networkmonitor_utils.nim, waku/common/logging.nim, waku/v2/node/rest/relay/types.nim, waku/v2/protocol/waku_archive/driver/queue_driver/queue_driver.nim, waku/v2/protocol/waku_filter/client.nim, waku/v2/protocol/waku_keystore/keystore.nim, waku/v2/protocol/waku_keystore/utils.nim, waku/v2/protocol/waku_noise/noise_handshake_processing.nim, waku/v2/protocol/waku_noise/noise_utils.nim, waku/v2/protocol/waku_rln_relay/group_manager/on_chain/group_manager.nim
This is a gardening PR 🪴 This fixes multiple `BareExcept` warnings. Some others cannot be fixed without changing the function, which raises the exception: this should be addressed in a separate PR.
=> fix: fixed multiple bare except warnings

apps/chat2/chat2.nim, apps/chat2bridge/chat2bridge.nim, apps/wakubridge/wakubridge.nim, apps/wakunode2/wakunode2.nim, examples/v2/publisher.nim, examples/v2/subscriber.nim, tools/networkmonitor/networkmonitor.nim, tools/networkmonitor/networkmonitor_utils.nim, tools/wakucanary/wakucanary.nim, waku/v2/node/builder.nim, waku/v2/utils/peers.nim, waku/v2/waku_node.nim
This PR introduces a `WakuNode` compatible builder. The idea is to establish here the builder type and then evolve it in future iterations. This is just the first PR introducing the type and the API. It maps the `WakuNode.new` to the `WakuNodeBuilder` API.
=> feat(node): added waku node builder type

waku/v2/node/waku_node.nim
* Prevents the relay from being mounted more than once.
* This prevents mounting more relay protocols in the switch, which created unnecessary streams under the hood.
=> chore: do not mount relay more than once

apps/wakunode2/wakunode2.nim, waku/common/utils/nat.nim
The `setupNat` method from `waku/common/utils/nat` module is unsuitable for production. Instead of returning an error, it quits the application with return code `1`.
This has been discovered during the refactoring process of the WakuNode and the Wakunode2 app.
=> fix(wakunode2): made setup nat return errors

apps/wakunode2/app.nim, apps/wakunode2/wakunode2.nim
This is the third PR of the `refactor(wakunode2): split setup logic into app module` refactoring series.
> **Note**
> This PR is not merging into the `master` branch. It is merging into `wakunode-develop`.
+ Start node procedure
=> refactor(wakunode2): split setup logic into app module (pt. 4)

apps/wakunode2/app.nim, apps/wakunode2/wakunode2.nim
This is the fifth PR of the `refactor(wakunode2): split setup logic into app module` refactoring series.
> **Note**
> This PR is not merging into the `master` branch. It is merging into `wakunode-develop`.
+ Start HTTP JSON-RPC server procedure
+ Start HTTP REST server procedure
+ Start metrics server procedure
+ Start console metrics procedure
=> refactor(wakunode2): split setup logic into app module (pt. 5)

apps/wakunode2/wakunode2.nim
The "resume waku archive on boot" functionality has been behind a compilation flag and has not been released and tested for a long time. I suggest dropping the integration with the application until this functionality becomes part of the roadmap again.
> **Note**
> This PR is not against the `master` branch. It is against `wakunode-develop` feature branch.
=> refactor(wakunode2): drop experimental store resume at node boot

Makefile, apps/wakunode2/app.nim, tests/all_tests_wakunode2.nim, tests/wakunode2/test_app.nim, waku.nimble
As discussed at today's nwaku PM call, I am adding an instance object holding reference to all the parts that compose the `wakunode2` app to support gray-box testing.
=> refactor(wakunode2): added peer storage app setup proc and tests (pt. 1)

apps/wakunode2/wakunode2_setup_rpc.nim, tests/v2/wakunode_jsonrpc/test_jsonrpc_store.nim
https://github.com/waku-org/nwaku/issues/1575
Separated change to always enable the store-rpc handler even though the 'storenode' param is not passed.
The storenode param is described ain:
https://github.com/waku-org/nwaku/blob/0627b4f8f2c83d34ece6baeaa64b2d8b9244937b/apps/wakunode2/config.nim#L212
=> chore: allow to call store api endpoints without a storenode (#1575)

apps/chat2/chat2.nim, apps/chat2bridge/chat2bridge.nim, apps/wakubridge/wakubridge.nim, apps/wakunode2/wakunode2.nim, tests/v2/test_peer_manager.nim, tests/v2/test_utils_peers.nim, tests/v2/wakunode_rest/test_rest_store.nim, tools/wakucanary/wakucanary.nim, waku/v2/node/jsonrpc/admin/handlers.nim, waku/v2/node/peer_manager/peer_manager.nim, waku/v2/node/waku_node.nim, waku/v2/utils/peers.nim
As per @LNSD's recommendation, we are adding a 'parseRemotePeerInfo'-equivalent function that doesn't raises any expection but deals with Restult[...] which is a better approach to handle errors.
=> refactoring: Adding parsePeerInfo and deprecating 'parseRemotePeerInfo'

.github/workflows/ci-experimental.yml, .github/workflows/ci.yml, Makefile, apps/wakunode2/app.nim, apps/wakunode2/wakunode2.nim, apps/wakunode2/wakunode2_setup_rest.nim, apps/wakunode2/wakunode2_setup_rpc.nim, tests/wakunode2/test_app.nim, waku/v2/node/rest/server.nim
This is the second part of the `App` implementation and test cases.
> **Note**
> This PR is not merging into the `master` branch. It is merging into the `wakunode-develop` feature branch.
=> refactor(wakunode2): added peer storage app setup proc and tests (pt. 2)

apps/wakunode2/app.nim, apps/wakunode2/wakunode2.nim, tools/networkmonitor/networkmonitor.nim
This is the last PR of the wakunode2 app refactoring. After these changes are merged, the remaining work will thoroughly test the `wakunode2` app to ensure the refactoring has not broken anything.
> **Note**
> The present PR does not merge changes into the `master` branch. The destination branch is the `wakunode-develop` feature branch.
=> refactor(wakunode2): call app in the wakunode2 main function

waku/v2/node/peer_manager/peer_manager.nim
* Fix log reporting wrong ok connected peers
* `countIt(true)` != `countIt(it == true)` 🤦
=> fix(logs): fix log reporting wrong ok connected peers

tests/v2/waku_relay/test_wakunode_relay.nim
* Fix test failing intermittently by increasing the delay.
* Since multiple messages were being sent, we need to wait a bit more for the gossip. Without that, we are asserting before the test is really completed.
* The issue is more prone to appear with debug or trace logs. New delay value leaves enough time.
=> chore: fix test failing intermittently

waku/v2/utils/peers.nim
Merely adds the content of `p2pPartStr` to the returned error in `parsePeerInfo` if the next error occurs:
` Error in parsePeerInfo: p2p part should contain /`
=> peers.nim: adding more detail in case the p2pPart doesn't contain '/'

waku/common/nimchronos.nim, waku/common/utils/DEPRECATION_NOTICE.md, waku/v2/node/peer_manager/peer_manager.nim
As we discussed many times, the `utils` module has been marked as deprecated. The contained modules will be moved to different packages in future PRs.
=> chore: add deprecation notice to utils module. move heartbeat to common

waku/v2/node/rest/server.nim
This is a small refactoring PR 🪴
We are using extensively `string` as the project's standard error type.
=> fix(rest): change rest server result error type to string

Makefile
Running `make test2` implied running the `testcommon` target. Sometimes this could be more convenient. This PR decouples both Makefile targets:
=> build: decouple test2 target from testcommon

waku/v2/node/waku_node.nim
closes #1626 
* Add a new metric `waku_histogram_message_size` containing the message size histogram.
* This allows to have better observability on the message distribution size.
Suggested usage:
* 98% of the messages are between 5 and 15 kBytes
* 0.7% of the messages are between 50 and 100 kBytes.
* 99% of the messages are lower than 37.6 kBytes.
=> feat: add metrics with msg size histogram

tests/v2/test_peer_manager.nim, waku/v2/node/peer_manager/peer_manager.nim
I saw PR #1609  after merge and noticed it could be potentially optimized to eliminate multiple loops over all connections and streams.
I've updated the procedures to not accept directions and rather return a tupplo of `(connectionsIn, connectionsOut)` and `(streamsIn, streamsOut)`
It makes code a bit less explicit, but we only need to loop over all connections and streems twice rather than 4 times (in and out direction for connections, in and out for streams)
@alrevuelta please review carefully, in case I misunderstood how things work in your code:)
=> refactor:optimize getting number of connections and streams

.github/pull_request_template.md, .github/workflows/pr-lint.yml
This PR adds a very basic PR template and an action to lint the PR title to make sure it follows the semantic commit messages.
Beware that mergers can still edit the commit message after it is linted - to prevent that, we'd have to setup a bot merging the PR based on CI and approvals.
=> feat:add commit message linter

.github/workflows/ci-experimental.yml, .github/workflows/ci.yml
Nimbus uses `QUICK_AND_DIRTY_COMPILER` flag in their [ci](https://github.com/status-im/nimbus-eth2/blob/stable/.github/workflows/ci.yml#L135) and [release](https://github.com/status-im/nimbus-eth2/blob/stable/docker/dist/entry_point.sh#L197) actions. This skips some verification checks for Nim correctness , hence speeds up the build process see for actual usage in `build_nim.sh` - https://github.com/status-im/nimbus-build-system/blob/master/scripts/build_nim.sh#L185
=> refactor: use QUICK_AND_DIRTY_COMPILER flag for CI

apps/wakunode2/app.nim, apps/wakunode2/config.nim
Summary:
* Allows to protect custom pusub topics with a given public key, provided via cli arguments.
* New flag `protected-topic` is added with the format `pubsubtopic:publickey`
* Continuation of https://github.com/waku-org/nwaku/pull/1614
* Related https://github.com/waku-org/nwaku/issues/1612
Example:
```
./build/wakunode2 \
--topics="/waku/2/topic-1/proto /waku/2/topic-2/proto"\
--protected-topic=/waku/2/topic-1/proto:0425b97b092867bf74532d96e50b6227450b1413078efd414929ff444ece0f9146e58d6ac785c13e76111841812d6ddd20c83c88a6a24815948896731410b0c70b \
--protected-topic=/waku/2/topic-2/proto:04e790854444ae882cc69b25ec7bd454e7bdb8d4b900a4add3eeb52cf62415d9d93a5c7eb3c9ea08e8e854d8b8ac26f5073aaac6fa68c69b8f078bbd48c2d5589d
```
Output:
```
NOT 2023-04-19 16:39:53.554+02:00 routing only …
```
=> feat: configure protected topics via cli

apps/wakunode2/wakunode2_validator_signed.nim, tests/wakunode2/test_validators.nim, waku/v2/waku_core/message/message.nim
=> chore: add timestamp and ephemeral for opt-in dos validator

waku/v2/waku_filter_v2/rpc_codec.nim
Fixes the protofield numbering in the nwaku implementation of https://rfc.vac.dev/spec/12/.
The `status_code` and `status_desc` fields were using field numbers `2` and `3`, whereas the specified field numbers are `10` and `11`.
cc @fryorcraken @danisharora099
=> fix: fix filter v2 proto fields

tests/v2/waku_rln_relay/test_waku_rln_relay.nim
After deletion behaviour in zerokit's master was changed, it caused ci errors in nwaku. This PR addresses that change in behaviour.
=> fix(rln-relay): handle invalid deletes

waku/v2/waku_filter_v2/protocol.nim, waku/v2/waku_filter_v2/rpc_codec.nim
Instead of raising a decoding error, the filter protocol should assume `SUBSCRIBER_PING` as the default request type if the corresponding field is not set. This also matches proto3 requirements for enums to have a `0` value, which do not need to be serialised: https://protobuf.dev/programming-guides/proto3/#default
cc @danisharora099
=> fix: change filter request default behaviour to subscriber-ping

waku/v2/waku_rln_relay/constants.nim, waku/v2/waku_rln_relay/rln/wrappers.nim
Since we pass in a json string to the ffi for additional configs, this pr updates nwaku to do the same
=> chore(rln-relay): use new config for ffi

waku/v2/node/peer_manager/peer_manager.nim
streams were used instead of connections
=> fix: streams were used instead of connections

examples/v2/README.md, examples/v2/filter_subscriber.nim, examples/v2/lightpush_publisher.nim
While working on testing the new filter protocol, I realised that it will have some value to package a lightpush publisher and filter subscriber as an example.
I've tried to keep to the spirit of the current subscriber-publisher example, but without adding to our current MAKE targets.
=> feat: example using filter and lightpush

apps/wakunode2/app.nim, apps/wakunode2/config.nim
Adding a new `topic` parameter can be repeated.
The `topics` parameter becomes deprecated because it is not consistent with the other "repeatable" ones as it expects a space-separated list of pubsub topics.
When setting different pubsub topics through the CLI, they can be repeated:
`./build/wakunode2 --topic=t1 --topic=t2 --topic=t3 ...`
However, when setting them from within a config file, they should be in an array format within the cfg file:
```
topic = [ "t1" "t2" "t3" ]
```
closes #1726
=> fix: wakunode2 config. adding new 'topic' config parameter.

.github/workflows/ci-experimental.yml, .github/workflows/ci.yml, .github/workflows/release-assets.yml
I've been experimenting with how we use cache inour CI builds - we only cache the nim compiler binary, which leads to potentially unnecessary rebuilds of some libs and recursive submodule initialization on every build.
I believe I was able to get `vendor/` submodules caching properly, so that we can reuse all of the content without submodule init and rebuilds of deps.
I've experimented with this in a fork of nwaku repo (https://github.com/nwaku-test-org/nwaku/blob/master/.github/workflows/test-cache.yml) and the change seemed to result in change of build time from 21-25 mins down to 13-17 mins.
Potential drawback is that previously when one submodule changed we'd still use cached nim compiler, but here it will trigger a compiler rebuild on the PR which is updating a dependency - hence …
=> refactor(ci): cache all of submodules/deps to speed up build time

CHANGELOG.md
This PR updates CHANGELOG for release [v0.17.0](https://github.com/waku-org/nwaku/milestone/9)
Please check if the changelog looks ok and propose highlights!
=> docs(changelog): release notes for v0.17.0

tests/v2/waku_rln_relay/test_rln_group_manager_onchain.nim, waku/v2/waku_rln_relay/conversion_utils.nim, waku/v2/waku_rln_relay/group_manager/group_manager_base.nim, waku/v2/waku_rln_relay/group_manager/on_chain/group_manager.nim, waku/v2/waku_rln_relay/group_manager/static/group_manager.nim, waku/v2/waku_rln_relay/rln/rln_interface.nim, waku/v2/waku_rln_relay/rln/wrappers.nim
- chore(rln-relay): bump zerokit
- feat(rln-relay): use new atomic_operations ffi api
Uses the new `atomic_operation` ffi api from zerokit which allows atomic batching of insertions and removals to the 
merkle tree.
cc: 
- @richard-ramos for the go-waku 
- @weboko for the js-rln 
implementations :)
to remove, uses `atomicWrite`
closes #1729
=> feat(rln-relay): use new atomic_operation ffi api

tests/v2/test_peer_manager.nim, waku/v2/node/peer_manager/peer_manager.nim
* Before this PR nwaku nodes constantly tried to create new outcoming relay connections up to max connections. In theory, this could cause a node to only have out connections, which is a selfish behaviour since this takes a lot of incoming slots (of other peers) in the network.
* This PR enforces a given in/out ratio of connections, leaving more incoming slots than outgoing, which is more altruistic with the network, something quite important in the fleets. It archieves so by:
* prunning exceding inbound connections
* not attempting mroe out connections if the target was reach. 
closes https://github.com/waku-org/nwaku/issues/1495
=> chore(networking): set and use target outbound connections + prune

Dockerfile
We came across compilation issues when building a docker image with heaptrack support.
`sudo make docker-image  DOCKER_IMAGE_NAME=nwaku:gc HEAPTRACKER=1`
The use of `alpine:edge` make the heaptrack build to start failing.
```
#0 1.755 In file included from /heaptrack/src/analyze/suppressions.cpp:7:
#0 1.755 /heaptrack/src/analyze/suppressions.h:20:5: error: 'int64_t' does not name a type
#0 1.755    20 |     int64_t matches = 0;
#0 1.755       |     ^~~~~~~
#0 1.755 /heaptrack/src/analyze/suppressions.h:12:1: note: 'int64_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
#0 1.755    11 | #include <vector>
#0 1.755   +++ |+#include <cstdint>
#0 1.755    12 | 
#0 1.755 /heaptrack/src/analyze/suppressions.h:21:5: error: 'int64_t' does not name a type
#0 1.755    21 …
```
=> fix: Dockerfile - forcing the use of alpine:3.16 when building the heaptrackapp

ci/Jenkinsfile.release
During the period of rln-relay testnet 3, we will make the experimental flag default to true for all fleet deployments.
=> fix(ci): make experimental default to true in fleet deployment

.sv4git.yml, .sv4git/templates/releasenotes-md.tpl, .sv4git/templates/rn-md-section-commits.tpl, Makefile
Adds a make target to generate release notes based on commit messages.
Example:
```
$ make release-notes 
- add release-notes target ([ec9b222e](https://github.com/waku-org/nwaku/commit/ec9b222e))
- **cbindings:** first commit - waku relay ([#1632](https://github.com/waku-org/nwaku/issues/1632)) ([#1714](https://github.com/waku-org/nwaku/issues/1714)) ([2defbd23](https://github.com/waku-org/nwaku/commit/2defbd23))
- example using filter and lightpush ([#1720](https://github.com/waku-org/nwaku/issues/1720)) ([8987d4a3](https://github.com/waku-org/nwaku/commit/8987d4a3))
- configure protected topics via cli ([#1696](https://github.com/waku-org/nwaku/issues/1696)) ([16b44523](https://github.com/waku-org/nwaku/commit/16b44523))
- **mem-analysis:** Adding Dockerfile_with_heaptrack …
```
=> feat: add release-notes target

Makefile, waku.nimble
This PR aims for adding the option to create a dynamic linking library (libwaku.so.)
To change the type of library just pass `STATIC=true` to the Makefile command, and it will generate a libwaku.a. If nothing is passed, it builds dynamic library by default.
1. To generate a static library (libwaku.a) and cwaku_example binary with the libwaku embbeded into it:
`make cwaku_example STATIC=true -j8`
2. To generate a dynamic library (libwaku.so) and cwaku_example binary with the libwaku embbeded into it:
`make cwaku_example -j8`
1. dynamic library: `make libwaku -j8`.
`-> produces: build/libwaku.so
2. static library: `make libwaku STATIC=true -j8`
`-> produces: build/libwaku.a
https://github.com/waku-org/nwaku/issues/1632
=> feat: cbindings - allowing libwaku.so (dynamic) library

tests/wakunode2/test_validators.nim
* Fix flaky test for dos topic. Too many messages were being sent, and in some cases the `check` was done before all the messages were gossiped, hence failing.
* This is fixed by sending less messages, that should take less time to gossip. If it happens again, plan b is to increase the timeouts.
* Thanks @rymnc for the report.
=> fix: fix flaky test for dos topic

.gitignore, apps/chat2/chat2.nim, docs/tutorial/onchain-rln-relay-chat2.md
Update operator docs to include keystore change for rln-relay
Part of #1624
=> fix(rln-relay): keystore usage

docs/contributors/continuous-integration.md, docs/contributors/release-process.md, docs/contributors/waku-fleets.md, docs/faq.md, docs/operators/README.md, docs/operators/docker-quickstart.md, docs/operators/overview.md, docs/operators/quickstart.md, docs/tutorial/db-migration.md, docs/tutorial/dingpu.md, docs/tutorial/filter.md, docs/tutorial/jsonrpc-api.md, docs/tutorial/nangang.md, docs/tutorial/onchain-rln-relay-chat2.md, docs/tutorial/rln-chat-cross-client.md, docs/tutorial/rln-chat2-local-test.md, docs/tutorial/store.md, docs/tutorial/websocket.md, examples/v2/README.md, waku.nimble
First of all, sorry for a lot of changes in a single PR, but once I started...
I went through the `docs/` folder and fixed links to repo(s) and CI. I also fixed the doc factually in a few cases and marked some with `TODO: Depricate or fix` to get your opinion since they are no longer useful/working
=> chore(docs): fix docs and mark some as deprecated

Makefile
It seems Github Action runners started using new machines with new fancy CPUs which include AVX512 instructions. These are not widely available in non-server / older HW (it seems), which result in unusable binaries built in GH Actions.
We can pass explicit architecture / CPU instruction set to build for to C compiler through Nim using `--passC:"-march=..."`
The list of supported architectures: https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html
I am choosing basic instruction set `x86-64` for this PR. This may potentially influence speed of some crypto algorithms (which would otherwise leverage AVX instructions), so we should consider doing some benchmarking in the future to asses the impact and consider some newer architecture(s), but to have current builds working and as general as …
=> fix(ci): enforce basic CPU instruction set to prevent execution problems

tests/v2/test_waku_peer_exchange.nim, waku/v2/waku_peer_exchange/protocol.nim
* Since peer exchange protocol is req/resp and after exchanging the req/resp it's not very likely that the stream will be reused, we shall close the stream.
* Note that `.closeWithEOF()` is used instead of `.close()` [see](https://github.com/status-im/nim-libp2p/blob/unstable/libp2p/stream/lpstream.nim#L327-L335).
* A test is added that will fail without the changes introduced in this PR.
* Note that the stream is closed but not the connection.
=> chore: close px connections after resp

apps/chat2/chat2.nim, tests/v2/test_waku_filter.nim, tests/v2/test_wakunode_filter.nim, tests/v2/waku_archive/test_driver_queue_query.nim, tests/v2/waku_archive/test_driver_sqlite.nim, tests/v2/waku_archive/test_driver_sqlite_query.nim, tests/v2/waku_archive/test_retention_policy.nim, tests/v2/waku_archive/test_waku_archive.nim, tests/v2/waku_store/test_waku_store.nim, tests/v2/waku_store/test_wakunode_store.nim, tests/v2/wakunode_jsonrpc/test_jsonrpc_store.nim, tests/v2/wakunode_rest/test_rest_store.nim, waku/v2/node/jsonrpc/filter/handlers.nim, waku/v2/node/waku_node.nim, waku/v2/waku_archive/archive.nim, waku/v2/waku_archive/driver.nim, waku/v2/waku_archive/driver/queue_driver/queue_driver.nim, waku/v2/waku_archive/driver/sqlite_driver/sqlite_driver.nim, waku/v2/waku_archive/retention_policy.nim, waku/v2/waku_archive/retention_policy/retention_policy_capacity.nim, waku/v2/waku_archive/retention_policy/retention_policy_time.nim, waku/v2/waku_filter/client.nim, waku/v2/waku_store/protocol.nim
This PR is a very first step on getting asynchronous calls to any CRUD `archive` operation.
Important to notice that this PR doesn't allow async calls per se. For example, in `waku/v2/waku_archive/driver/sqlite_driver/sqlite_driver.nim`, the method `getMessages()` will still be sync because the call to `s.db.selectMessagesByHistoryQueryWithLimit(..)` will still be blocking.
Instead, this PR is a reorganization to adopt the asynchronous patterns for `waku archive` and adapt the code for the upcoming PR's where we will aggregate the @LNSD's PR, and therefore, start incorporating the needed to allow async interaction with a PostgreSQL database.
Sorry for the big number of changes. These are the most relevant:
1. waku/v2/waku_archive/driver.nim
2. …
=> feat(postgresql): 1st commit to async sql (waku_archive/driver...)

.github/workflows/nightly.yml, docs/operators/overview.md
It might be useful to build releasable artifacts nightly and create/update a Github Release with included commits and artifacts.
This gives anyone a place to simply get and test latest binary artifacts and to us a place to experiment with how artifacts are produced and packaged.
The GH Actions job is triggered every night + can be triggered manually, it builds `wakunode2` and tools (`networkmonitor` and `wakucanary`)  and creates or updates the `nightly` tag and release.
See an example here: https://github.com/nwaku-test-org/nwaku/releases/tag/nightly
=> feat(ci): add nightly builds

.github/workflows/nightly.yml
As suggested by @rymnc, this PR adds artifacts with `EXPERIMENTAL=true` for nightly builds
You can see how it looks in the release here: https://github.com/nwaku-test-org/nwaku/releases/tag/nightly
Let me know if you have suggestions for different naming, as I am not 100% sure I like how it looks now:)
=> chore(ci): add experimental builds to nightly

tests/v2/test_peer_manager.nim, waku/v2/node/peer_manager/peer_manager.nim
closes #1749
Description:
* Allows a maximum amount of `colocationLimit` connected peers from the same ip.
* Runs a periodic task to trigger disconnections from peers not meeting the criteria.
Note that this PR does not prevent connection attempts from peers violating the `colocationLimit`. These connections will be succesful but cleaned up later on.
=> feat(networking): prune peers from same ip beyond colocation limit

apps/wakunode2/app.nim, tests/all_tests_v2.nim, tests/v2/test_waku_rendezvous.nim, tests/v2/testlib/wakunode.nim, tests/wakunode2/test_app.nim, waku/v2/node/waku_node.nim, waku/v2/node/waku_switch.nim
Rendezvous Discovery protocol allows peers to advertise their addresses at a rendezvous point and other peers to query the rendezvous point to discover new peers.
This will be particularly useful for peers using circuit relay as they can then easily advertise their circuit relay multiaddress and be discovered by other network participants.
This PR uses libp2p Rendezvous implementation and mounts the protocol by default when relay protocol is enabled.
closes #1605
=> feat(wakunode2): enable libp2p rendezvous protocol by default

.github/workflows/ci-experimental.yml, .github/workflows/ci.yml, Makefile, tests/all_tests_v2.nim, tests/postgres-docker-compose.yml
Allowing the execution of postgres unit tests on Linux GitHub runners
The next file is only left in order to run local tests manually:
tests/postgres-docker-compose.yml
The ci launches its postgres instance with `sudo docker run ...`
https://github.com/waku-org/nwaku/issues/1604
=> test(postgres): Allow run postgres tests only on ci Linux platforms

apps/wakunode2/app.nim, examples/v2/publisher.nim, examples/v2/subscriber.nim, tests/v2/test_waku_discv5.nim, tests/v2/test_waku_peer_exchange.nim, waku/v2/node/waku_node.nim, waku/v2/waku_discv5.nim
This repeats the changes introduced by @LNSD in https://github.com/waku-org/nwaku/pull/1709, but do so from a base repo branch rather than a fork. This allows contributors on the base repo to take ownership of fixing tests, rebasing and other tasks needed to merge the changes.
Original issue description below.
---
Waku discovery5 implementation does random walks through the DHT and reports the discovered nodes. To support Waku relay static shards discovery, we want to announce in the ENR the shards the node is subscribed to and keep only the discovered nodes that match specific criteria (a.k.a. predicate).
=> feat(discv5): added find random nodes with predicate (#1762)

.github/workflows/nightly.yml, .github/workflows/release-assets.yml, Makefile, config.nims
This PR updates `config.nims` according to findings by Nimbus about various CPU archs and options (https://github.com/status-im/nimbus-eth2/blob/stable/config.nims#L94). It also updates release workflows (Nightly and actual releases) to leverage these options.
Next, it adds `arm64` architecture for Mac OSX system to make the released assets run on Apple M1 hardware (cc @alrevuelta)
This also reverts #1759 which was an interim solution to enable compatibility between various CPU architectures.
Lastly, it changes the name of the uploaded binary artifacts to 
```
nwaku-${{matrix.arch}}-${{runner.os}}.tar.gz
```
i.e.
```
nwaku-arm64-macos.tar.gz
nwaku-amd64-linux.tar.gz
```
See the example nightly release here: https://github.com/nwaku-test-org/nwaku/releases/tag/nightly
closes #1760
=> chore(ci): properly set os and architecture for nightly and release

apps/chat2/chat2.nim, apps/chat2bridge/chat2bridge.nim, apps/networkmonitor/networkmonitor.nim, apps/wakubridge/wakubridge.nim, examples/v2/subscriber.nim, tests/v2/test_wakunode.nim, tests/v2/test_wakunode_lightpush.nim, tests/v2/waku_relay/test_waku_relay.nim, tests/v2/waku_relay/test_wakunode_relay.nim, tests/v2/waku_rln_relay/test_wakunode_rln_relay.nim, tests/wakubridge/test_wakubridge.nim, waku/v2/node/jsonrpc/relay/handlers.nim, waku/v2/node/peer_manager/peer_manager.nim, waku/v2/node/rest/relay/handlers.nim, waku/v2/node/rest/relay/topic_cache.nim, waku/v2/node/waku_node.nim, waku/v2/waku_relay/protocol.nim
=> feat(networking): integrate gossipsub scoring

waku/v2/waku_rln_relay/constants.nim
Updates the pmtree configuration `tree_config` according to the parameters which work best with ethereum mainnet.
- cache_capacity: max_number_of_leaves_inserted_per_block ~ 407 (based on the gas used by the register fn on the smart 
contract, and block gas limit) * leaf_size = ~13_024
- mode: high_throughput
- compression: false
- flush_interval: 12_000 (average block time)
closes #1775
=> chore(rln-relay): update tree_config

apps/wakunode2/config.nim, waku/v2/waku_rln_relay/constants.nim, waku/v2/waku_rln_relay/rln/wrappers.nim, waku/v2/waku_rln_relay/rln_relay.nim
This pr allows the user/operator to pass in the path to the persisted merkle tree, this will allow users to only sync 
from the block that they need to, instead of syncing from the start every single time. 
uses it
**Note**:
- A follow up PR will be created to actually make sure that the onchain sync starts from the last processed block, split 
the prs to reduce cognitive load.
addresses a part of https://github.com/waku-org/nwaku/issues/1772
=> chore(rln-relay): pass in the path to the tree db

waku/v2/waku_relay/protocol.nim
Reverts waku-org/nwaku#1786
There is a regression in that nim-libp2p version causing constant nwaku crashes
Tracking regression here: https://github.com/status-im/nim-libp2p/issues/910
=> chore(libp2p): Revert "chore(libp2p): update nim-libp2p"

tests/all_tests_v2.nim, tests/v2/waku_archive/test_driver_postgres.nim, tests/v2/waku_archive/test_driver_postgres_query.nim, waku/v2/waku_archive/driver/postgres_driver/asyncpool.nim, waku/v2/waku_archive/driver/postgres_driver/postgres_driver.nim
postgres_driver retention policy methods plus more tests
https://github.com/waku-org/nwaku/issues/1604
=> feat(postgres): complete implementation of driver and apply more tests

tests/v2/waku_rln_relay/test_waku_rln_relay.nim, waku/v2/waku_rln_relay/constants.nim, waku/v2/waku_rln_relay/rln/rln_interface.nim, waku/v2/waku_rln_relay/rln/wrappers.nim
This pr introduces the get_leaf ffi api that was recently merged to zerokit's master (https://github.com/vacp2p/zerokit/pull/177)
=> feat(rln-relay): integrate get_leaf ffi api

tests/v2/waku_rln_relay/test_rln_group_manager_static.nim
Generates a new temp path for the tree db, as it was failing intermittently due to same path being used between tests.
closes #1796
=> fix(rln-relay): flaky static group manager test

Dockerfile
* `docker build .` was broken in mac
* this PR fixes it by using `alpine:3.16`
=> fix: fix mac docker build alpine version

tests/v2/waku_rln_relay/test_waku_rln_relay.nim, waku/v2/waku_rln_relay/rln/rln_interface.nim, waku/v2/waku_rln_relay/rln/wrappers.nim
This PR introduces 2 new api's from zerokit, `set_metadata`, and `get_metadata`. They are both used to persist metadata about merkle tree state, like last block synced, etc. This is very useful to resume sync from an existing tree database.
Unblocks https://github.com/waku-org/nwaku/issues/1772
=> feat(rln-relay): metadata ffi api

apps/wakunode2/app.nim, waku/v2/waku_rln_relay/group_manager/on_chain/group_manager.nim
This feature makes use of the new ffi api's `set_metadata` and `get_metadata` introduced in #1803. This allows us to insert the block number we sync 
to, and to resume sync when we re-use the database. reduces complexity and improves node startup time *significantly*
closes #1772
=> feat(rln-relay): resume onchain sync from persisted tree db

ci/Jenkinsfile.release
We have some issue with experimental features related to RLN. This fix temporarily disables experimental builds by default on fleet deployments.
=> fix: temporary fix to disable default experimental builds on fleets

apps/networkmonitor/networkmonitor.nim, apps/wakunode2/app.nim, examples/v2/publisher.nim, examples/v2/subscriber.nim, tests/v2/test_waku_discv5.nim, tests/v2/test_waku_peer_exchange.nim, waku/v2/waku_discv5.nim
Process node config for either static sharding or named topics, verify and update the ENR.
- Parse topics from config then check their validity according to https://rfc.vac.dev/spec/51/
- Update ENR with sharded topic info.
Step 1 in closing #1776 
All feedback is welcome but more specifically on;
- ~~Had to make some func public. Could be undone in next step when discovery is re-org. Not sure yet. Otherwise maybe we want to change the ergonomics around RelayShard <-> Record.~~
- ~~Not using parsed topics internally seams inelegant. What do?~~
- ~~Could leave the new code where it is and re-org once discovery is changed. Otherwise, where does this new code fit IDK?~~
- ~~Nim "style", tips & tricks. egg. L522 I tried ```return err("Pubsub topic parsing error: " & topic.error)``` I don't …
=> feat: named & sharded topic validation and ENR update

apps/wakunode2/app.nim, apps/wakunode2/config.nim
This is for deprecating the `topics` param in favor of the `topic` one.
1. From CLI:
`./build/wakunode2 --topic="topic1" --topic="topic2" --config-file=cfg_node.txt`
In this case, the CLI overrides the config file params.
2. From config file:
`./build/wakunode2 --config-file=cfg_node.txt`
[cfg_node.txt](https://github.com/waku-org/nwaku/files/11769553/cfg_node.txt)
=> chore(config): Deprecation of the 'topics' param

tests/v2/test_waku_discv5.nim, waku/v2/node/waku_node.nim, waku/v2/waku_discv5.nim
Filter peer discovered by static shard information
- added predicate based on relay shard info.
- apply predicate when peers are discovered
- test predicate
Step 3 of #1776 
TODO: ~~test predicate proc~~,
=> feat: discovery peer filtering for relay shard

tests/wakunode2/test_app.nim
* due to this renaming `apps/wakunode2/config.nim → apps/wakunode2/external_config.nim` a test that wasnt updated broke ci.
* fix broken test with wrong import
=> fix(ci): fix broken test with wrong import

apps/wakunode2/app.nim, apps/wakunode2/external_config.nim, tests/v2/test_peer_manager.nim, tests/v2/testlib/wakunode.nim, waku/v2/node/builder.nim, waku/v2/node/peer_manager/peer_manager.nim, waku/v2/node/waku_node.nim
* Currently the `withPeerManager()` in the builder was not implemented nor used. This PR moves the switch creation from `waku_node` to the `builder` and simplifies `WakuNode.new()` having less parameters.
* This is done because otherwise, `withPeerManger` can't be used since to build the PeerManager, we need the Switch, since its built inside.
* This PR adds a new **unused** flag `max-relay-peers` to be used in future PRs.
* Note that it doesnt introduce any breaking change, unless `maxConnections` is configured <50, but this is not the case in the fleets.
* Prerequisite for https://github.com/waku-org/nwaku/pull/1813
=> chore: add peer manager config to builder

Dockerfile
This is needed to avoid the `wakunode2` app not starting due to lack of the 'libpq.so.5' library.
https://github.com/waku-org/nwaku/issues/1604
=> fix(docker): Adding 'libpq-dev' to the resulting docker image

ci/Jenkinsfile.release
To avoid basic runtime failures due to missing libraries:
```
> docker run --rm statusteam/nim-waku:deploy-wakuv2-test --version
could not load: libpq.so(.5|)
```
=> fix: sanity-check the docker image start

apps/wakunode2/app.nim, examples/v2/publisher.nim, examples/v2/subscriber.nim, tests/v2/test_waku_discv5.nim, tests/v2/test_waku_peer_exchange.nim, waku/v2/waku_discv5.nim
The issue was introduced in PR#1818.
Before this commit, the `wakunode2` app crashed with the next error:
ERR 2023-06-27 15:57:27.268+00:00 5/7 Starting node and protocols failed topics="wakunode main" tid=1 file=wakunode2.nim:92 error="failed to start waku discovery v5: "
```
./build/wakunode2 --config-file=cfg_node_a.txt
```
[cfg_node_a.txt](https://github.com/waku-org/nwaku/files/11885542/cfg_node_a.txt)
=> fix(discv5): Fixing issue that prevented the wakunode2 from starting

tests/v2/test_peer_manager.nim, waku/v2/node/peer_manager/peer_manager.nim
* Before: Disconnections due to ip collocation factor where triggered at a given fixed interval, using a "cleanup" function scheduled every few seconds.
* With this PR: Disconnections are triggered in the connection handle, which is executed right after the peer joins. This allows to react faster to such attacks, where we are attacked by sybils under the same IP.
* It also uses `asyncSpawn` to trigger disconnections instead.
=> chore(networking): disconnect due to colocation ip in conn handler

apps/networkmonitor/networkmonitor.nim, apps/wakubridge/wakubridge.nim, apps/wakunode2/app.nim, apps/wakunode2/internal_config.nim, tests/v2/testlib/wakunode.nim, tests/wakubridge/test_wakubridge.nim, waku/v2/node/builder.nim, waku/v2/node/waku_node.nim
Clean-up remnants of the discv5 re-org
- Remove discv5 from node and it's builder
- Require a record to init a node (it was previously using discv5 record).
- Fix various tests that assumed nodes with discv5.
Tracking #1812
=> chore: discv5 re-org clean-up

waku/v2/waku_archive/driver/builder.nim, waku/v2/waku_archive/driver/postgres_driver/postgres_driver.nim
This PR is a combination of:
1. Integration of Postgres in wakunode2.
2. refactoring of Waku Archive, database, etc.
First, apologies for that big PR:S. I started the integration of Postgres into wakinode2 but during the process, I ended up doing a more generic refactoring, sorry about that. I can explain everything until we are all happy with it.
The main purpose of this PR is to allow a Nwaku to mount the Waku Archive protocol by using Postgres as the underlying database. For that, run the WakuNode with:
`./build/wakunode2 --store-message-db-url="postgres://postgres:test123@localhost:5432/postgres" ...`
As usual, we can run two Nwaku nodes, `a`, and `b`.
`b` will act as the store node and will connect to the Postgres database.
1. Start local Postgres database. Go to the repo's root …
=> feat(postgres): integration of postgres in wakunode2

apps/wakunode2/app.nim, apps/wakunode2/internal_config.nim
This change is needed so that the `libwaku.nim` code gets simpler. The `libwaku.nim` can't import the 'WakuNodeConf' type because this is related to the wakunode2 app, and the library shouldn't know about it.
=> refactor(internalconfig): avoid passing a 'WakuNodeConf' item to the 'createRecord' proc

apps/wakunode2/app.nim, apps/wakunode2/external_config.nim, apps/wakunode2/internal_config.nim, library/libwaku.nim, waku/v2/waku_enr/sharding.nim
This PR brings the sharding creation to the `libwaku` and fixes compilation errors.
=> chore(refactor): Move record creation & fix libwaku compilation

apps/wakunode2/app.nim, apps/wakunode2/external_config.nim, tests/v2/test_peer_manager.nim, waku/v2/node/builder.nim, waku/v2/node/peer_manager/peer_manager.nim
* Prunes incoming relay connections exceeding `maxInRelayPeers`
* Does not attempt to connect to more than `maxOutRelayPeers`
* This leaves `maxConnections`-`maxInRelayPeers`-`maxOutRelayPeers` slots for service peers
* Amount of `maxRelayPeers` defaults to 80% of the `maxConnections`
[ref](https://excalidraw.com/#json=wmsjdjnZUWn0GKnoLy0mI,BG_ExLzzYByNYxdVBMN9MQ)
closes https://github.com/waku-org/nwaku/issues/1567
=> feat: limit relay connections below max conns

apps/wakunode2/app.nim, apps/wakunode2/external_config.nim, tests/v2/waku_rln_relay/test_waku_rln_relay.nim, tests/v2/waku_rln_relay/test_wakunode_rln_relay.nim, waku/v2/waku_rln_relay/rln_relay.nim
Runs rln verification only if bandwidth exceeds 1mbps. @jm-clius, what is the bandwidth cutoff you'd like to be the default?
closes #1837
=> chore(rln-relay): Verify proofs based on bandwidth usage

.github/workflows/release-assets.yml
For some reason actions would omit the `env` when templating the matrix for the `include` section (i.e. Mac OS + arm64 combination), which would result in the workflow failing.
Since the `NPROC` is same for all the combinations anyway, this PR moves it out to `env` block and then uses `arch` in the job name (which also makes more sense)
=> fix(ci): do not depend on number of procesors with job name

apps/wakunode2/app.nim, apps/wakunode2/external_config.nim, tests/wakunode2/test_app.nim
Added content topics in waku external config (pubsub VS content is now explicit). When used, a shard is picked and ENR is updated. Pubsub topics can also be used at the same time but only on the same cluster.
~~I also remove the default pubsub topic from config. Do we want to keep it until autoshard is working properly?~~
Let's not forget to deprecate the default pubsub topic when autosharding is :+1: 
Tracking #1846
=> feat: autosharding content topic in config

waku/v2/waku_rln_relay/rln_relay.nim
If we have the same externalNullifier and proofMetadata, and same `share_x` and `share_y` we should mark the message as spam.
closes #1862
=> fix(rln-relay): mark duplicated messages as spam

.gitignore, Makefile, examples/nodejs/binding.gyp, examples/nodejs/waku.js, examples/nodejs/waku_addon.c, library/libwaku.h, library/libwaku.nim, waku.nimble
As part of the C-bindings tasks for nwaku, this PR is the starting point of having a nwaku node as a NodeJs module.
This PR adds a nwaku client wrapped as a NodeJs addon (waku_addon.c), which is implemented using the [`Node-API C API`](https://nodejs.org/api/n-api.html).
The `libwaku.so` (dynamic) library should be generated beforehand (`make libwaku`.).
( Edited: the next error is not happening now. It happened because both the NodeJs and Nim runtimes where running in the same thread. Making Nim runtime to run in a separate thread made it to work correctly )
Showstopper :snail:  : there is not a good interoperability between NodeJs GC and the Nim GC, i.e. the waku node runs properly in NodeJs but after a little while, it crashes because a memory region handled by the Nim's GC, had been …
=> feat(cbindings): Nim Waku in NodeJs

.gitignore, apps/wakunode2/app.nim, tests/v2/wakunode_rest/test_rest_filter.nim, waku/v2/node/rest/filter/client.nim, waku/v2/node/rest/filter/handlers.nim, waku/v2/node/rest/filter/openapi.yaml, waku/v2/node/rest/filter/types.nim
Draft PR for preliminary review, I appreciate any comment on it. Specially on the test_rest_filter.nim tests as 
peers and not finding each other. Probably overlooked something in setting up.
- Interface added
- tests are added but not yet functional. 
nim c -r -d:chronicles_log_level=DEBUG --verbosity=0 --hints=off --outdir=build ./tests/v2/wakunode_rest/test_rest_filter.nim test "Subscribe a node to an array of topics - POST /filter/v1/subscriptions"
tracking: [#1851](https://github.com/waku-org/nwaku/issues/1851)
=> feat: Rest API interface for filter service. 

waku/v2/waku_enr/capabilities.nim
* Fixes an out of bounds crash when `waku2` field in the ENR is not set. This shouldn't really happen as thats not compliant with the spec and no node should have that field unset, but ofc we can't control that.
* Closes https://github.com/status-im/infra-misc/issues/164
* Note that while it was detected when using `networkmonitor` this could affect `wakunode2` if using waku2 field.
* Thanks @jakubgs for the report.
=> fix: fixes out of bounds crash when waku2 is not set

.github/workflows/ci.yml, docker/binaries/Dockerfile.bn.amd64
This PR adds a separate Dockerfile which creates an image from a binary built in CI.
It also adds a job which pushes it to a Docker repository (quay.io/wakuorg/nwaku-pr) separate from the one where standard releases are pushed (to keep the latter clean of these "ephemeral" images) - the PR images are cleaned up after 7 days.
Additional step comments the PR to present the newly created image to contributor and reviewers.
You can see the example here: https://github.com/nwaku-test-org/nwaku/pull/12
There is one caveat - to get the image served as quickly as possible, there is an extra `wakunode2` build running, this is not ideal, but it would increase "interactivity" of the PR. It is also easy to just "append" these 2 steps to existing build job if that is preferred - interested in …
=> feat(ci): add docker image builds per PR

.github/workflows/ci.yml
We were missing the `disableMarchNative` to prevent using CPU instructions only available on the action runners. Without this users might get  `Illegal instruction (core dumped)` error when running the PR image
=> fix(ci): add mising OS arch option to image build

.github/workflows/ci.yml
This PR makes sure the `comment` step only runs on PRs (as it fails CI for `master` otherwise)
It also configures the action to only update the comment and not post a new comment after each CI run
=> fix(ci): only add comment on PR and do not duplicate it

CHANGELOG.md
Updating Changelog for the (delayed) v0.19.0 release.
Please take a look at highlights and upgrade instructions and let me know if there is anything missing/incorrect.
=> chore(release): update changelog for delayed v0.19.0 release

waku/node/waku_node.nim
Previously, we would let the node continue as usualy if the rln-relay failed to mount ~ this PR addresses that issue by bubbling up 
the error to the `setupProtocols` proc in `wakunode2.nim`
Thanks @alrevuelta for the suggestion
Maybe we should convert all the mounting procs to return a result instead of raising exceptions?
=> fix(rln-relay): should error out on rln-relay mount failure

waku/node/waku_node.nim, waku/waku_rln_relay/group_manager/on_chain/group_manager.nim, waku/waku_rln_relay/rln/wrappers.nim, waku/waku_rln_relay/rln_relay.nim
This pr introduces a couple small changes for logging and fixes the startIndex starting from 0 instead of 1 like the contract
=> fix(rln-relay): invalid start index being set results in invalid proofs 

apps/chat2/chat2.nim, apps/chat2/config_chat2.nim, apps/wakunode2/app.nim, apps/wakunode2/external_config.nim, tests/waku_rln_relay/test_waku_rln_relay.nim, tests/waku_rln_relay/test_wakunode_rln_relay.nim, waku/node/waku_node.nim, waku/waku_rln_relay/rln_relay.nim
* Remove `rln-relay-pubsub-topic` and `rln-relay-content-topic` cli flags.
* Remove all references to pubsub and content topics in rln.
* Mount rln in all pubsub topics that relay is configured with.
* Adds tests to ensure that rln is applied in all pubsub/content topics configured in relay.
Related https://github.com/waku-org/nwaku/issues/1906
=> chore(rln): run rln in all relay pubsubtopics + remove cli flags

apps/chat2/chat2.nim, apps/wakunode2/app.nim, waku/node/waku_node.nim
This PR ensures that messages are processed only after the rln-relay is ready to verify proofs, i.e updated till latest 
head
Addresses a part of #1906
=> fix(rln-relay): waitFor startup, otherwise valid proofs will be marked invalid

waku/waku_rln_relay/constants.nim
This PR renames the `application` field in the keystore to `waku-rln-relay` to make it agnostic to the client (go-waku, 
nwaku).
cc: @richard-ramos thanks for the report
cc: @alrevuelta this may require you to manually change the `application` in the keystore you're using for the 
simulations - `sed -i s/nwaku-rln-relay/waku-rln-relay/g rlnKeystore.json`
closes #1903
=> chore(rln-relay): rename keystore application to waku-rln-relay

tools/rln_keystore_generator/external_config.nim, tools/rln_keystore_generator/rln_keystore_generator.nim
A follow up PR to #1925
The next follow up PR will actually execute the registration if `--execute` is true
=> chore(rln_keystore_generator): generate and persist credentials
